### ISSUE TITLE
Suddenly unable to run any Java application in my workspace - "is not a valid java project"

### ISSUE THREAD

**Issue by stodge** [redhat-developer/vscode-java#1028]
I suddenly started getting an error "... is not a valid java project" whenever I try to run one of my launchers. I didn't change any vscode settings, code or workspace settings. This is a clean copy of my code. I tried updating vscode to the latest version but it still fails.

The developer tools show:

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242

SyntaxError: Unexpected end of JSON input	at JSON.parse (<anonymous>)	at Object.<anonymous> (/home/mike/.vscode/extensions/vscjava.vscode-maven-0.18.1/dist/extension.js:71:29075)	at Generator.next (<anonymous>)	at s (/home/mike/.vscode/extensions/vscjava.vscode-maven-0.18.1/dist/extension.js:71:28558)
```

And:

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2478 ConfigError: The project '<project_name>' is not a valid java project.

	onDidNotificationChange	@	/usr/share/code/reso…kbench.main.js:2478

```

I can't run any Java apps in my workspace. Thanks!

##### Environment
- Operating System:

CentOS Linux release 7.6.1810 (Core)

- JDK version:

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

- Visual Studio Code version:

Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:24:14.598Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 3.10.0-957.27.2.el7.x86_64

- Java extension version:

0.47.0 (July 18th, 2019)

##### Steps To Reproduce
1. Try to launch any existing Java app in a clean copy of my own code

##### Current Result

I get the error:  ... is not a valid java project

##### Expected Result

The java application should run.

**Comment by stodge** [comment]
I don't know if vscode updated one of the extensions, but the problem appears to be at the project is contained in a folder with an underscore: my_project, while the maven project is my-project. The launcher used to use m_project, but this no longer worked. So I changed it to my-project and it seems to work. Not sure why it stopped working, but it looks like I'm good again. :)
