### ISSUE TITLE
Java IntelliSense stops working randomly

### ISSUE THREAD

**Issue by ccerghed** [redhat-developer/vscode-java#1040]
Issue Type: <b>Bug</b>

I have been using a very small project for a few months now, and have had the best experience with the Java Language support.  Intellisense was working great until the last 2 patches of Visual Studio Code, which apparently broke the extension.  It throws an exception, and then all IntelliSense stops working, including the JS/TS extension.  If I restart Visual Studio Code, it will start working again, until it hits the exception again.  Here are the details:

[Error - 2:12:06 PM] Aug 21, 2019 2:12:06 PM Problem with folding range for /dev-charlie-plugin/src/progressive/pims/AccessRequestResource.java
Invalid_Char_In_String
org.eclipse.jdt.core.compiler.InvalidInputException: Invalid_Char_In_String
	at org.eclipse.jdt.internal.core.util.PublicScanner.getNextToken(PublicScanner.java:1470)
	at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.computeFoldingRanges(FoldingRangeHandler.java:110)
	at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.foldingRange(FoldingRangeHandler.java:61)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$25(JDTLanguageServer.java:781)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$42(JDTLanguageServer.java:915)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Extension version: 0.47.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by maxi-billion** [comment]
I stopped by to say that I'm having a similar issue. Intellisense will randomly stop after using VS Code for some time; it seems to break when loading certain method suggestions after typing a dot. After that, Intellisense stops completely.

I get the following javascript errors in the console when this happens (not sure how to see the java exceptions @ccerghed reports however).

`ERR Unexpected token C in JSON at position 8666: SyntaxError: Unexpected token C in JSON at position 8666
	at JSON.parse (<anonymous>)
	at d.onData (<userhome>\.vscode\extensions\redhat.java-0.47.0\dist\extension.js:1:95843)
	at Socket.module.exports.listen.readable.on.e (<userhome>\.vscode\extensions\redhat.java-0.47.0\dist\extension.js:1:95207)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

16log.ts:173   ERR Header must provide a Content-Length property.: Error: Header must provide a Content-Length property.
	at d.onData (<userhome>\.vscode\extensions\redhat.java-0.47.0\dist\extension.js:1:95470)
	at Socket.module.exports.listen.readable.on.e (<userhome>\.vscode\extensions\redhat.java-0.47.0\dist\extension.js:1:95207)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

I am running Windows 10 as well.

**Comment by maxi-billion** [comment]
As an update, I can consistently trigger the Javascript errors when typing "System."

**Comment by fbricon** [comment]
@maxi-billion can you provide the message output after turning on [verbose tracing](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server)?

**Comment by snjeza** [comment]
@maxi-billion Could you disable the Spring Tools and Visual Studio IntelliCode extension and try to reproduce the issue?

**Comment by ccerghed** [comment]
Thank you, I disabled IntelliCode and it fixed the issue for me as well.
