### ISSUE TITLE
Error report after edit org.eclipse.jdt.core.prefs under .settings

### ISSUE THREAD

**Issue by leaxoy** [redhat-developer/vscode-java#105]
After edit `org.eclipse.jdt.core.prefs` in `.settings` dir to `java source = 1.8`, then restart vsc.
And vscode-java report an error.
```
[Warn  - 2:11:40 AM] Nov 26, 2016 2:11:40 AM The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
[Error - 2:11:42 AM] Nov 26, 2016 2:11:40 AM Exception occurred while saving project preferences: /neural/.settings/org.eclipse.jdt.core.prefs.
Resource is out of sync with the file system: '/neural/.settings/org.eclipse.jdt.core.prefs'.
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/neural/.settings/org.eclipse.jdt.core.prefs'.
```

**Comment by fbricon** [comment]
is this a pure eclipse project or is it maven based?

**Comment by leaxoy** [comment]
maven based, created by intellij idea

**Comment by fbricon** [comment]
Ok, I can reproduce the issue. 

If you want to set your java compilation level to 1.8, you must do it from the pom.xml as per https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html, then restart vscode.

In the mean time, you should delete the workspace:
- $HOME/Library/Application Support/Code/User/workspaceStorage on mac, or
- %APPDATA%\Code\User\workspaceStorage\ on windows, or
- $HOME/.config/Code/User/workspaceStorage/ on linux

**Comment by fbricon** [comment]
full log
```
Warn  - 4:55:10 PM] 25 nov. 2016 16:55:10 The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
[Error - 4:55:16 PM] 25 nov. 2016 16:55:10 Exception occurred while saving project preferences: /spring-boot-atomist/.settings/org.eclipse.jdt.core.prefs.
Resource is out of sync with the file system: '/spring-boot-atomist/.settings/org.eclipse.jdt.core.prefs'.
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/spring-boot-atomist/.settings/org.eclipse.jdt.core.prefs'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.write(FileSystemResourceManager.java:1125)
	at org.eclipse.core.internal.resources.File.internalSetContents(File.java:303)
	at org.eclipse.core.internal.resources.File.setContents(File.java:339)
	at org.eclipse.core.internal.resources.ProjectPreferences$1.run(ProjectPreferences.java:627)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.ProjectPreferences.save(ProjectPreferences.java:660)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalFlush(EclipsePreferences.java:431)
	at org.eclipse.core.internal.resources.ProjectPreferences.flush(ProjectPreferences.java:365)
	at org.eclipse.jdt.internal.core.JavaProject.setOption(JavaProject.java:2955)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:142)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:501)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:494)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:432)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:345)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:342)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:328)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:310)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:299)
	at org.jboss.tools.vscode.java.internal.managers.MavenProjectImporter.collectProjects(MavenProjectImporter.java:106)
	at org.jboss.tools.vscode.java.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:87)
	at org.jboss.tools.vscode.java.internal.managers.ProjectsManager.createProject(ProjectsManager.java:61)
	at org.jboss.tools.vscode.java.internal.handlers.InitHandler$1.run(InitHandler.java:89)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by leaxoy** [comment]
Thanks @fbricon I will have a try
