### ISSUE TITLE
Maven import failure caused by error parsing maven-compiler-plugin configuration

### ISSUE THREAD

**Issue by GabCamarda** [redhat-developer/vscode-java#1131]
When importing a multi-module maven project on vscode, it fails with this error message:
```The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project```. This is caused by the `NullPointerException` that can be seen in the logs below.

The project has a parent pom in the root, as well as in each module. The project is a mono-repo.

Running `mvn clean install` on cli returns no error and IntelliJ has no issues importing it. I've also reported a bug here, as I use emacs: emacs-lsp/lsp-java#167 
This could also be related: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496130

I've also tried with the following troubleshooting:
- run `mvn eclipse:clean`;
- run `mvn eclipse:eclipse`;
- remove `~/.m2/repository` and `mvn clean install`;
- [this](https://github.com/redhat-developer/vscode-java/issues/1118#issuecomment-547133688)
None of the above helped.

##### Environment
- Operating System: osx
- JDK version: openjdk version "11.0.4" 2019-07-16
- Visual Studio Code version: Version: 1.39.2
- Java extension version: 0.52.0

##### Steps To Reproduce
1. Open folder and select Maven multi-module project
This will trigger m2e to import all the modules but will fail to import, as described.

This is an extract of the logs
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:25:44.505
!MESSAGE >>New configuration: {java={home=null, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}}, configuration={checkProjectSettingsExclusions=true, updateBuildConfiguration=interactive, maven={userSettings=null}}, trace={server=off}, import={maven={enabled=true}, gradle={enabled=true, wrapper={enabled=true}, version=null, arguments=null, jvmArguments=null, home=null}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, maven={downloadSources=false}, referencesCodeLens={enabled=false}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=null}, comments={enabled=true}, onType={enabled=true}}, saveActions={organizeImports=false}, contentProvider={preferred=null}, autobuild={enabled=true}, maxConcurrentBuilds=1.0, completion={enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], filteredTypes=[java.awt.*, com.sun.*], importOrder=[java, javax, com, org]}, foldingRange={enabled=true}, progressReports={enabled=true}, codeGeneration={hashCodeEquals={useJava7Objects=false, useInstanceof=false}, useBlocks=false, generateComments=false, toString={template=${object.className} [${member.name()}=${member.value}, ${otherMembers}], codeStyle=STRING_CONCATENATION, skipNullValues=false, listArrayContents=true, limitElements=0.0}}, selectionRange={enabled=true}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=false, showQualifiedNames=false, showLogicalStructure=true, showToString=true, maxStringLength=0.0, hotCodeReplace=manual, enableRunDebugCodeLens=true, forceBuildBeforeLaunch=true, console=integratedTerminal}}, dependency={showOutline=true, syncWithFolderExplorer=true, autoRefresh=true, refreshDelay=2000.0, packagePresentation=flat}, help={firstView=auto}, test={report={showAfterExecution=onFailure, position=sideView}, editor={enableShortcuts=true}, log={level=info}, message={hintForDeprecatedConfig=true, hintForSetingDefaultConfig=true}, defaultConfig=, config={}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:25:44.506
!MESSAGE Starting Maven update for platform

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:25:44.539
!MESSAGE >> workspace/executeCommand java.maven.initializeSearcher

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:25:44.552
!MESSAGE >> workspace/executeCommand vscode.java.test.get.testpath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:25:44.596
!MESSAGE >> workspace/executeCommand java.project.list

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:27:14.533
!MESSAGE Starting Maven update for platform.webproxy

!ENTRY org.eclipse.m2e.core 4 0 2019-11-05 09:27:25.852
!MESSAGE Could not update project platform.webproxy configuration
!STACK 0
java.lang.NullPointerException
	at org.jboss.tools.maven.apt.internal.utils.ProjectUtils.parseProcessorOptions(ProjectUtils.java:94)
	at org.jboss.tools.maven.apt.internal.compiler.MavenCompilerJdtAptDelegate.getAnnotationProcessorConfiguration(MavenCompilerJdtAptDelegate.java:146)
	at org.jboss.tools.maven.apt.internal.AbstractAptConfiguratorDelegate.configureClasspath(AbstractAptConfiguratorDelegate.java:251)
	at org.jboss.tools.maven.apt.internal.AbstractAptProjectConfigurator.configureRawClasspath(AbstractAptProjectConfigurator.java:165)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.invokeJavaProjectConfigurators(AbstractJavaProjectConfigurator.java:208)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:164)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:439)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1370)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:335)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:317)
	at org.eclipse.jdt.ls.core.internal.managers.MavenBuildSupport.update(MavenBuildSupport.java:92)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter$1.runInWorkspace(MavenProjectImporter.java:244)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:27:28.461
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:27:55.132
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:27:55.308
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-11-05 09:27:55.310
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'
```

##### Current Result
Fails to import

##### Expected Result
Importing the project should be successful

**Comment by fbricon** [comment]
can you please show your maven-compiler-plugin configuration?

**Comment by GabCamarda** [comment]
Sure, where would that be?

**Comment by fbricon** [comment]
from a terminal, type `mvn help:effective-pom`

**Comment by GabCamarda** [comment]
Thanks, it's a very long file and contains some information about my work which I probably shouldn't share. Anything specific you're looking for? I could copy-paste an excerpt.

**Comment by fbricon** [comment]
yes the maven-compiler-plugin configuration

**Comment by GabCamarda** [comment]
```
<plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
          <executions>
            <execution>
              <id>default-compile</id>
              <phase>compile</phase>
              <goals>
                <goal>compile</goal>
              </goals>
              <configuration>
                <forceJavacCompilerUse>true</forceJavacCompilerUse>
                <compilerArgs>
                  <arg>-parameters</arg>
                  <arg>-XDcompilePolicy=simple</arg>
                  <arg />
                </compilerArgs>
                <annotationProcessorPaths>
                  <path>
                    <groupId>com.my-project</groupId>
                    <artifactId>platform.foundation.queue.annotation</artifactId>
                    <version>20191104.2037.20419</version>
                  </path>
                  <path>
                    <groupId>com.my-project</groupId>
                    <artifactId>platform.foundation.persistence.annotation</artifactId>
                    <version>20191104.2037.20419</version>
                  </path>
                  <path>
                    <groupId>com.my-project</groupId>
                    <artifactId>platform.foundation.errorprone</artifactId>
                    <version>20191104.2037.20419</version>
                  </path>
                </annotationProcessorPaths>
              </configuration>
            </execution>
            <execution>
              <id>default-testCompile</id>
              <phase>test-compile</phase>
              <goals>
                <goal>testCompile</goal>
              </goals>
              <configuration>
                <forceJavacCompilerUse>true</forceJavacCompilerUse>
                <compilerArgs>
                  <arg>-parameters</arg>
                  <arg>-XDcompilePolicy=simple</arg>
                  <arg />
                </compilerArgs>
                <annotationProcessorPaths>
                  <path>
                    <groupId>com.my-project</groupId>
                    <artifactId>platform.foundation.queue.annotation</artifactId>
                    <version>20191104.2037.20419</version>
                  </path>
                  <path>
                    <groupId>com.my-project</groupId>
                    <artifactId>platform.foundation.persistence.annotation</artifactId>
                    <version>20191104.2037.20419</version>
                  </path>
                  <path>
                    <groupId>com.my-project</groupId>
                    <artifactId>platform.foundation.errorprone</artifactId>
                    <version>20191104.2037.20419</version>
                  </path>
                </annotationProcessorPaths>
              </configuration>
            </execution>
          </executions>
          <configuration>
            <forceJavacCompilerUse>true</forceJavacCompilerUse>
            <compilerArgs>
              <arg>-parameters</arg>
              <arg>-XDcompilePolicy=simple</arg>
              <arg />
            </compilerArgs>
            <annotationProcessorPaths>
              <path>
                <groupId>com.my-project</groupId>
                <artifactId>platform.foundation.queue.annotation</artifactId>
                <version>20191104.2037.20419</version>
              </path>
              <path>
                <groupId>com.my-project</groupId>
                <artifactId>platform.foundation.persistence.annotation</artifactId>
                <version>20191104.2037.20419</version>
              </path>
              <path>
                <groupId>com.my-project</groupId>
                <artifactId>platform.foundation.errorprone</artifactId>
                <version>20191104.2037.20419</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
```
Does this help?

**Comment by fbricon** [comment]
Yes, you have empty `<arg/>` elements in your `<compilerArgs>` configs. Try to remove them, they're useless

**Comment by GabCamarda** [comment]
That did it, thank you! Would it be useful if the exception could be caught and display a message instead with a similar solution, as a possible solution? Just seeing a NPE in the logs could be anything for the end user.

**Comment by GabCamarda** [comment]
It would actually be useful if the LSP could ignore null fields. IntelliJ works fine with the same pom, so I'm assuming they probably ignore it or log a warning?

**Comment by GabCamarda** [comment]
Turns out that field is used by TeamCity. It is empty initially but it then gets assigned arguments during build.

**Comment by fbricon** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/1255
