### ISSUE TITLE
maven debug problem

### ISSUE THREAD

**Issue by SilenceUrStep** [redhat-developer/vscode-java#1205]
![image](https://user-images.githubusercontent.com/16930271/71139075-227f9e00-2248-11ea-8803-0a22659c587a.png)
first is like this pic
![image](https://user-images.githubusercontent.com/16930271/71139193-6c688400-2248-11ea-9cbc-8f3b2cb00469.png)
and for a second the terminal show up
![image](https://user-images.githubusercontent.com/16930271/71139198-7094a180-2248-11ea-983d-e3dae2502ae2.png)
##### Environment
- Operating System:windows 10
- JDK version:1.8
- Visual Studio Code version:1.41.0
- Java extension version:0.8.1

##### Steps To Reproduce
1. [step 1]
![image](https://user-images.githubusercontent.com/16930271/71139075-227f9e00-2248-11ea-8803-0a22659c587a.png)
[.log](https://github.com/redhat-developer/vscode-java/files/3981454/default.log)
##### Current Result
first is like this pic
![image](https://user-images.githubusercontent.com/16930271/71139193-6c688400-2248-11ea-9cbc-8f3b2cb00469.png)
and for a second the terminal show up
![image](https://user-images.githubusercontent.com/16930271/71139198-7094a180-2248-11ea-983d-e3dae2502ae2.png)
##### Expected Result
expect it works！
##### Additional Informations
it seems like request the port just one time，if dose not work ，throw exception
```
[Error - 上午10:14:37] 2019-12-19 10:14:37 [error response][attach]: Failed to attach to remote debuggee VM. Reason: java.net.ConnectException: Connection refused: connect
Failed to attach to remote debuggee VM. Reason: java.net.ConnectException: Connection refused: connect
com.microsoft.java.debug.core.DebugException: Failed to attach to remote debuggee VM. Reason: java.net.ConnectException: Connection refused: connect
	at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:253)
	at com.microsoft.java.debug.core.adapter.handler.AttachRequestHandler.handle(AttachRequestHandler.java:82)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:84)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.eclipse.jdi.internal.connect.SocketTransportService$2.run(SocketTransportService.java:147)
	... 1 more
```

**Comment by fbricon** [comment]
Closing as out-of-scope. Please open a bug report in https://github.com/microsoft/vscode-java-debug/issues
