### ISSUE TITLE
Could not lookup required component

### ISSUE THREAD

**Issue by z00420691** [redhat-developer/vscode-java#1215]
##### Environment
- Operating System:win32
- JDK version:1.8.0_231
- Visual Studio Code version:1.41
- Java extension version:0.55

##### Steps To Reproduce
Update this extension to 0.55 and the server failed to start. The log shows that 'Connection refused: connect' because of 'Could not lookup required component', but it works fine in version 0.54, maybe something wrong with maven? Wish your reply, best regards!

Complete log:
Eclipse.buildId=unknown
java.version=1.8.0_231
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -data c:\Users\xxxxx\AppData\Roaming\Code\User\workspaceStorage\d31cd756907699d63979284874225cab\redhat.java\jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-24 11:35:04.222
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.osgi 4 0 2019-12-24 11:35:05.378
!MESSAGE Application error
!STACK 1
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at java.net.Socket.connect(Socket.java:555)
	at java.net.Socket.<init>(Socket.java:451)
	at java.net.Socket.<init>(Socket.java:228)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$SocketStreamProvider.initializeConnection(ConnectionStreamFactory.java:48)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$SocketStreamProvider.getInputStream(ConnectionStreamFactory.java:56)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.getInputStream(ConnectionStreamFactory.java:112)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startConnection(JavaLanguageServerPlugin.java:323)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startLanguageServer(JavaLanguageServerPlugin.java:407)
	at org.eclipse.jdt.ls.core.internal.LanguageServer.start(LanguageServer.java:27)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-12-24 11:35:05.394
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:

!ENTRY org.eclipse.m2e.core 4 -1 2019-12-24 11:35:05.800
!MESSAGE Could not lookup required component
!STACK 0
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.repository.RepositorySystem
  roleHint: 
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:249)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lookup(MavenImpl.java:1293)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.addDefaultRepository(MavenImpl.java:1131)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getArtifactRepositories(MavenImpl.java:1087)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistry.updateRegistry(RepositoryRegistry.java:255)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistryUpdateJob.run(RepositoryRegistryUpdateJob.java:49)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4191)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 8 more

**Comment by testforstephen** [comment]
Could you try the command below?

**F1** -> **Java: Clean the Java language server workspace**
