### ISSUE TITLE
Contains emphasized items after fixing compile errors

### ISSUE THREAD

**Issue by spottedmahn** [redhat-developer/vscode-java#1235]
After fixing some compiler errors, VS code is complaining at the folder level that there's still a problem:

![image](https://user-images.githubusercontent.com/14079228/72372791-08b16980-36d5-11ea-8cb3-4108815ef75d.png)

On hover I see this:

![image](https://user-images.githubusercontent.com/14079228/72372798-0d761d80-36d5-11ea-983e-fd676e5f0033.png)

##### Environment
- JDK version: openjdk version "11.0.5" 2019-10-15
- Java extension version: 0.55.1
- Version: 1.41.1 (user setup)
- Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Date: 2019-12-18T14:58:56.166Z
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.18363

##### Steps To Reproduce
Not sure

[sanitized.log](https://github.com/redhat-developer/vscode-java/files/4060944/sanitized.log)

##### Expected Result
No red emphasis on the folder:

![image](https://user-images.githubusercontent.com/14079228/72373609-9fcaf100-36d6-11ea-9f93-cbe1d7183f14.png)

**Comment by snjeza** [comment]
@spottedmahn could you attach a project example?

**Comment by spottedmahn** [comment]
>could you attach a project example?

I can't unfortunately.  Doesn't the log help identify the problem?  If not, maybe more info can be logged so it can get tracked down?

**Comment by rgrunber** [comment]
Is this still reproducible with the project ? The first thing I would have checked is whether the problems view shows any items. I would think the "folder level" annotation for there being a problem is synchronized to whether any problems were reported for some document uri that is seen as being contained within that folder. So from that perspective, I would guess this could have been a VS Code issue. However, the logs also showed :

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2020-01-14 13:10:37.233
!MESSAGE failed to send diagnostics
!STACK 1
Java Model Exception: Java Model Status ['blahTest copy' is not a valid Java identifier]
    at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:585)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:256)
    at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
    at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:298)
    at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.visit(WorkspaceDiagnosticsHandler.java:162)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
    at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.resourceChanged(WorkspaceDiagnosticsHandler.java:95)
```

I suppose if the updated diagnostics failed to be reported to the client, it could result in some issues but it's hard to say. I would be very interested in the client logs as that would mention what diagnostics were sent before/after the compilation error was fixed.

**Comment by spottedmahn** [comment]
> Is this still reproducible with the project? 

I'm not sure.  I've moved on to other projects.  Probably best to close this issue 🤷‍♂️.
