### ISSUE TITLE
[Feature Request] When renaming code, have option to update relevant references in all places

### ISSUE THREAD

**Issue by tommai78101** [redhat-developer/vscode-java#1272]
#### Description

In large code bases, or code used in many different places, sometimes, we would have to rename the variable names, the package name, change some import packages, and modify the references in all places where those references are used.

It would be nice to have a way to automatically update the references when you want to refactor the code to make naming changes.

Currently, the workaround is by doing a CTRL+SHIFT+F on the highlighted text of the name of the reference to be able to search through many documents matching those references, and then one by one, open up those documents and manually rename them.

The other workaround is by using the feature in the extension, "Change All Occurrences", by pressing CTRL+F2 on the highlighted text. However, it seems that it only affects the currently opened document, and the changed text is not applied to all documents within the project / workspace. This means, we would still need to open up each document that contains the references and then do CTRL+F2.

Unless, I'm not aware of a feature that automatically updates the references in the VSCode Java Debugger extension, could we have this feature be added to the extension? This feature can also  greatly benefit in being placed in the menu item, "Refactor...", inside the right mouse button context menu.

Thank you for considering this.

##### Environment

- Operating System: **Ubuntu 18.04.3 LTS with Linux kernel 5.3.0-generic**
- JDK version: **Java SE 1.8 (OpenJavaSDK 8)**
- Visual Studio Code version: **1.42.1**
- Java extension version: **0.55.1**

##### Expected Result

Be able to update references in the entire project / workspace as I rename the reference's name.

**Comment by fbricon** [comment]
This is provided by the "rename" feature (F2)

**Comment by tommai78101** [comment]
@fbricon Please give me a chance to verify this on Monday, tomorrow. Thanks.

**Comment by tommai78101** [comment]
@fbricon 

I can confirm it is not supported.

![image](https://user-images.githubusercontent.com/6444116/74669037-61f93680-5174-11ea-8448-6fe61849775b.png)

I wondered if I'm doing it wrong?

**Comment by fbricon** [comment]
That's strange, it works for me. Could you [turn on verbose logging](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server) and attach the output view log here (from a clean vscode start)?

**Comment by tommai78101** [comment]
@fbricon 

I saw this in the logs. I wondered if it's related.

```

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:33.583
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:33.829
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:34.082
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:34.538
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:34.540
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:35.040
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:35.051
!MESSAGE >> java/findLinks

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:35.197
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:41.098
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:41.338
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:41.778
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:42.947
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:42.958
!MESSAGE >> document/didChange

!ENTRY org.eclipse.jdt.ls.core 4 0 2020-02-17 11:13:43.021
!MESSAGE Problem converting proposal to code actions
!STACK 1
org.eclipse.core.runtime.CoreException: Invalid AST rewriter
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.ASTRewriteCorrectionProposal.addEdits(ASTRewriteCorrectionProposal.java:95)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.CUCorrectionProposal.createTextChange(CUCorrectionProposal.java:109)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.CUCorrectionProposal.createChange(CUCorrectionProposal.java:115)
	at org.eclipse.jdt.core.manipulation.ChangeCorrectionProposalCore.getChange(ChangeCorrectionProposalCore.java:150)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionFromProposal(CodeActionHandler.java:162)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:136)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:614)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:963)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalArgumentException: Document does not match the AST
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.handleException(ASTRewriteAnalyzer.java:4498)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2252)
	at org.eclipse.jdt.core.dom.ReturnStatement.accept0(ReturnStatement.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:464)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:458)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2225)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2131)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:593)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitList(ASTRewriteAnalyzer.java:444)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:435)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteParagraphList(ASTRewriteAnalyzer.java:1238)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1940)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:430)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:305)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:294)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.ASTRewriteCorrectionProposal.addEdits(ASTRewriteCorrectionProposal.java:92)
	... 14 more
Caused by: org.eclipse.core.runtime.CoreException: End Of File
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.readNext(TokenScanner.java:95)
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.readToToken(TokenScanner.java:152)
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.readToToken(TokenScanner.java:165)
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.getTokenEndOffset(TokenScanner.java:190)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2242)
	... 39 more
!SUBENTRY 1 org.eclipse.jdt.ls.core 4 0 2020-02-17 11:13:43.022
!MESSAGE Invalid AST rewriter
!STACK 0
java.lang.IllegalArgumentException: Document does not match the AST
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.handleException(ASTRewriteAnalyzer.java:4498)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2252)
	at org.eclipse.jdt.core.dom.ReturnStatement.accept0(ReturnStatement.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:464)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:458)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2225)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2131)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:593)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitList(ASTRewriteAnalyzer.java:444)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:435)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteParagraphList(ASTRewriteAnalyzer.java:1238)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1940)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:430)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:305)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:294)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.ASTRewriteCorrectionProposal.addEdits(ASTRewriteCorrectionProposal.java:92)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.CUCorrectionProposal.createTextChange(CUCorrectionProposal.java:109)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.CUCorrectionProposal.createChange(CUCorrectionProposal.java:115)
	at org.eclipse.jdt.core.manipulation.ChangeCorrectionProposalCore.getChange(ChangeCorrectionProposalCore.java:150)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionFromProposal(CodeActionHandler.java:162)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:136)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:614)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:963)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.eclipse.core.runtime.CoreException: End Of File
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.readNext(TokenScanner.java:95)
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.readToToken(TokenScanner.java:152)
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.readToToken(TokenScanner.java:165)
	at org.eclipse.jdt.internal.core.dom.rewrite.TokenScanner.getTokenEndOffset(TokenScanner.java:190)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2242)
	... 39 more

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.154
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.210
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.212
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.213
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.416
!MESSAGE Reconciled 0. Took 7 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.550
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.856
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.927
!MESSAGE begin problem for /AtsTCDInterceptor.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.927
!MESSAGE 1 problems reported for /AtsTCDInterceptor.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.940
!MESSAGE begin problem for /WebSecurityConfiguration.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.941
!MESSAGE 3 problems reported for /WebSecurityConfiguration.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.950
!MESSAGE begin problem for /AdminService.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.950
!MESSAGE 15 problems reported for /AdminService.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:43.959
!MESSAGE Validated 3. Took 85 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.214
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.864
!MESSAGE >> document/prepareRename

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.958
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.960
!MESSAGE >> workspace/executeCommand java.project.list

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.962
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.965
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.965
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.965
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.966
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.966
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.970
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:44.973
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:46.969
!MESSAGE >> document/rename

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-02-17 11:13:51.692
!MESSAGE >> workspace/executeCommand java.resolvePath

```

**Comment by fbricon** [comment]
Doesn't seem related. We're interested in the `document/prepareRename` call, which shows no exception. Can you please try with verbose logging?

**Comment by tommai78101** [comment]
@fbricon I restarted VS Code for a second time, and it now sort of worked. Once renamed, only the contents of the Java file is updated, but the file name can't be renamed, unless the updated file content is saved first. 

1. File is saved beforehand.
2. Attempt to rename the reference by pressing F2.
3. Content of the file and the file name are updated.
4. I must save this file, otherwise the next steps won't work.
5. Attempt to rename the reference back to its original name.
6. Success.

If step 4 is not done, there are times where you can't rename it back to what it was before, and you have to manually fix the file name after saving the file contents.
