### ISSUE TITLE
Initialising Workspace runs out of heap space

### ISSUE THREAD

**Issue by ppanthony** [redhat-developer/vscode-java#1304]
[Initialising Workspace slow / running out of heap space]

Any ideas on what could be causing this? Or any way to provide VS code with more RAM? 

##### Environment
- Operating System: OS X 10.14.5
- JDK version: java version "1.8.0_241"
- Visual Studio Code version: Version: 1.42.1
- Java extension version: 0.57.0

##### Steps To Reproduce
None available. Sorry. 

```
!ENTRY org.eclipse.core.jobs 4 2 2020-02-27 11:59:07.653
!MESSAGE An internal error occurred during: "Initialize Workspace".
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.core.internal.localstore.UnifiedTree.getLocalList(UnifiedTree.java:360)
	at org.eclipse.core.internal.localstore.UnifiedTree.addChildren(UnifiedTree.java:148)
	at org.eclipse.core.internal.localstore.UnifiedTree.addNodeChildrenToQueue(UnifiedTree.java:254)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:120)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:978)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:961)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1557)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.updateProjects(MavenProjectImporter.java:227)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:202)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:155)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:145)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:267)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ppanthony** [comment]
cause was workspace specific. some sort of lock possibly. rechecking out the project and reinstall vscode resolved
