### ISSUE TITLE
Classpath is incomplete, org.osgi.framework.BundleException

### ISSUE THREAD

**Issue by spottedmahn** [redhat-developer/vscode-java#1306]
Brand new project created via Gradle but I'm getting:

>Classpath is incomplete. Only syntax errors will be reported.  [more info](https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning)

![image](https://user-images.githubusercontent.com/14079228/75454811-097c2300-5944-11ea-9230-3ca2473e0531.png)

##### Environment
- Operating System: Win 10 v1909
- JDK version: openjdk version "11.0.5" 2019-10-15
- Visual Studio Code version: 1.42.1 (user setup)
- Java extension version: version: 0.57.0

##### Steps To Reproduce
1. not sure, just started a new project via gradle, done the same thing a few times before.  clearly something is different though as I didn't hit this issue previously.

[java language server log - no classpath file.txt](https://github.com/redhat-developer/vscode-java/files/4262148/no.classpath.file.txt)

##### Current Result
it's not doing it's "thing".  I don't know all the details of what it's thing, sorry.

##### Expected Result
It should be compiling my project

##### Additional Informations
<details><summary>org.osgi.framework.BundleException: Exception call stack </summary>
>!ENTRY org.eclipse.equinox.registry 4 0 2020-02-26 16:30:55.481
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.core.internal.registry.osgi.Activator.stop() of bundle org.eclipse.equinox.registry.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:919)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1029)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:370)
	at org.eclipse.osgi.container.Module.doStop(Module.java:658)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1885)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1760)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:202)
	at org.eclipse.osgi.container.Module.doStop(Module.java:658)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.eclipse.core.internal.registry.TableWriter.saveOrphans(TableWriter.java:442)
	at org.eclipse.core.internal.registry.TableWriter.saveExtensionRegistry(TableWriter.java:150)
	at org.eclipse.core.internal.registry.TableWriter.saveCache(TableWriter.java:86)
	at org.eclipse.core.internal.registry.ExtensionRegistry.stop(ExtensionRegistry.java:821)
	at org.eclipse.core.internal.registry.osgi.Activator.stopRegistry(Activator.java:156)
	at org.eclipse.core.internal.registry.osgi.Activator.stop(Activator.java:71)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:899)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:891)
	... 13 more
Root exception:
java.lang.NullPointerException
	at org.eclipse.core.internal.registry.TableWriter.saveOrphans(TableWriter.java:442)
	at org.eclipse.core.internal.registry.TableWriter.saveExtensionRegistry(TableWriter.java:150)
	at org.eclipse.core.internal.registry.TableWriter.saveCache(TableWriter.java:86)
	at org.eclipse.core.internal.registry.ExtensionRegistry.stop(ExtensionRegistry.java:821)
	at org.eclipse.core.internal.registry.osgi.Activator.stopRegistry(Activator.java:156)
	at org.eclipse.core.internal.registry.osgi.Activator.stop(Activator.java:71)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:899)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:891)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1029)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:370)
	at org.eclipse.osgi.container.Module.doStop(Module.java:658)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1885)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1760)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:202)
	at org.eclipse.osgi.container.Module.doStop(Module.java:658)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Thread.java:834)
</details>

**Comment by spottedmahn** [comment]
Java extension version: 0.57.0 not 0.55.1 as above.  can't currently update my issue...

https://twitter.com/spottedmahn/status/1233039702913175552?s=20

I'll come back and clean this after the GitHub issues are fixed...

**Comment by spottedmahn** [comment]
[Cleaned the workspace storage](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) and it started working

![image](https://user-images.githubusercontent.com/14079228/75456111-1d298880-5948-11ea-9eb6-ea1724b9e7bb.png)

**Comment by spottedmahn** [comment]
re: closing

Don't we want to get to the bottom of these things so we don't have to clean the workspace?

Isn't creating a new project a pretty basic task?

**Comment by snjeza** [comment]
Could you always reproduce the issue?
If so, could you, please, attach your project?
