### ISSUE TITLE
Project failed to load: "org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions$LookupStrategy" may not be fully initialized

### ISSUE THREAD

**Issue by spottedmahn** [redhat-developer/vscode-java#1317]
I opened up my project I've been working on for weeks and it didn't "load".  Load being the Java Build Status never finished and the status bar icon just keeps spinning.

##### Environment
- Operating System: Win 10, WSL 1
- JDK version: openjdk 11.0.5 2019-10-15
- Visual Studio Code version: 1.42.1
- Java extension version: 0.58.0

##### Steps To Reproduce
1. no clue, it just happens sometimes on open of the project

[Trace - 10.09.28 AM Sending request.txt](https://github.com/redhat-developer/vscode-java/files/4293662/Trace.-.10.09.28.AM.Sending.request.txt)

### Snippet of language support log

[Warn  - 10:10:14 AM] Mar 5, 2020, 10:10:14 AM While loading class "org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions$LookupStrategy", thread "Thread[Worker-0: Loading available Gradle versions,5,main]" timed out waiting (30134ms) for thread "Thread[Worker-1: Initialize Workspace,5,main]" to finish starting bundle "org.eclipse.buildship.core_3.1.4.v20200211-2258-s [11]". To avoid deadlock, thread "Thread[Worker-0: Loading available Gradle versions,5,main]" is proceeding but "org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions$LookupStrategy" may not be fully initialized.
Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.4.v20200211-2258-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=11] STARTED [STARTED]
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.4.v20200211-2258-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=11] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:350)
	at org.eclipse.osgi.container.Module.start(Module.java:419)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:493)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:571)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:477)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:60)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 30 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:347)
	... 11 more
Caused by: org.eclipse.osgi.framework.util.ThreadInfoReport: Thread dump

##### Current Result
The project won't load (well technically it loaded after a few minutes)

##### Expected Result
The project should load in an appropriate amount of time

##### Additional Information
As I was typing up this issue it started working 🤷‍♂️

I've attached the updated log:
[Trace - 10.09.28 AM Sending request - after it started working.txt](https://github.com/redhat-developer/vscode-java/files/4293664/Trace.-.10.09.28.AM.Sending.request.-.after.it.started.working.txt)

**Comment by jdneo** [comment]
Show be addressed by https://github.com/eclipse/buildship/commit/2d105739966ef4d07dc12b368d22553f8efcffc4

**Comment by spottedmahn** [comment]
thanks @jdneo!!
