### ISSUE TITLE
Cannot decrypt model file Illegal key size error

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-java#1322]
When opening a Quarkus Gradle project (see sample project), in the "Language Support for Java" output, I get this error:
```
[Error - 12:24:32 PM] 10-Mar-2020 12:24:32 PM Cannot decrypt model file
Illegal key size
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaModelLoader.decrypt(PythiaModelLoader.java:76)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaModelLoader.access$0(PythiaModelLoader.java:70)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaModelLoader$1.run(PythiaModelLoader.java:57)
```

##### Environment
- Operating System: macOS Catalina 10.15.2
- JDK version: 1.8.0_121
- Visual Studio Code version: 1.43
- Java extension version: 0.58.0

##### Steps To Reproduce
1. Unzip the sample project .zip file
2. Open VS Code, open File -> Open...
3. Select the `quarkus-getting-started-gradlee` folder
4. In the terminal view, select the "OUTPUT" tab and choose "Language Support for Java" in the dropdown
5. Error appears in the output

Sample project: 
[quarkus-getting-started-gradlee.zip](https://github.com/redhat-developer/vscode-java/files/4313566/quarkus-getting-started-gradlee.zip)

Java Language Server's workspace logs: https://gist.github.com/xorye/6c67df5e413c1f5d1a1c2824e60999ce

**Comment by snjeza** [comment]
@xorye you can try to disable the  [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode extension.

**Comment by snjeza** [comment]
related issue - #779
