### ISSUE TITLE
bug of create a  multi-module project

### ISSUE THREAD

**Issue by unusPanda** [redhat-developer/vscode-java#1412]
[I created a multi-module project, but the sub-module reports an error as follows
DemoApplication.java is not on the classpath of project demo, only syntax errors are reportedJava(32)]

##### Environment
- Operating System: windows 10
- JDK version: jdk-11.0.6 
- Visual Studio Code version: 1.44.2
- Java extension version:0.60.0
- springboot version:
##### Steps To Reproduce
1. [I created a multi-module project with spingboot and maven]
2. [open the  application class of sub-module]

##### Expected Result
DemoApplication.java is not on the classpath of project demo, only syntax errors are reportedJava(32)
![批注 2020-04-27 083940](https://user-images.githubusercontent.com/53925297/80324278-b00c7380-8862-11ea-9a06-70d89dcf7767.jpg)

**Comment by testforstephen** [comment]
This screenshot simply shows that your project is not being properly imported. But we need more information for further investigation. Could you share us a sample project to reproduce it? Also provide the log would help a lot. The log file can be fetched via **F1 -> Java: Open Java language server log file**

**Comment by fbricon** [comment]
make sure the parent project has pom packaging and lists modul1

**Comment by kiaoraPanda** [comment]
> This screenshot simply shows that your project is not being properly imported. But we need more information for further investigation. Could you share us a sample project to reproduce it? Also provide the log would help a lot. The log file can be fetched via **F1 -> Java: Open Java language server log file**


Java Model Exception: Java Model Status [modul1/src/main/java/com/example/modul1 [in demo] is not on its project's build path]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:583)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:256)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getKind(PackageFragmentRoot.java:530)
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForPackageFragmentRoot(PackageNode.java:168)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:136)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:477)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:74)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by kiaoraPanda** [comment]
> make sure the parent project has pom packaging and lists modul1

pom of parent project add this 	<modules>
        <module>modul1</module>
	</modules>
