### ISSUE TITLE
When writing Java code, why is the response speed of vscode java code prompt not as fast and efficient as that of Eclipse? Always wait for 1 second before appearing. . .

### ISSUE THREAD

**Issue by 395053994** [redhat-developer/vscode-java#1427]
Issue Type: <b>Bug</b>

When writing Java code, why is the response speed of vscode java code prompt not as fast and efficient as that of Eclipse? Always wait for 1 second before appearing. . .

Extension version: 0.61.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (4.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by fbricon** [comment]
@395053994 couple things you can try:
- disable all  other Java related extensions, see if one of them interferes with performance
- completion performance depends on the size of your codebase, for a large number of classes, you might want to increase the heap size given to the Java Language Server (Xmx value in `java.jdt.ls.vmargs`

**Comment by XLCYun** [comment]
Same problem here. It's impossible to use now. I have to choose to use text intellisense instead of this. 
- Disabled all extensions, and only open this extension does not solved this problem. 
- Setting `java.jdt.ls.vmargs` does not solved this problem. 

Please fix it, tell me what I can help. 
I use Remote Package to write code on my server , I don't know if it is related. 
And use JAVA OpenSDK 11.

**Comment by fbricon** [comment]
@XLCYun do you know when you started to see a performance degradation? You can install older releases from https://download.jboss.org/jbosstools/static/jdt.ls/stable/

**Comment by XLCYun** [comment]
> @XLCYun do you know when you started to see a performance degradation? You can install older releases from https://download.jboss.org/jbosstools/static/jdt.ls/stable/

Thank you. It works when I downgrade to v56. It's much more faster right now. 
The vscode intellisense tells me it needs to be at lease v57 for it to work, if I just ignore it, everything  seem fine. However I updated to v57, and it's alright. 
I think I have(I am not pretty sure) try v60, but it did not work out. . 

@395053994 Maybe you could try downgrade to v60 or older to try if the situation improved?

**Comment by XLCYun** [comment]
> @XLCYun do you know when you started to see a performance degradation? You can install older releases from https://download.jboss.org/jbosstools/static/jdt.ls/stable/

I just tried to downgrade one version by one version, and version above v59.0 is unbearable slow. 
the most currently working version is v59.0, even v59.1 is not working. 

Hope this help.

**Comment by fbricon** [comment]
Thanks that'll be helpful to narrow the regression down

**Comment by fbricon** [comment]
Strange, there should be literally no difference between 0.59 and 0.59.1

**Comment by XLCYun** [comment]
> Strange, there should be literally no difference between 0.59 and 0.59.1

Weird,  give me more time, I will try use for longer time for these versions to check if the performances do differ.

**Comment by per-steinar** [comment]
I have also been experiencing the same issue for the last 2-3 weeks. 
I have tried all versions of the plugin back to 0.58.0 and the problem appears in every version.
I have also tried to roll back VS Code (Ubuntu 18.04 and VS Code installed as snap) to 1.43.2 and Java Language Support 0.58.0 and 0.59.0, and the issue still occurs.

The issue only seems to disappear for a short while when the system has not been used for a while.  

`[2020-05-07 11:33:53.449] [exthost] [error] [redhat.java] provider FAILED
[2020-05-07 11:33:53.449] [exthost] [error] Error: The request (id: 35, method: 'textDocument/hover') has been cancelled
    at /home/USER_NAME/.vscode/extensions/redhat.java-0.61.0/dist/extension.js:1:73459
    at /home/USER_NAME/.vscode/extensions/redhat.java-0.61.0/dist/extension.js:1:73753
    at Immediate.<anonymous> (/home/USER_NAME/.vscode/extensions/redhat.java-0.58.0/dist/extension.js:1:74114)
    at processImmediate (internal/timers.js:439:21)`

**Comment by per-steinar** [comment]
I have tested some more, and it looks like the CPU usage of the language server peaks at 200 % CPU when the performance drops
`cat /proc/10198/cmdline 
/usr/lib/jvm/java-11-openjdk-amd64/bin/java--add-modules=ALL-SYSTEM--add-opensjava.base/java.util=ALL-UNNAMED--add-opensjava.base/java.lang=ALL-UNNAMED-Declipse.application=org.eclipse.jdt.ls.core.id1-Dosgi.bundles.defaultStartLevel=4-Declipse.product=org.eclipse.jdt.ls.core.product-Dfile.encoding=utf8-noverify-Xmx1G-XX:+UseG1GC-XX:+UseStringDeduplication-Dlog.level=ALL-jar/home/USER_NAME/.vscode/extensions/redhat.java-0.61.0/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar-configuration/home/USER_NAME/.config/Code/User/globalStorage/redhat.java/0.61.0/config_linux-data/home/USER_NAME/.config/Code/User/workspaceStorage/7fd5a6d7073fa1bef98ee52117dda382/redhat.java/jdt_wsroot`

**Comment by fbricon** [comment]
can you try with the default java.jdt.ls.vmargs settings (`-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m`)

**Comment by fbricon** [comment]
would be interesting to take a Thread dump when CPU peaks at 200% (`jstack` is your friend)

**Comment by per-steinar** [comment]
Ok, that's possible. Where would you like me to send it?

**Comment by fbricon** [comment]
you can attach it here as a zip file, or send it to <my github handle> at redhat.com, if you want to keep is private

**Comment by per-steinar** [comment]
I have sent it by email.

**Comment by fbricon** [comment]
@per-steinar thanks. 
From what I can see com.microsoft.java.test.plugin is pretty busy computing stuff. Can you check how vscode-java behaves if you disable the vscode-java-test extension?

**Comment by per-steinar** [comment]
@fbricon I have vscode-java-test extension and the performance issues seem to go away. However, i have re-enablet it, and the performance issues has not occurred again. However, I have upgaded to VS Code 1.45.0, perhaps it contain some mind of fix.

**Comment by 395053994** [comment]
vscode java code hint is still slow and need to wait 0.5 seconds or 1 second,
There is still no Eclipse, IDEA IDE responsive and agile, which is very frustrating. The same is the Eclipse JDT engine, why is Eclipse so responsive and agile? You have not found the cause of the problem!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Per-Steinar Karlsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午5:24
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
@fbricon I have vscode-java-test extension and the performance issues seem to go away. However, i have re-enablet it, and the performance issues has not occurred again. However, I have upgraded to VS Code 1.45.0, perhaps it contain some mind of fix.

**Comment by 395053994** [comment]
vscode java code hint is still slow and need to wait 0.5 seconds or 1 second,
There is still no Eclipse, IDEA IDE responsive and agile, which is very frustrating. The same is the Eclipse JDT engine, why is Eclipse so responsive and agile? You have not found the cause of the problem!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fred Bricon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 晚上10:42
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
@per-steinar thanks.
 From what I can see com.microsoft.java.test.plugin is pretty busy computing stuff. Can you check how vscode-java behaves if you disable the vscode-java-test extension?

**Comment by 395053994** [comment]
vscode java code hint is still slow and need to wait 0.5 seconds or 1 second,
There is still no Eclipse, IDEA IDE responsive and agile, which is very frustrating. The same is the Eclipse JDT engine, why is Eclipse so responsive and agile? You have not found the cause of the problem!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Per-Steinar Karlsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 晚上9:18
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
Ok, that's possible. Where would you like me to send it?

**Comment by 395053994** [comment]
vscode java code hint is still slow and need to wait 0.5 seconds or 1 second,
There is still no Eclipse, IDEA IDE responsive and agile, which is very frustrating. The same is the Eclipse JDT engine, why is Eclipse so responsive and agile? You have not found the cause of the problem!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Per-Steinar Karlsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 晚上9:48
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
I have sent it by email.

**Comment by 395053994** [comment]
vscode java code hint is still slow and need to wait 0.5 seconds or 1 second,
There is still no Eclipse, IDEA IDE responsive and agile, which is very frustrating. The same is the Eclipse JDT engine, why is Eclipse so responsive and agile? You have not found the cause of the problem!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"XLCYun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 晚上7:04
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





  
Strange, there should be literally no difference between 0.59 and 0.59.1
  
Weird,  give me more time, I will try use for longer time for these versions to check if the performances do differ.

**Comment by 1470391328** [comment]
I have the similair problem, the auto_completion works terrible

**Comment by fbricon** [comment]
Guys, please check the completion performance when there are no other Java related extensions installed (not just disabled). Depending on your platform they are located in :

- Windows %USERPROFILE%\.vscode\extensions
- Mac $HOME/.vscode/extensions
- Linux $HOME/.vscode/extensions

You might need to execute the "clean the Java language server workspace directory"

**Comment by 395053994** [comment]
After continuous analysis, the reason why the code prompt is slow should be
The following extension: Caused by the Visual Studio IntelliCode extension, because I disabled it, while using other AI extensions the code prompts quickly





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fred Bricon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 下午4:59
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
Guys, please check the completion performance when there are no other Java related extensions installed (not just disabled). Depending on your platform they are located in :
  
Windows %USERPROFILE%.vscode\extensions
 
Mac $HOME/.vscode/extensions
 
Linux $HOME/.vscode/extensions
  
You might need to execute the "clean the Java language server workspace directory"

**Comment by 395053994** [comment]
After continuous analysis, the reason why the code prompt is slow should be
The following extension: Caused by the Visual Studio IntelliCode extension, because I disabled it, while using other AI extensions the code prompts quickly



In addition, pressing the content assist key also needs to wait for one second before the code prompt appears.




------------------ 原始邮件 ------------------
发件人:&nbsp;"Fred Bricon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 下午4:59
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
Guys, please check the completion performance when there are no other Java related extensions installed (not just disabled). Depending on your platform they are located in :
  
Windows %USERPROFILE%.vscode\extensions
 
Mac $HOME/.vscode/extensions
 
Linux $HOME/.vscode/extensions
  
You might need to execute the "clean the Java language server workspace directory"

**Comment by per-steinar** [comment]
I have some days been running without the intelliCode-extention, but the issue still occurs. You may contact me by email  if you want me to do any tests.

**Comment by kgoedert** [comment]
I have this issue too. My version o vscode and  the java extension are both up to date. I disabled the intellicode extension and it made no difference. But I noted something yesterday. It was happening only on test classes by some reason. In classes without @Test or any other test annotations, everything was normal.

**Comment by 395053994** [comment]
Since we have all found the problem, we should pay attention to solving it in the next iteration. Found that many times they iterate are some unimportant questions, I do not know why? For example: the console text output has a blank space, and these problems cannot be copied. I have lost faith in vscode.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Per-Steinar Karlsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 下午5:41
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
I have some days been running without the intelliCode-extention, but the issue still occurs. You may contact me by email  if you want me to do any tests.

**Comment by 395053994** [comment]
It is not difficult to mention a lot of bugs that are obvious. But bugs that do affect coding have never been fixed, and it is really difficult for commercial products to improve.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kgoedert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 晚上6:04
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
I have this issue too. My version o vscode and  the java extension are both up to date. I disabled the intellicode extension and it made no difference. But I noted something yesterday. It was happening only on test classes by some reason. In classes without @test or any other test annotations, everything was normal.

**Comment by 395053994** [comment]
It is not difficult to mention a lot of bugs that are obvious. But bugs that do affect coding have never been fixed, and it is really difficult for commercial products to improve.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Per-Steinar Karlsen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 下午5:41
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
I have some days been running without the intelliCode-extention, but the issue still occurs. You may contact me by email  if you want me to do any tests.

**Comment by 395053994** [comment]
Since we have all found the problem, we should pay attention to solving it in the next iteration. Found that many times they iterate are some unimportant questions, I do not know why? For example: the console text output has a blank space, and these problems cannot be copied. I have lost faith in vscode.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kgoedert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 晚上6:04
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
I have this issue too. My version o vscode and  the java extension are both up to date. I disabled the intellicode extension and it made no difference. But I noted something yesterday. It was happening only on test classes by some reason. In classes without @test or any other test annotations, everything was normal.

**Comment by snjeza** [comment]
@per-steinar @395053994 @kgoedert Could you attach a sample project reproducing this issue?

**Comment by kgoedert** [comment]
This is the sample project I was working on, and noticed the problem.
https://github.com/kgoedert/hello-quarkus/tree/practice-3

Does this help, or you need me to attach something more specific?

**Comment by snjeza** [comment]
@kgoedert Could you send your settings.json?

**Comment by kgoedert** [comment]
{
  "gitlens.advanced.messages": {
    "suppressShowKeyBindingsNotice": true
  },
  "gitlens.historyExplorer.enabled": true,
  "editor.minimap.enabled": false,
  "workbench.startupEditor": "newUntitledFile",
  "window.zoomLevel": 0,
  "latex-workshop.view.pdf.viewer": "tab",
  "python.testing.unittestEnabled": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": false
  },
  "gitlens.gitExplorer.files.layout": "auto",
  "files.exclude": {
    "**/.git": false,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "workbench.editor.enablePreview": false,
  "editor.largeFileOptimizations": false,
  "terminal.integrated.rendererType": "dom",
  "java.errors.incompleteClasspath.severity": "ignore",
  "editor.wordWrapColumn": 150,
  "editor.wordWrap": "wordWrapColumn",
  "java.completion.guessMethodArguments": true,
  "java.configuration.updateBuildConfiguration": "automatic",
  "extensions.ignoreRecommendations": false,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "workbench.colorTheme": "Nord",
  "eslint.alwaysShowStatus": true,
  "explorer.confirmDragAndDrop": false,
  "sync.gist": "934ab495b3f0204e8c836ab1d606a98d",
  "editor.renderControlCharacters": false,
  "zenMode.hideTabs": false,
  "zenMode.hideStatusBar": false,
  "zenMode.centerLayout": false,
  "gitlens.views.repositories.files.layout": "auto",
  "gitlens.views.fileHistory.enabled": true,
  "gitlens.views.lineHistory.enabled": true,
  "tslint.alwaysShowRuleFailuresAsWarnings": true,
  "prettier.printWidth": 120,
  "prettier.singleQuote": true,
  "prettier.arrowParens": "always",
  "java.home": "/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home",
  "java.debug.settings.showHex": true,
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "terminal.external.osxExec": "iTerm2.app",
  "terminal.integrated.fontFamily": "Hack Nerd Font",
  "java.configuration.checkProjectSettingsExclusions": false,
  "[java]": {
    "editor.defaultFormatter": "redhat.java"
  },
  "quarkus.tools.alwaysShowWelcomePage": false,
  "python.jediEnabled": false,
  "java.completion.favoriteStaticMembers": [
    "org.junit.Assert.*",
    "org.junit.Assume.*",
    "org.junit.jupiter.api.Assertions.*",
    "org.junit.jupiter.api.Assumptions.*",
    "org.junit.jupiter.api.DynamicContainer.*",
    "org.junit.jupiter.api.DynamicTest.*",
    "org.mockito.Mockito.*",
    "org.mockito.ArgumentMatchers.*",
    "org.mockito.Answers.*",
    "org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*",
    "org.springframework.test.web.servlet.result.MockMvcResultMatchers.*",
    "org.hamcrest.Matchers.*",
    "org.hamcrest.MatcherAssert.*",
    "io.restassured.RestAssured.*"
  ],
  "go.formatTool": "goimports",
  "go.useLanguageServer": true,
  "files.associations": {
  
    "*.java": "java"
  },
  "java.semanticHighlighting.enabled": true,
  "editor.formatOnSave": true,
  "java.saveActions.organizeImports": true
}

**Comment by snjeza** [comment]
@kgoedert I can't reproduce the issue when using your settings. It is reproducible with the following settings:
```
"java.completion.maxResults": 0,
```
Could you try to disable all other extensions and only keep "Language Support For Java"?

**Comment by 395053994** [comment]
Because the project is a commercial project, it cannot be disclosed due to confidentiality restrictions. For example: you can create a 30-module Maven project to test and see how, my current project is like this. The version before idea IDE 2019 will also be very slow and stupid. After the 2019 version is thoroughly optimized, the speed is amazing. You can experience it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Snjeza"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 凌晨0:39
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
@per-steinar @395053994 @kgoedert Could you attach a sample project reproducing this issue?

**Comment by 395053994** [comment]
Because the project is a commercial project, it cannot be disclosed due to confidentiality restrictions. For example: you can create a 30-module Maven project to test and see how, my current project is like this. The version before idea IDE 2019 will also be very slow and stupid. After the 2019 version is thoroughly optimized, the speed is amazing. You can experience it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kgoedert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 凌晨1:46
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
This is the sample project I was working on, and noticed the problem.
 https://github.com/kgoedert/hello-quarkus/tree/practice-3
 
Does this help, or you need me to attach something more specific?

**Comment by 395053994** [comment]
Because the project is a commercial project, it cannot be disclosed due to confidentiality restrictions. For example: you can create a 30-module Maven project to test and see how, my current project is like this. The version before idea IDE 2019 will also be very slow and stupid. After the 2019 version is thoroughly optimized, the speed is amazing. You can experience it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Snjeza"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 凌晨2:17
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
@kgoedert Could you send your settings.json?

**Comment by 395053994** [comment]
Because the project is a commercial project, it cannot be disclosed due to confidentiality restrictions. For example: you can create a 30-module Maven project to test and see how, my current project is like this. The version before idea IDE 2019 will also be very slow and stupid. After the 2019 version is thoroughly optimized, the speed is amazing. You can experience it.






------------------ 原始邮件 ------------------
发件人:&nbsp;"Snjeza"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 凌晨0:39
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
@per-steinar @395053994 @kgoedert Could you attach a sample project reproducing this issue?

**Comment by 395053994** [comment]
Because the project is a commercial project, it cannot be disclosed due to confidentiality restrictions. For example: you can create a 30-module Maven project to test and see how, my current project is like this. The version before idea IDE 2019 will also be very slow and stupid. After the 2019 version is thoroughly optimized, the speed is amazing. You can experience it.






------------------ 原始邮件 ------------------
发件人:&nbsp;"kgoedert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 凌晨1:46
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
This is the sample project I was working on, and noticed the problem.
 https://github.com/kgoedert/hello-quarkus/tree/practice-3
 
Does this help, or you need me to attach something more specific?

**Comment by 395053994** [comment]
Because the project is a commercial project, it cannot be disclosed due to confidentiality restrictions. For example: you can create a 30-module Maven project to test and see how, my current project is like this. The version before idea IDE 2019 will also be very slow and stupid. After the 2019 version is thoroughly optimized, the speed is amazing. You can experience it.






------------------ 原始邮件 ------------------
发件人:&nbsp;"Snjeza"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 凌晨2:17
收件人:&nbsp;"redhat-developer/vscode-java"<vscode-java@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [redhat-developer/vscode-java] Slow code completion (#1427)





 
@kgoedert Could you send your settings.json?

**Comment by XLCYun** [comment]
Hi, it's been 17 days since my last comment, I am using the newest version now, and enable whole `Java Extension Pack`. And it seems this problem occurs and only occurs when I am writing my large unit test code. It's usual for me to write multiple unit test cases in a file over 500+ lines, and sometimes even more, and when it's too large, it got slow. 
And in `java build status` output, it required more time to `Building`, `Validate Document` and `Publish Diagnostics`. I don't know if this is related. So I think it's a problem with the Java Language Server? Or at least it is related with Test Runner or test annotation? 
I am new to Java, really hope I can help more. Thanks.

**Comment by kgoedert** [comment]
> @kgoedert I can't reproduce the issue when using your settings. It is reproducible with the following settings:
> 
> ```
> "java.completion.maxResults": 0,
> ```
> 
> Could you try to disable all other extensions and only keep "Language Support For Java"?

I disable the other extensions and it helped a lot. Haven't used it much to see it the problem persists. Now, I just have to find which one of the extensions if being the problem

**Comment by fbricon** [comment]
Regardless of the slowness induced by 3rd party plugins, @Eskibear is working on restoring snappy completion in vscode-java (see https://github.com/microsoft/vscode/issues/96779 and https://github.com/microsoft/language-server-protocol/issues/1003).
