### ISSUE TITLE
change symbal error

### ISSUE THREAD

**Issue by rcl4444** [redhat-developer/vscode-java#1439]
##### Environment
- Operating System:
Windows_NT x64 10.0.17763
- JDK version:
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
- Visual Studio Code version:
1.45.0 (system setup)
- Java extension version:
Language Support for Java(TM) by Red Hat 0.61.0
##### Steps To Reproduce
1. [step 1]
select class right click to modify symbol
![image](https://user-images.githubusercontent.com/19640490/81463636-90276900-91ed-11ea-8460-eb63bea17854.png)

2. [step 2]
```
[Error - 下午12:05:18] Request textDocument/rename failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:126)
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:1)
	at java.util.Collections.indexedBinarySearch(Collections.java:332)
	at java.util.Collections.binarySearch(Collections.java:320)
	at org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:799)
	at org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:784)
	at org.eclipse.text.edits.TextEdit.addChild(TextEdit.java:340)
	at org.eclipse.jdt.internal.corext.refactoring.changes.TextChangeCompatibility.insert(TextChangeCompatibility.java:87)
	at org.eclipse.jdt.internal.corext.refactoring.changes.TextChangeCompatibility.addTextEdit(TextChangeCompatibility.java:45)
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.rename.RenameTypeProcessor.addConstructorRenames(RenameTypeProcessor.java:1252)
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.rename.RenameTypeProcessor.createChange(RenameTypeProcessor.java:1148)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.createChange(ProcessorBasedRefactoring.java:290)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:125)
	at org.eclipse.jdt.ls.core.internal.handlers.RenameHandler.rename(RenameHandler.java:91)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$21(JDTLanguageServer.java:698)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:74)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```

**Comment by rcl4444** [comment]
When I operate in the class definition file, the above error occurs in the calling interface

**Comment by fbricon** [comment]
Can you provide a sample project reproducing the error?

**Comment by rcl4444** [comment]
@fbricon 
[sample](https://github.com/rcl4444/mytest/tree/master)
![image](https://user-images.githubusercontent.com/19640490/81498692-efbe6b00-92f8-11ea-992b-d4e8fe099fa4.png)
![image](https://user-images.githubusercontent.com/19640490/81498695-f947d300-92f8-11ea-8613-c238d146a9e7.png)

**Comment by fbricon** [comment]
Can't reproduce with vscode-java 1.46. Closing.
