### ISSUE TITLE
"IllegalArgumentException: Path must include project and resource name" for some folders

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-java#1447]
Java extension is not working when opening some folders (it works for soem others).
For instance when opening the folder examples of https://github.com/apache/camel-k/tree/master/examples

there is this error in output:

```
[Error - 3:33:47 PM] May 13, 2020 3:33:47 PM An internal error occurred during: "Initialize workspace".
Path must include project and resource name: /examples
java.lang.IllegalArgumentException: Path must include project and resource name: /examples
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2122)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:311)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$1.run(JDTLanguageServer.java:277)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

##### Environment
- Operating System: Fedora 31
- JDK version: Java 8
- Visual Studio Code version: 1.45.0
- Java extension version: 0.61.0

##### Steps To Reproduce
1. clone locally https://github.com/apache/camel-k/
2. in VS Code, File -> Open Folder...
3. select the examples folder inside the cloned repository
4. Open one of the Java files
--> stack trace in output log
--> several errors reported in files

[Please attach a sample project reproducing the error]

full log with trace activated:
https://gist.github.com/apupier/ca016099587a7730745d1841b094f7e6

##### Additional Informations

it was working few weeks/months ago

**Comment by apupier** [comment]
found out that it was because there was already some .project file. (whcih i already deleted withotu keeping them of course sigh)

it would be nice to have an improved errro message in case there is a .project exisitng but the project cannot be loaded.

**Comment by pradhyu** [comment]
> found out that it was because there was already some .project file. (whcih i already deleted withotu keeping them of course sigh)
> 
> it would be nice to have an improved errro message in case there is a .project exisitng but the project cannot be loaded.

Thanks man deleting the .project dir made things work for me.

**Comment by dgkm** [comment]
> found out that it was because there was already some .project file. (whcih i already deleted withotu keeping them of course sigh)
> 
> it would be nice to have an improved errro message in case there is a .project exisitng but the project cannot be loaded.

The error message is not clear for this problem and it took us almost few months before we could find this issue on github.

**Comment by snjeza** [comment]
Related issue - https://github.com/redhat-developer/vscode-java/issues/2436
