### ISSUE TITLE
Global "java.jdt.ls.vmargs" Setting Ignored

### ISSUE THREAD

**Issue by sebascomeau** [redhat-developer/vscode-java#1589]
I'm working behind a corporate proxy. I need to set proxy settings in various places to make everything works but in my case when running my app with the proxy setting in "java.jdt.ls.vmargs" it doesn't work. It's working though if I put the same value into the launch.json file under the "vmArgs" key but in "java.jdt.ls.vmargs" the setting it's ignored. My app need to download at runtime a embedmongo zip when running locally.

I followed the instrution to add proxy setting into user setting json.
https://github.com/redhat-developer/vscode-java/wiki/Using-a-Proxy

I tried previous verions of vscode-java but no success. I don't know if I'm doing something wrong.

##### Environment
- Operating System: Windows 10
- JDK version: AdoptOpenJDK 8, 11, 14
- Visual Studio Code version: 1.48.1
- Java extension version: 0.65.0

##### Steps To Reproduce
1. Added proxy settings in settings.json under "java.jdt.ls.vmargs" setting key.
2. Write code that will downloadStream outside that required proxy to be set.

##### Current Result
JVM cannot download the embedmongo zip file by using the vmArgs proxy setting.

##### Expected Result
JVM should download the embedmongo zip file by using the vmArgs proxy setting.

##### Additional Informations

Here's my java settings in my settings.json file.

```json
{
  "java.completion.favoriteStaticMembers": [
    "org.assertj.core.api.Assertions.*",
    "org.junit.Assume.*",
    "org.junit.jupiter.api.Assertions.*",
    "org.junit.jupiter.api.Assumptions.*",
    "org.junit.jupiter.api.DynamicContainer.*",
    "org.junit.jupiter.api.DynamicTest.*",
    "org.mockito.Mockito.*",
    "org.mockito.ArgumentMatchers.*",
    "org.mockito.Answers.*",
    "org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*",
    "org.springframework.test.web.servlet.result.MockMvcResultMatchers.*"
  ],
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-1.8",
      "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.265.01-hotspot",
      "default": true
    },
    {
      "name": "JavaSE-11",
      "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.8.10-hotspot"
    },
    {
      "name": "JavaSE-14",
      "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-14.0.2.12-hotspot"
    }
  ],
  "java.configuration.updateBuildConfiguration": "automatic",
  "java.home": "C:\\Program Files\\AdoptOpenJDK\\jdk-14.0.2.12-hotspot",
  "java.jdt.ls.vmargs": "-Dhttp.proxyHost=proxy.prv -Dhttp.proxyPort=80 -Dhttps.proxyHost=proxy.prv -Dhttps.proxyPort=443",
  "java.maven.downloadSources": true,
  "java.project.importOnFirstTimeStartup": "automatic",
  "java.saveActions.organizeImports": true,
  "java.semanticHighlighting.enabled": true,
}
```

**Comment by testforstephen** [comment]
"java.jdt.ls.vmargs" setting is used to specify extra VM arguments to launch Java language server itself. The debugger won't consume such setting. When your business logic has download service, exactly you should leverage vmArgs in launch.json for that.

**Comment by sebascomeau** [comment]
I followed the extension documentation.
https://github.com/redhat-developer/vscode-java/wiki/Using-a-Proxy

The same issue was raised in 2019 and this was fixed.
https://github.com/redhat-developer/vscode-java/issues/1175

**Comment by sebascomeau** [comment]
I need those proxy settings because the embed mongo db executable need to be downloaded at runtime whe running the app locally.

Url that need to be downloaded with proxy:
https://downloads.mongodb.org/win32/mongodb-win32-x86_64-3.5.5.zip

```
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: prepare executable
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:64) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:45) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoServer(EmbeddedMongoAutoConfiguration.java:113) ~[spring-boot-autoconfigure-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	... 79 common frames omitted
Caused by: java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-3.5.5.zip
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	... 86 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_265]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_265]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_265]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_265]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_265]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_265]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_265]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_265]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681) ~[na:1.8.0_265]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_265]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_265]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_265]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_265]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_265]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[na:1.8.0_265]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570) ~[na:1.8.0_265]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_265]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[na:1.8.0_265]
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
	... 90 common frames omitted
```

**Comment by sebascomeau** [comment]
@xxbeanxx explained to me the different of vmArgs in launch.json and settings.json. The one in settings.json is for the language server, in my case Maven. The one in launch.json if for the application.

Thanks for the clarification.

**Comment by testforstephen** [comment]
Nice to know you figure it out. i will close the issue. If you need more information, feel free to reopen it.
