### ISSUE TITLE
ResourceException: Problems encountered while copying resources.

### ISSUE THREAD

**Issue by Xiot** [redhat-developer/vscode-java#169]
I started getting the error below popping up every once in a while since upgrading to one of the later releases.

##### Environment
- Operating System: OSX Sierra - 10.12.3
- JDK version: 8.121
- Visual Studio Code version: 1.10.2
- Java extension version: 0.0.13

##### Steps To Reproduce
1. Ever since the latest update I have been receiving the error below. This is happening on an Android project.

```
[Error - 5:00:10 PM] Mar 20, 2017 2:50:47 PM JavaBuilder handling ImageBuilderInternalException while building: jdt.ls-java-project
Problems encountered while copying resources.
org.eclipse.core.internal.resources.ResourceException: Problems encountered while copying resources.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.copy(FileSystemResourceManager.java:336)
	at org.eclipse.core.internal.resources.Resource.copy(Resource.java:545)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.copyResource(AbstractImageBuilder.java:383)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder$3.visit(BatchImageBuilder.java:231)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.copyExtraResourcesBack(BatchImageBuilder.java:200)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.cleanOutputFolders(BatchImageBuilder.java:124)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:47)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:180)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Contains: Resource '/jdt.ls-java-project/src/pom.xml' does not exist.
```

Unfortunately, I am not able to upload a sample project right now.

**Comment by leonardoam** [comment]
I'm having the same issue here. Any updates? I also have the following exception:

`[Error - 3:44:28 PM] Mar 27, 2017 3:44:24 PM Problem importing to workspace
The project description file (.project) for 'bi-internal' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
org.eclipse.core.internal.resources.ResourceException: The project description file (.project) for 'bi-internal' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:901)
	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:904)
	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:774)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1056)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1102)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.updateProjects(MavenProjectImporter.java:109)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:92)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:104)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)`

**Comment by fbricon** [comment]
did you delete some files?

**Comment by fbricon** [comment]
Most likely, you can fix the problem by wiping out  %APPDATA%\Code\User\workspaceStorage (or ~/Library/Application Support/Code/User/workspaceStorage on MacOS) and restart vscode

**Comment by leonardoam** [comment]
I'm on Linux (Antergos), could you get me the corresponding path? I probably deleted some files trying to solve the first issue (mentioned by Xiot).

**Comment by leonardoam** [comment]
Found it:

Path for Linux users: .config/Code/User/workspaceStorage/
I'm trying this solution right now (I'll try reinstalling instead of restarting, because my Visual Code seems to be pretty messed up).

**Comment by leonardoam** [comment]
UPDATE:
After cleaning .config/Code and reinstalling Visual Code, the .project exception was fixed but now I got this exception whenever I try to use suggestions:

```[Error - 4:12:30 PM] Mar 27, 2017 4:12:02 PM Problem with codeComplete for file:///home/leonardo/IdeaProjects/bi-internal/java/src/main/java/com/arquivei/internal/ExecutePipeline.java
null
java.util.concurrent.CancellationException
	at org.eclipse.lsp4j.jsonrpc.CompletableFutures.lambda$computeAsync$0(CompletableFutures.java:29)
	at org.eclipse.jdt.ls.core.internal.CancellableProgressMonitor.isCanceled(CancellableProgressMonitor.java:36)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.checkCancel(CompletionEngine.java:1818)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.acceptType(CompletionEngine.java:1315)
	at org.eclipse.jdt.internal.core.SearchableEnvironmentRequestor.acceptType(SearchableEnvironmentRequestor.java:115)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypesInBinaryPackage(NameLookup.java:1087)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:1021)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:964)
	at org.eclipse.jdt.internal.core.NameLookup.findAllTypes(NameLookup.java:330)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:997)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:964)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findTypes(SearchableEnvironment.java:670)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findTypes(SearchableEnvironment.java:466)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findTypesAndPackages(CompletionEngine.java:10832)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnSingleNameReference(CompletionEngine.java:3451)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:1849)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2075)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:131)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:357)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:345)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:79)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.lambda$0(CompletionHandler.java:39)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)```

**Comment by Xiot** [comment]
I may have switched branches at some point.
I'm currently using both Android Studio and VSCode at the same time depending on what I need to do.

**Comment by gorkem** [comment]
@leonardoam This exception indicates that VSCode sends a cancellation of the code assist. I wonder if some other extension that provides keybindings is interfering?

**Comment by gorkem** [comment]
@fbricon I think the case that @Xiot has with multiple tools working on same codebase, is why we should rethink about how we run the builders. 

One idea is to tell the builders to stop copying resources during build. Unlike Eclipse etc. we delegate that sort of functionality build tasks.

**Comment by fbricon** [comment]
@gorkem if anything, that should be an optional behavior, as that'd make, for instance, developing a spring-boot app while doing spring-boot:run, much less productive.

**Comment by gorkem** [comment]
@fbricon Does `spring-boot:run` depends on resources (in addition to compiled files) to be copied as well?

**Comment by fbricon** [comment]
@gorkem possibly :-)

**Comment by leonardoam** [comment]
@gorkem I'm using the following extensions:

Git Blame by Wade Anderson
Git History by Don Jayamanne
Git Project Manager by Felipe Caputo
gitignore by Codezombie
Java Language Support by George Fraser
Java Snippets Taiwo Kareem
Language Support for Java(Tm) by Red Hat
MagicPython by MagicStack Inc.
Markdown Theme Kit by Microsoft
Material-theme by zhuangtongfa
Python by Don Jayamanne
Python for VSCode by Thomas Haakon Townsend
vscode-icons by Roberto Huertas

I'll try later uninstalling other extensions and see if the problem occurs.

**Comment by leonardoam** [comment]
UPDATE: I tried deactivating all extensions and the error persists.

**Comment by fbricon** [comment]
@Xiot does your android project contain one or more pom.xml files?

**Comment by Xiot** [comment]
@fbricon Nope. Don't have any pom.xml

**Comment by stact** [comment]
Wow this post if from 2017 and solved the issue 💯 

You can clean the workspace directory in the following way:

Open the command palette (F1)
select Java: Clean the Java Language Server Workspace
select Restart and delete from the confirmation prompt

Thx @fbricon
