### ISSUE TITLE
ClassFormatException - trying to index something that is not a class.

### ISSUE THREAD

**Issue by mikerussellnz** [redhat-developer/vscode-java#170]
Error when application references icu4j-2.6.1.jar.   Appears to be attempting to index file named "LocaleElements_zh__PINYIN" which is not a class file. 

[Error - 6:28:33 PM] 24/03/2017 6:25:00 PM Unable to index C:/Users/twlrlm/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar|Lcom/ibm/icu/impl/data/LocaleElements_zh__PINYIN;
null
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:406)
	at org.eclipse.jdt.internal.core.nd.indexer.Indexer.addElement(Indexer.java:677)
	at org.eclipse.jdt.internal.core.nd.indexer.Indexer.rescanArchive(Indexer.java:541)
	at org.eclipse.jdt.internal.core.nd.indexer.Indexer.rescan(Indexer.java:231)
	at org.eclipse.jdt.internal.core.nd.indexer.Indexer.lambda$0(Indexer.java:115)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:182)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Warn  - 6:30:46 PM] 24/03/2017 6:25:00 PM The Java indexing could not index C:/Users/twlrlm/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar|com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class. This .class file doesn't follow the class file format specification. Please report this issue against the .class file vendor

**Comment by gorkem** [comment]
Filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=514175 for eclipse.jdt.core

**Comment by fbricon** [comment]
@mikerussellnz this version of icu4j is known to be broken (see [these](https://bugs.eclipse.org/bugs/show_bug.cgi?id=197733) [bugs](http://stackoverflow.com/a/3143924)). You should try to use a more recent version if you can
