### ISSUE TITLE
java.io.IOException: Buffer is closed at org.eclipse.jdt.internal.core.CompilationUnit.getContents(CompilationUnit.java:695)

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#1740]
I've had the following exception occur in a `package-info.java` file. Most likely this was due to formatting the Java sources outside VS Code. There was no way to make the errors go away, except restarting VS Code.
> java.io.IOException: Buffer is closed at org.eclipse.jdt.internal.core.CompilationUnit.getContents(CompilationUnit.java:695)

##### Environment
- Operating System: Windows 10
- JDK version: 15.0.1
- Visual Studio Code version: 1.52.0
- Java extension version: v0.72.0

##### Steps To Reproduce
I don't have ready-made reproducible steps, but it should be reproducible by just editing Java sources outside of VS Code.

##### Current Result

![Inkedsnip_LI](https://user-images.githubusercontent.com/15714253/101990392-1dacc900-3ca7-11eb-95e1-46f4d23900a3.png)

##### Expected Result

No errors.

**Comment by katorly** [comment]
I've just encountered the same issue.
I was coding a java program on my computer **inside vscode** that has many classes for about 3 hours, and vscode suddenly popped out this.
Reloading the vscode will make everything normal again.
 
im using JDK 17, Windows 10.

**Comment by thisisrajneel** [comment]
thanks for this @katorly
