### ISSUE TITLE
Sometimes several objects are shown in red after a small change, saying it can not find the type

### ISSUE THREAD

**Issue by jonathanvila** [redhat-developer/vscode-java#1766]
[provide a description of the issue]

##### Environment
- Operating System: Fedora 33
- JDK version: 11.0.2
- Visual Studio Code version: 1.52.1
- Java extension version:

##### Steps To Reproduce
1. [step 1]
It doesn't happen always, but happens often. To change one type somewhere and that triggers something and shows lots of classes as not found.

https://user-images.githubusercontent.com/1836434/104616247-59fa8d00-568a-11eb-8a29-31159179c0d4.mp4

2. [step 2]

[Please attach a sample project reproducing the error]
https://github.com/jonathanvila/windup-operator

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
[languag-server.log](https://github.com/redhat-developer/vscode-java/files/5815628/languag-server.log)
Basically this is the error inside : 
`
org.osgi.framework.BundleException: Exception in org.eclipse.lsp4mp.jdt.core.MicroProfileCorePlugin.stop() of bundle org.eclipse.lsp4mp.jdt.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:891)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1025)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:370)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1886)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1761)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:202)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Workspace is closed.
	at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:432)
	at org.eclipse.lsp4mp.jdt.internal.core.MicroProfilePropertiesListenerManager.destroy(MicroProfilePropertiesListenerManager.java:245)
	at org.eclipse.lsp4mp.jdt.core.MicroProfileCorePlugin.stop(MicroProfileCorePlugin.java:39)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:871)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:863)
	... 13 more
Root exception:
java.lang.IllegalStateException: Workspace is closed.
`

**Comment by snjeza** [comment]
@jonathanvila could you try to disable the Quarkus extension and reproduce the issue?
