### ISSUE TITLE
redhat.java-0.73.0 [redhat.java] provider FAILED

### ISSUE THREAD

**Issue by weathery** [redhat-developer/vscode-java#1774]
##### Error Log
``` CommandLine
[2021-01-19 17:08:33.744] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/admin/.vscode/extensions/vscjava.vscode-java-debug-0.30.0/dist/extension
[2021-01-19 17:08:33.777] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-pack {"startup":false,"extensionId":{"value":"vscjava.vscode-java-pack","_lower":"vscjava.vscode-java-pack"},"activationEvent":"onLanguage:java"}
[2021-01-19 17:08:33.777] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/admin/.vscode/extensions/vscjava.vscode-java-pack-0.12.1/out/extension
[2021-01-19 17:08:34.197] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2021-01-19 17:09:29.105] [exthost] [error] [redhat.java] provider FAILED
[2021-01-19 17:09:29.106] [exthost] [error] Error: The request (id: 1, method: 'textDocument/hover') has been cancelled
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76464
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
[2021-01-19 17:09:29.107] [exthost] [error] [redhat.java] provider FAILED
[2021-01-19 17:09:29.107] [exthost] [error] Error: The request (id: 2, method: 'textDocument/hover') has been cancelled
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76464
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
[2021-01-19 17:09:29.107] [exthost] [error] [redhat.java] provider FAILED
[2021-01-19 17:09:29.107] [exthost] [error] Error: The request (id: 3, method: 'textDocument/hover') has been cancelled
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76464
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
[2021-01-19 17:09:29.108] [exthost] [error] [redhat.java] provider FAILED
[2021-01-19 17:09:29.108] [exthost] [error] Error: The request (id: 4, method: 'textDocument/hover') has been cancelled
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76464
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
[2021-01-19 17:09:29.108] [exthost] [error] [redhat.java] provider FAILED
[2021-01-19 17:09:29.108] [exthost] [error] Error: The request (id: 5, method: 'textDocument/hover') has been cancelled
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76464
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
[2021-01-19 17:09:29.109] [exthost] [error] [redhat.java] provider FAILED
[2021-01-19 17:09:29.109] [exthost] [error] Error: The request (id: 6, method: 'textDocument/hover') has been cancelled
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76464
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
[2021-01-19 17:09:29.109] [exthost] [error] [redhat.java] provider FAILED
[2021-01-19 17:09:29.109] [exthost] [error] Error: The request (id: 7, method: 'textDocument/hover') has been cancelled
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76464
	at c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
```

##### Environment
- Operating System: Windows
- JDK version: oracle JDK-11.0.9
- Visual Studio Code version: v1.52.1
- Java Extension Pack: v0.12.1
- Java extension version: v0.73.0
- Maven: v3.6.3

##### Steps To Reproduce
While ran successfully as follow, but the output echo this error and CPU load upto 100%.
``` CommandLine
a68b3cba Importing Maven project(s) [Done]
e251d48a Repository registry initialization [Done]
04da89a9 Validate documents [Done]
42d31142 Publish Diagnostics [Done]
01a1751c Building [Done]
```

**Comment by weathery** [comment]
when upgraded to redhat.java-0.74.0, this issue resolved.

**Comment by consal** [comment]
Not for me, I still have the same, all my log is filled with these messages

**Comment by sunfenglong** [comment]
me too!!
version 1.4.0

**Comment by itaygoz** [comment]
Same for me, [error] [redhat.java] provider FAILED
redhat.java-1.4.0

**Comment by pinkli** [comment]
Same for me, the language server stops working after few minutes.

**Comment by rgrunber** [comment]
The errors themselves are harmful, so I would probably mark this as closed for now. See https://github.com/redhat-developer/vscode-java/issues/1976#issuecomment-858683678 for details. However @pinkli if you're still running into the issue you described, feel free to mention, or re-open.
