### ISSUE TITLE
When I open my project, the extension fails

### ISSUE THREAD

**Issue by EuniceB** [redhat-developer/vscode-java#1843]
Whenever I open my project, the extension fails with:
```
ERR Cannot read property 'rows' of undefined: TypeError: Cannot read property 'rows' of undefined
    at u.open (/home/x/.vscode/extensions/redhat.java-0.76.0/dist/extension.js:15:69804)
    at S.startSendingEvents (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:32770)
    at u._setupExtHostProcessListeners (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:37551)
    at u.attachPtyToTerminal (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:34952)
    at S.$onDidStartTask (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:46370)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
I inspected the extensions file and it seems that e is undefined:
```
open(e){
   s.serverTasks.suggestTaskEntrySize(e.rows-1);
   const t=s.serverTasks.getHistory();
   this.printTasks(t)
}
```

and then after a few seconds:
```
ERR The request (id: 1, method: 'textDocument/documentSymbol') has been cancelled: Error: The request (id: 1, method: 'textDocument/documentSymbol') has been cancelled
    at /home/x/.vscode/extensions/redhat.java-0.76.0/dist/extension.js:1:76464
    at /home/x/.vscode/extensions/redhat.java-0.76.0/dist/extension.js:1:76758
    at Immediate.<anonymous> (/home/x/.vscode/extensions/redhat.java-0.76.0/dist/extension.js:1:77117)
    at processImmediate (internal/timers.js:456:21)
```

Here are some info messages it shows before:
```
{
  message: 'Starting Java server with: /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:/home/eunice/.vscode/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar -noverify -jar /home/eunice/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /home/eunice/.config/Code/User/globalStorage/redhat.java/0.76.0/config_ss_linux -data /home/eunice/.config/Code/User/workspaceStorage/dfcb4a389a57c5e007b1c06673447101/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2021-03-22 10:41:18.617'
}
{
  message: 'Starting Java server with: /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:/home/eunice/.vscode/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar -noverify -jar /home/eunice/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /home/eunice/.config/Code/User/globalStorage/redhat.java/0.76.0/config_linux -data /home/eunice/.config/Code/User/workspaceStorage/dfcb4a389a57c5e007b1c06673447101/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2021-03-22 10:41:18.689'
}
```
This previously worked so I'm not sure what changed.

##### Environment
- Operating System: Debian GNU/Linux 10 (buster)
- JDK version: OpenJDK Java 11 AMD64, project JDK: 1.8
- Visual Studio Code version: 1.54.3
- Java extension version: 0.76.0

**Comment by apupier** [comment]
@EuniceB Can you share your project? Or provide a reproducer with a specific simplified project?

**Comment by EuniceB** [comment]
I can reproduce it just by creating a project with the Spring Boot Initializer Java support extension.
Here are the parameters I used:

- Maven
- Java version 8
- Spring boot version 2.4.4 
- Project language Java
- Packaging type jar

And my preferences:
```
{
  "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\x\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
  "java.completion.favoriteStaticMembers": [
    "org.junit.Assert.*",
    "org.junit.Assume.*",
    "org.junit.jupiter.api.Assertions.*",
    "org.junit.jupiter.api.Assumptions.*",
    "org.junit.jupiter.api.DynamicContainer.*",
    "org.junit.jupiter.api.DynamicTest.*",
    "org.mockito.Mockito.*",
    "org.mockito.ArgumentMatchers.*",
    "org.mockito.Answers.*"
  ],
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-1.8",
      "path": "C:/Program Files/Java/jdk1.8.0_281"
    },
    {
      "name": "JavaSE-11",
      "path": "C:/Program Files/Java/jdk-11.0.10"
    }
  ],
  "files.exclude": {
    "**/.classpath": true,
    "**/.project": true,
    "**/.settings": true,
    "**/.factorypath": true
  },
  "java.completion.guessMethodArguments": true,
  "java.configuration.updateBuildConfiguration": "automatic",
  "java.project.importOnFirstTimeStartup": "automatic",
  "java.refactor.renameFromFileExplorer": "preview",
  "java.saveActions.organizeImports": true,
  "java.showBuildStatusOnStart.enabled": true,
  "java.signatureHelp.enabled": true,
  "java.dependency.showMembers": true,
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "editor.linkedEditing": true,
  "git.autofetch": true,
  "settingsSync.keybindingsPerPlatform": false,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "typescript.updateImportsOnFileMove.enabled": "always",
  "eslint.alwaysShowStatus": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.validate": [
    "javascript"
  ],
  "spring-boot.ls.java.home": "/usr/lib/jvm/java-11-openjdk-amd64",
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "terminal.external.windowsExec": "\"C:\\Program Files\\Git\\git-bash.exe\""
}
```
