### ISSUE TITLE
Code completion in Java Language Server is not working

### ISSUE THREAD

**Issue by zguesmi** [redhat-developer/vscode-java#1884]
When I open my java project the language server is loaded correctly but when I start editing code
completion does not work. Cleaning the Java Language Server workspace does not help.
The following exception is raised by the language server.
```
!ENTRY org.eclipse.jdt.ls.core 4 2 2021-04-16 13:57:00.647
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 0
java.lang.NoSuchMethodError: 'org.eclipse.lsp4j.TextEdit org.eclipse.lsp4j.CompletionItem.getTextEdit()'
	at com.microsoft.jdtls.intellicode.core.vscode.VSCodeCompletionItem.<init>(VSCodeCompletionItem.java:76)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.lambda$0(CommandHandler.java:64)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.executeCommand(CommandHandler.java:64)
```

##### Environment
- Operating System: `Ubuntu 20.04.2 LTS`
- JDK version: `openjdk 11.0.7 2020-04-14`
- Visual Studio Code version: `VSCodium 1.55.2`
- Java extension version: `v0.77.0`

##### Steps To Reproduce
1. Open a java project in VSCodium
2. Start editing a java file.

Full language server logs: https://gist.github.com/zguesmi/619d2871dc4ff27e1203b888a8592e06

##### Current Result
The code completion does not work.

##### Expected Result
The code completion should be working.

**Comment by fbricon** [comment]
Try disabling Microsoft's Intellicode extension

**Comment by zguesmi** [comment]
Thank you very much for your quick response! This did indeed fix the issue.

**Comment by fbricon** [comment]
@testforstephen @CsCherrYY @jdneo could you guys investigate on the intellicode side?

**Comment by testforstephen** [comment]
I installed IntelliCode extension v1.2.12 in my machine, code completion works well.

@zguesmi What's your IntelliCode extension version? And would you mind sharing some sample snippet to trigger the completion?

**Comment by zguesmi** [comment]
@testforstephen I am sorry I missed your request. My IntelliCode extension version is `v1.2.8`.

**Comment by zguesmi** [comment]
@testforstephen I am sorry I missed your request. My IntelliCode extension version is `v1.2.8`.
When I enable vsintellicode for java and I open any java project, the issue appears. When I hit `ctrl+space` for completion I see the following exception in Java Language Server logs:
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2021-05-20 22:12:55.375
!MESSAGE Error in calling delegate command handler
!STACK 0
java.lang.NoSuchMethodError: 'org.eclipse.lsp4j.TextEdit org.eclipse.lsp4j.CompletionItem.getTextEdit()'
	at com.microsoft.jdtls.intellicode.core.vscode.VSCodeCompletionItem.<init>(VSCodeCompletionItem.java:76)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.lambda$0(CommandHandler.java:64)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.executeCommand(CommandHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:502)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by snjeza** [comment]
>  I am sorry I missed your request. My IntelliCode extension version is v1.2.8.

@zguesmi Could you try to upgrade the IntelliCode version to 1.2.14?

**Comment by zguesmi** [comment]
It seems to work correctly when I upgrade to version `1.2.14`.

**Comment by zguesmi** [comment]
@testforstephen should we close this?

**Comment by testforstephen** [comment]
yes, since it's fixed, we could close it.
