### ISSUE TITLE
Intermitent test failures in "should register all java commands"

### ISSUE THREAD

**Issue by rgrunber** [redhat-developer/vscode-java#1892]
On the build job, this only fails on Mac but I have been able to reproduce the failures locally as well on Linux.

```
1) Java Language Extension - Standard
       should register all java commands:
      AssertionError [ERR_ASSERTION]: Some Java commands are not registered properly or a new command is not added to the test.

...
...

      + expected - actual

         "java.action.showSupertypeHierarchy"
         "java.action.showTypeHierarchy"
         "java.apply.workspaceEdit"
         "java.clean.workspace"
      -  "java.edit.organizeImports"
         "java.execute.workspaceCommand"
         "java.ignoreIncompleteClasspath"
         "java.ignoreIncompleteClasspath.help"
         "java.open.clientLog"
--
         "java.open.serverLog"
         "java.project.addToSourcePath"
         "java.project.import"
         "java.project.listSourcePaths"
      -  "java.project.refreshDiagnostics"
         "java.project.removeFromSourcePath"
         "java.project.updateSourceAttachment"
         "java.projectConfiguration.status"
         "java.projectConfiguration.update"

  	at /Users/travis/build/redhat-developer/vscode-java/out/test/standard-mode-suite/extension.test.js:74:20

  	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by rgrunber** [comment]
`vscode.commands.getCommands(true).then((commands) => {...})` sometimes returns N command and occasionally starts returning N+2 (the extra 2 commands from above). This is starting to look like some kind of timing issue.

I'm still not sure why those 2 commands are taking longer to return when there are others defined in the jdt.ls.core extension point (plugin.xml) that make their way into commands list every time.
