### ISSUE TITLE
Formatter doesn't load format config after update

### ISSUE THREAD

**Issue by gline9** [redhat-developer/vscode-java#1917]
After updating to the latest version of the plugin, the format configuration configured no longer is used when formatting files through vscode.

##### Environment
- Operating System: Windows
- JDK version: 11
- Visual Studio Code version: 1.55.2
- Java extension version: 0.79.0

##### Steps To Reproduce
1. Place eclipse xml file on the file system tested with version 18 format
2. Configure url to point to file in global settings Java > Format > Settings: Url with format `file:///D:/<file location>`
3. Open java project
4. Format java file in project
5. Formatting uses default formatting and not the formatting configured in the xml file.

##### Current Result

File is formatted with the default format profile not the provided xml config

##### Expected Result

File is formatted with the provided xml config

##### Additional Informations

Prior to the update the profile name inside the xml file didn't need to be provided and formatting worked correctly, not sure which version I came from or if you have a way I could get that information for you.

After update if the profile isn't provided a null pointer exception occurs and is as follows.
Providing the profile name results in no NullPointerException but also doesn't format according to the config file.

```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.ui.preferences.formatter.ProfileVersionerCore.updateAndComplete(ProfileVersionerCore.java:98)
	at org.eclipse.jdt.ls.core.internal.managers.FormatterManager.readSettingsFromStream(FormatterManager.java:181)
	at org.eclipse.jdt.ls.core.internal.managers.FormatterManager.configureFormatter(FormatterManager.java:191)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didChangeConfiguration(JDTLanguageServer.java:474)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by fbricon** [comment]
Can you please share a sample project reproducing this issue?

**Comment by snjeza** [comment]
>1.  Place eclipse xml file on the file system tested with version 18 format
@gline9 could you attach an eclipse xml file example?

**Comment by gline9** [comment]
I've created a minimal reproduction (left the xml file as is besides changing some names) [here](https://github.com/gline9/vscode-java-format-reproduction). 

To reproduce format the provided java file, notice that the curly brace for the class is joined back to a single line instead of multiple lines as is configured in the xml file.

It also looks like the issue persists with relative paths instead of absolute paths as well as having the setting inside the .vscode folder instead of a global setting.

**Comment by marcanpilami** [comment]
Same here - please note I had to revert to 0.77 (as 0.78 and 0.79 both fail) so the regression is likely in 0.78.

**Comment by x3rAx** [comment]
Thanks @marcanpilami, you saved my day. With version 0.77 it works again!

**Comment by snjeza** [comment]
@gline9 @marcanpilami @x3rAx could you check https://github.com/snjeza/vscode-test/raw/master/java-0.79.1.vsix

**Comment by zhouxinghong** [comment]
java-0.79.1.vsix
It can be formatted correctly, but the following exception is still received when the java project is started. I don't know what caused it? 0.77 will not have this problem

**Comment by snjeza** [comment]
@zhouxinghong could you show your java.format.settings.url property?

**Comment by x3rAx** [comment]
> @gline9 @marcanpilami @x3rAx could you check https://github.com/snjeza/vscode-test/raw/master/java-0.79.1.vsix

This version is working and I don't have any output for "Language Support for Java" and "Language Support for Java (Syntax Server)" so I guess this is good 😅

**Comment by zhouxinghong** [comment]
> @zhouxinghong您可以显示您的java.format.settings.url属性吗？


 "java.format.settings.url": "D:\\tool\\Microsoft\\java-intellij-idea-style-lambda-5.xml", 
or
 "java.format.settings.url": "D:/tool/Microsoft/java-intellij-idea-style-lambda-5.xml",
 Never take effect Log

**Comment by OzelotVanilla** [comment]
I think I have encountered the same problem. I have also changed the file in `.vscode\extensions\redhat.java-0.79.0\formatters\` (move my settings into this file, then comment out my original setting in `settings.json` and change format profile name to "Eclipse"), but it still format file in default java style. I have uninstalled ESlint, and I think it is not this confliction caused this bug.

**Comment by Nightenom** [comment]
same problem for me, worked fine till recent updates
```
[Error - 12:19:44] 2. 5. 2021 12:19:44 Illegal character in opaque part at index 2: P:\data\final_format.xml
Illegal character in opaque part at index 2: P:\data\final_format.xml
java.net.URISyntaxException: Illegal character in opaque part at index 2: P:\data\final_format.xml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parse(URI.java:3120)
	at java.base/java.net.URI.<init>(URI.java:600)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.getURIs(StandardProjectsManager.java:458)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.fileChanged(StandardProjectsManager.java:176)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceEventsHandler.didChangeWatchedFiles(WorkspaceEventsHandler.java:115)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didChangeWatchedFiles(JDTLanguageServer.java:496)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by snjeza** [comment]
> "java.format.settings.url": "D:\tool\Microsoft\java.xml",
or
"java.format.settings.url": "D:/tool/Microsoft/java.xml",

@zhouxinghong could you try
```
 "java.format.settings.url": "D:\\tool\Microsoft\\java.xml",
```
or
```
"java.format.settings.url": file:"D:/tool/Microsoft/java.xml",
```

**Comment by snjeza** [comment]
> same problem for me, worked fine till recent updates

@Nightenom could you try

```
 P:\data\final_format.xml
"java.format.settings.url": "file: P:/data/final_format.xml",
```
instead of 
```
"java.format.settings.url": "P:\data\final_format.xml",
```

**Comment by snjeza** [comment]
@OzelotVanilla @Nightenom Can you, please, try https://github.com/snjeza/vscode-test/raw/master/java-0.79.1.vsix

**Comment by OzelotVanilla** [comment]
@snjeza Thank you. Hope the information I gave can help you solve this bug.

**Comment by snjeza** [comment]
@OzelotVanilla Yes, it helps. Thanks.

**Comment by Nightenom** [comment]
The path changes are not valid because uri can have only one colon, the file:// prefix doesn't work for the same reason. The vsix you supplied works nice using the old setting, didn't try the other paths.

**Comment by snjeza** [comment]
> The path changes are not valid because uri can have only one colon, the file:// prefix doesn't work for the same reason. The vsix you supplied works nice using the old setting, didn't try the other paths.

@Nightenom Could you try

```
"java.format.settings.url": "file:/P:/data/final_format.xml",
```

**Comment by Nightenom** [comment]
> @Nightenom Could you try
> 
> ```
> "java.format.settings.url": "file:/P:/data/final_format.xml",
> ```

Using live version (not the one you posted here that does work normally) - doesn't work as it's not valid URI, `file:///P:/data/final_format.xml` which is valid URI doesn't crash but doesn't work either

**Comment by snjeza** [comment]
> Using live version (not the one you posted here which does work normally) - this crashes as it's not valid URI, file:///P:/data/final_format.xml which is valid URI doesn't crash but doesn't work either

@Nightenom Please try https://github.com/snjeza/vscode-test/raw/master/java-0.79.1.vsix

**Comment by Nightenom** [comment]
I've tried it already and already told you twice it works :)

**Comment by snjeza** [comment]
@Nightenom ok. Thank you!

**Comment by future2r** [comment]
I have a related problem. After starting VS Code, the formatter file (just "java.format.settings.url": "formatter.xml" in my case) is not found and my source files are formatted with default settings. But, when I open the file "formatter.xml", press Ctrl+S once, then everything works fine.

**Comment by snjeza** [comment]
@future2r Could you try https://github.com/snjeza/vscode-test/raw/master/java-0.79.1.vsix

**Comment by gline9** [comment]
@snjeza https://github.com/snjeza/vscode-test/raw/master/java-0.79.1.vsix fixed the problem for me.
