### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by wgumenyuk** [redhat-developer/vscode-java#1935]
Unfortunately the autocomplete doesn't work after updating to JDK version 16. Setting `java.trace.server` to `verbose` reveals the following error:

```
[Error - 08:32:52] 07.05.2021, 08:32:52 Error in calling delegate command handler
Cannot invoke "org.eclipse.jdt.core.ICompilationUnit.findPrimaryType()" because "unit" is null
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.ICompilationUnit.findPrimaryType()" because "unit" is null
	at com.microsoft.java.test.plugin.util.TestSearchUtils.searchCodeLens(TestSearchUtils.java:94)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:50)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:502)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I'm using Gradle 7.0 to build my projects. Has anyone encountered this issue before? Returning to an older version of the JDK didn't help sadly.

##### Environment
- Operating System: Windows 10 Home
- JDK version: 16.0.1
- Visual Studio Code version: 1.56.0
- Java extension version: 0.79.1

##### Steps To Reproduce
- No idea

##### Current Result
- Autocomplete and dependency resolution don't work

##### Expected Result
- Working autocomplete

##### Additional Informations
- Gradle: 7.0

**Comment by jdneo** [comment]
This exception is raised by [test runner extension](https://github.com/microsoft/vscode-java-test) where it tries to find the test methods in the current java source file. From my understanding, it will not impact on the auto-completion feature.

The exception is caused because the following invocation returns null.

```java
final ICompilationUnit unit = JDTUtils.resolveCompilationUnit(uri);
```

indicating that the uri of the current java source file does not exist in the backend Java Model. So would you mind to share a sample project which can repro this issue?

**Comment by wgumenyuk** [comment]
Thanks for your quick reply! Here's the sample project you requested: [issue-1935.zip](https://github.com/redhat-developer/vscode-java/files/6440808/issue-1935.zip).

**Comment by jdneo** [comment]
I can repro this issue with JDK 16. (JDK11 works well)

An error message can be seen:

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2021-05-08 12:45:47.602
!MESSAGE Index out of bounds
!STACK 1
Java Model Exception: Java Model Status [Index out of bounds]
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:162)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:389)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:382)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:944)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementAtSelection(JDTUtils.java:925)
	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getSourceActionCommands(SourceAssistProcessor.java:106)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:208)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:645)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
!SUBENTRY 1 org.eclipse.jdt.core 4 980 2021-05-08 12:45:47.602
!MESSAGE Index out of bounds
```

**Comment by wgumenyuk** [comment]
I'll just switch to JDK 11 for now. I guess it is a compatibility problem with this extension and JDK 16?

**Comment by fbricon** [comment]
@jdneo starting jdt.ls with Java 16.0.1 works for me, I get completion without any errors, either with a Maven or a Gradle 7 project

Please attach a sample project reproducing the issue

**Comment by jdneo** [comment]
I'm using the project the user provided here: https://github.com/redhat-developer/vscode-java/issues/1935#issuecomment-834242367

BTW, when I play with it, it's not stable repro. Sometimes it works as well on my machine. What I did is each time remove the workspace storage and reimport it again.
