### ISSUE TITLE
Does VS Code report an error when opening the spring5.x project Java language engine? ? ? The project framework is the combined development model of spring5.x + redis+maven. . .

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#1952]
Deprecated. . .

**Comment by snjeza** [comment]
@zhouxinghong Could you attach your settings.json?

**Comment by zhouxinghong** [comment]
Since the content of the setting is very large, sending it completely is not an ideal approach. You can describe in detail the key Java configuration that may cause the problem, and I will filter it out and provide it to you.

**Comment by snjeza** [comment]
java.format.settings.url

**Comment by zhouxinghong** [comment]
"java.format.settings.url": "file:///D:/tool/eclipse/eclipse-style.xml",

**Comment by zhouxinghong** [comment]
This is the current setting

**Comment by snjeza** [comment]
Could you send a new log?
The error
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2021-05-20 09:26:55.315
!MESSAGE unknown protocol: d
!STACK 0
java.net.MalformedURLException: unknown protocol: d
at java.base/java.net.URL.(URL.java:652)
at java.base/java.net.URL.fromURI(URL.java:719)
at java.base/java.net.URI.toURL(URI.java:1116)
at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.configureSettings(StandardProjectsManager.java:274)
```
can happen if you set

"java.format.settings.url": "D:/tool/eclipse/eclipse-style.xml",

or something similar that.

**Comment by zhouxinghong** [comment]
!SESSION 2021-05-21 11:38:24.190 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.10
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -data c:\Users\HNG\AppData\Roaming\Code - Insiders\User\workspaceStorage\21afc6d45024e6e4989754ad5eb61355\redhat.java\jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:30.078
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:30.864
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:30.966
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:31.035
!MESSAGE Initializing Java Language Server 1.1.2.202105191833

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-05-21 11:38:31.272
!MESSAGE unknown protocol: d
!STACK 0
java.net.MalformedURLException: unknown protocol: d
	at java.base/java.net.URL.<init>(URL.java:652)
	at java.base/java.net.URL.fromURI(URL.java:719)
	at java.base/java.net.URI.toURL(URI.java:1116)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.configureSettings(StandardProjectsManager.java:274)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$3.preferencesChange(StandardProjectsManager.java:541)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager$1.run(PreferenceManager.java:212)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager.preferencesChanged(PreferenceManager.java:215)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager.update(PreferenceManager.java:183)
	at org.eclipse.jdt.ls.core.internal.preferences.StandardPreferenceManager.update(StandardPreferenceManager.java:66)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:116)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:72)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:235)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.444
!MESSAGE Setting F:\tool\Java\jdk-11.0.8 as 'JavaSE-11' environment (id:1621568311186)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.449
!MESSAGE JVM Runtimes changed, saving new configuration

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.564
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.565
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.provideSemanticTokens, java.project.resolveStackTraceLocation, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.project.getSemanticTokensLegend, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.resolveSourceAttachment, java.project.addToSourcePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.566
!MESSAGE Static Commands: [sts.java.addClasspathListener, sts.java.removeClasspathListener]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.567
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.568
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.569
!MESSAGE Non-Static Commands: [sts.java.javadoc]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.569
!MESSAGE Static Commands: [sts.java.type]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:38:33.570
!MESSAGE Non-Static Commands: []
..........

**Comment by zhouxinghong** [comment]
The exception was reported during the startup of vscode Java

**Comment by zhouxinghong** [comment]
Wait a moment

**Comment by zhouxinghong** [comment]
"java.format.settings.url": "D:/tool/eclipse/eclipse-style.xml",
**********************************************************************************
!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:52:39.942
!MESSAGE Initializing Java Language Server 1.1.2.202105191833

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-05-21 11:52:40.492
!MESSAGE unknown protocol: d
!STACK 0
java.net.MalformedURLException: unknown protocol: d
	at java.base/java.net.URL.<init>(URL.java:652)
	at java.base/java.net.URL.fromURI(URL.java:719)
	at java.base/java.net.URI.toURL(URI.java:1116)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.configureSettings(StandardProjectsManager.java:274)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$3.preferencesChange(StandardProjectsManager.java:541)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager$1.run(PreferenceManager.java:212)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager.preferencesChanged(PreferenceManager.java:215)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager.update(PreferenceManager.java:183)
	at org.eclipse.jdt.ls.core.internal.preferences.StandardPreferenceManager.update(StandardPreferenceManager.java:66)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:116)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:72)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:235)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:52:42.567
!MESSAGE Setting F:\tool\Java\jdk-11.0.8 as 'JavaSE-11' environment (id:1621569160128)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:52:42.571
!MESSAGE JVM Runtimes changed, saving new configuration

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 11:52:42.662
!MESSAGE Static Commands: []
...........

**Comment by zhouxinghong** [comment]
The above is the exception reproduced after setting "java.format.settings.url": "D:/tool/eclipse/eclipse-style.xml"

**Comment by snjeza** [comment]
You should use
```
"java.format.settings.url": "file:///D:/tool/eclipse/eclipse-style.xml",
```

**Comment by zhouxinghong** [comment]
"java.format.settings.url": "file:///D:/tool/eclipse/eclipse-style.xml",and "java.format.settings.url": "D:/tool/eclipse/eclipse-style.xml",
The error is the same.
The default is this setting "java.format.settings.url": "file:///D:/tool/eclipse/eclipse-style.xml",

**Comment by zhouxinghong** [comment]
Found the cause of the problem?

**Comment by snjeza** [comment]
@zhouxinghong could you set 
```
"java.format.settings.url": "file:///D:/tool/eclipse/eclipse-style.xml"
```
[Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)
and send a new log after cleaning of the workspace.

**Comment by zhouxinghong** [comment]
SESSION 2021-05-21 22:20:23.927 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.10
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -data c:\Users\HNG\AppData\Roaming\Code - Insiders\User\workspaceStorage\21afc6d45024e6e4989754ad5eb61355\redhat.java\jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:29.200
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:29.871
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:30.079
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:30.103
!MESSAGE Initializing Java Language Server 1.1.2.202105191833

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-05-21 22:20:30.697
!MESSAGE unknown protocol: d
!STACK 0
java.net.MalformedURLException: unknown protocol: d
	at java.base/java.net.URL.<init>(URL.java:652)
	at java.base/java.net.URL.fromURI(URL.java:719)
	at java.base/java.net.URI.toURL(URI.java:1116)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.configureSettings(StandardProjectsManager.java:274)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$3.preferencesChange(StandardProjectsManager.java:541)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager$1.run(PreferenceManager.java:212)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager.preferencesChanged(PreferenceManager.java:215)
	at org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager.update(PreferenceManager.java:183)
	at org.eclipse.jdt.ls.core.internal.preferences.StandardPreferenceManager.update(StandardPreferenceManager.java:66)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:116)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:72)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:235)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:33.816
!MESSAGE Setting F:\tool\Java\jdk-11.0.8 as 'JavaSE-11' environment (id:1621606830161)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:33.824
!MESSAGE JVM Runtimes changed, saving new configuration

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:33.862
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-05-21 22:20:33.869
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

**Comment by snjeza** [comment]
Could you send your client logs -  c:\Users\HNG\AppData\Roaming\Code - Insiders\User\workspaceStorage\21afc6d45024e6e4989754ad5eb61355\redhat.java\client* or the  c:\Users\HNG\AppData\Roaming\Code - Insiders\User\workspaceStorage\21afc6d45024e6e4989754ad5eb61355\redhat.java directory?

**Comment by zhouxinghong** [comment]
[redhat.java.zip](https://github.com/redhat-developer/vscode-java/files/6524095/redhat.java.zip)

**Comment by pecko** [comment]
I can't see your "java.format.settings.url" in attached files.

**Comment by snjeza** [comment]
I can't see "java.format.settings.url" in the attached files

**Comment by zhouxinghong** [comment]
Currently the most detailed record information:
[.log](https://github.com/redhat-developer/vscode-java/files/6525554/default.log)

**Comment by snjeza** [comment]
@zhouxinghong you have set

```
"java.format.settings.url": "D:/tool/eclipse/eclipse-style.xml"
```
See line 173 in your log
```
...
{java=
...
format={enabled=true, settings={url=D:/tool/eclipse/eclipse-style.xml
...
```
Run File>Preferences>Settings and check your User and Workspace preferences:
![pref](https://user-images.githubusercontent.com/388609/119211271-72077080-bab1-11eb-8750-81d5950815f9.gif)

**Comment by zhouxinghong** [comment]
The 173-line original code configuration is: "java.format.settings.url": "file:///D:/tool/eclipse/eclipse-style.xml"

**Comment by zhouxinghong** [comment]
Do you mean that you need to set "java.format.settings.url": "file:///D:/tool/eclipse/eclipse-style.xml" in Workspace? Can't be set in User?

**Comment by zhouxinghong** [comment]
The following are the current settings:
User: file:///D:/tool/eclipse/eclipse-style.xml
Workspace: D:/tool/eclipse/eclipse-style.xml

**Comment by zhouxinghong** [comment]
Thank you for your help, you are really great!

**Comment by zhouxinghong** [comment]
This is mainly a problem left over before version 0.79.2.
You are really great! Thanks a lot!
