### ISSUE TITLE
Extension stopped working on some (but not all) Java files

### ISSUE THREAD

**Issue by bibhas2** [redhat-developer/vscode-java#1974]
This is a project I have been working on for a long time without any problem. But starting this morning the extension is having problems with one of the Java files. The following functions have stopped working:

- All compile errors are disabled. There's no feedback if there are any compile errors.
- Command clicking method names do nothing. But command clicking class names do navigation.
- Can not rename any symbols. I keep getting ``Renaming this symbol is not supported``.

This issue seems localized to a small number of Java files only. Other Java files work as expected.

##### Environment
- Operating System: macOS Big Sur 11.4
- JDK version:
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment Zulu15.29+15-CA (build 15.0.2+7)
OpenJDK 64-Bit Server VM Zulu15.29+15-CA (build 15.0.2+7, mixed mode)
```
- Visual Studio Code version: 1.56.2 (Universal)
- Java extension version: Java Extension Pack 0.16.0. Language Support for Java 0.79.2

JDK setting in ``pom.xml``:

```xml
<properties>
	<maven.compiler.source>10</maven.compiler.source>
	<maven.compiler.target>10</maven.compiler.target>
</properties>
```
##### Steps To Reproduce
This is a project I have been working on for a long time without any problem. But starting this morning the extension is having problems with one of the Java files. 

1. Open the Maven project.
2. The following no longer works in one of the Java files:
- All compile errors are disabled. There's no feedback if there are any compile errors.
- Command clicking method names do nothing. But command clicking class names do navigation.

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

below is the log I found in ``Log (Extension Host)`` panel. There are some errors shown at the end.

```
[2021-06-07 13:16:28.490] [exthost] [info] extension host started
[2021-06-07 13:16:28.511] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-06-07 13:16:28.511] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-06-07 13:16:28.520] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-06-07 13:16:28.520] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2021-06-07 13:16:28.521] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-07 13:16:28.521] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2021-06-07 13:16:28.543] [exthost] [info] ExtensionService#_doActivateExtension redhat.java {"startup":true,"extensionId":{"value":"redhat.java","_lower":"redhat.java"},"activationEvent":"workspaceContains:pom.xml"}
[2021-06-07 13:16:28.544] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/batman/.vscode/extensions/redhat.java-0.79.2/dist/extension
[2021-06-07 13:16:28.589] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-pack {"startup":true,"extensionId":{"value":"vscjava.vscode-java-pack","_lower":"vscjava.vscode-java-pack"},"activationEvent":"workspaceContains:pom.xml"}
[2021-06-07 13:16:28.589] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/batman/.vscode/extensions/vscjava.vscode-java-pack-0.16.0/out/extension
[2021-06-07 13:16:28.631] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-debug {"startup":true,"extensionId":{"value":"vscjava.vscode-java-test","_lower":"vscjava.vscode-java-test"},"activationEvent":"workspaceContains:pom.xml"}
[2021-06-07 13:16:28.631] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/batman/.vscode/extensions/vscjava.vscode-java-debug-0.34.0/dist/extension
[2021-06-07 13:16:28.654] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-maven {"startup":true,"extensionId":{"value":"vscjava.vscode-maven","_lower":"vscjava.vscode-maven"},"activationEvent":"workspaceContains:**/pom.xml"}
[2021-06-07 13:16:28.654] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/batman/.vscode/extensions/vscjava.vscode-maven-0.31.0/dist/extension
[2021-06-07 13:16:28.714] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-06-07 13:16:28.714] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-06-07 13:16:28.771] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-06-07 13:16:28.771] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js
[2021-06-07 13:16:28.808] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-07 13:16:28.809] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js
[2021-06-07 13:16:28.856] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2021-06-07 13:16:28.872] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2021-06-07 13:16:31.608] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-test {"startup":true,"extensionId":{"value":"vscjava.vscode-java-test","_lower":"vscjava.vscode-java-test"},"activationEvent":"workspaceContains:pom.xml"}
[2021-06-07 13:16:31.608] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/batman/.vscode/extensions/vscjava.vscode-java-test-0.30.0/main.js
[2021-06-07 13:16:31.659] [exthost] [info] eager extensions activated
[2021-06-07 13:16:31.665] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-06-07 13:16:31.665] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-06-07 13:16:31.673] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-06-07 13:16:31.673] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-06-07 13:16:31.674] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-06-07 13:16:31.674] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-06-07 13:16:40.520] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode {"startup":false,"extensionId":{"value":"VisualStudioExptTeam.vscodeintellicode","_lower":"visualstudioexptteam.vscodeintellicode"},"activationEvent":"onLanguage:java"}
[2021-06-07 13:16:40.520] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/batman/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.14/dist/intellicode
[2021-06-07 13:16:40.756] [exthost] [error] [redhat.java] provider FAILED
[2021-06-07 13:16:40.756] [exthost] [error] Canceled: Canceled
	at b.makeCancelError (/Users/batman/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:723521)
	at b.handleFailedRequest (/Users/batman/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:723372)
	at /Users/batman/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:691126
```

Error from JavaScript console.

```
workbench.desktop.main.js:62 [Extension Host] rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:62 [Extension Host] stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	at Socket.Writable.write (internal/streams/writable.js:292:11)	at /Users/bibhas/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:883089	at new Promise (<anonymous>)	at c.write (/Users/bibhas/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:883007)	at _.doWrite (/Users/bibhas/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:872593)	at /Users/bibhas/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:872488
```
##### Current Result
Some of the functions of Java extension such as compile error display and navigation aren't working in some of the files.

##### Expected Result
Java extension's compile error display and navigation should be working fully in all Java files.

**Comment by bibhas2** [comment]
This was my bad. The Java file where the extension wasn't working was not within the Maven project. Since the extension partially works in such files I was confused.
