### ISSUE TITLE
'textDocument/hover' has been cancelled

### ISSUE THREAD

**Issue by consal** [redhat-developer/vscode-java#1976]
Error Log
```
ERR The request (id: 428, method: 'textDocument/hover') has been cancelled: Error: The request (id: 428, method: 'textDocument/hover') has been cancelled
	at /Users/cooluser/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:851725
	at /Users/cooluser/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:852019
	at Immediate.<anonymous> (/Users/cooluser/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:852384)
	at processImmediate (internal/timers.js:461:21)
log.ts:296   ERR The request (id: 429, method: 'textDocument/hover') has been cancelled: Error: The request (id: 429, method: 'textDocument/hover') has been cancelled
	at /Users/cooluser/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:851725
	at /Users/cooluser/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:852019
	at Immediate.<anonymous> (/Users/cooluser/.vscode/extensions/redhat.java-0.79.2/dist/extension.js:2:852384)
	at processImmediate (internal/timers.js:461:21)
```
Environment
Operating System: macOS
JDK version: Adapt JDK-11.0.9
Visual Studio Code version: v1.56.2
Java Extension Pack: v0.12.1
Java extension version: v0.79.2
Maven: v3.6.3
Steps To Reproduce
Import any Java project, CPU skyrockets and the log is filled with these messages.

a68b3cba Importing Maven project(s) [Done]
e251d48a Repository registry initialization [Done]
04da89a9 Validate documents [Done]
42d31142 Publish Diagnostics [Done]
01a1751c Building [Done]
Current Result
Expected Result

**Comment by rgrunber** [comment]
I can reproduce this going back a long time. As you've seen, there are quite a few errors reported with a similar stacktrace.

The error in the client log :
```
[2021-06-09 15:50:39.268] [renderer3] [error] The request (id: 3, method: 'textDocument/hover') has been cancelled: Error: The request (id: 3, method: 'textDocument/hover') has been cancelled
	at handleResponse (/home/rgrunber/git/vscode-java/dist/extension.js:79128:48)
	at processMessageQueue (/home/rgrunber/git/vscode-java/dist/extension.js:78943:17)
	at Immediate.<anonymous> (/home/rgrunber/git/vscode-java/dist/extension.js:78927:13)
	at processImmediate (internal/timers.js:461:21)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
```

In the logs showing client/server interaction :

```
[Trace - 3:50:39 PM] Sending request 'textDocument/hover - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///home/rgrunber/sample-projects/json-example/src/org/example/Main.java"
    },
    "position": {
        "line": 14,
        "character": 5
    }
}

...
...

[Info  - 3:50:39 PM] Jun 9, 2021, 3:50:39 PM >> document/hover
[Trace - 3:50:39 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 3
}

[Trace - 3:50:39 PM] Received response 'textDocument/hover - (3)' in 155ms. Request failed: The request (id: 3, method: 'textDocument/hover') has been cancelled (-32800).
```

Looks like this is happening from https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java#L286 but I'm not sure if the client is mistakenly logging this or if lsp4j is not setting something correctly.

**Comment by rgrunber** [comment]
The following phrase from https://microsoft.github.io/language-server-protocol/specifications/specification-current/#cancelRequest may be relevant :

`If the request returns an error response on cancellation it is advised to set the error code to ErrorCodes.RequestCancelled`

To me this seems like the action to take if there is an error relating to cancellation. However that implies that cancellations need not be considered errors. But lsp4j seems to be treating every cancellation this way.
