### ISSUE TITLE
After opening a project and stopping operation for 3 hours, opening a class needs to wait about 3 minutes for the grammar to be successfully parsed

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2081]
> ### After opening a project and stopping operation for 3 hours, opening a class needs to wait about 3 minutes before the java service can be used normally. For example, all functions such as syntax highlighting, smart prompt, and code jump cannot be used normally during this period. Similarly, other plug-ins that depend on java language services are also blocked in the java.execute.workspaceCommand interface of the language server

##### Environment
- Operating System: Windows_NT x64 10.0.19043
- JDK version: 16
- Visual Studio Code version: 1.60.0-insider (system setup)
- Java extension version: 0.81.0
- Gradle version：7.2

##### Steps To Reproduce
1. Open a very large project, such as the springboot source code project
2. Wait for more than 3 hours without any operation
3. Go back to this workspace again and open a class at will

##### Additional Informations
This issue will affect the promotion of VSCode-Java, and the current department members have gradually used

**Comment by snjeza** [comment]
> Can you recommend a tool for viewing a Java language service thread, let me see the problem more conveniently.

You can try jstack:
- [jstack](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jstack.html)
- [Generate a Java thread dump on Microsoft Windows](https://access.redhat.com/solutions/19170)

**Comment by mozhuanzuojing** [comment]
> > Can you recommend a tool for viewing a Java language service thread, let me see the problem more conveniently.
> 
> You can try jstack:
> 
> * [jstack](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jstack.html)
> * [Generate a Java thread dump on Microsoft Windows](https://access.redhat.com/solutions/19170)

Thanks @snjeza .
I try to intercept the thread returned by the java language server blocking.

**Comment by mozhuanzuojing** [comment]
@snjeza I organized a brief log and added notes to the log.

[pause.log](https://github.com/redhat-developer/vscode-java/files/7026787/pause.log)

**Comment by mozhuanzuojing** [comment]
@snjeza 

> The thread state I observed today

[java Languge Server Blocking thread.log](https://github.com/redhat-developer/vscode-java/files/7027535/java.Languge.Server.Blocking.thread.log)

[java Languge Server Blocking thread 2.log](https://github.com/redhat-developer/vscode-java/files/7027536/java.Languge.Server.Blocking.thread.2.log)


> ### Tomorrow I will continue to record the thread stack several times

**Comment by mozhuanzuojing** [comment]
@snjeza  This issue is about to be closed because it did not reappear on version 0.82.2

- ## The following only records the thread status of version 0.82.2

> Gradle Deamon JVM Threads state.

1. [jstack Gradle Deamon JVM begin before.log](https://github.com/redhat-developer/vscode-java/files/7028667/jstack.Gradle.Deamon.JVM.begin.before.log)
2. [jstack Gradle Deamon JVM begin after 5 seconds.log](https://github.com/redhat-developer/vscode-java/files/7028671/jstack.Gradle.Deamon.JVM.begin.after.5.seconds.log)
3. [jstack Gradle Deamon JVM begin after 10 seconds.log](https://github.com/redhat-developer/vscode-java/files/7028674/jstack.Gradle.Deamon.JVM.begin.after.10.seconds.log)
4. [jstack Gradle Deamon JVM end after.log](https://github.com/redhat-developer/vscode-java/files/7028675/jstack.Gradle.Deamon.JVM.end.after.log)


> Java Language JVM Threads state.

1.

**Comment by snjeza** [comment]
> This morning I opened a class in the workspace for the first time and saw the log of reinitialization and compilation. I don’t know why this is triggered.

I think some of your extensions have been updated, probably, Test Runner for Java - vscjava.vscode-java-test.
Could you try to disable Eclipse PDE support - yaozheng.vscode-pde?

**Comment by mozhuanzuojing** [comment]
@snjeza  Today I disabled yaozheng.vscode-pde, and I still have the same problem.

# I think the main problem is the following lines of log. The main reason for the blocking is the recompilation of Gradle.

- At present, I also found a related situation: the first time the Gradle plugin is opened or a Gradle task is executed after a period of time, it will start a new Gradle Deamon JVM, and then recompile the project. JVM exits automatically after the compilation is complete. Will this affect the Gradle Deamon started by the Java plug-in? I think it will have an impact. Very helpless!

```log
"Worker-26: Update project am" #291 prio=5 os_prio=0 cpu=238343.75ms elapsed=645.03s tid=0x000002a3cb2ddda0 nid=0x1a84 runnable  [0x000000d6ed8fe000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.WindowsNativeDispatcher.FindFirstFile0(java.base@16.0.1/Native Method)
	at sun.nio.fs.WindowsNativeDispatcher.FindFirstFile(java.base@16.0.1/WindowsNativeDispatcher.java:185)
	at sun.nio.fs.WindowsLinkSupport.getRealPath(java.base@16.0.1/WindowsLinkSupport.java:232)
	at sun.nio.fs.WindowsPath.toRealPath(java.base@16.0.1/WindowsPath.java:931)
	at sun.nio.fs.WindowsPath.toRealPath(java.base@16.0.1/WindowsPath.java:42)
	at org.eclipse.core.internal.filesystem.local.nio.DosHandler.fetchFileInfo(DosHandler.java:45)
	at org.eclipse.core.internal.filesystem.local.LocalFileNativesManager.fetchFileInfo(LocalFileNativesManager.java:65)
	at org.eclipse.core.internal.filesystem.local.LocalFile.fetchInfo(LocalFile.java:161)
	at org.eclipse.core.filesystem.provider.FileStore.fetchInfo(FileStore.java:260)
	at org.eclipse.core.filesystem.provider.FileStore.childInfos(FileStore.java:99)
	at org.eclipse.core.internal.localstore.UnifiedTree.getLocalList(UnifiedTree.java:360)
	at org.eclipse.core.internal.localstore.UnifiedTree.addChildren(UnifiedTree.java:148)
	at org.eclipse.core.internal.localstore.UnifiedTree.addNodeChildrenToQueue(UnifiedTree.java:254)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:120)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:978)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:961)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1562)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.importRootProject(ImportRootProjectOperation.java:104)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.access$300(ImportRootProjectOperation.java:39)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation$1.run(ImportRootProjectOperation.java:69)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2333)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.runInWorkspace(ImportRootProjectOperation.java:58)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.run(ImportRootProjectOperation.java:51)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.runInToolingApi(DefaultGradleBuild.java:225)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:58)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2338)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:39)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.run(DefaultGradleBuild.java:192)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:100)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:86)
	at org.eclipse.jdt.ls.core.internal.managers.GradleBuildSupport.update(GradleBuildSupport.java:92)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$3.runInWorkspace(ProjectsManager.java:355)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

   Locked ownable synchronizers:
	- None
```




[jstack Java Language thread state 30 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037732/jstack.Java.Language.thread.state.30.seconds.log)
[jstack Java Language thread state 35 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037733/jstack.Java.Language.thread.state.35.seconds.log)
[jstack Java Language thread state 40 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037734/jstack.Java.Language.thread.state.40.seconds.log)
[jstack Java Language thread state 50 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037735/jstack.Java.Language.thread.state.50.seconds.log)
[jstack Java Language thread state 60 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037736/jstack.Java.Language.thread.state.60.seconds.log)
[jstack Java Language thread state 70 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037737/jstack.Java.Language.thread.state.70.seconds.log)
[jstack Java Language thread state 80 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037738/jstack.Java.Language.thread.state.80.seconds.log)
[jstack Java Language thread state 90 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037739/jstack.Java.Language.thread.state.90.seconds.log)
[jstack Java Language thread state 100 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037740/jstack.Java.Language.thread.state.100.seconds.log)
[jstack Java Language thread state 110 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037742/jstack.Java.Language.thread.state.110.seconds.log)
[jstack Java Language thread state 120 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037743/jstack.Java.Language.thread.state.120.seconds.log)
[jstack Java Language thread state 130 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037744/jstack.Java.Language.thread.state.130.seconds.log)
[jstack Java Language thread state 140 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037745/jstack.Java.Language.thread.state.140.seconds.log)
[jstack Java Language thread state 150 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037746/jstack.Java.Language.thread.state.150.seconds.log)
[jstack Java Language thread state 160 seconds.log](https://github.com/redhat-developer/vscode-java/files/7037747/jstack.Java.Language.thread.state.160.seconds.log)

**Comment by snjeza** [comment]
@mozhuanzuojing Could you set the following properties:

```
"java.trace.server": "verbose",
"java.configuration.updateBuildConfiguration": "interactive",
```

disable the Visual Studio IntelliCode extension and send your JDT LS log (blockExecuteCommand.log)?

**Comment by mozhuanzuojing** [comment]
@snjeza This morning's log 08:44 ~ 08:52

> ### This is sampling
```log
[Trace - 上午8:47:07] Sending request 'workspace/executeCommand - (3019)'.
[Info  - 上午8:47:42] 2021年8月25日上午8:47:42 >> workspace/executeCommand vscode.java.prop.decrypt
[Trace - 上午8:47:42] Received response 'workspace/executeCommand - (3019)' in 34671ms.


[Trace - 上午8:49:10] Sending request 'textDocument/hover - (3030)'.
[Info  - 上午8:49:10] 2021年8月25日上午8:49:10 >> document/hover
[Trace - 上午8:49:11] Received response 'textDocument/hover - (3030)' in 1056ms.


[Trace - 上午8:48:32] Sending request 'workspace/executeCommand - (3026)'. 
Params: {
    "command": "vscode.java.resolveMainMethod",
    "arguments": [
        "file:///d%3A/project/ALL/am/AM_FA/facard/src/private/nc/impl/fa/asset/AssetImpl.java"
    ]
}
[Trace - 上午8:48:57] Received response 'workspace/executeCommand - (3026)' in 24644ms.
```
> ## full verbose log

[2021-08-25T08：44 ~ 08：52.log](https://github.com/redhat-developer/vscode-java/files/7042913/2021-08-25T08.44.08.52.log)

**Comment by mozhuanzuojing** [comment]
@snjeza please help me:
 The refresh operation of the vscode-gradle plugin will call the refresh project interface of the vscode-java plugin. Can this call be changed to let the user confirm whether to refresh, because the project does not need to be refreshed at all. It takes about 10 minutes to wait for each unnecessary refresh. I am very very very angry about this behavior! Makes my mood particularly bad. More serious is the impact on the promotion of vscode-java.


***
#### The following is the log called by vscode-gradle refresh operation

> ### sampling log
```log

####################################################################################
                             START TIME: [Trace - 上午9:15:46]
                               END TIME: [Trace - 上午9:26:15]
####################################################################################


######################################## Updating am configuration ############################################
[Trace - 上午9:16:29] Received notification 'language/status'.
Params: {
    "type": "Message",
    "message": "Updating am configuration"
}
[Info  - 上午9:16:29] 2021年8月25日上午9:16:29 Starting Gradle update for am
[Info  - 上午9:19:09] 2021年8月25日上午9:19:09 Updated am in 202992 ms
[Trace - 上午9:19:10] Received notification 'language/status'.
Params: {
    "type": "Message",
    "message": "Updating am configuration"
}

######################################## Refreshing workspace ############################################
[Trace - 上午9:19:10] Received notification 'language/progressReport'.
Params: {
    "id": "966bbe3f-67c8-4347-9cb3-e968b522c875",
    "task": "Refreshing workspace",
    "subTask": "Refreshing '/nccmain/alter-src-public'.",
    "status": "1% Refreshing '/nccmain/alter-src-public'.",
    "totalWork": 1000,
    "workDone": 9,
    "complete": false
}
[Trace - 上午9:25:02] Received notification 'language/progressReport'.
Params: {
    "id": "966bbe3f-67c8-4347-9cb3-e968b522c875",
    "task": "Refreshing workspace",
    "subTask": "Refreshing '/nccweb/client/yyconfig/modules/aim/embase/routeroad/config/action'.",
    "status": "100% Refreshing '/nccweb/client/yyconfig/modules/aim/embase/routeroad/config/action'.",
    "totalWork": 1000,
    "workDone": 996,
    "complete": false
}

######################################## Building each module ############################################
[Trace - 上午9:25:21] Received notification 'language/progressReport'.
Params: {
    "id": "fde31a9c-8fb1-4728-8de7-b27544e26f7e",
    "task": "Building",
    "status": "0% ",
    "totalWork": 1000,
    "workDone": 0,
    "complete": false
}
[Trace - 上午9:26:08] Received notification 'language/progressReport'.
Params: {
    "id": "fde31a9c-8fb1-4728-8de7-b27544e26f7e",
    "task": "Building",
    "subTask": "",
    "status": "100% ",
    "totalWork": 1000,
    "workDone": 1000,
    "complete": true
}

```

> ## full verbose log

[refresh.log](https://github.com/redhat-developer/vscode-java/files/7043041/refresh.log)

**Comment by snjeza** [comment]
@mozhuanzuojing could you try disabling all other Java related extensions, leave only the Language Support for Java(TM) by Red Hat?

**Comment by snjeza** [comment]
> [Info  - 上午9:16:29] 2021年8月25日上午9:16:29 Starting Gradle update for am
[Info  - 上午9:19:09] 2021年8月25日上午9:19:09 Updated am in 202992 ms

The Gradle update is called in the following cases:

- you run the Update project from the build.gradle file
- build.gradle or gradle.properties has been changed  (an external program or another extension can do it)
- a gradle preferences in settings.json has been changed
- .classpath has been deleted

You can try to set the following property:

```
"java.configuration.updateBuildConfiguration": "interactive",
```
or
```
"java.configuration.updateBuildConfiguration": "disabled",
```

**Comment by snjeza** [comment]
>  but I don't trust them to fix it soon

us? :)

**Comment by mozhuanzuojing** [comment]
> @mozhuanzuojing I can't reproduce the issue using the [spring-boot](https://github.com/spring-projects/spring-boot) project.
> Could you try disabling all other Java related extensions, leave only the Language Support for Java(TM) by Red Hat?

Okay, I use spring-boot for testing today

**Comment by mozhuanzuojing** [comment]
> The Gradle update is called in the following cases:
> 
> * you run the Update project command from the build.gradle file
> * build.gradle or gradle.properties has been changed  (an external program or another extension can do it)
> * a gradle preference in settings.json has been changed
> * .classpath has been deleted

I checked all files and configurations and there are no traces of changes. And also did not run `Update project command`
Includes `settings.json` `.classpath` `build.gradle` `gradle.properties`

**Comment by mozhuanzuojing** [comment]
> or
> 
> ```
> "java.configuration.updateBuildConfiguration": "disabled",
> ```

i will try it

**Comment by mozhuanzuojing** [comment]
> us? :)

Are you a team? Haha

**Comment by trinhpham** [comment]
@mozhuanzuojing I have the same problem and I use Spring Boot also.
Did you figure out which extension causes the issue?
Disabling all other extensions makes me feel like a soldier without weapons :rofl:

**Comment by snjeza** [comment]
@trinhpham You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2108#issuecomment-921396583 and [Performance degrades with Gradle Project](https://github.com/redhat-developer/vscode-java/wiki/Gradle-Support#performance-degrades-with-gradle-project)
