### ISSUE TITLE
Java LS sometimes hangs while loading a gradle project

### ISSUE THREAD

**Issue by snjeza** [redhat-developer/vscode-java#2088]
Steps To Reproduce:

1. git clone https://github.com/mac-comp127/welcome-app.git
2. cd welcome-app.git
3. code . 
Wait for VS Code to build the project.
4. exit VS Code
5. code .

If you repeat steps 4 and 5 a few times, VS Code will hang.

- Operating System: All
- JDK version: 16.0.1
- Visual Studio Code version: 1.59.1
- Java extension version: 0.81.0

**Comment by snjeza** [comment]
@fbricon @rgrunber @Artur- @pcantrell Could you try to reproduce the issue using https://github.com/snjeza/vscode-test/raw/master/java-0.82.3.vsix

**Comment by BeefaloKing** [comment]
I get this exact issue using JDK version 16.0.2. I noticed deleting the generated ".project" file in the project root temporarily fixes this, but repeating 4&5 above cause the issue to happen again.

**Comment by rgrunber** [comment]
I believe I've run into this. Haven't tried the .vsix yet but I will :

My logs showed :

```
[Warn  - 5:13:49 PM] Sep 13, 2021, 5:13:49 PM While loading class "org.eclipse.buildship.core.internal.preferences.PersistentModelConverter$11", thread "Thread[Worker-4: Load persistent model for all projects,5,main]" timed out waiting (30008ms) for thread "Thread[Worker-2: Initialize Workspace,5,main]" to finish starting bundle "org.eclipse.buildship.core_3.1.5.v20210616-0346-s [14]". To avoid deadlock, thread "Thread[Worker-4: Load persistent model for all projects,5,main]" is proceeding but "org.eclipse.buildship.core.internal.preferences.PersistentModelConverter$11" may not be fully initialized.
Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.5.v20210616-0346-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=14] STARTED [STARTED]
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.5.v20210616-0346-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=14] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:350)
	at org.eclipse.osgi.container.Module.start(Module.java:419)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:404)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:388)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:467)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at org.eclipse.buildship.core.internal.preferences.PersistentModelConverter.toModel(PersistentModelConverter.java:135)
	at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence.doLoadModel(DefaultModelPersistence.java:127)
	at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence.access$000(DefaultModelPersistence.java:51)
	at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$1.load(DefaultModelPersistence.java:60)
	at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$1.load(DefaultModelPersistence.java:56)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
	at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$2.run(DefaultModelPersistence.java:190)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 30 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:347)
	... 23 more
Caused by: org.eclipse.osgi.framework.util.ThreadInfoReport: Thread dump

ThreadId: 30 ThreadName: Worker-2: Initialize Workspace ThreadState: WAITING
  Blocked On: com.google.common.util.concurrent.SettableFuture@75dfb6aa LockOwnerId: -1 LockOwnerName: null
  Synchronizers Locked: 
    java.util.concurrent.locks.ReentrantLock$NonfairSync@1093a168
  Monitors Locked: none
  Stack Trace: 
    java.base@16.0.2/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@16.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
    com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:537)
    com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104)
    com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240)
    com.google.common.cache.LocalCache$LoadingValueReference.waitForValue(LocalCache.java:3582)
    com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2175)
    com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2162)
    com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
    com.google.common.cache.LocalCache.get(LocalCache.java:3951)
    com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
    com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
    com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
    org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence.loadModel(DefaultModelPersistence.java:67)
    org.eclipse.buildship.core.internal.CorePlugin.scheduleSynchronizationForAbsentModels(CorePlugin.java:223)
    org.eclipse.buildship.core.internal.CorePlugin.start(CorePlugin.java:120)
    org.eclipse.osgi.internal.framework.BundleContextImpl.lambda$2(BundleContextImpl.java:808)
    org.eclipse.osgi.internal.framework.BundleContextImpl$$Lambda$76/0x0000000801096050.run(Unknown Source)
    java.base@16.0.2/java.security.AccessController.executePrivileged(AccessController.java:784)
    java.base@16.0.2/java.security.AccessController.doPrivileged(AccessController.java:554)
    org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:802)
    org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:759)
    org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1019)
    org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
    org.eclipse.osgi.container.Module.doStart(Module.java:605)
    org.eclipse.osgi.container.Module.start(Module.java:468)
    org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:404)
    org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
    org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
    org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
    org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:388)
    org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
    org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:463)
    org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
    java.base@16.0.2/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
    java.base@16.0.2/java.lang.Class.getDeclaredConstructors0(Native Method)
    java.base@16.0.2/java.lang.Class.privateGetDeclaredConstructors(Class.java:3305)
    java.base@16.0.2/java.lang.Class.getConstructor0(Class.java:3510)
    java.base@16.0.2/java.lang.Class.getDeclaredConstructor(Class.java:2691)
    org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
    org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
    org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
    org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
    org.eclipse.jdt.ls.core.internal.ExtensionsExtractor.makeExtension(ExtensionsExtractor.java:47)
    org.eclipse.jdt.ls.core.internal.ExtensionsExtractor.extractOrderedExtensions(ExtensionsExtractor.java:39)
    org.eclipse.jdt.ls.core.internal.managers.BuildSupportManager.obtainBuildSupports(BuildSupportManager.java:38)
    org.eclipse.jdt.ls.core.internal.managers.BuildSupportManager.find(BuildSupportManager.java:53)
    org.eclipse.jdt.ls.core.internal.managers.BuildSupportManager.find(BuildSupportManager.java:45)
    org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.deleteInvalidProjects(StandardProjectsManager.java:141)
    org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.cleanInvalidProjects(StandardProjectsManager.java:128)
    org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:120)
    org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:209)
    org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
    org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

ThreadId: 34 ThreadName: Worker-4: Load persistent model for all projects ThreadState: RUNNABLE
  Blocked On: org.eclipse.osgi.internal.container.EquinoxReentrantLock@48d1f90d[Locked by thread Worker-2: Initialize Workspace]
  Synchronizers Locked: none
  Monitors Locked: 
    com.google.common.cache.LocalCache$StrongEntry@21c3e9a9
  Stack Trace: 
    java.management@16.0.2/sun.management.ThreadImpl.dumpThreads0(Native Method)
    java.management@16.0.2/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
    java.management@16.0.2/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
    org.eclipse.osgi.framework.util.ThreadInfoReport.getThreadDump(ThreadInfoReport.java:30)
    org.eclipse.osgi.framework.util.ThreadInfoReport.<init>(ThreadInfoReport.java:23)
    org.eclipse.osgi.container.Module.lockStateChange(Module.java:347)
    org.eclipse.osgi.container.Module.start(Module.java:419)
    org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:404)
    org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
    org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
    org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
    org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:388)
    org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:467)
    org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
    java.base@16.0.2/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
    org.eclipse.buildship.core.internal.preferences.PersistentModelConverter.toModel(PersistentModelConverter.java:135)
    org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence.doLoadModel(DefaultModelPersistence.java:127)
    org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence.access$000(DefaultModelPersistence.java:51)
    org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$1.load(DefaultModelPersistence.java:60)
    org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$1.load(DefaultModelPersistence.java:56)
    com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
    com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
    com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
    com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
    com.google.common.cache.LocalCache.get(LocalCache.java:3951)
    com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
    com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
    org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$2.run(DefaultModelPersistence.java:190)
    org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rgrunber** [comment]
Only additional thing I would maybe investigate is whether we could achieve the same thing with setting autoStart=true and startLevel=0 like in https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.product/languageServer.product#L75 .

**Comment by snjeza** [comment]
> Only additional thing I would maybe investigate is whether we could achieve the same thing with setting autoStart=true and startLevel=0 like in https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.product/languageServer.product#L75 for the buildship+m2e plugins.

@rgrunber See
 https://github.com/eclipse/eclipse.jdt.ls/pull/1874/commits/7a53bbb41833f03187c754b34c3de97b62f5cb34#diff-a66ce976d16a16e66f00ca6bd926089df91767ebc6d61c8c121504e5651272b4R228
and
https://github.com/eclipse/eclipse.jdt.ls/pull/1874/commits/7a53bbb41833f03187c754b34c3de97b62f5cb34#diff-a66ce976d16a16e66f00ca6bd926089df91767ebc6d61c8c121504e5651272b4R223

**Comment by rgrunber** [comment]
> > Only additional thing I would maybe investigate is whether we could achieve the same thing with setting autoStart=true and startLevel=0 like in https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.product/languageServer.product#L75 for the buildship+m2e plugins.
> 
> @rgrunber See
> [eclipse/eclipse.jdt.ls@7a53bbb#diff-a66ce976d16a16e66f00ca6bd926089df91767ebc6d61c8c121504e5651272b4R228](https://github.com/eclipse/eclipse.jdt.ls/commit/7a53bbb41833f03187c754b34c3de97b62f5cb34#diff-a66ce976d16a16e66f00ca6bd926089df91767ebc6d61c8c121504e5651272b4R228)
> and
> [eclipse/eclipse.jdt.ls@7a53bbb#diff-a66ce976d16a16e66f00ca6bd926089df91767ebc6d61c8c121504e5651272b4R223](https://github.com/eclipse/eclipse.jdt.ls/commit/7a53bbb41833f03187c754b34c3de97b62f5cb34#diff-a66ce976d16a16e66f00ca6bd926089df91767ebc6d61c8c121504e5651272b4R223)

Right. We'd never be sure the jobs actually complete.
