### ISSUE TITLE
CancellationException in output log

### ISSUE THREAD

**Issue by aeschli** [redhat-developer/vscode-java#213]
Language support for Java ™ for Visual Studio Code, v0.4.0

- java version "1.8.0_131"
- created a sample maven app 
- doing code assist in AppTest.java
```
    public void testApp2()
    {
        String s = "Hello";
        s.|<assist here

    }
```
- shows the folloing exception in the Java output.
No harm seems done, all works fine, but confuses a bit.

```
java.util.concurrent.CancellationException
	at org.eclipse.lsp4j.jsonrpc.CompletableFutures.lambda$computeAsync$0(CompletableFutures.java:29)
	at org.eclipse.jdt.ls.core.internal.CancellableProgressMonitor.isCanceled(CancellableProgressMonitor.java:36)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.checkCancel(CompletionEngine.java:1818)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.acceptType(CompletionEngine.java:1315)
	at org.eclipse.jdt.internal.core.SearchableEnvironmentRequestor.acceptType(SearchableEnvironmentRequestor.java:115)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypesInBinaryPackage(NameLookup.java:1087)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:1021)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:964)
	at org.eclipse.jdt.internal.core.NameLookup.findAllTypes(NameLookup.java:330)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:997)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:964)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findTypes(SearchableEnvironment.java:670)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findTypes(SearchableEnvironment.java:466)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findTypesAndPackages(CompletionEngine.java:10832)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnSingleNameReference(CompletionEngine.java:3451)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:1849)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2075)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:131)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:357)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:345)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:79)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.lambda$0(CompletionHandler.java:39)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.CancellationException
	at org.eclipse.lsp4j.jsonrpc.CompletableFutures.lambda$computeAsync$0(CompletableFutures.java:29)
	at org.eclipse.jdt.ls.core.internal.CancellableProgressMonitor.isCanceled(CancellableProgressMonitor.java:36)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.checkCancel(CompletionEngine.java:1818)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.acceptType(CompletionEngine.java:1315)
	at org.eclipse.jdt.internal.core.SearchableEnvironmentRequestor.acceptType(SearchableEnvironmentRequestor.java:115)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypesInBinaryPackage(NameLookup.java:1087)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:1021)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:964)
	at org.eclipse.jdt.internal.core.NameLookup.findAllTypes(NameLookup.java:330)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:997)
	at org.eclipse.jdt.internal.core.NameLookup.seekTypes(NameLookup.java:964)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findTypes(SearchableEnvironment.java:670)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findTypes(SearchableEnvironment.java:466)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.findTypesAndPackages(CompletionEngine.java:10832)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.completionOnSingleNameReference(CompletionEngine.java:3451)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:1849)
	at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.java:2075)
	at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:131)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:357)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:345)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:79)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.lambda$0(CompletionHandler.java:39)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fbricon** [comment]
Doing my best to try to reproduce the issue, but no dice so far. Even putting a breakpoint on the server then hitting escape on the vscode side doesn't generate the CancellationException.

@aeschli do you see the problem consistently?

**Comment by fbricon** [comment]
Even though I can't reproduce the issue, I made sure no exception is propagated when calling monitor.isCancelled() in https://github.com/eclipse/eclipse.jdt.ls/commit/79e64210cc9008e67d395af6d8f02422562992f6

**Comment by aeschli** [comment]
@fbricon Trying again, I also can't reproduce it anymore today.
From how I remember it, the CancellationException can occur with every method that takes a progress monitor. When you use a method that takes an IProgressMonitor you need to handle it.
