### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by KREATIV-LSH** [redhat-developer/vscode-java#2141]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `0.82.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.60.2`

:warning: 
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 160,
		"activateCallTime": 15,
		"activateResolvedTime": 22749,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscjava.vscode-java-test",
				"_lower": "vscjava.vscode-java-test"
			},
			"activationEvent": "onLanguage:java"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Connection got disposed."
		}
	],
	"runningLocation": 1
}
```

**Comment by KREATIV-LSH** [comment]
I tried running a Java class inside of vscode but it wouldn't do anything and when I went to the extensions tab I saw that there was an error in the extension

**Comment by KREATIV-LSH** [comment]
No still same thing

**Comment by sclorng** [comment]
I got a connection disposed.
I clean workspace and restart, extension open projects in workspace (refresh and build status done) and right after the LS log shows 

```
0f2c5957 Importing Maven project(s) [Done]
fc1a5c5a Repository registry initialization [Done]
0ef3205d Clean workspace... [Done]
8c4824dc Building [Done]
e21641cf Validate documents [Done]
6c728cc1 Building [Done]
e820027d Publish Diagnostics [Done]
8ee82c93 Building [Done]
```

And right after 8ee82c93 :

LSJ logs
```
[Error - 6:01:58 PM] Connection to server got closed. Server will not be restarted.
```

around the same time
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2021-12-08 18:01:58.239
!MESSAGE >> workspace/executeCommand java.getPackageData

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-12-08 18:01:58.260
!MESSAGE >> workspace/executeCommand java.getPackageData
```

Developer tools logs
```
stack trace: Error: Connection got disposed.	at Object.dispose (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:901161)	at Object.dispose (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:748103)	at b.handleConnectionClosed (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:748291)	at b.handleConnectionClosed (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:821964)	at t (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:746405)	at invoke (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:902787)	at o.fire (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:903548)	at Z (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:890300)	at invoke (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:902787)	at o.fire (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:903548)	at p.fireClose (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:911439)	at Socket.<anonymous> (/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2:913024)	at Socket.emit (events.js:327:22)	at Pipe.<anonymous> (net.js:673:12)
E @ workbench.desktop.main.js:77
$logExtensionHostMessage @ workbench.desktop.main.js:1525
_doInvokeHandler @ workbench.desktop.main.js:1525
_invokeHandler @ workbench.desktop.main.js:1525
_receiveRequest @ workbench.desktop.main.js:1525
_receiveOneMessage @ workbench.desktop.main.js:1525
(anonymous) @ workbench.desktop.main.js:1525
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:85
_receiveMessage @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:69
acceptChunk @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:610
fire @ workbench.desktop.main.js:69
_fileReader.onload @ workbench.desktop.main.js:610
load (async)
y @ workbench.desktop.main.js:610
create @ workbench.desktop.main.js:610
connect @ workbench.desktop.main.js:610
c @ workbench.desktop.main.js:610
r @ workbench.desktop.main.js:610
s @ workbench.desktop.main.js:610
d @ workbench.desktop.main.js:610
b @ workbench.desktop.main.js:610
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
b @ workbench.desktop.main.js:610
(anonymous) @ workbench.desktop.main.js:1578
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ workbench.desktop.main.js:1578
jr @ workbench.desktop.main.js:1572
_createInstance @ workbench.desktop.main.js:599
createInstance @ workbench.desktop.main.js:599
v @ workbench.desktop.main.js:1572
(anonymous) @ workbench.desktop.main.js:2967
_startExtensionHosts @ workbench.desktop.main.js:2967
_initialize @ workbench.desktop.main.js:2967
(anonymous) @ workbench.desktop.main.js:2968
requestIdleCallback (async)
e.runWhenIdle @ workbench.desktop.main.js:77
(anonymous) @ workbench.desktop.main.js:2968
Promise.then (async)
Yl @ workbench.desktop.main.js:2968
_createInstance @ workbench.desktop.main.js:599
_createServiceInstance @ workbench.desktop.main.js:599
_createServiceInstanceWithOwner @ workbench.desktop.main.js:599
_createAndCacheServiceInstance @ workbench.desktop.main.js:599
_safeCreateAndCacheServiceInstance @ workbench.desktop.main.js:599
_getOrCreateServiceInstance @ workbench.desktop.main.js:599
_createInstance @ workbench.desktop.main.js:599
createInstance @ workbench.desktop.main.js:599
acquireInstantiationService @ workbench.desktop.main.js:1925
(anonymous) @ workbench.desktop.main.js:2635
invokeFunction @ workbench.desktop.main.js:599
initServices @ workbench.desktop.main.js:2635
startup @ workbench.desktop.main.js:2635
open @ workbench.desktop.main.js:2883
async function (async)
open @ workbench.desktop.main.js:2883
C @ workbench.desktop.main.js:2883
m.load.configureDeveloperSettings @ workbench.js:1
(anonymous) @ bootstrap-window.js:1
i._invokeFactory @ loader.js:5
i.complete @ loader.js:5
i._onModuleComplete @ loader.js:6
i._onModuleComplete @ loader.js:6
i._resolve @ loader.js:6
i.defineModule @ loader.js:5
v @ loader.js:6
define @ loader.js:6
(anonymous) @ workbench.desktop.main.js:2968
(anonymous) @ workbench.desktop.main.js:2968
workbench.desktop.main.js:1851 [[object Object]]Connection got disposed.
$onExtensionRuntimeError @ workbench.desktop.main.js:1851
_doInvokeHandler @ workbench.desktop.main.js:1525
_invokeHandler @ workbench.desktop.main.js:1525
_receiveRequest @ workbench.desktop.main.js:1525
_receiveOneMessage @ workbench.desktop.main.js:1525
(anonymous) @ workbench.desktop.main.js:1525
fire @ workbench.desktop.main.js:69
fire @ workbench.desktop.main.js:85
_receiveMessage @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:69
acceptChunk @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:85
(anonymous) @ workbench.desktop.main.js:610
fire @ workbench.desktop.main.js:69
_fileReader.onload @ workbench.desktop.main.js:610
load (async)
y @ workbench.desktop.main.js:610
create @ workbench.desktop.main.js:610
connect @ workbench.desktop.main.js:610
c @ workbench.desktop.main.js:610
r @ workbench.desktop.main.js:610
s @ workbench.desktop.main.js:610
d @ workbench.desktop.main.js:610
b @ workbench.desktop.main.js:610
processTicksAndRejections @ internal/process/task_queues.js:93
async function (async)
b @ workbench.desktop.main.js:610
(anonymous) @ workbench.desktop.main.js:1578
processTicksAndRejections @ internal/process/task_queues.js:93
Promise.then (async)
start @ workbench.desktop.main.js:1578
jr @ workbench.desktop.main.js:1572
_createInstance @ workbench.desktop.main.js:599
createInstance @ workbench.desktop.main.js:599
v @ workbench.desktop.main.js:1572
(anonymous) @ workbench.desktop.main.js:2967
_startExtensionHosts @ workbench.desktop.main.js:2967
_initialize @ workbench.desktop.main.js:2967
(anonymous) @ workbench.desktop.main.js:2968
requestIdleCallback (async)
e.runWhenIdle @ workbench.desktop.main.js:77
(anonymous) @ workbench.desktop.main.js:2968
Promise.then (async)
Yl @ workbench.desktop.main.js:2968
_createInstance @ workbench.desktop.main.js:599
_createServiceInstance @ workbench.desktop.main.js:599
_createServiceInstanceWithOwner @ workbench.desktop.main.js:599
_createAndCacheServiceInstance @ workbench.desktop.main.js:599
_safeCreateAndCacheServiceInstance @ workbench.desktop.main.js:599
_getOrCreateServiceInstance @ workbench.desktop.main.js:599
_createInstance @ workbench.desktop.main.js:599
createInstance @ workbench.desktop.main.js:599
acquireInstantiationService @ workbench.desktop.main.js:1925
(anonymous) @ workbench.desktop.main.js:2635
invokeFunction @ workbench.desktop.main.js:599
initServices @ workbench.desktop.main.js:2635
startup @ workbench.desktop.main.js:2635
open @ workbench.desktop.main.js:2883
async function (async)
open @ workbench.desktop.main.js:2883
C @ workbench.desktop.main.js:2883
m.load.configureDeveloperSettings @ workbench.js:1
(anonymous) @ bootstrap-window.js:1
i._invokeFactory @ loader.js:5
i.complete @ loader.js:5
i._onModuleComplete @ loader.js:6
i._onModuleComplete @ loader.js:6
i._resolve @ loader.js:6
i.defineModule @ loader.js:5
v @ loader.js:6
define @ loader.js:6
(anonymous) @ workbench.desktop.main.js:2968
(anonymous) @ workbench.desktop.main.js:2968
workbench.desktop.main.js:1851 Error: Connection got disposed.
	at Object.dispose (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at Object.dispose (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at b.handleConnectionClosed (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at b.handleConnectionClosed (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at t (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at invoke (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at o.fire (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at Z (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at invoke (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at o.fire (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at p.fireClose (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at Socket.<anonymous> (vscode-file://vscode-app/home/vscode/.vscode-server/extensions/redhat.java-1.0.0/dist/extension.js:2)
	at Socket.emit (events.js:327)
	at Pipe.<anonymous> (net.js:673)
```

**Comment by mohitsuman** [comment]
@KREATIV-LSH @sclorng can you please try out the latest release of the extension and let us know if this issue still happens or we can close this.

**Comment by KREATIV-LSH** [comment]
I switched to Linux and never tested it again, unfortunately I don't have the Windows install I used back then so I can't test it.
