### ISSUE TITLE
Maven Local Dependencies: Failed to get sources. Instead, stub sources have been generated by the disassembler.

### ISSUE THREAD

**Issue by rhystedstone** [redhat-developer/vscode-java#2143]
None of my maven projects show documentation on class from local maven dependencies and display a message when trying to get the "super implementation": 
> Failed to get sources.
Instead, stub sources have been generated by the disassembler.

##### Environment
- Operating System:    Windows 10 Pro 21H1
- JDK version:    jdk-16.0.2.7-hotspot
- Visual Studio Code version:    1.60.2 (user setup)
- Java extension version:    0.82.0

##### Steps To Reproduce
1. Use a locallly-installed dependency in your maven project
2. Attempt to view it's source or docs

pom.xml:
```java
        <dependency>
            <groupId>net.abyssalvoid.guiapi</groupId>
            <artifactId>guiapi</artifactId>
            <version>0.4.0</version>
            <scope>provided</scope>
        </dependency>
```
When trying to get the definition of any of the classes:
```java
 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
```

##### Logs
DevTools log:
_(Note: These errors only occured when trying to view the definitions)_
```
 ERR Internal error.: Error: Internal error.
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:871621
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:871915
    at Immediate.<anonymous> (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:872280)
    at processImmediate (internal/timers.js:461:21)
2log.ts:301   ERR Cannot read property 'slice' of undefined: TypeError: Cannot read property 'slice' of undefined
    at l.printTask (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623409)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623288
    at Array.forEach (<anonymous>)
    at l.printTasks (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623271)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623219
    at c.fire (c:\Users\Rhys\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at Object.u.updateServerTask (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:625194)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:643598
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:870514
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:870732
    at Immediate._onImmediate (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:872280)
    at processImmediate (internal/timers.js:461:21)
log.ts:301   ERR Cannot read property 'slice' of undefined: TypeError: Cannot read property 'slice' of undefined
    at l.printTask (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623479)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623288
    at Array.forEach (<anonymous>)
    at l.printTasks (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623271)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623219
    at c.fire (c:\Users\Rhys\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at Object.u.updateServerTask (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:625194)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:643598
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:870514
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:870732
    at Immediate._onImmediate (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:872280)
    at processImmediate (internal/timers.js:461:21)
log.ts:301   ERR Cannot read property 'slice' of undefined: TypeError: Cannot read property 'slice' of undefined
    at l.printTask (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623409)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623288
    at Array.forEach (<anonymous>)
    at l.printTasks (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623271)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:623219
    at c.fire (c:\Users\Rhys\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at Object.u.updateServerTask (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:625194)
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:643598
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:870514
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:870732
    at Immediate._onImmediate (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:872280)
    at processImmediate (internal/timers.js:461:21)
log.ts:301   ERR Internal error.: Error: Internal error.
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:871621
    at c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:871915
    at Immediate.<anonymous> (c:\Users\Rhys\.vscode\extensions\redhat.java-0.82.0\dist\extension.js:2:872280)
    at processImmediate (internal/timers.js:461:21)
```

Language Server Log:
_(Again, while trying to find the definition)_
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:02.952
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:02.952
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:02.952
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:03.127
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:03.174
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:03.195
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:03.609
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:03.854
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:04.889
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:05.272
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:05.744
!MESSAGE >> document/definition

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-10-01 01:11:05.747
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:05.767
!MESSAGE >> java/classFileContents

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:05.794
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:05.814
!MESSAGE >> textDocument/semanticTokens/full

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:05.981
!MESSAGE >> document/foldingRange

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-10-01 01:11:05.982
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:06.034
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:07.801
!MESSAGE >> document/definition

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-10-01 01:11:07.802
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-10-01 01:11:08.837
!MESSAGE >> document/didClose

```

##### Current Result
We just see:
` // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.`
##### Expected Result
A fully or somewhat-documented class, showing the "Super Implementation"
##### Additional Information
I've found two other GitHub issues referencing this problem, however, both were inconclusive:
- #2055 was just closed without any explanation - Possibly the author didn't want to share any examples
- #1231 was caused by the use of incorrect case in artifact IDs, however, this problem occurs on every project I have that uses local dependencies and I have verified the artifact ID.

The project doesn't fail to compile, it just doesn't show any documentation or implementations.
It doesn't matter if VSCode or Eclipse compiled the code.
It has been tested with my own dependencies and other authors'.
Finally, this issue doesn't occur on remote dependencies.

**Comment by snjeza** [comment]
I can't reproduce the issue.
@rhystedstone Have you installed the guiapi sources?
```
mvn source:jar install
```

**Comment by rhystedstone** [comment]
> I can't reproduce the issue. @rhystedstone Have you installed the guiapi sources?
> 
> ```
> mvn source:jar install
> ```

Thank you for this.
I have searched many places and never found this solution!
