### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by 0xD8C4A475** [redhat-developer/vscode-java#2202]
```
[renderer1] [error] Cannot read property 'slice' of undefined: TypeError: Cannot read property 'slice' of undefined
    at l.printTask (<projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:646781)
    at <projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:646660
    at Array.forEach (<anonymous>)
    at l.printTasks (<projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:646643)
    at <projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:646591
    at a.fire (<projectpath>\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at Object.u.updateServerTask (<projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:648566)
    at <projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:666970
    at <projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:893886
    at <projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:894104
    at Immediate._onImmediate (<projectpath>\data\extensions\redhat.java-1.0.0\dist\extension.js:2:895652)
    at processImmediate (internal/timers.js:461:21)
```

##### Environment
- Operating System: Windows 10 Latest
- JDK version: 1.8-14
- Visual Studio Code version: 1.61.2
- Java extension version: v1.0.0

##### Steps To Reproduce
1. Start VSCode with Language Support for Java(TM) by Red Hat extension
2. Output -> Log(Window)

**Comment by fbricon** [comment]
I believe this was fixed 3 years ago, by https://github.com/eclipse-jdtls/eclipse.jdt.ls/commit/e64c205d6b2c3edbf6a9f5df3b4c216ba35d3c87#diff-fd5c56b9cb5b5d6284eb995eb75b220631d55836ed4d7c5bc123bca9c7e1dbb9R184, which guarantees the token is non-null in all situations.
