### ISSUE TITLE
Incomplete classpath when opening eclipse.jdt.ls in VSCode

### ISSUE THREAD

**Issue by aeschli** [redhat-developer/vscode-java#221]
VSCode 1.12
vscode-java 0.4.0

- git clone https://github.com/eclipse/eclipse.jdt.ls.git
- run `./mvnw clean verify`
- open VSCode on the folder
- error `Classpath is incomplete. Only syntax errors will be reported`

Output shows:
```
[Error - 10:48:28 PM] May 22, 2017 10:48:27 PM JavaBuilder handling ImageBuilderInternalException while building: jdt.ls-java-project
Problems encountered while copying resources.
org.eclipse.core.internal.resources.ResourceException: Problems encountered while copying resources.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.copy(FileSystemResourceManager.java:336)
	at org.eclipse.core.internal.resources.Resource.copy(Resource.java:545)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.copyResource(AbstractImageBuilder.java:383)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder$3.visit(BatchImageBuilder.java:231)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.copyExtraResourcesBack(BatchImageBuilder.java:200)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.cleanOutputFolders(BatchImageBuilder.java:124)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:47)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:110)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Contains: Resource '/jdt.ls-java-project/src/pom.xml' does not exist.
```

Is it a supported scenario? Would be great to selfhost.

**Comment by fbricon** [comment]
Dogfooding is @gorkem's wet dream :-)

It's not supported at the moment because jdt.ls needs PDE plugins to build itself. Probably also needs m2e-tycho support. 

Regardless, `Resource '/jdt.ls-java-project/src/pom.xml' does not exist` looks weird (I'm assuming you cloned the repo under jdt.ls-java-project). We need to investigate why it's looking for a pom.xml under src/

**Comment by fbricon** [comment]
I should create a `wet-dream` label

**Comment by hpolloni** [comment]
@fbricon are you talking about the "jdt.ls-java-project" bit?

AFAIK, that's the default project name used in Eclipse JDT LS.

src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java:     public static final String DEFAULT_PROJECT_NAME= "jdt.ls-java-project";

**Comment by fbricon** [comment]
@hpolloni yes, I was confused initially. I should have known better since I implemented it :-)

**Comment by hpolloni** [comment]
Don't mean to hijack the thread. I was just browsing that class yesterday (trying to add custom classpaths). That's why I remembered

**Comment by gorkem** [comment]
I think we can close this. We have a solution at https://github.com/gorkem/jdt.ls.pde

**Comment by rgrunber** [comment]
Closing as requested long ago. We can revisit this in https://github.com/redhat-developer/vscode-java/issues/2046 .

**Comment by testforstephen** [comment]
This is already supported. Our team is already using the [vscode-pde](https://marketplace.visualstudio.com/items?itemName=yaozheng.vscode-pde) extension to dogfood eclipse.jdt.ls in VS Code.
