### ISSUE TITLE
Error during initialization

### ISSUE THREAD

**Issue by CarlPer** [redhat-developer/vscode-java#2260]
An internal error occurred during: "Initialize workspace".

##### Environment
- Operating System: Win 10
- JDK version:  1.8
- Visual Studio Code version: 1.63.2
- Java extension version: 1.2.0

##### Steps To Reproduce
1.  Open up VSCode

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
```
[Error - 16:27:22] 22 dec. 2021 16:27:22 An internal error occurred during: "Initialize workspace".
URI is not hierarchical
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.addWatcher(StandardProjectsManager.java:532)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:467)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by snjeza** [comment]
> JDK version: 1.8

@CarlPer could you try JDK >= 11?

**Comment by testforstephen** [comment]
@CarlPer Could you pls share the full logs? thanks.

**F1 -> Java: Open All Log Files**

**Comment by CarlPer** [comment]
@snjeza Same for JDK 11
`[Error - 09:48:41] 10 jan. 2022 09:48:41 An internal error occurred during: "Initialize workspace".
URI is not hierarchical
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.addWatcher(StandardProjectsManager.java:532)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:467)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by CarlPer** [comment]
@testforstephen here is the log
[.log](https://github.com/redhat-developer/vscode-java/files/7837664/default.log)

**Comment by testforstephen** [comment]
@CarlPer Your setting `"java.settings.url"` is not a valid URI, you need to set it to `"file:///C:/Users/Rottosson/.vscode/settings.prefs"`.

**Comment by snjeza** [comment]
@CarlPer There isn't .vscode\settings.prefs
You should remove the _java.settings.url_ property.

**Comment by CarlPer** [comment]
@snjeza  "file:///C:/Users/Rottosson/.vscode/settings.prefs" did not solve the problem.
The file works, because if I remove it I will lose a lot of project warnings/infos.

**Comment by snjeza** [comment]
>  "file:///C:/Users/Rottosson/.vscode/settings.prefs" did not solve the problem.
The file works, because if I remove it I will lose a lot of project warnings/infos.

@CarlPer could you try to create/add 
```
C:\\Users\\Rottosson\\.vscode\\settings.prefs
```

**Comment by CarlPer** [comment]
@snjeza Tried that and starting with "file:\\C...."
Neither does work and I get this new error instead:
`[Error - 07:39:42] 12 jan. 2022 07:39:42 Illegal character in opaque part at index 2: C:\Users\Rottosson\.vscode\settings.prefs
Illegal character in opaque part at index 2: C:\Users\Rottosson\.vscode\settings.prefs
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\Rottosson\.vscode\settings.prefs
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.getURIs(StandardProjectsManager.java:503)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.fileChanged(StandardProjectsManager.java:199)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceEventsHandler.didChangeWatchedFiles(WorkspaceEventsHandler.java:115)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didChangeWatchedFiles(JDTLanguageServer.java:497)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by CarlPer** [comment]
@snjeza Thanks, now it finally works!
