### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by weathery** [redhat-developer/vscode-java#2315]
When i update the maven project, VScode occure "Extension host terminated unexpectedly."

##### Environment
- Operating System: Win 7 x64
- JDK version: Oracle jdk-11.0.13
- Visual Studio Code version: v1.64.2
- Java extension version:  v1.2.0 - v1.3.0

##### Steps To Reproduce
1. click the pom.xml of the maven's project, and right click the "update project".
2. terminal show as followd:
```
2c6c12d5 Repository registry initialization [Done]
64daf42a Importing Maven project(s) [Done]
be763b1d Refreshing workspace [Done]
9528a487 Validate documents [Done]
b52ba2c7 Publish Diagnostics [Done]
18efd8b4 Building [Done]
8c9ef352 Building [Done]
efd78240 Resolve plugin dependency [Done]
17354cef Building [Done]
e5d03309 Building [Done]
51f3710e Register Watchers [Done]
50ba0f1c Building [Done]
7a54bc3e Building [Done]
```
3. vscode show:
![image](https://user-images.githubusercontent.com/8264089/153540766-8c26bbd4-1e45-445b-9ade-7624976782f8.png)

4. Log(Extension Host):
```
[2022-02-11 15:13:37.575] [exthost] [info] Extension host with pid 8184 started
[2022-02-11 15:13:37.685] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-02-11 15:13:37.714] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-02-11 15:13:37.719] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.github
[2022-02-11 15:13:37.763] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-02-11 15:13:37.789] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-02-11 15:13:37.955] [exthost] [info] Eager extensions activated
[2022-02-11 15:13:37.956] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-02-11 15:13:37.980] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:13:37.986] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:13:37.990] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:13:38.003] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:14:01.651] [exthost] [info] extension host terminating: renderer closed the socket
[2022-02-11 15:14:01.660] [exthost] [info] Extension host with pid 8184 exiting with code 0
[2022-02-11 15:14:03.971] [exthost] [info] Extension host with pid 4960 started
[2022-02-11 15:14:03.972] [exthost] [info] Skipping acquiring lock for c:\Users\Admin\AppData\Roaming\Code\User\workspaceStorage\5282d38c9d954842928a7578a5c806ba.
[2022-02-11 15:14:04.167] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-02-11 15:14:04.191] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-02-11 15:14:04.196] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.github
[2022-02-11 15:14:04.199] [exthost] [info] ExtensionService#_doActivateExtension GabrielBB.vscode-lombok, startup: true, activationEvent: 'workspaceContains:pom.xml'
[2022-02-11 15:14:04.206] [exthost] [info] ExtensionService#_doActivateExtension redhat.java, startup: true, activationEvent: 'workspaceContains:pom.xml'
[2022-02-11 15:14:04.258] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-dependency, startup: true, activationEvent: 'workspaceContains:pom.xml'
[2022-02-11 15:14:04.279] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-pack, startup: true, activationEvent: 'workspaceContains:pom.xml'
[2022-02-11 15:14:04.450] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-02-11 15:14:04.468] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-02-11 15:14:05.240] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-maven, startup: true, activationEvent: 'workspaceContains:**/pom.xml'
[2022-02-11 15:14:05.360] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-02-11 15:14:06.999] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2022-02-11 15:14:07.133] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2022-02-11 15:14:16.722] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:14:16.733] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:14:16.738] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:14:16.750] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2022-02-11 15:15:17.226] [exthost] [info] Eager extensions activated
[2022-02-11 15:15:22.689] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:java'
[2022-02-11 15:15:22.793] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-debug, startup: false, activationEvent: 'onLanguage:java'
[2022-02-11 15:16:48.687] [exthost] [warning] TextEditor is closed/disposed
[2022-02-11 15:16:50.139] [exthost] [error] Error: The request (id: 13, method: 'workspace/executeCommand') has been cancelled
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109208
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109502
	at Immediate.<anonymous> (c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109867)
	at processImmediate (internal/timers.js:461:21) java.execute.workspaceCommand {"value":"redhat.java","_lower":"redhat.java"}
[2022-02-11 15:16:50.424] [exthost] [info] ExtensionService#_doActivateExtension redhat.vscode-xml, startup: false, activationEvent: 'onLanguage:xml'
[2022-02-11 15:16:53.063] [exthost] [warning] [redhat.vscode-xml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[xml]', provide the URI of a resource or 'null' for any resource.
[2022-02-11 15:16:59.334] [exthost] [error] [redhat.java] provider FAILED
[2022-02-11 15:16:59.334] [exthost] [error] Error: The request (id: 4, method: 'textDocument/hover') has been cancelled
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109208
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109502
	at Immediate.<anonymous> (c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109867)
	at processImmediate (internal/timers.js:461:21)
[2022-02-11 15:16:59.383] [exthost] [error] [redhat.java] provider FAILED
[2022-02-11 15:16:59.383] [exthost] [error] Error: The request (id: 5, method: 'textDocument/hover') has been cancelled
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109208
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109502
	at Immediate.<anonymous> (c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109867)
	at processImmediate (internal/timers.js:461:21)
[2022-02-11 15:16:59.385] [exthost] [error] [redhat.java] provider FAILED
[2022-02-11 15:16:59.385] [exthost] [error] Error: The request (id: 6, method: 'textDocument/hover') has been cancelled
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109208
	at c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109502
	at Immediate.<anonymous> (c:\Users\Admin\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:1109867)
	at processImmediate (internal/timers.js:461:21)
[2022-02-11 15:18:03.810] [exthost] [warning] TextEditor is closed/disposed
[2022-02-11 15:18:27.703] [exthost] [warning] TextEditor is closed/disposed
[2022-02-11 15:18:45.416] [exthost] [warning] TextEditor is closed/disposed
[2022-02-11 15:18:49.215] [exthost] [warning] TextEditor is closed/disposed
```

**Comment by rgrunber** [comment]
Do you have the sample project that was causing these errors ?

The redhat.java errors I've seen before and shouldn't cause the extension host to crash, though maybe we can catch the cancellation nicely. See https://github.com/redhat-developer/vscode-java/issues/1976 for more on that.
