### ISSUE TITLE
Runtime Status: Connection got disposed. (Uncaught Error)

### ISSUE THREAD

**Issue by mvrahden** [redhat-developer/vscode-java#2345]
The `redhat.java` extension fails to start adequately (I believe since VSCode was updated last week).

Sidenotes:
- This behavior was observed in the previous update cycle as well.
- As can be seen from the logs, the `redhat.yaml` extension seems to have a similar problem.

##### VSCode Logs (Remote Extension Host)

```log
[2022-03-07 09:10:25.657] [exthost] [info] Extension host with pid 16045 started
[2022-03-07 09:10:25.691] [exthost] [info] Lock '/home/mvrahden/.vscode-server/data/User/workspaceStorage/854578f51996e7edadbf7399f974a9e8/vscode.lock': Lock acquired.
[2022-03-07 09:10:26.649] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
[2022-03-07 09:10:26.698] [exthost] [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
[2022-03-07 09:10:26.833] [exthost] [info] ExtensionService#_doActivateExtension DavidAnson.vscode-markdownlint, startup: false, activationEvent: 'onLanguage:markdown'
[2022-03-07 09:10:26.914] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-03-07 09:10:26.927] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.github
[2022-03-07 09:10:26.938] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-03-07 09:10:26.992] [exthost] [info] ExtensionService#_doActivateExtension cssho.vscode-svgviewer, startup: true, activationEvent: '*'
[2022-03-07 09:10:27.044] [exthost] [info] ExtensionService#_doActivateExtension EditorConfig.EditorConfig, startup: true, activationEvent: '*'
[2022-03-07 09:10:27.083] [exthost] [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
[2022-03-07 09:10:27.135] [exthost] [info] ExtensionService#_doActivateExtension mtxr.sqltools, startup: true, activationEvent: '*', root cause: mtxr.sqltools-driver-pg
[2022-03-07 09:10:27.265] [exthost] [info] ExtensionService#_doActivateExtension ryanluker.vscode-coverage-gutters, startup: true, activationEvent: '*'
[2022-03-07 09:10:27.787] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-03-07 09:10:27.973] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-03-07 09:10:27.998] [exthost] [info] ExtensionService#_doActivateExtension mtxr.sqltools-driver-pg, startup: true, activationEvent: '*'
[2022-03-07 09:10:29.029] [exthost] [info] ExtensionService#_doActivateExtension redhat.fabric8-analytics, startup: true, activationEvent: 'workspaceContains:**/package.json,**/pom.xml,**/requirements.txt,**/go.mod'
[2022-03-07 09:10:29.338] [exthost] [info] ExtensionService#_doActivateExtension golang.go, startup: true, activationEvent: 'workspaceContains:*.go,*/*.go,*/*/*.go'
[2022-03-07 09:10:29.815] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-03-07 09:10:29.860] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-03-07 09:10:29.871] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
[2022-03-07 09:10:29.918] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2022-03-07 09:10:30.213] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
[2022-03-07 09:10:30.933] [exthost] [info] ExtensionService#_doActivateExtension jinliming2.vscode-go-template, startup: false, activationEvent: 'onStartupFinished'
[2022-03-07 09:10:30.939] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onStartupFinished', root cause: SonarSource.sonarlint-vscode
[2022-03-07 09:10:31.015] [exthost] [info] Eager extensions activated
[2022-03-07 09:10:31.590] [exthost] [info] ExtensionService#_doActivateExtension SonarSource.sonarlint-vscode, startup: false, activationEvent: 'onStartupFinished'
[2022-03-07 09:15:16.131] [exthost] [warning] TextEditor is closed/disposed
[2022-03-07 09:15:24.553] [exthost] [info] ExtensionService#_doActivateExtension vscode.markdown-math, startup: false, activationEvent: 'api', root cause: vscode.markdown-language-features
[2022-03-07 09:15:24.571] [exthost] [info] ExtensionService#_doActivateExtension jebbs.plantuml, startup: false, activationEvent: 'api', root cause: vscode.markdown-language-features
[2022-03-07 09:15:24.718] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-dependency, startup: false, activationEvent: 'onLanguage:java'
[2022-03-07 09:15:24.808] [exthost] [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:java'
[2022-03-07 09:15:24.914] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-debug, startup: false, activationEvent: 'onLanguage:java'
[2022-03-07 09:15:24.987] [exthost] [info] ExtensionService#_doActivateExtension redhat.java, startup: false, activationEvent: 'onLanguage:java'
[2022-03-07 09:15:25.112] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-pack, startup: false, activationEvent: 'onLanguage:java'
[2022-03-07 09:15:25.505] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-maven, startup: false, activationEvent: 'workspaceContains:**/pom.xml'
[2022-03-07 09:15:25.946] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:15:26.111] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:15:30.917] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-java-test, startup: false, activationEvent: 'onLanguage:java'
[2022-03-07 09:16:25.668] [exthost] [error] [redhat.java] provider FAILED
[2022-03-07 09:16:25.669] [exthost] [error] TypeError: s.logFailedRequest is not a function
	at /home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:671013
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at async O.provideCodeActions (/home/mvrahden/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/out/vs/workbench/api/node/extensionHostProcess.js:85:96518)
[2022-03-07 09:32:30.295] [exthost] [error] [redhat.java] provider FAILED
[2022-03-07 09:32:30.296] [exthost] [error] Error: The request (id: 31, method: 'textDocument/hover') has been cancelled
	at /home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983104
	at /home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983398
	at Immediate.<anonymous> (/home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983763)
	at processImmediate (internal/timers.js:461:21)
[2022-03-07 09:32:54.344] [exthost] [error] [redhat.java] provider FAILED
[2022-03-07 09:32:54.344] [exthost] [error] Error: The request (id: 36, method: 'textDocument/hover') has been cancelled
	at /home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983104
	at /home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983398
	at Immediate.<anonymous> (/home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983763)
	at processImmediate (internal/timers.js:461:21)
[2022-03-07 09:32:59.925] [exthost] [warning] TextEditor is closed/disposed
[2022-03-07 09:33:00.000] [exthost] [info] ExtensionService#_doActivateExtension redhat.vscode-yaml, startup: false, activationEvent: 'onLanguage:yaml'
[2022-03-07 09:33:00.555] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:34:08.096] [exthost] [warning] TextEditor is closed/disposed
[2022-03-07 09:38:07.507] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-03-07 09:38:07.517] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
[2022-03-07 09:38:07.978] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:38:10.389] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:38:28.402] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:38:58.455] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:39:01.128] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:39:30.157] [exthost] [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
[2022-03-07 09:51:59.597] [exthost] [error] [redhat.java] provider FAILED
[2022-03-07 09:51:59.597] [exthost] [error] Error: The request (id: 41, method: 'textDocument/hover') has been cancelled
	at /home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983104
	at /home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983398
	at Immediate.<anonymous> (/home/mvrahden/.vscode-server/extensions/redhat.java-1.4.0/dist/extension.js:2:983763)
	at processImmediate (internal/timers.js:461:21)
[2022-03-07 09:52:07.122] [exthost] [warning] TextEditor is closed/disposed
[2022-03-07 09:52:26.309] [exthost] [warning] TextEditor is closed/disposed
[2022-03-07 09:52:36.654] [exthost] [warning] TextEditor is closed/disposed
[2022-03-07 09:52:39.168] [exthost] [warning] TextEditor is closed/disposed
```

##### Environment
- Operating System: `Windows 10 + WSL2`
- JDK version:
```xml
<?xml version="1.0" encoding="UTF8"?>
<toolchains>
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>11</version>
      <vendor>adoptopenjdk</vendor>
    </provides>
    <configuration>
      <jdkHome>/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64</jdkHome>
    </configuration>
  </toolchain>
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>16</version>
      <vendor>adoptopenjdk</vendor>
    </provides>
    <configuration>
      <jdkHome>/usr/lib/jvm/adoptopenjdk-16-hotspot-amd64</jdkHome>
    </configuration>
  </toolchain>
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>17</version>
      <vendor>adoptium</vendor>
    </provides>
    <configuration>
      <jdkHome>/usr/lib/jvm/temurin-17-jdk-amd64</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
```
- Visual Studio Code version:
```txt
Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```
- Java extension version: `1.4.0 (March 3rd, 2022)`

**Comment by testforstephen** [comment]
The issue I saw on #2268 is just some logging issue, the whole Java language features work well. Your issue seems related with WSL.

**Comment by mvrahden** [comment]
@testforstephen thanks for your answer. Yes, in this case the language features do not work as expected. No class path can be resolved and many other issues are appearing.
But I would argue that this is not necessarily related to WSL. All other extensions work very well after updates, only `redhat.***` extensions break. So these extensions must be doing something different from others.
Do you have an idea on where to look at? I'm not familiar with the project and wouldn't know where to start digging.
The issue is still ongoing and forces me to use another IDE for Java projects.
Thanks

**Comment by testforstephen** [comment]
Could you share the logs at "**F1 -> Java: Open All Log Files**"?

**Comment by mvrahden** [comment]
These are excerpts from the most recent restart of VSCode.
If you need a wider timespan of logs, just let me know.

**Comment by mvrahden** [comment]
So, it seems that the issue resolved itself. Thank you for your help!
