### ISSUE TITLE
Cannot refactor in static init

### ISSUE THREAD

**Issue by Nightenom** [redhat-developer/vscode-java#2370]
As shown in the picture below, refactor actions are not available in static init.

##### Environment
- Operating System: Windows_NT x64 10.0.19043
- JDK version: OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
- Visual Studio Code version: 1.65.2
- Java extension version: v1.4.0

##### Steps To Reproduce
1. Create a class with static method and static init and fill them with longer expressions.
2. Try to refactor in static method - see it works
3. Try to refactor in static init - see it doesn't work

Hopefully, no logs are needed, reproducible in many environments.

##### Current Result
Refactor actions are **not** available in static init.

##### Expected Result
Refactor actions are available in static init.

##### Additional Informations
Compiled pictures of using refactor action on both places.
![image](https://user-images.githubusercontent.com/17338378/159332964-fd089125-fc6d-4206-a232-b24760caff98.png)

**Comment by rgrunber** [comment]
This should be a simple change. @snjeza's change is simply catching an error that failed the entire code action collection in the static initializer case.

```
[Trace - 2:41:03 PM] Received response 'textDocument/codeAction - (444)' in 69ms. Request failed: Internal error. (-32603).
Error data: "java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke \"org.eclipse.jdt.core.dom.MethodDeclaration.getParent()\" because the return value of \"org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractFieldRefactoring.getMethodDeclaration()\" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke \"org.eclipse.jdt.core.dom.MethodDeclaration.getParent()\" because the return value of \"org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractFieldRefactoring.getMethodDeclaration()\" is null
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractFieldRefactoring.getEnclosingTypeDeclaration(ExtractFieldRefactoring.java:888)
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractFieldRefactoring.checkInitialConditions(ExtractFieldRefactoring.java:315)
	at org.eclipse.jdt.ls.core.internal.text.correction.RefactorProposalUtility.getExtractFieldProposal(RefactorProposalUtility.java:556)
	at org.eclipse.jdt.ls.core.internal.text.correction.RefactorProposalUtility.getGenericExtractFieldProposal(RefactorProposalUtility.java:527)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getExtractFieldProposal(RefactorProcessor.java:295)
	at org.eclipse.jdt.ls.core.internal.corrections.RefactorProcessor.getProposals(RefactorProcessor.java:140)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:177)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda5(JDTLanguageServer.java:666)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambdabash(BaseJDTLanguageServer.java:75)
	... 7 more
```
