### ISSUE TITLE
Extension stop to work after 1.5.0 update

### ISSUE THREAD

**Issue by massimeddu-sonic** [redhat-developer/vscode-java#2423]
[server.log](https://github.com/redhat-developer/vscode-java/files/8519853/server.log)

After the upgrade to java extension version 1.5.0 (on Code insider running with Remote container setup), the extension stops to work
[client.log](https://github.com/redhat-developer/vscode-java/files/8519854/client.log)
 (see attached log). I have multiple java projects in my root directory.

##### Environment
- Operating System: Linux x64 5.13.0-40-generic
- JDK version: OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
- Visual Studio Code version: Version: 1.67.0-insider
- Java extension version: 1.5.0

##### Steps To Reproduce
1. Update to extension version 1.5.0

**Comment by fbricon** [comment]
can you try to execute the "Java: Clean Java Language server workspace" command?

**Comment by massimeddu-sonic** [comment]
Hi @fbricon thanks for the quick reply. Unfortunately it didn't solve my issue. If it could help to identify the issue, this is the Output I can see under the VsCode "Output" tab for:

Language Support for Java:
```
[Error - 1:26:37 PM] Apr 20, 2022, 1:26:37 PM An internal error occurred during: "Initialize workspace".
Path must include project and resource name: /etl
java.lang.IllegalArgumentException: Path must include project and resource name: /hunter
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2139)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:414)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:276)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Language Support for Java (Syntax Server):
```
[Error - 2:06:37 PM] Apr 20, 2022, 2:06:37 PM Error computing hover
_/services/etl/src/main/java/com/batch/service/impl [in src_171b55] is not on its project's build path
Java Model Exception: Error in Java Model (code 1006): _/services/etl/src/main/java/com/batch/service/impl [in src_171b55] is not on its project's build path
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:584)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:254)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:528)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:248)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:528)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1240)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:248)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:597)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:328)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:314)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:296)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:972)
	at org.eclipse.jdt.ls.core.internal.HoverInfoProvider.computeHover(HoverInfoProvider.java:102)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.computeHover(HoverHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.hover(HoverHandler.java:43)
	at org.eclipse.jdt.ls.core.internal.syntaxserver.SyntaxLanguageServer.lambda$8(SyntaxLanguageServer.java:367)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

Thank you
