### ISSUE TITLE
Error during importing an Eclipse project whose sources are at root

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2436]
Prepare an Eclipse project, whose source are at project root: 
[eclipse-project.zip](https://github.com/redhat-developer/vscode-java/files/8567945/eclipse-project.zip)

Open it in VS Code, and following errors can be ovserved:

```
!MESSAGE An internal error occurred during: "Initialize workspace".
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /eclipse-project
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2139)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:414)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:276)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rgrunber** [comment]
Reproduced as well.
