### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'sendRequest')

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#2481]
Below error randomly occurs:

```
[2022-05-30 10:00:24.949] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'sendRequest')
	at c:\Users\admin\.vscode\extensions\redhat.java-1.6.6\dist\extension.js:2:698983
	at o._executeContributedCommand (c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:31333)
	at o._doExecuteCommand (c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:30153)
	at o._doExecuteCommand (c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:30868)
	at processTicksAndRejections (node:internal/process/task_queues:96:5) java.execute.workspaceCommand {"value":"redhat.java","_lower":"redhat.java"}
```

There are lots of places that `client.sendRequest` is called. NPE somewhere I guess.

**Comment by tristan957** [comment]
I am seeing the same issue. Pulled these logs:

```
[2022-06-09 15:31:58.554] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
[2022-06-09 15:31:58.713] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'sendRequest')
	at /home/tpartin/.vscode-server/extensions/redhat.java-1.7.0/dist/extension.js:2:698984
	at o._executeContributedCommand (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:83:62521)
	at o.$executeContributedCommand (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:83:63225)
	at s._doInvokeHandler (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:86:13828)
	at s._invokeHandler (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:86:13512)
	at s._receiveRequest (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:86:12173)
	at s._receiveOneMessage (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:86:10843)
	at /home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:86:8949
	at g.invoke (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at a.fire (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
	at /home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:102:34863
	at g.invoke (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at a.fire (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
	at r._receiveMessage (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:66:23606)
	at /home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:66:21140
	at g.invoke (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at v.acceptChunk (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:66:15856)
	at /home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:66:14986
	at g.invoke (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at f._processReadQueue (/home/tpartin/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/workbench/api/node/extensionHostProcess.js:102:21280) java.execute.workspaceCommand {"value":"redhat.java","_lower":"redhat.java"}
```

**Comment by mmcintyre123** [comment]
Any updates on this?

**Comment by m0t1x** [comment]
Any update?
I still have issue in VS Code: v1.86.0, RedHat Java Language Support: v1.27.0

**Comment by sergeysavchuk** [comment]
This issue still appears to be relevant in VS Code Version: **1.92.2.**
Could you please take a look or let us know if there are any updates or workarounds?
Thanks.
