### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'stop')

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#2501]
version: v1.8.2022060904-win32-x64

```
TypeError: Cannot read properties of undefined (reading 'stop')
	at c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:702887
	at invoke (c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:1030744)
	at s.fire (c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:1031505)
	at Object.fireDidServerModeChange (c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:675417)
	at c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:790922
	at c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:1021843
	at c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:1022061
	at Immediate._onImmediate (c:\Users\yanzh\.vscode-insiders\extensions\redhat.java-1.8.2022060904-win32-x64\dist\extension.js:2:1023609)
	at processImmediate (C:\Users\yanzh\Work\vscode-java-pack\lib\internal\timers.js:464:21)
	at process.callbackTrampoline (node:internal/async_hooks:130:17) {stack: 'TypeError: Cannot read properties of undefine…Trampoline (node:internal/async_hooks:130:17)', message: 'Cannot read properties of undefined (reading 'stop')'}

```

content of the corresponding location:
```
E.apiManager.getApiInstance().onDidServerModeChange((t=>{t===g.ServerMode.STANDARD&&(R.getClient().stop().then((e=>{R.stop()})),M.setServerStatus
```

it's webpack-ed, probably somewhere related to `onDidServerModeChange`, client is undefined.

**Comment by Eskibear** [comment]
Looks like it's below line. Not sure if it's because I'm in Extension Development Host mode. Shall we add null check here for the client?

https://github.com/redhat-developer/vscode-java/blob/4d954f70dd46aafd219245bf8e38c361492dfbfc/src/extension.ts#L430

**Comment by jdneo** [comment]
dup with https://github.com/redhat-developer/vscode-java/issues/2503. It should be fixed in https://github.com/redhat-developer/vscode-java/pull/2506

**Comment by Eskibear** [comment]
That makes sense. I'm closing it.
