### ISSUE TITLE
couldn't start client language support for java(syntax server)

### ISSUE THREAD

**Issue by IsabelNotHere** [redhat-developer/vscode-java#2561]
[provide a description of the issue]

##### Environment
- Operating System: macOS  monterey 12.4
- JDK version: openjdk 17.0.2
- Visual Studio Code version: 1.69.1
- Java extension version: 1.8.0

##### Steps To Reproduce
1. [step 1] open a springboot gradle project 
2. [step 2] the problem appears 

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

toggle developer log:
workbench.desktop.main.js:2272 [[object Object]]Cannot read properties of null (reading 'sendNotification')
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199

workbench.desktop.main.js:2272 TypeError: Cannot read properties of null (reading 'sendNotification')
	at didChangeConfiguration (vscode-file://vscode-app/Users/aubryisabel/.vscode/extensions/redhat.java-1.8.0-darwin-arm64/dist/extension.js:2:901545)
	at K.onDidChangeConfiguration (vscode-file://vscode-app/Users/aubryisabel/.vscode/extensions/redhat.java-1.8.0-darwin-arm64/dist/extension.js:2:954816)
	at K.register (vscode-file://vscode-app/Users/aubryisabel/.vscode/extensions/redhat.java-1.8.0-darwin-arm64/dist/extension.js:2:954202)
	at K.initialize (vscode-file://vscode-app/Users/aubryisabel/.vscode/extensions/redhat.java-1.8.0-darwin-arm64/dist/extension.js:2:953951)
	at w.initializeFeatures (vscode-file://vscode-app/Users/aubryisabel/.vscode/extensions/redhat.java-1.8.0-darwin-arm64/dist/extension.js:2:977259)
	at vscode-file://vscode-app/Users/aubryisabel/.vscode/extensions/redhat.java-1.8.0-darwin-arm64/dist/extension.js:2:968586
$onExtensionRuntimeError @ workbench.desktop.main.js:2272
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:544
_receiveMessage @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
invoke @ workbench.desktop.main.js:82
deliver @ workbench.desktop.main.js:82
fire @ workbench.desktop.main.js:82
acceptChunk @ workbench.desktop.main.js:544
(anonymous) @ workbench.desktop.main.js:544
O @ workbench.desktop.main.js:3173
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199

client.log
{
  message: "Failed to initialize Language Support for Java (Syntax Server) due to TypeError: Cannot read properties of null (reading 'sendNotification')",
  level: 'error',
  timestamp: '2022-07-13 20:10:08.924'
}
{
  message: "Failed to initialize Language Support for Java (Syntax Server) due to TypeError: Cannot read properties of null (reading 'sendNotification')",
  level: 'error',
  timestamp: '2022-07-13 20:10:08.925'
}
{
  message: "Failed to initialize Language Support for Java (Syntax Server) due to TypeError: Cannot read properties of null (reading 'sendNotification')",
  level: 'error',
  timestamp: '2022-07-13 20:10:08.925'
}

##### Additional Informations
my MacBook Pro will be so hot and slow when open language support for java extention runtime status

**Comment by zjx20** [comment]
Same issue in v1.10.0 extension.

```plain
[Error - 3:20:51 PM] Starting client failed
TypeError: Cannot read properties of null (reading 'sendNotification')
	at didChangeConfiguration (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:815699)
	at V.onDidChangeConfiguration (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:869625)
	at V.register (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:869011)
	at V.initialize (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:868760)
	at b.initializeFeatures (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:891979)
	at /Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:883306
[Error - 3:20:51 PM] Connection to server is erroring. Shutting down server.
[Error - 3:20:51 PM] Connection to server got closed. Server will not be restarted.
[Error - 3:20:51 PM] Stopping server failed
Error: Connection got disposed.
	at Object.dispose (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1040826)
	at Object.dispose (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:887823)
	at b.handleConnectionClosed (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:888011)
	at b.handleConnectionClosed (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:961642)
	at t (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:886125)
	at i.invoke (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1042452)
	at s.fire (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1043213)
	at Q (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1029965)
	at i.invoke (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1042452)
	at s.fire (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1043213)
	at _.fireClose (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1054658)
	at Socket.<anonymous> (/Users/x/.vscode/extensions/redhat.java-1.10.0-darwin-arm64/dist/extension.js:2:1055443)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)

```

**Comment by 3ter** [comment]
I'm getting the following after running `Java: Clean Java Language Server Workspace` as @DotIN13 proposed:
`[Error - 11:07:30 PM] Connection to server got closed. Server will not be restarted.`

For me the code decorations (probably those https://github.com/microsoft/vscode-java-test/issues/470) for running tests vanish. I'm not sure if this is related.

**Comment by zs19940317** [comment]
the same error as above, is there a solution?
