### ISSUE TITLE
java.lang.IllegalArgumentException: URI has an authority component

### ISSUE THREAD

**Issue by Labouh** [redhat-developer/vscode-java#259]
When using the extension on any simple maven java project I got exception on exception in output console and a "Classpath is incomplete. Only syntax errors will be reported" in code UI
So it seems to be an issue on the settings on PC (I try to set proxy but without success)
Any idea how to solve this issue!,
Thanks by advance for any help
Regards
##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_131
- Visual Studio Code version: 1.12.2
- Java extension version: 0.7.0

##### Steps To Reproduce
Open any project under a corporate PC (that I am not fully administrator)

##### Current Result
[Error - 09:30:14] 17 juil. 2017 09:29:58 Failed to read package name from file://s90104/Users/U805679/userdata/screenplay-pattern-todomvc/src/main/java/net/serenitybdd/ChromeDriverNoExt.java
URI has an authority component
java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(File.java:423)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.getPackageName(JDTUtils.java:185)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.getFakeCompilationUnit(JDTUtils.java:151)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:129)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.resolveCompilationUnit(JDTUtils.java:102)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.handleOpen(DocumentLifeCycleHandler.java:121)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler$2.run(DocumentLifeCycleHandler.java:78)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.didOpen(DocumentLifeCycleHandler.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didOpen(JDTLanguageServer.java:349)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Labouh** [comment]
It seems that it does not like UNC names (miss a /?)
I copy my project on the C: drive it the error disappear 

So sound like an issue when using network drive and UNC names (?)

Regards
