### ISSUE TITLE
When opening Java Project, the Java Build Status is spinning forever.

### ISSUE THREAD

**Issue by tarekahf** [redhat-developer/vscode-java#2623]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version:  JavaSE-1.8 (for the project) and JavaSE-11 for vs code
- Visual Studio Code version: 1.70.0
- Java extension version: Extension Pack for Java v0.25.0

##### Steps To Reproduce
1. Open Java Project
2. The Java Build Status indicator on the status bar is spinning forever.
3. The status bar Java Build status shows an 
info popup as "Building - Lightweight mode".
![vscode java build status spinning](https://user-images.githubusercontent.com/20842027/184017103-b4a7f81e-7420-4121-b01d-4e091d02984c.png)

[Please attach a sample project reproducing the error]
I don't have a sample project now. Will try to make a simple one to verify.

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
[vscode-app-1660164678368.log](https://github.com/redhat-developer/vscode-java/files/9303962/vscode-app-1660164678368.log)
[.log](https://github.com/redhat-developer/vscode-java/files/9303975/default.log)

##### Current Result
Java build status is spinning and the project is not loaded

##### Expected Result
The project was opening and compiling correctly just last week. I think the recent update broke something.

##### Additional Informations
The project was opening and compiling correctly just last week. I think the recent update broke something.

**Comment by testforstephen** [comment]
> workbench.desktop.main.js:2279 Error: Header must provide a Content-Length property.

@tarekahf Your issue is duplicated with https://github.com/redhat-developer/vscode-java/issues/2577#issuecomment-1208922149, pls take a look at the workaround there.

**Comment by jundiaufa11** [comment]
@tarekahf i have a problem like you, try this https://github.com/redhat-developer/vscode-java/issues/2577#issuecomment-1208922149 working on me

**Comment by tarekahf** [comment]
Thanks all for the reply... Was that magic or what? It worked. I'll wait for tomorrow to confirm. Then you can close. I'll check it using another WiFi connection...

**Comment by tarekahf** [comment]
Just a quick question about the message I saw about lightweight mode for Java projects. Is there a heavyweight mode and what's the difference? Can you please share a link for details?

**Comment by tarekahf** [comment]
> I'm having the same issue, but the workaround mentioned doesn't fix my problem. I have no code even in my project yet. just a basic pom importing two aws dependencies. This just started sometime in the last week. I'm on version 1.70.1.
> 
> ![vscode](https://user-images.githubusercontent.com/33233012/184736285-fd2336c3-5815-4a08-8b71-0c866cb07c5b.jpg) ![image](https://user-images.githubusercontent.com/33233012/184736515-8f1d97d4-0619-4c95-aab9-aef31d60c73c.png)

For me the problem was resolved but I will wait until this one is also solved. I have another project that uses maven so I'm going to test it out.

**Comment by shivamfet** [comment]
I am also facing the same issue. Mine is maven project.

**Comment by snjeza** [comment]
@shivamfet could you provide a project example?

**Comment by shivamfet** [comment]
Hi @snjeza 

Following is the snapshot of project outline, it is a maven project. Hope it helps

![image](https://user-images.githubusercontent.com/37039508/186242942-9a5e9a88-ce31-4f37-ba05-383702bc36a6.png)

This is the remote-settings.json file

`{  
        "java.jdt.ls.java.home": "/usr/java/jdk-17.0.2",
        "java.jdt.ls.vmargs": "-Xlog:jni+resolve=off",
        "java.dependency.syncWithFolderExplorer": true,
        "http.proxy": "...",       
        "http.proxyStrictSSL": false,
        "maven.executable.path": "...",
        "maven.settingsFile": "...",
        "maven.executable.options" : ".....",
        "files.exclude": {
     
        }
}`

**Comment by shivamfet** [comment]
Hi @snjeza 

Developer Tools log says:

`mainThreadExtensionService.ts:79 [[object Object]]Header must provide a Content-Length property.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 Error: Header must provide a Content-Length property.
	at p.onData (/home/skakkar/.vscode-server/extensions/redhat.java-1.9.0/dist/extension.js:2:1052283)
	at Socket.<anonymous> (/home/skakkar/.vscode-server/extensions/redhat.java-1.9.0/dist/extension.js:2:1052004)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:79 [[object Object]]Header must provide a Content-Length property.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 Error: Header must provide a Content-Length property.
	at p.onData (/home/skakkar/.vscode-server/extensions/redhat.java-1.9.0/dist/extension.js:2:1052283)
	at Socket.<anonymous> (/home/skakkar/.vscode-server/extensions/redhat.java-1.9.0/dist/extension.js:2:1052004)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)`

**Comment by snjeza** [comment]
@shivamfet What OS are you using?

**Comment by shivamfet** [comment]
Hi @snjeza 

It is MAC OS Monterey version 12.1

**Comment by shivamfet** [comment]
Hi @snjeza 
Sorry to bug you again. Any pointers or workaround if you can suggest it will be really helpful.

Regards
Shivam

**Comment by snjeza** [comment]
@shivamfet I'm working on it.

**Comment by snjeza** [comment]
A related issue - https://github.com/redhat-developer/vscode-java/pull/2646

**Comment by snjeza** [comment]
@shivamfet Could you check https://github.com/snjeza/vscode-test/raw/master/java-1.10.0.vsix ? It includes https://github.com/redhat-developer/vscode-java/pull/2646/

**Comment by tarekahf** [comment]
> @shivamfet Could you check https://github.com/snjeza/vscode-test/raw/master/java-1.10.0.vsix ? It includes #2646
> 
> You should remove
> 
> ```
> "java.jdt.ls.vmargs": "-Xlog:jni+resolve=off",
> ```
> 
> It will be added automatically

I have opened an old project which is maven-based using vscode. I am 100% sure it was working fine several months ago. No, it is not working. I see the build status indicator spinning forever on the status bar. I didn't find any reference to `java.jdt.ls.vmargs` in vscode settings.

See attached the required debug files:
[.log](https://github.com/redhat-developer/vscode-java/files/9446917/default.log)
[vscode-app-1661795875882.log](https://github.com/redhat-developer/vscode-java/files/9446918/vscode-app-1661795875882.log)

**Comment by snjeza** [comment]
@tarekahf What version of VS Code are you using?

**Comment by tarekahf** [comment]
> @tarekahf What version of VS Code are you using?

I got the following from vs code help/about:

> Version: 1.70.2 (user setup)
> Commit: e4503b30fc78200f846c62cf8091b76ff5547662
> Date: 2022-08-16T05:35:13.448Z
> Electron: 18.3.5
> Chromium: 100.0.4896.160
> Node.js: 16.13.2
> V8: 10.0.139.17-electron.0
> OS: Windows_NT x64 10.0.19042

**Comment by snjeza** [comment]
@tarekahf Could you try to install https://github.com/snjeza/vscode-test/raw/master/java-1.10.0.vsix

**Comment by tarekahf** [comment]
> @tarekahf Could you try to install https://github.com/snjeza/vscode-test/raw/master/java-1.10.0.vsix

But why? it's working for me now.

**Comment by snjeza** [comment]
> But why? it's working for me now.

 "-Xlog:jni+resolve=off" will be added automatically. See https://github.com/redhat-developer/vscode-java/pull/2646

**Comment by tarekahf** [comment]
You mean if I download this

https://github.com/snjeza/vscode-test/raw/master/java-1.10.0.vsix

Then the settings

"-Xlog:jni+resolve=off" 

will be added automatically?

Will this happen for existing project, new project, or both? Will it apply For maven based project, no-build tool project, or both?

**Comment by snjeza** [comment]
> will be added automatically?

Right!

> Will this happen for existing project, new project, or both? Will it apply For maven based project, no-build tool project, or both?

It should be added always.

**Comment by tarekahf** [comment]
> > will be added automatically?
> 
> Right!
> 
> > Will this happen for existing project, new project, or both? Will it apply For maven based project, no-build tool project, or both?
> 
> It should be added always.

Please bear with me as I cannot afford to mess up with my vs code setup.

So, you are saying that this download:

https://github.com/snjeza/vscode-test/raw/master/java-1.10.0.vsix

Is an updated version for vscode and will fix the problem of Java Build Status spinning forever.

But what will happen to my current stable vs code setup? will it override my current vs code installation?

**Comment by snjeza** [comment]
> But what will happen to my current stable vs code setup? will it override my current vs code installation?

@tarekahf you can wait for the stable VS Code 1.10.0 release - https://github.com/redhat-developer/vscode-java/pull/2648
