### ISSUE TITLE
Space in path of java.settings.url causes URISyntaxException

### ISSUE THREAD

**Issue by matter-it-does** [redhat-developer/vscode-java#2637]
```
Illegal character in path at index xx: /Users/t/OneDrive - company/code/java_global.prefs
java.net.URISyntaxException: Illegal character in path at index xx: /Users/t/OneDrive - company/code/java_global.prefs
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.getURIs(StandardProjectsManager.java:533)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.fileChanged(StandardProjectsManager.java:201)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceEventsHandler.didChangeWatchedFiles(WorkspaceEventsHandler.java:115)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didChangeWatchedFiles(JDTLanguageServer.java:518)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:130)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

##### Environment
- Operating System: macOS
- JDK version: 
- Visual Studio Code version:  Version: 1.70.2
- Java extension version: v1.9.0

##### Steps To Reproduce

In settings, set java.settings.url to a path with space in it.

##### Current Result

The exception above

##### Expected Result
no exception

**Comment by jdneo** [comment]
It not a space problem, the root cause is that we do not deal with the url string properly, when the path is windows fs format.

`c:/` is an invalid protocol format as a URL.

**Comment by jdneo** [comment]
@matter-it-does 

The error is thrown from [here](https://github.com/eclipse/eclipse.jdt.ls/blob/7195e7cccebc7f993c890728ca39d4c43ca14aa4/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java#L543) due to `/Users/t/OneDrive - company/code/java_global.prefs` cannot be parsed to a URI.

Then it will be dealt as a file path. In your case, are the settings in the `java_global.prefs` file take effect?

**Comment by matter-it-does** [comment]
> @matter-it-does
> Then it will be dealt as a file path. In your case, are the settings in the `java_global.prefs` file take effect?

@jdneo 

Oh I just noticed, they take effect, but the exception is a bit confusing and cluttering

**Comment by rgrunber** [comment]
Would @snjeza 's PR from https://github.com/redhat-developer/vscode-java/pull/2451 help with this ?

**Comment by jdneo** [comment]
Seems not. https://github.com/redhat-developer/vscode-java/pull/2451 is to check invalid url value. While in this case, user's url is a valid value.

The exception is thrown because the server will first try to parse a windows file path string to a URL. After failure, the server fallbacks to treat it as a file path. So it's still working finally.

**Comment by oliviercailloux** [comment]
Still occurs. Quite annoying in 2025 to not be able to use spaces in paths.

Version: 1.103.1
Commit: 360a4e4fd251bfce169a4ddf857c7d25d1ad40da
Date: 2025-08-12T16:25:40.542Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Linux x64 6.1.0-38-amd64
