### ISSUE TITLE
Java projects aren't imported to IDE after update

### ISSUE THREAD

**Issue by olgapshen** [redhat-developer/vscode-java#2698]
### Discussed in https://github.com/redhat-developer/vscode-java/discussions/2697

<div type='discussions-op-text'>

<sup>Originally posted by **olgapshen** September 26, 2022</sup>
I try to submit follow issuem and it don't gives me "Submit new issue" button available...

##### Environment
- Operating System: openSUSE Leap 15.3
- JDK version: openjdk version "11.0.13" 2021-10-19
- Visual Studio Code version: 1.71.2
- Java extension version: v1.10.0

##### Steps To Reproduce
1. F1 -> Java: Clean Java Language ...
2. Reload and delete

[Sample project](https://github.com/olgapshen/VSCodeIssue)
[Logs](https://github.com/olgapshen/VSCodeIssue/blob/main/client.log.2022-09-26)

##### Current Result
* Java Projects tab displays no projects, just "Import Projects" button
* No server log file availabe
* Configure Java Runtime page displays nothig, except "Refresh" button

##### Expected Result
Java project is imported to IDE

##### Additional Informations
Issue started after update to recent version.
Error from "Developer Tools":

> ERR ENOENT: no such file or directory, open '/home/olga/.config/Code/User/workspaceStorage/a173b3b78960646b4119193930553375/redhat.java/jdt_ws/.metadata/.log': Error: ENOENT: no such file or directory, open '/home/olga/.config/Code/User/workspaceStorage/a173b3b78960646b4119193930553375/redhat.java/jdt_ws/.metadata/.log'
</div>

**Comment by jdneo** [comment]
![image](https://user-images.githubusercontent.com/6193897/192227776-bef7eb36-99e7-43fd-ab6a-afc5b8b1f973.png)

Could you check if there is a error message when you opened your project in VSCode? - Click the bell icon at the bottom right corner

**Comment by olgapshen** [comment]
No... No such message while oppening the IDE or during the usage.

**Comment by testforstephen** [comment]
@olgapshen I believe your issue duplicates with https://github.com/redhat-developer/vscode-java/issues/2655#issuecomment-1249983464 and https://github.com/microsoft/vscode-java-debug/issues/1212. The JDK on OpenSUSE doesn't contain the `release` file, that breaks the Java extension.

**Comment by olgapshen** [comment]
Hi! Several new things. 

First of all, I upgraded Gradle to 7.5.1 and successfully built the project with VSCode Gradle plugin.
The screenshot below.

Second I messed little button in bottom of the screen: "Lightweight mode", I pressed, and IDE tried to build the Java project, but with new errors.

I updated the logs in the repo:

* [Client log](https://github.com/olgapshen/VSCodeIssue/blob/main/client.log.2022-09-26)
* [Server log](https://github.com/olgapshen/VSCodeIssue/blob/main/.log)

![изображение](https://user-images.githubusercontent.com/13800244/192252825-be02b288-41a8-43e5-b9bf-74e1df5785ad.png)

**Comment by olgapshen** [comment]
> @olgapshen I believe your issue duplicates with [#2655 (comment)](https://github.com/redhat-developer/vscode-java/issues/2655#issuecomment-1249983464) and [microsoft/vscode-java-debug#1212](https://github.com/microsoft/vscode-java-debug/issues/1212). The JDK on OpenSUSE doesn't contain the `release` file, that breaks the Java extension.

Sorry, but no, as I see I have `release` versionm sinse it doesn't have `-devel` suffix.
And I just updated the package:

![изображение](https://user-images.githubusercontent.com/13800244/192254033-a4bd2968-f839-4d15-ab12-5fc8cb911b22.png)

**Comment by testforstephen** [comment]
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2022-09-26 13:11:44.181
!MESSAGE Initialization failed 
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(org.eclipse.jdt.internal.compiler.util.JRTUtil$JrtFileVisitor, int)" because the return value of "org.eclipse.jdt.internal.compiler.util.JRTUtil.getJrtSystem(java.io.File, String)" is null
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.walkModuleImage(JRTUtil.java:242)
	at org.eclipse.jdt.internal.core.JavaProject.loadModulesInJimage(JavaProject.java:983)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:782)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1103)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1048)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1025)
	at org.eclipse.jdt.internal.core.JavaProject.buildStructure(JavaProject.java:538)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:266)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:597)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:328)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:314)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:269)
	at org.eclipse.jdt.internal.core.JavaProject.getPackageFragmentRoots(JavaProject.java:2384)
	at org.eclipse.jdt.internal.core.JavaProject.getPackageFragments(JavaProject.java:2408)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.cleanupResources(ProjectsManager.java:278)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:107)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:244)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Looking at the logs you shared, it's exactly same as  https://github.com/redhat-developer/vscode-java/issues/2655#issuecomment-1249983464 and https://github.com/microsoft/vscode-java-debug/issues/1212. 

A quick workaround is to manually create a `release` file in your jdk home.
```shell
sudo sh -c 'echo "JAVA_VERSION=\"11.0.16.0\"" > /usr/lib64/jvm/java-11-openjdk-11/release'
```

**Comment by olgapshen** [comment]
Thank you very much!!! It really was a problem! You are the best!
