### ISSUE TITLE
Class parsing error (codeLens crash)

### ISSUE THREAD

**Issue by Nightenom** [redhat-developer/vscode-java#2710]
Following code crashes code helper functions.

##### Environment
- Operating System: win 10 21h2 19044.2006
- JDK version: `OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)`
- Visual Studio Code version: 1.71.2
- Java extension version: latest (v 1.11)

##### Steps To Reproduce
1. use code from [this gist](https://gist.github.com/Nightenom/e406e6c4816919a12dd62543dcf1951b#file-partbuilder-java)
3. [extension logs](https://gist.github.com/Nightenom/e406e6c4816919a12dd62543dcf1951b#file-client-log-from-extension)
2. you should see this: 
![image](https://user-images.githubusercontent.com/17338378/193412041-86ddb43c-70cd-4ae1-96e9-c1ed108f374a.png)

**Comment by snjeza** [comment]
@Nightenom I can't reproduce the issue when using your gist.
Could you provide a project example reproducing the error.

**Comment by Nightenom** [comment]
Sorry for not providing project info: running on latest gradle, application is using JPMS. Minimal repro case: [test.zip (can upload to repo if needed)](https://github.com/redhat-developer/vscode-java/files/9708915/test.zip) - it downloads few libraries, if I tried to strip dependencies in build.gradle the problem has gone for some reason..

Note that full stacktrace is on top of logs (in supplied gist), for some reason the stacktraces down there are cut

Also getting this error when starting vscode with java pack disabled, then enabling it locally (`Enable (workspace)`), full refresh (command Clean Java Language Server Workspace) doesn't help, although `Developer: Reload Window` does (more likely few restarts do fix it, extension never comes up if this message appear + getting crash notification pop up):
```
[Error - 18:20:31] Starting client failed
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.osgi.framework.BundleContext.getBundle()" because "context" is null
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.startBundles(BundleUtils.java:266)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:167)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:91)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:63)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:250)
	... 16 more
```

**Comment by Nightenom** [comment]
@snjeza any update?

**Comment by snjeza** [comment]
This is an upstream issue. I can reproduce it in Eclipse.

**Comment by snjeza** [comment]
A workaround: 
Replace

```
public static final PartBuilder<Integer> EMPTY = new PartBuilder<>()
```
with
```
public static final PartBuilder<Integer> EMPTY = new PartBuilder<Integer>()
```

**Comment by Nightenom** [comment]
Did not test (dont have access to repo with issue now), but fixed upstream in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/828
