### ISSUE TITLE
Error on startup: 'overlaps the location of another project'...

### ISSUE THREAD

**Issue by aeschli** [redhat-developer/vscode-java#280]
0.8.0, Linux 14.04

- Opening up VSCode on a folder containing the devoxx sample (https://github.com/fbricon/devoxx.git) gives me the following error:

> Contains: /home/aeschli/workspaces/samples/devoxx overlaps the location of another project: 'devoxx'

- the underlying problem is that the hidden Eclipe workspace can only have a single project od a given name
- looks like I already opened a devoxx project some time (that's possible, but should not be of my concern)
- it would be good if the other location would be printed so we can find out if it's a valid conflict
- a solution would be to always qualify all project names so they are unique
- or, another solution would be to always delete such duplicated projects (and rebuild them if they are used again later) 

[Error - 11:07:12 AM] Aug 21, 2017 11:07:11 AM Problem importing to workspace
Invalid project description.
org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:169)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:53)
	at org.eclipse.core.internal.resources.Project.create(Project.java:263)
	at org.eclipse.core.internal.resources.Project.create(Project.java:247)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.create(ProjectConfigurationManager.java:995)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:162)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:133)
	at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:117)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:75)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Contains: OK
Contains: /home/aeschli/workspaces/samples/devoxx overlaps the location of another project: 'devoxx'

**Comment by fbricon** [comment]
I'm not sure how you could have overlapping projects, given that we basically create a new workspace per folder opened. Unless there's a bug in the workspace creation which would generate the same workspace name/hash from different locations

**Comment by dr3s** [comment]
I also have seen this opening multiple projects with the same name.  in my case it was a fork of an original project.

**Comment by fbricon** [comment]
@dr3s were the fork and the original project living under the same directory?

**Comment by dr3s** [comment]
same parent yes but they of course had different names for the directory
with each git repo

**Comment by fbricon** [comment]
so you opened a folder containing 2 versions of the same project?

**Comment by dr3s** [comment]
no I opened two folders each containing a git repo with a different name
but a maven/eclipse project with the same name.  the two code windows were
opened at different times.  the only thing they shared is a parent
directory not in a code window and the project name.  I prob did open an
ancestor directory like my home directory at some point though.

**Comment by fbricon** [comment]
does the ancestor folder have a .vscode/ directory?

**Comment by dr3s** [comment]
yup, it's about 5 directories up.

**Comment by Perksey** [comment]
Hitting this as well. In my case:
- the entire gradle workspace contains 3 projects
- two of which are configured in a root gradle file
- one of which is configured in a separate gradle file
- project `c` depends on both projects `a` and `b`
- project `b` depends on project `a`
- project `b` is not present in "Java Projects", the others have loaded but have compile errors
