### ISSUE TITLE
No java projects found when I created it using the extension

### ISSUE THREAD

**Issue by MichaelOdumosu57** [redhat-developer/vscode-java#2964]
[provide a description of the issue]
maven could find the project when its created but java cant I am suspecting there cant be numbers in the path because the parent folder is e2e and its a testng project is it because of the numbers in the path because thats really unfortuate it should be allowed I dont have a java background so idk if a convention

##### Environment
- Operating System: Microsoft WIndows 11 Pro
- JDK version:
- java 17.0.4.1 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)

- Visual Studio Code version:
- 
1.75.1
441438abd1ac652551dbe4d408dfcec8a499b8bf
x64

- Java extension version:
Project manager for java 0.21.1

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
No projects found i nthe workspace create a workspace

##### Expected Result
I should see the maven project or better yet it should ask to import a project or tell me the error when it fails to auto load or import

**Comment by jdneo** [comment]
Could you share a sample project?

**Comment by MichaelOdumosu57** [comment]
sure watch the video from this link its unlisted lmk if access issues https://youtu.be/gjOmGMCgnWQ
[project.zip](https://github.com/redhat-developer/vscode-java/files/10840013/project.zip)

**Comment by fbricon** [comment]
You have an error message saying the Java language server failed to start. Can you attach the logs from the "Java: Open All Log Files" command?

**Comment by fbricon** [comment]
@rgrunber @jdneo @testforstephen I believe there's a button to open the logs when the server fails. This might be a different case, but It should also show up here.

**Comment by MichaelOdumosu57** [comment]
G
[log.txt](https://github.com/redhat-developer/vscode-java/files/10845145/log.txt)
reetings that is a false positive the extension then contiunes to try to open the java project regardless of whether it sees it as valid or invalid nevertheless here is the .log file and the command is "Java: Open Java Language Server Log File" (just being silly helpling out)

**Comment by jdneo** [comment]
I saw this error in the log:

```
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompletionContext.getCandidatesFromModel(PythiaCompletionContext.java:226)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompetionRanker.getScores(PythiaCompetionRanker.java:74)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompetionRanker.getRankings(PythiaCompetionRanker.java:35)
	at com.microsoft.jdtls.intellicode.core.ModelBasedRankingProvider.rank(ModelBasedRankingProvider.java:54)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getAggregatedRankingResult(CompletionProposalRequestor.java:281)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:215)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:211)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:222)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:93)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$5(JDTLanguageServer.java:579)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

@Eskibear

to reproduce, add

```
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20220924</version>
</dependency>
```

to a maven project, and then using the following snippet:

```java
public static void main(String[] args) {
	JSONObject obj = new JSONObject();
	System.out.println(obj.toString());
	for (i = 0; i < obj.; i++) {

	}
}
```

**Comment by jdneo** [comment]
I can reproduce if opening the attached workspace file. Need to take a further look what's happening.

**Comment by jdneo** [comment]
1. We do not support setting the project root as the source root directory, see: https://github.com/eclipse-m2e/m2e-core/issues/1209

2. I found that if commenting out the profile section, then the project `foo` can be imported

**Comment by MichaelOdumosu57** [comment]
But currently is the extension feels like it it will support java projects that arent the root directory of the workspace please keep this feature there is absolutely no reason to take it out, if you do I am going to tell my org to make a video about it to the thousands of followers we have. please keep this support :)

**Comment by MichaelOdumosu57** [comment]
Greetings any update
