### ISSUE TITLE
toString() affecting original object type?

### ISSUE THREAD

**Issue by xxc-zsz** [redhat-developer/vscode-java#2966]
I'm not quite sure if this is a Java question, or a VS Code question: 

I have a JSONObject using org.json, and I'm outputting it to string:
```
 JSONObject obj = new JSONObject(); 
 System.out.print(obj.toString());
```
at this point, when using the "intellisense" for VSCode, if I use obj, I get the appropriate intellisense options:
```
JSONObject obj = new JSONObject(); 
System.out.print(obj.toString());
int len  = obj.length();
```
[![enter image description here][1]][1]

However, when I attempt to iterate over it using a for loop, when I'm getting the length of the object, the intellisense never shows, and I get an error that 
"obj cannot be resolved to a type". 
```
JSONObject obj = new JSONObject(); 
System.out.print(obj.toString());
for (int i = 0; i < obj.; i++) {
```

[![enter image description here][2]][2]

Interestingly, if I do something else with the object before using it within the for loop, or comment out `System.out.print(obj.toString());` , the intellisense works as expected.

[![enter image description here][3]][3]
[![enter image description here][4]][4]

At this point, I don't know if this is something to do with the print and toString() methods somehow affecting the original `obj` object? Or if it's some bug or limitation in VSCode.

  [1]: https://i.stack.imgur.com/OxtAe.png
  [2]: https://i.stack.imgur.com/86cD8.png
  [3]: https://i.stack.imgur.com/HlfdB.png
  [4]: https://i.stack.imgur.com/QWrUu.png

**Comment by jdneo** [comment]
I saw this error in the log:

```
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompletionContext.getCandidatesFromModel(PythiaCompletionContext.java:226)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompetionRanker.getScores(PythiaCompetionRanker.java:74)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompetionRanker.getRankings(PythiaCompetionRanker.java:35)
	at com.microsoft.jdtls.intellicode.core.ModelBasedRankingProvider.rank(ModelBasedRankingProvider.java:54)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getAggregatedRankingResult(CompletionProposalRequestor.java:281)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:215)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:211)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:222)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:93)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$5(JDTLanguageServer.java:579)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

@Eskibear

to reproduce, add

```
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20220924</version>
</dependency>
```

to a maven project, and then using the following snippet:

```java
public static void main(String[] args) {
	JSONObject obj = new JSONObject();
	System.out.println(obj.toString());
	for (i = 0; i < obj.; i++) {

	}
}
```

**Comment by Eskibear** [comment]
I can reproduce it with type `JSONObject`. Strangely it works well with other types... Will investigate.

**Comment by Eskibear** [comment]
Confirmed that data model for `JSONObject` is incomplete, not as expected. When your cursor is in a conditional block, intellicode uses a different model data to predict. However, it's missing for `JSONObject`.

I will fix it in intellicode-java.

**Comment by Eskibear** [comment]
@xxc-zsz 

Steps to quickly verify the fix:
- download [com.microsoft.jdtls.intellicode.core-0.7.0-fix.zip](https://github.com/redhat-developer/vscode-java/files/10895163/com.microsoft.jdtls.intellicode.core-0.7.0-fix.zip)
- **rename** it to `com.microsoft.jdtls.intellicode.core-0.7.0-fix.jar`. (do not extract)
- copy it into folder `~/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.30/dist/`
- open file `~/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.30/package.json`, search for "core-0.7.0.jar", change it to "core-0.7.0-fix.jar" accordingly, save the file.
- reload/re-open your Java project, try the code comletion.

**Comment by Eskibear** [comment]
fixed in intellicode.. it should be in the next release of intellicode.
