### ISSUE TITLE
Itellisense it's working

### ISSUE THREAD

**Issue by Tiffany-Seymour** [redhat-developer/vscode-java#3055]
Intellisense isn't picking up anything for gradle project with proto.
The project is created, and the directories are pointed correctly in the classpath. Code compiles on gradle, but the intellisense won't boot up.

Not seeing any errors in the extension manager, but do see this:
`2023-04-10 13:13:59.192 [info] ExtensionService#_doActivateExtension VisualStudioExptTeam.vscodeintellicode, startup: false, activationEvent: 'onLanguage:java'`

Followed by:
``` 
2023-04-10 13:21:47.565 [error] TypeError: Cannot set properties of undefined (setting 'text')
	at e.update (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:725023)
	at Object.<anonymous> (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:775935)
	at Generator.next (<anonymous>)
	at s (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:771466)
2023-04-10 13:22:20.351 [error] TypeError: Cannot set properties of undefined (setting 'text')
	at e.update (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:725023)
	at Object.<anonymous> (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:775935)
	at Generator.next (<anonymous>)
	at s (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:771466)
2023-04-10 13:23:00.368 [error] TypeError: Cannot set properties of undefined (setting 'text')
	at e.update (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:725023)
	at Object.<anonymous> (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:775935)
	at Generator.next (<anonymous>)
	at s (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:771466)
2023-04-10 13:25:12.638 [error] TypeError: Cannot set properties of undefined (setting 'text')
	at e.update (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:725023)
	at Object.<anonymous> (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:775935)
	at Generator.next (<anonymous>)
	at s (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:771466)
2023-04-10 13:25:28.052 [error] TypeError: Cannot set properties of undefined (setting 'text')
	at e.update (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:725023)
	at Object.<anonymous> (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:775935)
	at Generator.next (<anonymous>)
	at s (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:771466)
2023-04-10 13:25:28.405 [error] TypeError: Cannot set properties of undefined (setting 'text')
	at e.update (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:725023)
	at Object.<anonymous> (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:775935)
	at Generator.next (<anonymous>)
	at s (/Users/ts/.vscode/extensions/redhat.java-1.16.0-darwin-arm64/dist/extension.js:2:771466) 
```
There are some other errors in that log that I am unsure are related:
<details>
  <summary>[warn] vscjava.vscode-gradle</summary>

```
2023-04-10 13:21:26.150 [warning] [vscjava.vscode-gradle] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
```
</details>

<details>
  <summary>[warn] redhat.java</summary>

```
2023-04-10 13:21:26.235 [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.
2023-04-10 13:21:26.252 [error] Error: write after end
	at new NodeError (node:internal/errors:371:5)
	at _write (node:internal/streams/writable:319:11)
	at Writable.write (node:internal/streams/writable:334:10)
	at /Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1092878
	at new Promise (<anonymous>)
	at c.write (/Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1092796)
	at m.doWrite (/Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1082403)
	at /Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1082298
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processImmediate (node:internal/timers:437:9)
```
</details>

<details>
  <summary>[error] Canceled</summary>

```
023-04-10 13:25:34.809 [error] Canceled: Canceled
	at new l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:105190)
	at c.O (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:11692)
	at G.<computed>.Q.charCodeAt.G.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:8967)
	at m.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:125211)
	at m.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124587)
	at L.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:123880)
	at m.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:125797)
	at m.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124687)
	at m.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:124587)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:23801)
	at D (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1467156)
	at E.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at h.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1481885)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1485952
	at Array.forEach (<anonymous>)
	at g.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1485938)
	at t.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:12398)
	at t.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:12533)
	at t.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1469286)
	at t.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:12533)
	at C (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:12084)
	at E.Y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:11147)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:9131
	at Array.map (<anonymous>)
	at E.R (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:9118)
	at E.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:9389)
	at d.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:1544)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:18690)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:14829)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
```
</details>

<details>
  <summary>[error] vscjava.vscode-java-pack</summary>

```
2023-04-10 13:25:55.297 [info] ExtensionService#_doActivateExtension vscjava.vscode-java-pack, startup: false, activationEvent: 'onLanguage:java'
2023-04-10 13:25:55.412 [error] Error: write after end
	at new NodeError (node:internal/errors:371:5)
	at _write (node:internal/streams/writable:319:11)
	at Writable.write (node:internal/streams/writable:334:10)
	at /Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1092878
	at new Promise (<anonymous>)
	at c.write (/Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1092796)
	at m.doWrite (/Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1082403)
	at /Users/ts/.vscode/extensions/vscjava.vscode-gradle-3.12.7/dist/index.js:2:1082298
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processImmediate (node:internal/timers:437:9)
```
</details>

The project is working with intellisense in intellij 

<details>
  <summary>settings.gradle</summary>

```
pluginManagement {
    repositories {
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
        gradlePluginPortal()
    }
}

rootProject.name = '<<REMOVED>>'
include 'src:main:proto'
findProject(':src:main:proto')?.name = 'proto'
```
</details>

<details>
  <summary>build.gradle (in root)</summary>

```
import org.gradle.plugins.ide.eclipse.model.SourceFolder

buildscript {
	ext {
		protobufVersion = '3.19.1'
		protobufPluginVersion = '0.8.18'
		grpcVersion = '1.54.0'
	}
	repositories {
		maven {
			url "https://plugins.gradle.org/m2/"
		}
	}
	dependencies {
		classpath "org.openapitools:openapi-generator-gradle-plugin:4.3.1"
		classpath("org.springframework.boot:spring-boot-gradle-plugin:3.0.5")
	}
}

plugins {
	id 'org.springframework.boot' version '3.0.5'
	id 'io.spring.dependency-management' version '1.1.0'
	id 'java'
	id 'jacoco'
	id 'com.google.protobuf' version "${protobufPluginVersion}"
	id 'eclipse'
	id 'idea'
}
apply plugin: 'io.spring.dependency-management'
apply plugin: 'idea'

// Disables building the slim jar. Without this, two jars are generated.
// One of the jars (created by Spring) is a fat jar (includes all needed
// dependencies to run the jar). The other created by the standard jar
// step builds a "thin" jar which we are not using (depends on the thin
// launcher https://github.com/dsyer/spring-boot-thin-launcher).
jar {
	enabled = false
}

group = <<REMOVED>>
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}

configurations {
	developmentOnly
	runtimeClasspath {
		extendsFrom developmentOnly
	}
}

bootJar {
	classpath configurations.developmentOnly
}

bootRun {
	systemProperties = System.properties
	jvmArgs=["-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"]
}

dependencies {
	// implementation 'org.springframework.boot:spring-boot-starter-web'
	// implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation "io.grpc:grpc-protobuf:${grpcVersion}"
	implementation "io.grpc:grpc-stub:${grpcVersion}"
	compileOnly 'org.projectlombok:lombok:1.18.26'
	annotationProcessor 'org.projectlombok:lombok:1.18.26'
	testCompileOnly 'org.projectlombok:lombok:1.18.26'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'
	implementation 'com.google.cloud:spring-cloud-gcp-dependencies:4.1.3'
	implementation 'com.vladmihalcea:hibernate-types-55:2.21.1'
	implementation 'org.springframework.data:spring-data-commons'
	implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.0'
	implementation 'org.openapitools:jackson-databind-nullable:0.2.6'
	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'io.honeycomb:honeycomb-opentelemetry-sdk:1.4.2'
	implementation 'org.apache.groovy:groovy:4.0.11'
	implementation 'net.devh:grpc-server-spring-boot-starter:2.14.0.RELEASE'

	runtimeOnly 'org.postgresql:postgresql'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	compileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.0'
	implementation 'javax.annotation:javax.annotation-api:1.3.2'

	annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                "**/generated/*",
				"**/<<REMOVED>>/*",
				"**/com/<<REMOVED>>/*",
				"**/com/<<REMOVED>>/*"
            ])
        }))
    }
	reports {
		xml.required = true
		html.required = true
		csv.required = false
		xml.outputLocation = file("${buildDir}/reports/xml/")
	}
}

protobuf {
	protoc {
		artifact = "com.google.protobuf:protoc:${protobufVersion}"
	}
	generatedFilesBaseDir = "$projectDir/src/generated"
	clean {
		delete generatedFilesBaseDir
	}
	plugins {
		grpc {
			artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
		}
	}
	generateProtoTasks {
		all()*.plugins {
			grpc {}
		}
	}
}

// Optional
eclipse {
	classpath {
		file.beforeMerged { cp ->
			def generatedGrpcFolder = new SourceFolder('src/generated/main/grpc', null);
			generatedGrpcFolder.entryAttributes['ignore_optional_problems'] = 'true';
			cp.entries.add( generatedGrpcFolder );
			def generatedJavaFolder = new SourceFolder('src/generated/main/java', null);
			generatedJavaFolder.entryAttributes['ignore_optional_problems'] = 'true';
			cp.entries.add( generatedJavaFolder );
		}
	}
}

// Optional
idea {
	module {
		sourceDirs += file("src/generated/main/java")
		sourceDirs += file("src/generated/main/grpc")
		generatedSourceDirs += file("src/generated/main/java")
		generatedSourceDirs += file("src/generated/main/grpc")
	}
}
```
</details>

##### Environment
- Operating System: ventura 13.1
- JDK version: java 17.0.3.1 2022-04-22 LTS
- Visual Studio Code version:  1.77.1 (Universal)
- Java extension version: v1.16.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by Tiffany-Seymour** [comment]
After rebuilding the project one piece at a time, can confirm that adding these to the settings.gradle is what is breaking the intellisense:
settings.gradle
```
include 'src:main:proto'
findProject(':src:main:proto')?.name = 'proto'
```

**Comment by fbricon** [comment]
`java.jdt.ls.protobufSupport.enabled` should be set to true (default value).  Only works for Gradle `com.google.protobuf` plugin `0.8.4` or higher.

https://github.com/redhat-developer/vscode-java/pull/2629/files.

If that's already the case, please attach a sample project reproducing the issue.
