### ISSUE TITLE
Java compiler problem with enums using windows1252 encoding

### ISSUE THREAD

**Issue by bernardomoraisbh** [redhat-developer/vscode-java#3060]
So I'm trying to migrate from eclipse to vs code, all my projects are usually created using windows1252 for java files and utf8 for build/html/xhtml files, but when I try to run some projects that have special characters on enum names the compiler reports Syntax error for every single one of them, but when I open the files all the error messages disappear, if I close the file they return.

![erro1](https://user-images.githubusercontent.com/26288503/231458471-d40184d8-065d-4668-9aa6-e71fb7293f51.png)

![workspace](https://user-images.githubusercontent.com/26288503/231458426-663b1f4b-b7bc-4f7b-961f-17995d1e0cc4.gif)

##### Workspace Settings

`
"settings": {
	"files.autoGuessEncoding": true,
	"java.configuration.updateBuildConfiguration": "automatic",
	"explorer.autoReveal": false
	"[java]": {
		"files.encoding": "windows1252"
	}
}
`

##### Preferences Settings

`
"java.jdt.ls.vmargs": "-Dfile.encoding=windows1252 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\berna\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
"rsp-ui.rsp.java.home": "C:\\R2DA\\java\\jdk-11.0.10",
"[java]": {
	"files.encoding": "windows1252"
},
"files.encoding": "windows1252",
"sonarlint.ls.javaHome": "C:\\R2DA\\java\\jdk-11.0.10",
"spring-boot.ls.java.home": "C:\\Program Files\\Java\\jdk-17",
"java.import.gradle.java.home": "C:\\R2DA\\java\\jdk-11.0.10",
"java.project.encoding": "setDefault",
"java.jdt.ls.java.home": "C:\\Program Files\\Java\\jdk-17",
"java.configuration.runtimes": [
	{
		"name": "JavaSE-11",
		"path": "C:\\R2DA\\java\\jdk-11.0.10",
		"default": true,
	}
],
"spring-boot.ls.java.vmargs": [
	"-Dfile.encoding=windows1252"
],
"java.debug.settings.vmArgs": "-Dfile.encoding=windows1252",
`

##### Spring Dashboard Application Start Log

`
PS C:\R2DA\recivil\api-sistema-registro>  & 'C:\R2DA\java\jdk-11.0.10\bin\java.exe' '@C:\Users\berna\AppData\Local\Temp\cp_2u4mmuey7f1wwsl3uwa1ds5ug.argfile' 'api.sistema.registro.ApiSistemaRegistroApplication'
...
nested exception is java.lang.IllegalArgumentException: api.entidade.sistema.registro.enums.EnumPermissoes is not an enum type
        at api.sistema.registro.ApiSistemaRegistroApplication.main(ApiSistemaRegistroApplication.java:12) ~[main/:na]
Caused by: java.lang.IllegalArgumentException: api.entidade.sistema.registro.enums.EnumPermissoes is not an enum type
        at java.base/java.lang.Class.enumConstantDirectory(Class.java:3578) ~[na:na]
        at java.base/java.lang.Enum.valueOf(Enum.java:234) ~[na:na]
        at org.springframework.core.type.classreading.MergedAnnotationReadingVisitor.visitEnum(MergedAnnotationReadingVisitor.java:105) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.core.type.classreading.MergedAnnotationReadingVisitor$ArrayVisitor.visitEnum(MergedAnnotationReadingVisitor.java:171) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.asm.ClassReader.readElementValue(ClassReader.java:3056) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.asm.ClassReader.readElementValues(ClassReader.java:2981) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.asm.ClassReader.readElementValue(ClassReader.java:3155) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.asm.ClassReader.readElementValues(ClassReader.java:2975) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.asm.ClassReader.readMethod(ClassReader.java:1393) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.asm.ClassReader.accept(ClassReader.java:718) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.asm.ClassReader.accept(ClassReader.java:401) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:429) ~[spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        ... 21 common frames omitted
`

##### Environment
- Operating System: Windows 11 22H2
- JDK version: 17.0.6 and 11.0.10
- Visual Studio Code version: 1.77.2
- Java extension version: Project Manager for Java  v0.21.2 Debugger for Java  v0.49.1 | Language Support for Java(TM) by Red Hat  v1.16.0 

##### Project Settings
- Gradle 6.3
- Java 11
- Spring Boot 2.3.8.RELEASE

##### Steps To Reproduce
1. Create a enum using windows1252 encoding and characters like ç ã é ú...
2. Close the file and reload the project

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

Compiler not working properly and error when running my spring projects over the Spring Dashboard Extension.

##### Expected Result

No compile errors and projects inside my workspace should be compiled with windows1252 encoding.

##### Additional Informations

I tried using the "spring-boot.ls.java.vmargs" settings for passing the encoding arg for the Spring Boot Dashboard extension, but I don't think it's working properly, since when I try to run the application over the dashboard I got only this args " & 'C:\R2DA\java\jdk-11.0.10\bin\java.exe' '@C:\Users\berna\AppData\Local\Temp\cp_2u4mmuey7f1wwsl3uwa1ds5ug.argfile' 'api.sistema.registro.ApiSistemaRegistroApplication'" and as soon as the application fails to start the file cp_2u4mmuey7f1wwsl3uwa1ds5ug.argfile is erased from the file system.

**Comment by snjeza** [comment]
> Steps To Reproduce
 Create a enum using windows1252 encoding and characters like ç ã é ú...
 Close the file and reload the project

@bernardomoraisbh Could you attach a project example?

**Comment by bernardomoraisbh** [comment]
Sure, https://github.com/bernardomoraisbh/api-test

**Comment by bernardomoraisbh** [comment]
> > Steps To Reproduce
> > Create a enum using windows1252 encoding and characters like ç ã é ú...
> > Close the file and reload the project
> 
> @bernardomoraisbh Could you attach a project example?

Sure, [https://github.com/bernardomoraisbh/api-test](https://github.com/bernardomoraisbh/api-test)

**Comment by snjeza** [comment]
@bernardomoraisbh You need to use `windows-1252` instead of `windows1252`

**Comment by bernardomoraisbh** [comment]
> @bernardomoraisbh You need to use `windows-1252` instead of `windows1252`

Where exactly?
Usually I get this message:
`
Value is not accepted. Valid values: "utf8", "utf8bom", "utf16le", "utf16be", "windows1252", "iso88591", "iso88593", "iso885915", "macroman", "cp437", "windows1256", "iso88596", "windows1257", "iso88594", "iso885914", "windows1250", "iso88592", "cp852", "windows1251", "cp866", "iso88595", "koi8r", "koi8u", "iso885913", "windows1253", "iso88597", "windows1255", "iso88598", "iso885910", "iso885916", "windows1254", "iso88599", "windows1258", "gbk", "gb18030", "cp950", "big5hkscs", "shiftjis", "eucjp", "euckr", "windows874", "iso885911", "koi8ru", "koi8t", "gb2312", "cp865", "cp850".
`

**Comment by snjeza** [comment]
> Where exactly?

<your_project>/.settings/org.eclipse.core.resources.prefs - https://github.com/bernardomoraisbh/api-test/blob/main/.settings/org.eclipse.core.resources.prefs

a patch
```
diff --git a/.settings/org.eclipse.core.resources.prefs b/.settings/org.eclipse.core.resources.prefs
index f45bc94..68a0304 100644
--- a/.settings/org.eclipse.core.resources.prefs
+++ b/.settings/org.eclipse.core.resources.prefs
@@ -1,2 +1,2 @@
 eclipse.preferences.version=1
-encoding/<project>=windows1252
+encoding/<project>=windows-1252
```

![win1252](https://user-images.githubusercontent.com/388609/232158774-f9345eac-0b8d-44de-9047-1f82f5c17abd.gif)

**Comment by bernardomoraisbh** [comment]
It partially fixes the problem, but if you delete the build files (I only commited them for test purposes, usually they are not commited) VS Code recreates the org.eclipse.core.resources.prefs with `encoding/<project>=windows1252`, any idea on how to fix this?

To test try deletting this folders and import the project again:
`
.gradle
.settings
bin
`

**Comment by bernardomoraisbh** [comment]
I also noted that sometimes VS Code changes the file with windows1252 instead of windows-1252

**Comment by snjeza** [comment]
> I also noted that sometimes VS Code changes the file with windows1252 instead of windows-1252

You are right. VS Code uses `windows1252` and Eclipse/Java LS uses `windows-1252`
```
```
"java.jdt.ls.vmargs": "-Dfile.encoding=windows-1252 ...",
"[java]": {
   "files.encoding": "windows1252"
},
"files.encoding": "windows1252",
"java.debug.settings.vmArgs": "-Dfile.encoding=windows-1252",
```

**Comment by snjeza** [comment]
> To test try deletting this folders and open the project again:

You can try to set
```
```
"java.jdt.ls.vmargs": "-Dfile.encoding=windows-1252 <your_vm_args>",
"[java]": {
   "files.encoding": "windows1252"
},
"files.encoding": "windows1252",
"java.debug.settings.vmArgs": "-Dfile.encoding=windows-1252",
```

**Comment by bernardomoraisbh** [comment]
Not worked, now I'm stuck with this error:

![image](https://user-images.githubusercontent.com/26288503/232162282-cb1a8a42-c59c-4872-9904-52897068d76e.png)

![image](https://user-images.githubusercontent.com/26288503/232162312-815394b4-e10d-49ef-86b0-cf7053ef8ad1.png)

![image](https://user-images.githubusercontent.com/26288503/232162321-5333ac3e-05ba-4cd9-ae7f-de000c4799ce.png)

**Comment by snjeza** [comment]
Could you try the following
```
- set
"java.jdt.ls.vmargs": "-Dfile.encoding=windows-1252 <your_vm_args>",
"[java]": {
   "files.encoding": "windows1252"
},
"files.encoding": "windows1252",
"java.debug.settings.vmArgs": "-Dfile.encoding=windows-1252",

- close VS Code
$ cd api-test
$ rm -rf .project .classpath .settings .gradle bin
$ code .
```

**Comment by bernardomoraisbh** [comment]
Only changing the settings as you said did not work for me, I had to delete all build files, delete the VS Code workspace cache (AppData\Roaming\Code\User\workspaceStorage) and remove the `"java.settings.url":".settings/org.eclipse.jdf.core.prefs"` from my settings.json.

`
{
"security.workspace.trust.untrustedFiles": "open",
"workbench.editorAssociations": {
		"*.ipynb": "jupyter-notebook"
},
"notebook.cellToolbarLocation": {
		"default": "right",
		"jupyter-notebook": "left"
},
"python.defaultInterpreterPath": "C:\\Users\\berna\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
"files.exclude": {
		"**/.classpath": true,
		"**/.project": true,
		"**/.settings": true,
		"**/.factorypath": true
},
"editor.suggestSelection": "first",
"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
"java.jdt.ls.vmargs": "-Dfile.encoding=windows-1252 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\berna\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
"rsp-ui.rsp.java.home": "C:\\R2DA\\java\\jdk-11.0.10",
"redhat.telemetry.enabled": false,
"rsp-ui.enableStartServerOnActivation": [
	{
		"id": "redhat.vscode-server-connector",
		"name": "Red Hat Server Connector",
		"startOnActivation": true
	}
],
"vetur.format.options.useTabs": true,
"editor.tabSize": 2,
"editor.renderWhitespace": "all",
"eslint.format.enable": true,
"editor.detectIndentation": false,
"editor.insertSpaces": false,
"files.eol": "\r\n",
"[javascript]": {
	"editor.defaultFormatter": "dbaeumer.vscode-eslint",
	"files.encoding": "utf8"
},
"[vue]": {
	"editor.defaultFormatter": "dbaeumer.vscode-eslint",
	"files.encoding": "utf8"
},
"[java]": {
	"files.encoding": "windows1252"
},
"[xhtml]": {
	"files.encoding": "utf8"
},
"[jsf]": {
	"files.encoding": "utf8"
},
"[json]": {
	"files.encoding": "utf8"
},
"[jsonc]": {
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"files.encoding": "utf8"
},
"[python]": {
	"editor.formatOnType": true
},
"eslint.validate": [
	"javascript",
	"javascriptreact",
	"typescript",
	"typescriptreact",
	"html",
	"vue",
],
"editor.codeActionsOnSave": {
	"source.fixAll.eslint": true,
	"source.organizeImports": true,
},
"files.encoding": "windows1252",
"rest-client.suppressResponseBodyContentTypeValidationWarning": true,
"vscode-edge-devtools.mirrorEdits": true,
"workbench.iconTheme": "vscode-icons",
"java.debug.settings.showHex": false,
"java.saveActions.organizeImports": true,
"debug.javascript.autoAttachFilter": "disabled",
"vetur.format.defaultFormatter.js": "vscode-typescript",
"vetur.format.defaultFormatter.html": "js-beautify-html",
"vetur.validation.interpolation": true,
"vetur.experimental.templateInterpolationService": true,
"files.autoGuessEncoding": true,
"vetur.useWorkspaceDependencies": true,
"files.trimTrailingWhitespace": true,
"files.insertFinalNewline": true,
"[html]": {
	"editor.defaultFormatter": "vscode.html-language-features"
},
"sonarlint.rules": {
	"javascript:S4144": {
		"level": "off"
	},
	"Web:S5264": {
		"level": "off"
	}
},
"editor.unicodeHighlight.invisibleCharacters": false,
"boot-java.rewrite.reconcile": true,
"sync.gist": "cca71b285a52e3d6a1660f963f030ce0",
"indentRainbow.lightIndicatorStyleLineWidth": 1,
"indentRainbow.colors": [
	"rgba(255,255,64,0.07)",
	"rgba(127,255,127,0.07)",
	"rgba(255,127,255,0.07)",
	"rgba(79,236,236,0.07)"
],
"sonarlint.ls.javaHome": "C:\\R2DA\\java\\jdk-11.0.10",
"spring-boot.ls.java.home": "C:\\Program Files\\Java\\jdk-17",
"java.import.gradle.java.home": "C:\\R2DA\\java\\jdk-11.0.10",
"java.project.encoding": "setDefault",
"java.jdt.ls.java.home": "C:\\Program Files\\Java\\jdk-17",
"java.configuration.runtimes": [
	{
		"name": "JavaSE-11",
		"path": "C:\\R2DA\\java\\jdk-11.0.10",
		"default": true,
	}
],
"spring-boot.ls.java.vmargs": [
	"-Dfile.encoding=windows-1252"
],
"java.debug.settings.vmArgs": "-Dfile.encoding=windows-1252",
"workbench.colorTheme": "Default Dark+ Experimental",
}

`

Now I don't get any errors because of encoding and the spring dashboard is working fine.

But I have a new warning for all my projects:
![image](https://user-images.githubusercontent.com/26288503/232168702-c2c8b958-7b9a-46e9-aae6-82910eeebd8a.png)
Any idea on how to fix this "Project ... has no explicit encoding set" warning?

**Comment by snjeza** [comment]
> Only changing the settings as you said did not work for me, I had to delete all build files, delete the VS Code workspace cache (AppData\Roaming\Code\User\workspaceStorage)

You can try to set 
```
"java.import.generatesMetadataFilesAtProjectRoot": true,
```
and try steps at https://github.com/redhat-developer/vscode-java/issues/3060#issuecomment-1509358928
It will create .project, .classpath, .settings in your project's root file and configure the windows-1252 encoding
Otherwise you have to remove your workspace

>  and remove the "java.settings.url":".settings/org.eclipse.jdf.core.prefs" from my settings.json.

Could you show your ".settings/org.eclipse.jdt.core.prefs"?

> Any idea on how to fix this "Project ... has no explicit encoding set" warning?

- remove your workspace
- remove the GabrielBB.vscode-lombok extension. it is deprecated

```
"java.project.encoding": "setDefault",
"java.import.generatesMetadataFilesAtProjectRoot": true,
"java.jdt.ls.vmargs": "-Dfile.encoding=windows-1252 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\berna\\lombok-1.18.26.jar\"",

```
- download lombok-1.18.26.jar from https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.26/lombok-1.18.26.jar
- restart VS Code

or set 
```
"java.project.encoding": "ignore",
```

**Comment by bernardomoraisbh** [comment]
> You can try to set
> 
> ```
> "java.import.generatesMetadataFilesAtProjectRoot": true,
> ```
> and try steps at [#3060 (comment)](https://github.com/redhat-developer/vscode-java/issues/3060#issuecomment-1509358928) It will create .project, .classpath, .settings in your project's root file and configure the windows-1252 encoding Otherwise you have to remove your workspace

Changing this created the .settings / .classpath / .project files and folders inside the project folder, but it didn't set the encoding (no errors after importing) inside the .settings/org.eclipse.core.resources.prefs file, this file doesn't even exists at all.

![image](https://user-images.githubusercontent.com/26288503/232175585-38c684cf-706f-4aaa-a730-1b8a2669455a.png)

![image](https://user-images.githubusercontent.com/26288503/232175590-5594e7b3-bf98-49c8-914c-7954bd2422ee.png)

![image](https://user-images.githubusercontent.com/26288503/232175596-f5d0dcab-ea61-4833-8b31-830b1333216f.png)

![image](https://user-images.githubusercontent.com/26288503/232175602-5cbbc712-3973-44b6-9ba3-881ffb62ac3f.png)

![image](https://user-images.githubusercontent.com/26288503/232175615-e9008936-7fb0-41e6-b0da-4339244e9bfa.png)

> Could you show your ".settings/org.eclipse.jdt.core.prefs"?
File does not exists anymore and the VS Code project build is not building it.

> ```
> "java.project.encoding": "ignore",
> ```

This setting actually fixed the "Project ... has no explicit encoding set" warning, thanks!
