### ISSUE TITLE
Extension continuously crashing and very slow at completion, formatting, etc.

### ISSUE THREAD

**Issue by Holt59** [redhat-developer/vscode-java#3077]
I just came back to working with VS Code and Java after a month or two, and I am having tons of issue with this extensions, making it almost unusable.

Some of the issues:
- When trying to format on save, the extension takes a very long time, possibly crashing, and ending-up not formatting.
- When trying to complete a word, the extension is sometimes stuck at "Loading... ", after some times (usually > 10s), a crash message appear in the log window and the completion appears.
- The extension does not update the error immediately, e.g., the extension can display errors for 30s-1min after modifying a document.

##### Environment
- Operating System: Windows 10
- JDK version: I have multiple JDK configured in VS Code, not sure which one the extension is using (1.8 202, 17.0.4.1, 18.0.1.1), project is targeting Java 8.
- Visual Studio Code version: 1.77.3
- Java extension version: v1.18.2023041804 (pre-release), although the same problems occurs with the release version.

##### Additional Informations

I am sorry for not being able to provide a project reproducing the issue but this is internal stuff that cannot be disclosed.

Below are some of the logs:

```
2023-04-18 15:36:45.594 [error] [redhat.java] provider FAILED
2023-04-18 15:36:45.595 [error] Error: The request (id: 930, method: 'textDocument/hover') has been cancelled
	at c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1071031
	at ie (c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1071325)
	at c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1066109
	at Immediate.<anonymous> (c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1066129)
	at process.processImmediate (node:internal/timers:466:21)

2023-04-18 15:51:01.262 [error] [redhat.java] provider FAILED
2023-04-18 15:51:01.263 [error] Error: The request (id: 1388, method: 'textDocument/documentSymbol') has been cancelled
	at c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1071031
	at ie (c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1071325)
	at c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1066109
	at Immediate.<anonymous> (c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1066129)
	at process.processImmediate (node:internal/timers:466:21)
2023-04-18 15:51:01.275 [error] Error: The request (id: 1396, method: 'workspace/executeCommand') has been cancelled
	at c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1071031
	at ie (c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1071325)
	at c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1066109
	at Immediate.<anonymous> (c:\Users\XXX\.vscode\extensions\redhat.java-1.18.2023041804-win32-x64\dist\extension.js:2:1066129)
	at process.processImmediate (node:internal/timers:466:21) java.execute.workspaceCommand {"value":"redhat.java","c":"redhat.java"}
```

**Note:** I just downgraded to 1.15.0 and the problems disappear (**update**: problem is still present but occur less often with 1.15.0).

**Comment by snjeza** [comment]
@Holt59  
1. Could you attach your log files?

- open the command palette ( F1 )
- select `Java: Open All Log Files`

2. Are you using lombok?

**Comment by Holt59** [comment]
@snjeza 

I'll try to upload log files reproducing the issue with pre-release version. Is there an easy way to start with clear all previous logs?

I'm not using lombok.

**Comment by Holt59** [comment]
@snjeza Here is a gist containing logs https://gist.github.com/Holt59/4b76ef79ef6ce06de7417f37a29e9c22

During that session, I encountered the following problems:

- There were some unused variables in a functions that I removed, after removing them, VS Code kept the "unused variable" warning for a very long time before removing it.
- I started to write a method, writing `public XX` and then Ctrl+Space for completion, and I was stuck in "Loading... " for quite a long time (> 10s) before getting an actual completion.

**Comment by Holt59** [comment]
@snjeza It looks like the issue is that building takes a very long time which is why everything is "delayed" until the build is done. In the build log I see the following line:

```
dce80554 Building: 66% Refreshing '/yyy'. [661/1000]
```

That takes a very long time (like from ~570 to 650).

**Comment by testforstephen** [comment]
@Holt59 thanks for reporting the issue.

A possible cause of the slow responsiveness of the Java extension is that the build job locks the workspace and prevents other features from being scheduled. Could you please share the thread dump of the Java extension when you experience this issue? This would help us to analyze the root cause. Thanks.

Here are the steps for thread dump:
1. Close the irrelevent VS Code windows except the current one.
2. In the terminal, run the `jps` command and look for the pid of the process named “org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar”.
```
>jps
23492 Jps
3940 Main
20524 GradleDaemon
20924 org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar       <==== This is the pid of Java extension process
```
4. In the terminal, run `jstack <pid>` to dump threads of Java extension
```
>jstack 20924
```

**Comment by Holt59** [comment]
@testforstephen I've added the `jstack`  (from the JDK 17) output to the gist. I've run `jstack` when the `dce80554 Building: 66% Refreshing '/yyy'. [661/1000]` was running in the build status.

**Comment by Holt59** [comment]
@testforstephen Updated the jstack in the gist, I triggered a completion during a build stuck, that stayed in "Loading... " and run jstack when this occurred.

**Comment by testforstephen** [comment]
@Holt59 Great, thanks. I see the stuck point in the thread dump.

The didChange (typing) thread is blocked by the AutoBuildJob thread. The AutoBuildJob thread acquires the scheduling rule on the workspace root and does not release it until it finishes. This prevents any other operation that requires the same or child scheduling rule, such as didChange, from proceeding. This is exactly the same case we have discussed in https://github.com/eclipse/eclipse.jdt.ls/issues/2518 and https://github.com/eclipse/eclipse.jdt.ls/issues/2519.

- jsonrpc main dispatcher thread is stuck at handling didChange.
```
"pool-1-thread-1" #37 prio=5 os_prio=0 cpu=3390.62ms elapsed=3187.13s tid=0x0000023ac2c09a10 nid=0x2ac in Object.wait()  [0x000000c7a16fe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.6/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@17.0.6/Unknown Source)
	at org.eclipse.core.internal.jobs.ThreadJob.waitForRun(ThreadJob.java:322)
	- locked <0x00000000c04b0670> (a java.lang.Object)
	at org.eclipse.core.internal.jobs.ThreadJob.joinRun(ThreadJob.java:208)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:95)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:316)  <==== Waiting for a scheduling rule for the current resource file
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2332)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2377)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.didChange(BaseDocumentLifeCycleHandler.java:337)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didChange(JDTLanguageServer.java:853)
	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.6/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@17.0.6/Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda$188/0x000000010040ec10.apply(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher$$Lambda$186/0x0000000100406710.consume(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.6/Unknown Source)
	at java.util.concurrent.FutureTask.run(java.base@17.0.6/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.6/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.6/Unknown Source)
	at java.lang.Thread.run(java.base@17.0.6/Unknown Source)
```

- AutoBuildJob
```
"Worker-30: Building" #298 prio=5 os_prio=0 cpu=3734.38ms elapsed=654.08s tid=0x0000023ac8068a50 nid=0xbbf8 runnable  [0x000000c7a14fd000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:110)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:978)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:961)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1573)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.refreshResources(MavenBuilderImpl.java:280)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:176)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$$Lambda$463/0x000000010062b7c8.call(Unknown Source)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$$Lambda$462/0x000000010062b5a8.call(Unknown Source)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)   <=== This will hold the lock on workspace root
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Holt59** [comment]
@testforstephen Thanks for the information, is there any reason why this would be way more visible on latest release of the extension than on 1.15? Is there a way to fix this in some way?

**Comment by Holt59** [comment]
@snjeza @testforstephen I narrowed the issue down to the refreshing of the workspace by the JDT server, in particular because I have a large folder at the root of the project.

Is there any way to configure the JDT through VS Code to ignore that folder? I tried using `java.import.exclusions` but it did nothing.

**Comment by fbricon** [comment]
@Holt59 try `java.project.resourceFilters`
