### ISSUE TITLE
 java.lang.StackOverflowError at BfDependencyCollector.processDependency(BfDependencyCollector.java:252)

### ISSUE THREAD

**Issue by acristu** [redhat-developer/vscode-java#3085]
##### Environment
- Operating System: Windows 11
- JDK version: openjdk 17.0.6 2023-01-17
- Visual Studio Code version: 1.77.3
- Java extension version: v1.17.0

##### Steps To Reproduce
1. Open this project https://github.com/snowflakedb/snowflake-kafka-connector

##### Current Result

```
!ENTRY org.eclipse.core.jobs 4 2 2023-04-25 18:33:39.743
!MESSAGE An internal error occurred during: "Initialize Workspace".
!STACK 0
java.lang.StackOverflowError
	at org.eclipse.aether.util.graph.manager.ClassicDependencyManager.getKey(ClassicDependencyManager.java:216)
	at org.eclipse.aether.util.graph.manager.ClassicDependencyManager.manageDependency(ClassicDependencyManager.java:154)
	at org.eclipse.aether.internal.impl.collect.PremanagedDependency.create(PremanagedDependency.java:93)
	at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.processDependency(BfDependencyCollector.java:252)
	at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.processDependency(BfDependencyCollector.java:269)
	at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.processDependency(BfDependencyCollector.java:269)
	at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.processDependency(BfDependencyCollector.java:269)
. . . 
```

##### Expected Result

Project should initialize correctly

**Comment by snjeza** [comment]
@acristu you may want to take a look at https://github.com/redhat-developer/vscode-java/issues/3080#issuecomment-1516822980

**Comment by snjeza** [comment]
This issue is an upstream [m2e](https://github.com/eclipse-m2e/m2e-core) issue.

**Comment by yeroc** [comment]
@snjeza I seem to have run into a similar issue after recently upgrading VS Code.  Is there a specific m2e issue we can vote/follow?

**Comment by snjeza** [comment]
>  I seem to have run into a similar issue after recently upgrading VS Code. Is there a specific m2e issue we can vote/follow?

We should set DEPENDENCY_COLLECTOR_IMPL_BF to df by default - https://github.com/redhat-developer/vscode-java/blob/master/src/javaServerStarter.ts#L35
[m2e](https://github.com/eclipse-m2e/m2e-core) also uses it.
cc @fbricon @rgrunber @mickaelistria @jdneo @testforstephen

**Comment by rgrunber** [comment]
Can we bring this up in maven-resolver itself since that's where the bf/df collectors reside ? Is it reproducible from commandline ? https://issues.apache.org/jira/projects/MRESOLVER/issues . The whole reason we went to `bf` was for the performance benefit.

**Comment by snjeza** [comment]
>  Is it reproducible from commandline ?

Yes, it is.

```
$ mvn -v
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
$ git clone git@github.com:snowflakedb/snowflake-kafka-connector.git
cd snowflake-kafka-connector
mvn clean verify -Daether.dependencyCollector.impl=bf
```

> The whole reason we went to `bf` was for the performance benefit.

I know, but it breaks some projects. Maven and m2e use `df` per default.

**Comment by rgrunber** [comment]
Maybe commenting on https://issues.apache.org/jira/browse/MRESOLVER-324 , since that's the proposal to switch over to `bf`.

**Comment by testforstephen** [comment]
> Maybe commenting on https://issues.apache.org/jira/browse/MRESOLVER-324 , since that's the proposal to switch over to `bf`.

Agree. @snjeza Could you comment your findings in the upstream issue?

**Comment by snjeza** [comment]
@testforstephen I have requested a Jira account at https://selfserve.apache.org/jira-account.html ; waiting for approval.

**Comment by snjeza** [comment]
@rgrunber @testforstephen You may want to take a look at https://issues.apache.org/jira/browse/MRESOLVER-376

**Comment by cstamas** [comment]
what resolver version is in use here?

**Comment by cstamas** [comment]
```diff
diff --git a/pom.xml b/pom.xml
index f2fa58e..e14d153 100644
--- a/pom.xml
+++ b/pom.xml
@@ -481,6 +481,12 @@
             <artifactId>system-rules</artifactId>
             <version>1.19.0</version>
             <scope>test</scope>
+            <exclusions>
+                <exclusion>
+                    <groupId>junit</groupId>
+                    <artifactId>junit</artifactId>
+                </exclusion>
+            </exclusions>
         </dependency>
 
         <!--Kafka JSON converter for SMT unit test-->
```

Seems this is a bug in BF collector, above is a workaround.

**Comment by jchojnacka-tbscg** [comment]
I have similar issue, I cleared workspaceStorage and I run VSC with -Daether.dependencyCollector.impl=bf and my error changed to:

```
[Error - 11:56:24 AM] Jul 3, 2023, 11:56:24 AM An internal error occurred during: "Building".
null
java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector$ParallelDescriptorResolver.resolveDescriptors(BfDependencyCollector.java:490)
	at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.resolveArtifactDescriptorAsync(BfDependencyCollector.java:402)
```

**Comment by jchojnacka-tbscg** [comment]
@snjeza Tried with bf and df and still not working :/

**Comment by snjeza** [comment]
@jchojnacka-tbscg Could you attach a project example?

**Comment by jchojnacka-tbscg** [comment]
not possible, as is a company project

**Comment by snjeza** [comment]
Could you show your log?

**Comment by snjeza** [comment]
> what resolver version is in use here?

@cstamas VS Code >= 1.20.0 uses maven 3.9.1, maven-resolver 1.9.7
