### ISSUE TITLE
An internal error occurred during: "Initialize Workspace"

### ISSUE THREAD

**Issue by KeplerIO** [redhat-developer/vscode-java#313]
Installed Language Support for Java by Red Hat. After installing JDK and setting path in Environment Variables and setting the java.home option in VS Code to point to the right place, I open a file "main.java" in VS Code to test. Intellisense isn't working for imports then I check Output window.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_144
- Visual Studio Code version: 1.16.1
- Java extension version: 0.10.0

##### Steps To Reproduce
1. Install Language Support for java by Red Hat
2. Install JDK
3. Set JDK path in Environment Variables
4. Set java.home path in VS Code settings
5. Create new projects directory and add the file "main.java"
6. Wait a few seconds and check Output window

--Output--
[Error - 12:42:46 PM] Request textDocument/codeAction failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 12:42:46 PM] Oct 2, 2017 12:42:43 PM An internal error occurred during: "Initialize Workspace".
null
java.lang.NullPointerException
	at org.eclipse.jdt.internal.launching.LaunchingPlugin.readInstallInfo(LaunchingPlugin.java:1008)
	at org.eclipse.jdt.internal.launching.LaunchingPlugin.timeStampChanged(LaunchingPlugin.java:980)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.populateVMForType(VMDefinitionsContainer.java:557)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.populateVMTypes(VMDefinitionsContainer.java:494)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.parseXMLIntoContainer(VMDefinitionsContainer.java:473)
	at org.eclipse.jdt.launching.JavaRuntime.addPersistedVMs(JavaRuntime.java:1499)
	at org.eclipse.jdt.launching.JavaRuntime.initializeVMs(JavaRuntime.java:2671)
	at org.eclipse.jdt.launching.JavaRuntime.getDefaultVMId(JavaRuntime.java:548)
	at org.eclipse.jdt.launching.JavaRuntime.getDefaultVMInstall(JavaRuntime.java:493)
	at org.eclipse.jdt.internal.launching.JREContainerInitializer.resolveVM(JREContainerInitializer.java:159)
	at org.eclipse.jdt.internal.launching.JREContainerInitializer.initialize(JREContainerInitializer.java:60)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3071)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2043)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3497)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2687)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2851)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1956)
	at org.eclipse.jdt.internal.core.DynamicProjectReferences.getDependentProjects(DynamicProjectReferences.java:34)
	at org.eclipse.core.internal.resources.ProjectDescription.computeDynamicReferencesForProject(ProjectDescription.java:950)
	at org.eclipse.core.internal.resources.ProjectDescription.getAllBuildConfigReferences(ProjectDescription.java:265)
	at org.eclipse.core.internal.resources.Project.internalGetReferencedBuildConfigs(Project.java:787)
	at org.eclipse.core.internal.resources.Workspace.computeActiveBuildConfigOrder(Workspace.java:720)
	at org.eclipse.core.internal.resources.Workspace.getBuildOrder(Workspace.java:1567)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:459)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:134)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 12:42:47 PM] Oct 2, 2017 12:42:43 PM An internal error occurred during: "Repository registry initialization".
Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.newPlexusContainer(MavenImpl.java:1318)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer0(MavenImpl.java:1220)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer(MavenImpl.java:1211)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lookup(MavenImpl.java:1270)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:470)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:439)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistry.updateRegistry(RepositoryRegistry.java:223)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistryUpdateJob.run(RepositoryRegistryUpdateJob.java:47)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NullPointerException
	at org.eclipse.m2e.core.internal.embedder.ExtensionModule.configure(ExtensionModule.java:51)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:75)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 14 more

[Info  - 12:42:48 PM] Connection to server got closed. Server will restart.
[Error - 12:42:55 PM] Request textDocument/codeAction failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 12:42:55 PM] Oct 2, 2017 12:42:52 PM An internal error occurred during: "Initialize Workspace".
null
java.lang.NullPointerException
	at org.eclipse.jdt.internal.launching.LaunchingPlugin.readInstallInfo(LaunchingPlugin.java:1008)
	at org.eclipse.jdt.internal.launching.LaunchingPlugin.timeStampChanged(LaunchingPlugin.java:980)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.populateVMForType(VMDefinitionsContainer.java:557)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.populateVMTypes(VMDefinitionsContainer.java:494)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.parseXMLIntoContainer(VMDefinitionsContainer.java:473)
	at org.eclipse.jdt.launching.JavaRuntime.addPersistedVMs(JavaRuntime.java:1499)
	at org.eclipse.jdt.launching.JavaRuntime.initializeVMs(JavaRuntime.java:2671)
	at org.eclipse.jdt.launching.JavaRuntime.getDefaultVMId(JavaRuntime.java:548)
	at org.eclipse.jdt.launching.JavaRuntime.getDefaultVMInstall(JavaRuntime.java:493)
	at org.eclipse.jdt.internal.launching.JREContainerInitializer.resolveVM(JREContainerInitializer.java:159)
	at org.eclipse.jdt.internal.launching.JREContainerInitializer.initialize(JREContainerInitializer.java:60)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3071)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2043)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3497)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2687)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2851)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1956)
	at org.eclipse.jdt.internal.core.DynamicProjectReferences.getDependentProjects(DynamicProjectReferences.java:34)
	at org.eclipse.core.internal.resources.ProjectDescription.computeDynamicReferencesForProject(ProjectDescription.java:950)
	at org.eclipse.core.internal.resources.ProjectDescription.getAllBuildConfigReferences(ProjectDescription.java:265)
	at org.eclipse.core.internal.resources.Project.internalGetReferencedBuildConfigs(Project.java:787)
	at org.eclipse.core.internal.resources.Workspace.computeActiveBuildConfigOrder(Workspace.java:720)
	at org.eclipse.core.internal.resources.Workspace.getBuildOrder(Workspace.java:1567)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:459)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:134)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 12:42:56 PM] Oct 2, 2017 12:42:52 PM An internal error occurred during: "Repository registry initialization".
Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.newPlexusContainer(MavenImpl.java:1318)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer0(MavenImpl.java:1220)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer(MavenImpl.java:1211)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lookup(MavenImpl.java:1270)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:470)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:439)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistry.updateRegistry(RepositoryRegistry.java:223)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistryUpdateJob.run(RepositoryRegistryUpdateJob.java:47)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NullPointerException
	at org.eclipse.m2e.core.internal.embedder.ExtensionModule.configure(ExtensionModule.java:51)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:75)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 14 more

[Info  - 12:42:57 PM] Connection to server got closed. Server will restart.
[Error - 12:43:03 PM] Request textDocument/codeAction failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 12:43:03 PM] Oct 2, 2017 12:43:00 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
null
java.lang.NullPointerException
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.getProjectsManager(JavaLanguageServerPlugin.java:314)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.visit(WorkspaceDiagnosticsHandler.java:84)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.resourceChanged(WorkspaceDiagnosticsHandler.java:62)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:496)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:134)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Warn  - 12:43:04 PM] Oct 2, 2017 12:43:00 PM The workspace will exit with unsaved changes in this session.
[Error - 12:43:04 PM] Oct 2, 2017 12:43:00 PM An internal error occurred during: "Repository registry initialization".
Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.newPlexusContainer(MavenImpl.java:1318)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer0(MavenImpl.java:1220)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer(MavenImpl.java:1211)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lookup(MavenImpl.java:1270)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:470)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:439)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistry.updateRegistry(RepositoryRegistry.java:223)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistryUpdateJob.run(RepositoryRegistryUpdateJob.java:47)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NullPointerException
	at org.eclipse.m2e.core.internal.embedder.ExtensionModule.configure(ExtensionModule.java:51)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:75)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 14 more

[Info  - 12:43:05 PM] Connection to server got closed. Server will restart.
[Error - 12:43:11 PM] Request textDocument/codeAction failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
[Error - 12:43:11 PM] Oct 2, 2017 12:43:08 PM An internal error occurred during: "Initialize Workspace".
null
java.lang.NullPointerException
	at org.eclipse.jdt.internal.launching.LaunchingPlugin.readInstallInfo(LaunchingPlugin.java:1008)
	at org.eclipse.jdt.internal.launching.LaunchingPlugin.timeStampChanged(LaunchingPlugin.java:980)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.populateVMForType(VMDefinitionsContainer.java:557)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.populateVMTypes(VMDefinitionsContainer.java:494)
	at org.eclipse.jdt.internal.launching.VMDefinitionsContainer.parseXMLIntoContainer(VMDefinitionsContainer.java:473)
	at org.eclipse.jdt.launching.JavaRuntime.addPersistedVMs(JavaRuntime.java:1499)
	at org.eclipse.jdt.launching.JavaRuntime.initializeVMs(JavaRuntime.java:2671)
	at org.eclipse.jdt.launching.JavaRuntime.getDefaultVMId(JavaRuntime.java:548)
	at org.eclipse.jdt.launching.JavaRuntime.getDefaultVMInstall(JavaRuntime.java:493)
	at org.eclipse.jdt.internal.launching.JREContainerInitializer.resolveVM(JREContainerInitializer.java:159)
	at org.eclipse.jdt.internal.launching.JREContainerInitializer.initialize(JREContainerInitializer.java:60)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3071)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2043)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3497)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2687)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2851)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1956)
	at org.eclipse.jdt.internal.core.DynamicProjectReferences.getDependentProjects(DynamicProjectReferences.java:34)
	at org.eclipse.core.internal.resources.ProjectDescription.computeDynamicReferencesForProject(ProjectDescription.java:950)
	at org.eclipse.core.internal.resources.ProjectDescription.getAllBuildConfigReferences(ProjectDescription.java:265)
	at org.eclipse.core.internal.resources.Project.internalGetReferencedBuildConfigs(Project.java:787)
	at org.eclipse.core.internal.resources.Workspace.computeActiveBuildConfigOrder(Workspace.java:720)
	at org.eclipse.core.internal.resources.Workspace.getBuildOrder(Workspace.java:1567)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:459)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.run(InitHandler.java:134)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 12:43:12 PM] Oct 2, 2017 12:43:08 PM An internal error occurred during: "Repository registry initialization".
Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: null
  at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821) (via modules: org.codehaus.plexus.DefaultPlexusContainer$BootModule -> org.eclipse.m2e.core.internal.embedder.ExtensionModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.newPlexusContainer(MavenImpl.java:1318)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer0(MavenImpl.java:1220)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getPlexusContainer(MavenImpl.java:1211)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lookup(MavenImpl.java:1270)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:470)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.getSettings(MavenImpl.java:439)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistry.updateRegistry(RepositoryRegistry.java:223)
	at org.eclipse.m2e.core.internal.repository.RepositoryRegistryUpdateJob.run(RepositoryRegistryUpdateJob.java:47)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NullPointerException
	at org.eclipse.m2e.core.internal.embedder.ExtensionModule.configure(ExtensionModule.java:51)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.codehaus.plexus.DefaultPlexusContainer$BootModule.configure(DefaultPlexusContainer.java:821)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:75)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 14 more

[Error - 12:43:14 PM] Connection to server got closed. Server will not be restarted.

**Comment by fbricon** [comment]
Wow I've seen my fair share of Eclipse errors, but never this one O_o
What does your java.home variable look like?

**Comment by devKepler** [comment]
@fbricon 
"java.home": "C:\\Program Files\\Java\\jdk1.8.0_144\\"

**Comment by fbricon** [comment]
Can you try to delete your [workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) and try again?

**Comment by devKepler** [comment]
@fbricon Sure, stand by

**Comment by devKepler** [comment]
@fbricon Sill receiving the same errors in output window

**Comment by fbricon** [comment]
@snjeza any idea?

**Comment by devKepler** [comment]
@fbricon Verified this is not a JDK configuration issue as I can compile and run my "main.java from the command-line.

**Comment by snjeza** [comment]
> Create a new projects directory and add the "main.java" file 

@devKepler did you create a new or open an existing directory?

**Comment by rgrunber** [comment]
Given how long ago this happened, I'm inclined to close for now. If anyone can still reproduce this feel free to re-open.
