### ISSUE TITLE
Can't properly import Quarkus project in vscodium - No delegateCommandHandler for java.project.checkImportStatus

### ISSUE THREAD

**Issue by kubealex** [redhat-developer/vscode-java#3196]
- Operating System: Any
- JDK version: Any
- Visual Studio Code version: vscodium 1.80.0
- Java extension version: 1.20.0

##### Steps To Reproduce
1. Open a quarkus app folder in vscodium
2. wait for project explorer to load the project

##### Current Result

2023-07-12 11:06:02.158 [error] Error: No delegateCommandHandler for java.project.checkImportStatus
	at /home/alerossi/.vscode-oss/extensions/redhat.java-1.20.0-linux-x64/dist/extension.js:2:1090335
	at ie (/home/alerossi/.vscode-oss/extensions/redhat.java-1.20.0-linux-x64/dist/extension.js:2:1090629)
	at /home/alerossi/.vscode-oss/extensions/redhat.java-1.20.0-linux-x64/dist/extension.js:2:1085413
	at Immediate.<anonymous> (/home/alerossi/.vscode-oss/extensions/redhat.java-1.20.0-linux-x64/dist/extension.js:2:1085433)
	at process.processImmediate (node:internal/timers:466:21) java.execute.workspaceCommand {"value":"redhat.java","_lower":"redhat.java"}

##### Expected Result

Project loads

**Comment by kubealex** [comment]
It seems that recent updates solved the issue.
