### ISSUE TITLE
Unable to build vscode-java locally

### ISSUE THREAD

**Issue by AmeyaLokre** [redhat-developer/vscode-java#3252]
[Unable to build vscode-java locally]

##### Environment
- Operating System: macOS Ventura 13.5
- JDK version: 17.0.4.1 (x86_64) "Oracle Corporation" - "Java SE 17.0.4.1"
- Visual Studio Code version: N/A
- Java extension version: 1.7.0

##### Steps To Reproduce
1. Followed the steps on [Contributing.md](https://github.com/redhat-developer/vscode-java/blob/v1.7.0/CONTRIBUTING.md) to clone vscode-java and eclipse.jdt.ls and following the file structure as mentioned on the Contributing page.
2. execute `npm run build-server` command

##### Current Result
```
11:18 $ npm run build-server

> java@1.7.0 build-server
> ./node_modules/.bin/gulp build_server

[11:18:39] Using gulpfile ~/workspace/vscode-java-build-package/vscode-java/gulpfile.js
[11:18:39] Starting 'build_server'...
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
[11:18:39] 'build_server' errored after 309 ms
[11:18:39] Error: Command failed: ./mvnw -Pserver-distro clean package -D eclipse.jdt.ls.skipGradleChecksums
    at checkExecSyncError (node:child_process:820:11)
    at Object.execSync (node:child_process:891:15)
    at /Users/alokre/workspace/vscode-java-build-package/vscode-java/gulpfile.js:129:5
    at taskWrapper (/Users/alokre/workspace/vscode-java-build-package/vscode-java/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:426:15)
    at runBound (node:domain:437:12)
    at asyncRunner (/Users/alokre/workspace/vscode-java-build-package/vscode-java/node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

##### Expected Result
Build the vsix image of vscode-java

**Comment by snjeza** [comment]
I can't reproduce the issue. 
@AmeyaLokre Could you try the following:
```
$ cd <your_jdtls_root>
$ git clone git@github.com:redhat-developer/vscode-java.git
$ git clone git@github.com:eclipse-jdtls/eclipse.jdt.ls.git
$ cd vscode-java
$ npm install
$ npm run build-server
```

**Comment by AmeyaLokre** [comment]
This is my directory structure:
```
13:42 $ ls
eclipse.jdt.ls	vscode-java
````

After retrying the steps you mentioned, still facing the same error.
```
13:40 $ npm run build-server

> java@1.7.0 build-server
> ./node_modules/.bin/gulp build_server

[13:41:02] Using gulpfile ~/workspace/1-vscode-java-build-package/vscode-java/gulpfile.js
[13:41:02] Starting 'build_server'...
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
[13:41:05] 'build_server' errored after 3 s
[13:41:05] Error: Command failed: ./mvnw -Pserver-distro clean package -Declipse.jdt.ls.skipGradleChecksums
    at checkExecSyncError (node:child_process:820:11)
    at Object.execSync (node:child_process:891:15)
    at /Users/alokre/workspace/1-vscode-java-build-package/vscode-java/gulpfile.js:129:5
    at taskWrapper (/Users/alokre/workspace/1-vscode-java-build-package/vscode-java/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:426:15)
    at runBound (node:domain:437:12)
    at asyncRunner (/Users/alokre/workspace/1-vscode-java-build-package/vscode-java/node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by AmeyaLokre** [comment]
maven version:
```
13:48 $ mvn -v
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /usr/local/Cellar/maven/3.9.4/libexec
Java version: 17.0.4.1, vendor: Oracle Corporation
```

node version:
```
13:48 $ node -v
v18.4.0
```

**Comment by AmeyaLokre** [comment]
For some reason, the command `mvnw() + ' -Pserver-distro clean package -Declipse.jdt.ls.skipGradleChecksums` is not detecting the file `./mvn` in the `eclipse.jdt.ls` repo.

**Comment by fbricon** [comment]
is `eclipse.jdt.ls/mvnw` executable? can you run a jdt.ls build manually?

**Comment by snjeza** [comment]
> ls
eclipse.jdt.ls	vscode-java

Could you check the following:

```
$ ls
eclipse.jdt.ls	vscode-java
$ cd vscode-java
$ ls ../eclipse.jdt.ls/mvnw
../eclipse.jdt.ls/mvnw
$ npm run build-server
```

**Comment by AmeyaLokre** [comment]
```
14:26 $ ../eclipse.jdt.ls/mvnw -version
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```
@snjeza , you are right. the command `mvnw -version` is throwing the same error as seen before.
is there any recommended documentation or readme i can follow to configure mvnw for eclipse ? Thanks!

**Comment by snjeza** [comment]
@AmeyaLokre you can try

```
$ cd vscode-java
$ rm ../eclipse.jdt.ls/.mvn/wrapper/maven-wrapper.jar
$ nmp run build-server
```

**Comment by AmeyaLokre** [comment]
@snjeza , getting the same error after running those steps.
the directory `eclipse.jdt.ls/.mvn/wrapper/` did not contain a `maven-wrapper.jar` file.

**Comment by snjeza** [comment]
> the directory eclipse.jdt.ls/.mvn/wrapper/ did not contain a maven-wrapper.jar file.

It should be downloaded after calling `npm run build-server`.

Could you try
```
$ cd vscode-java
$ cd ../eclipse.jdt.ls
$ rm .mvn/wrapper/maven-wrapper.jar
$ ./mvnw clean
```

**Comment by AmeyaLokre** [comment]
right, the `npm run build-server` command was generating the `maven-wrapper.jar`. I deleted it and then ran the `./mvnw clean`
```20:46 $ ./mvnw clean
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain```

**Comment by snjeza** [comment]
@AmeyaLokre could you try

```
$ cd vscode-java
$ cd ../eclipse.jdt.ls
$ rm .mvn/wrapper/maven-wrapper.jar
$ rm -rf ~/.m2/wrapper/dists/
$ ./mvnw clean
```

**Comment by AmeyaLokre** [comment]
unfortunately, the same error after performing those steps 😓 

more context: this is the first time I am building a project using maven wrapper (read up some blogs online to understand more about it). Are there any specific maven wrapper config steps needed to be able to build the image for vscode-java ?

**Comment by snjeza** [comment]
Could you run

```
$ cd vscode-java
$ cd ../eclipse.jdt.ls
$ ls -l .mvn/wrapper/maven-wrapper.jar
$ ls -l ~/.m2/wrapper/dists/apache-maven-3.9.3-bin/*/apache-maven-3.9.3/lib
```

**Comment by AmeyaLokre** [comment]
```$ ls -l .mvn/wrapper/maven-wrapper.jar
ls: .mvn/wrapper/maven-wrapper.jar: No such file or directory```

```$ ls -l ~/.m2/wrapper/dists/apache-maven-3.9.3-bin/*/apache-maven-3.9.3/lib
ls: /Users/alokre/.m2/wrapper/dists/apache-maven-3.9.3-bin/*/apache-maven-3.9.3/lib: No such file or directory```

This is what my `~/.m2` directory consists of as of now after reinstalling maven on my local setup.
```$ ls -l ~/.m2/
total 0
drwxr-xr-x  5 alokre  staff  160 Aug 23 10:43 repository```

**Comment by AmeyaLokre** [comment]
@snjeza . 
reconfigured my local machine and reinstalled maven alongwith maven wrapper.

Had to run the following steps in `eclipse.jdt.ls` repo to get the environment configured properly.
```
mvn clean
mvn install
mvn wrapper:wrapper
```
And then running `./mvnw clean` didnt throw the error: `Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain`.

Running `npm run build-server` then succeeded when running it from `vscode-java` repo.

**Comment by AmeyaLokre** [comment]
User error: incorrectly configured maven wrapper
