### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'text')

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#3276]
rejected promise not handled within 1 second: TypeError: Cannot set properties of undefined (setting 'text')
extensionHostProcess.js:108
stack trace: TypeError: Cannot set properties of undefined (setting 'text')
    at Object.update (c:\Work\Code\vscode-java\src\languageStatusItemFactory.ts:146:12)
    at RuntimeStatusBarProvider.<anonymous> (c:\Work\Code\vscode-java\src\runtimeStatusBarProvider.ts:220:33)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Work\Code\vscode-java\dist\extension.js:100929:58)

**Comment by rgrunber** [comment]
I ran into this as well but am having difficulty reproducing now. I noticed it happening on very new file I opened, and I was in the settings menu before that.

```
extensionHostProcess.js:131
rejected promise not handled within 1 second: TypeError: Cannot set properties of undefined (setting 'text')
extensionHostProcess.js:131
stack trace: TypeError: Cannot set properties of undefined (setting 'text')
    at Object.update (/home/rgrunber/git/vscode-java/dist/extension.js:98471:19)
    at RuntimeStatusBarProvider.<anonymous> (/home/rgrunber/git/vscode-java/dist/extension.js:101261:80)
    at Generator.next (<anonymous>)
    at fulfilled (/home/rgrunber/git/vscode-java/dist/extension.js:101064:58)
extensionHostProcess.js:131
rejected promise not handled within 1 second: TypeError: Cannot set properties of undefined (setting 'text')
extensionHostProcess.js:131
stack trace: TypeError: Cannot set properties of undefined (setting 'text')
    at Object.update (/home/rgrunber/git/vscode-java/dist/extension.js:98471:19)
    at RuntimeStatusBarProvider.<anonymous> (/home/rgrunber/git/vscode-java/dist/extension.js:101261:80)
    at Generator.next (<anonymous>)
    at fulfilled (/home/rgrunber/git/vscode-java/dist/extension.js:101064:58)
```
