### ISSUE TITLE
java.lang.String is not an interface

### ISSUE THREAD

**Issue by pablocarle** [redhat-developer/vscode-java#3342]
##### Environment
- Operating System: MacOS Ventura 13.6
- JDK version: 20- oracle
- Visual Studio Code version: 
```
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0
```

- Java extension version: 1.23.0

##### Current Result

```
!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-16 17:07:49.855
!MESSAGE Non-Static Commands: [java.maven.initializeSearcher, java.maven.searchArtifact, java.maven.addDependency, java.maven.controlContext]

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-16 17:07:49.882
!MESSAGE RepositoryRegistryUpdateJob finished 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-16 17:07:49.905
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-10-16 17:08:10.331
!MESSAGE Initialization failed 
!STACK 0
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: java.lang.IllegalArgumentException: java.lang.String is not an interface
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.microsoft.gradle.bs.importer.GradleBuildServerProjectImporter.importToWorkspace(GradleBuildServerProjectImporter.java:105)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:152)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:114)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:260)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: java.lang.IllegalArgumentException: java.lang.String is not an interface
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-16 17:08:10.378
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-16 17:08:10.384
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-16 17:08:10.387
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-16 17:08:10.767
!MESSAGE >> build jobs finished
```

##### Additional Informations
I've tried going back to 1.22.1 and different JVMs (Semeru / Oracle) but still the same error.

**Comment by snjeza** [comment]
@pablocarle Could you try to disable or remove the `Gradle for Java` extension?

**Comment by pablocarle** [comment]
@snjeza Just tried it and indeed it works with `Gradle for Java` disabled.
Does this mean these two are incompatible?
Thank you.

**Comment by snjeza** [comment]
@pablocarle You can create a new issue at https://github.com/microsoft/vscode-gradle/issues
