### ISSUE TITLE
Completion on constructor is broken

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#3358]
![image](https://github.com/redhat-developer/vscode-java/assets/14052197/97414491-fc28-45a3-a0a3-4405c629dd7e)

See the screenshot above, it suggests very few results for constructor completion. It's supposed to suggest `ArrayList` in the list.
BTW, I used the latest 1.24 pre-release version on Windows.

**Comment by snjeza** [comment]
@testforstephen I can't reproduce the issue.
![wincomp](https://github.com/redhat-developer/vscode-java/assets/388609/79b69930-7398-4685-ade5-6323d2a4af95)

Could you attach your project?

**Comment by testforstephen** [comment]
It can be reproduced when changing the setting `java.completion.guessMethodArguments` to `off`.

**Comment by testforstephen** [comment]
```
[Error - 1:30:38 PM] Oct 25, 2023, 1:30:38 PM Failed to convert completion proposal to completion item
Cannot invoke "String.isEmpty()" because "<parameter1>" is null
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "<parameter1>" is null
	at java.base/java.lang.String.concat(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.toCompletionItem(CompletionProposalRequestor.java:430)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:292)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:258)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:291)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:121)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.completion(JDTLanguageServer.java:633)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

This should be a regression introduced by https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2874
