### ISSUE TITLE
Not Starting Up Properly Probably Due to Unix Domain Socket Length Limitations

### ISSUE THREAD

**Issue by tthornton3-chwy** [redhat-developer/vscode-java#3371]
Good evening! I and a couple other people on the team can say now that after upgrading to the latest VSCode Insiders / vscode-java standard/preview versions, the extension is not starting up successfully.
The "spinning" wheel keeps spinning indefinitely, and if you go to "Show Build Status" you get an absolutely empty window with no logs/status, at any point.
There are no interesting errors in any of the typical "Output" windows, for anything java. However, a `Java: Open all Log Files` gives at least this:

```
!SESSION 2023-10-30 16:02:54.536 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
Framework arguments:  --pipe=/var/folders/c4/f8v01p_s2sn9_hrx6y18dlxr0000gq/T/vscode-b4e4949e2fde772119c33ebd3ad375f0e8b742abf2.sock
Command-line arguments:  -data /Users/[redacted]/Library/Application Support/Code - Insiders/User/workspaceStorage/e0a072670fac3ceed984d299690f5fdc/redhat.java/jdt_ws --pipe=/var/folders/c4/f8v01p_s2sn9_hrx6y18dlxr0000gq/T/vscode-b4e4949e2fde772119c33ebd3ad375f0e8b742abf2.sock

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-10-30 16:02:56.397
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-10-30 16:02:56.474
!MESSAGE Unix domain path too long
!STACK 0
java.net.SocketException: Unix domain path too long
	at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:148)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(UnixDomainSockets.java:144)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:851)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$PipeStreamProvider.initializeNamedPipe(ConnectionStreamFactory.java:117)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$PipeStreamProvider.<init>(ConnectionStreamFactory.java:89)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.createProvider(ConnectionStreamFactory.java:269)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.getSelectedStream(ConnectionStreamFactory.java:257)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.getInputStream(ConnectionStreamFactory.java:275)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startConnection(JavaLanguageServerPlugin.java:344)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startLanguageServer(JavaLanguageServerPlugin.java:441)
	at org.eclipse.jdt.ls.core.internal.LanguageServerApplication.start(LanguageServerApplication.java:54)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```

This makes me think like maybe something was changed where the socket lives, and when running Insiders the path just gets too big / longer than 100~ characters?
This would explain why i'm not seeing any log/error messages in "Show Build Status", since we aren't able to actually connect to the socket!

Nothing was changed between 1.23.0 and 1.24.0 over here that would make any sense, so I'm wondering if it's a VS Code Insiders issue with its temp path logic?

##### Environment
- Operating System: MacOS 13.5 on Silicon
- JDK version: My `java.import.gradle.java.home` and `java.jdt.ls.java.home` are at: `17.0.3-tem` but getting rid of these doesn't make this go away/do anything different.
- Visual Studio Code version: `1.84.0-insider` (No updates at the time of posting)
- Java extension version: `v1.24.0` and the preview one too!

##### Steps To Reproduce
1. Have a Mac on Silicon
2. Have any Java project open in VS Code Insiders w/ latest Language Server extension
3. See the spinny icon spin away, and see the log above!

##### Current Result
Plugin does not initialize properly, with the error above, and the spinning icon continue to spin indefinitely.

##### Expected Result
App initalizes properly.

**Comment by snjeza** [comment]
The related issue - https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2932

**Comment by tthornton3-chwy** [comment]
Noice! If this is a duplicate I'm happy to close, or if it'll be good to capture it here i'm happy it staying too. Either way i've subscribed to the above, and I will happily test if there's a possible fix! 

Btw:  `try setting "java.transport":"stdio" in your settings.` did at least semi-temporarily fix things for me, until we can try again with the new transport method!

**Comment by balthild** [comment]
This problem presents again in version `1.40.0`.

<details>
<summary>Log</summary>

```
!SESSION 2025-03-19 16:32:46.825 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=zh_US_#Hans
Framework arguments:  --pipe=/private/var/folders/h8/9n_pvqp529x5rqpd5wlf1xy00000gn/T/nix-shell.9H0maj/lsp-4195cf4365baf01e2d34.sock
Command-line arguments:  -data /Users/balthild/Library/Application Support/Code/User/workspaceStorage/b06fd457b842f38130c6a6d3731b3c8c/redhat.java/jdt_ws --pipe=/private/var/folders/h8/9n_pvqp529x5rqpd5wlf1xy00000gn/T/nix-shell.9H0maj/lsp-4195cf4365baf01e2d34.sock

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-19 16:32:47.649
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-19 16:32:47.672
!MESSAGE Started org.eclipse.buildship.core 16ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-19 16:32:47.672
!MESSAGE Started org.eclipse.m2e.core 0ms

!ENTRY org.eclipse.jdt.ls.core 4 0 2025-03-19 16:32:47.676
!MESSAGE Unix domain path too long
!STACK 0
java.net.SocketException: Unix domain path too long
	at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(Unknown Source)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$PipeStreamProvider.initializeNamedPipe(ConnectionStreamFactory.java:117)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$PipeStreamProvider.<init>(ConnectionStreamFactory.java:89)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.createProvider(ConnectionStreamFactory.java:269)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.getSelectedStream(ConnectionStreamFactory.java:257)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.getInputStream(ConnectionStreamFactory.java:275)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startConnection(JavaLanguageServerPlugin.java:396)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startLanguageServer(JavaLanguageServerPlugin.java:494)
	at org.eclipse.jdt.ls.core.internal.LanguageServerApplication.start(LanguageServerApplication.java:47)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:219)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:713)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:647)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1588)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1560)

!ENTRY org.eclipse.jdt.core.javac 2 0 2025-03-19 16:32:47.681
!MESSAGE Could not resolve module: org.eclipse.jdt.core.javac [52]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=23))"


!ENTRY org.eclipse.equinox.launcher.cocoa.macosx.x86_64 2 0 2025-03-19 16:32:47.681
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.cocoa.macosx.x86_64 [41]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=cocoa) (osgi.os=macosx) (osgi.arch=x86_64) )"
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=cocoa) (osgi.os=macosx) (osgi.arch=x86_64) )"


!ENTRY org.eclipse.osgi 4 0 2025-03-19 16:32:47.682
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Input stream must be configured.
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:310)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createIoLauncher(Launcher.java:125)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createLauncher(Launcher.java:101)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startConnection(JavaLanguageServerPlugin.java:404)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startLanguageServer(JavaLanguageServerPlugin.java:494)
	at org.eclipse.jdt.ls.core.internal.LanguageServerApplication.start(LanguageServerApplication.java:47)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:219)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:713)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:647)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1588)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1560)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-19 16:32:47.686
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:

!ENTRY org.eclipse.core.jobs 4 2 2025-03-19 16:32:48.033
!MESSAGE An internal error occurred during: "Initialize After Load".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.runtime.content.IContentTypeManager.getContentType(String)" because the return value of "org.eclipse.core.runtime.Platform.getContentTypeManager()" is null
	at org.eclipse.jdt.internal.core.util.Util.getJavaLikeExtensions(Util.java:844)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.hasJavaLikeNamesChanged(IndexManager.java:627)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.getIndexes(IndexManager.java:514)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.getIndexes(PatternSearchJob.java:196)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.ensureReadyToRun(PatternSearchJob.java:99)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:268)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllTypeNames(BasicSearchEngine.java:1937)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllTypeNames(BasicSearchEngine.java:1765)
	at org.eclipse.jdt.core.search.SearchEngine.searchAllTypeNames(SearchEngine.java:1107)
	at org.eclipse.jdt.core.JavaCore.updateLegacyIndex(JavaCore.java:4885)
	at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4832)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin$1.run(JavaLanguageServerPlugin.java:201)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SESSION 2025-03-20 01:10:40.333 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=zh_US_#Hans
Framework arguments:  --pipe=/private/var/folders/h8/9n_pvqp529x5rqpd5wlf1xy00000gn/T/nix-shell.p6Gusg/lsp-75591489a67ad1e382f0.sock
Command-line arguments:  -data /Users/balthild/Library/Application Support/Code/User/workspaceStorage/b06fd457b842f38130c6a6d3731b3c8c/redhat.java/jdt_ws --pipe=/private/var/folders/h8/9n_pvqp529x5rqpd5wlf1xy00000gn/T/nix-shell.p6Gusg/lsp-75591489a67ad1e382f0.sock

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-20 01:10:41.441
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-20 01:10:41.460
!MESSAGE Started org.eclipse.buildship.core 13ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-20 01:10:41.460
!MESSAGE Started org.eclipse.m2e.core 0ms

!ENTRY org.eclipse.jdt.ls.core 4 0 2025-03-20 01:10:41.464
!MESSAGE Unix domain path too long
!STACK 0
java.net.SocketException: Unix domain path too long
	at java.base/sun.nio.ch.UnixDomainSockets.connect0(Native Method)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(Unknown Source)
	at java.base/sun.nio.ch.UnixDomainSockets.connect(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$PipeStreamProvider.initializeNamedPipe(ConnectionStreamFactory.java:117)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory$PipeStreamProvider.<init>(ConnectionStreamFactory.java:89)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.createProvider(ConnectionStreamFactory.java:269)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.getSelectedStream(ConnectionStreamFactory.java:257)
	at org.eclipse.jdt.ls.core.internal.ConnectionStreamFactory.getInputStream(ConnectionStreamFactory.java:275)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startConnection(JavaLanguageServerPlugin.java:396)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startLanguageServer(JavaLanguageServerPlugin.java:494)
	at org.eclipse.jdt.ls.core.internal.LanguageServerApplication.start(LanguageServerApplication.java:47)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)

!ENTRY org.eclipse.equinox.launcher.cocoa.macosx.x86_64 2 0 2025-03-20 01:10:41.468
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.cocoa.macosx.x86_64 [41]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=cocoa) (osgi.os=macosx) (osgi.arch=x86_64) )"
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=cocoa) (osgi.os=macosx) (osgi.arch=x86_64) )"


!ENTRY org.eclipse.jdt.core.javac 2 0 2025-03-20 01:10:41.468
!MESSAGE Could not resolve module: org.eclipse.jdt.core.javac [52]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=23))"


!ENTRY org.eclipse.osgi 4 0 2025-03-20 01:10:41.469
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Input stream must be configured.
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:310)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createIoLauncher(Launcher.java:125)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createLauncher(Launcher.java:101)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startConnection(JavaLanguageServerPlugin.java:404)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.startLanguageServer(JavaLanguageServerPlugin.java:494)
	at org.eclipse.jdt.ls.core.internal.LanguageServerApplication.start(LanguageServerApplication.java:47)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-03-20 01:10:41.471
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:

!ENTRY org.eclipse.core.jobs 4 2 2025-03-20 01:10:41.755
!MESSAGE An internal error occurred during: "Initialize After Load".
!STACK 0
java.lang.IllegalStateException: Workspace is already closed or not ready yet. Consider tracking the org.eclipse.core.resources.IWorkspace service (using your favorite technique, e.g. Declarative Services, ServiceTracker, Blueprint, ...) instead of calling the static method here to prevent such issues!
	at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:518)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3040)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2145)
	at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4752)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin$1.run(JavaLanguageServerPlugin.java:201)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
<details>

**Comment by rgrunber** [comment]
The path is `/private/var/folders/h8/9n_pvqp529x5rqpd5wlf1xy00000gn/T/nix-shell.9H0maj/lsp-4195cf4365baf01e2d34.sock`. That is 103 characters.

The code ultimately calls https://github.com/openjdk/jdk21/blob/master/src/java.base/unix/native/libnio/ch/UnixDomainSockets.c#L85-L86 -> https://github.com/openjdk/jdk21/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/unix/native/libnio/ch/nio_util.h#L54-L56 . I believe `sun_path` is held with `sys/un.h`. According to https://developer.apple.com/documentation/kernel/sockaddr_un/1541426-sun_path , the value is 104, so that makes `MAX_UNIX_DOMAIN_PATH_LEN` have a value of 102.

Yes, switching to `stdio` is a workaround. Technically there is code to detect this error and auto-switch to `stdio` but I'm guessing the [safe limit on Darwin is hard-coded to 103](https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/node/main.ts#L173) and so your path doesn't trigger it (the limit should be 102).

Does your system have `XDG_RUNTIME_DIR` environment variable point to `/private/var/folders/...` ? Would you be able to shorten that environment variable ?

**Comment by balthild** [comment]
There's no `XDG_RUNTIME_DIR` defined. The java environment is managed by `nix-direnv` so I think I cannot shorten it (actually I don't know how it is implemented and why the sock is placed there...)
