### ISSUE TITLE
High CPU usage and memory consumption even if doing nothing 

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#3387]
_originally reported by @wkia at https://github.com/microsoft/vscode-java-debug/issues/1408_

> I'm working with OpenJDK 11/17/21/... source code on Windows 11, WSL, and Linux.
> 
> "Debugger for Java" is v0.55.0. This issue is related to [#1330 (comment)](https://github.com/microsoft/vscode-java-debug/issues/1330#issuecomment-1803271792), but I tried to reproduce it from scratch.
> 
> The example from WSL, just open VSCode with my workspace and see - it consumes CPU and memory for a long time:
> 
> ```
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
>  6174 user      20  0   37.9g  14.2g   3.5m  S 832.9  91.0  11:57.35 /home/user/.vscode-server/extensions/redhat.java-1.24.0-linux-x64/jre/17.0.8.1-linux-x86_64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.ecli+
> ```
> 
> And then, when memory is about to out, it looks like it drops the process and starts again - with a small amount of memory and high CPU usage, increasing memory consumption every sec.
> 
> ##### Steps To Reproduce (on Win11/WSL)
> 1. Install VSCode on Win11, and install "Remote Development" extension pack
> 2. Open WSL terminal, and run the following commands:
> 3. `git clone https://github.com/openjdk/jdk.git openjdk`
> 4. `cp MyApp.java openjdk` (see below for MyApp.java source code)
> 5. `cd openjdk`
> 6. `code . &`
> 7. In VSCode, Install "Debugger for Java", "Language support for Java" to remote WSL.
> 8. In VSCode, open `~/openjdk/MyApp.java` file in editor.
> 9. In WSL terminal, run `top -c` and see `.vscode-server/extensions/redhat.java-1.24.0-linux-x64/jre/17.0.8.1-linux-x86_64/bin/java` consuming CPU and memory. (in my case it consumes all CPU cores)
> 10. Wait patiently, and still click 'Increase memory' and 'Reload window' in VSCode if it asks, continue seeing RedHat java process in `top -c` list consuming CPU and RAM.
> 11. You could stop here, but you also can try to reach the maximum memory amount in WSL allocated for VSCode by clicking 'Increase memory'/'Reload window', and possibly you will see behaviour described in [Cannot debug JDK17 itself with "Debugger for Java" v0.49.1 #1330 (comment)](https://github.com/microsoft/vscode-java-debug/issues/1330#issuecomment-1803271792)
> 12. (Optional) You could also try to close and open VSCode again, instead of 'Reload'ing window. It seems it helps to reproduce it faster.
> 
> ##### MyApp.java
> ```
> public class MyApp {
>     public static void main(String[] args) {
>         System.out.println("Hello world!");
>         System.out.println("Sleeping...");
>         Thread.sleep(20000);
>         System.out.println("Finished");
>     }
> }
> ```

**Comment by wkia** [comment]
I tried to dump the "redhat.java" process consumed 14GB RAM, and open the dump with visualvm. See screentshots here https://github.com/microsoft/vscode-java-debug/issues/1330#issuecomment-1803335715

**Comment by zhiqiang-hhhh** [comment]
Meet same problem

**Comment by johnmccutchan** [comment]
This is extremely annoying and happens daily for me.

**Comment by tonyganchev** [comment]
Similar problems. on leaving my WSL dormant for the night I find it in the morning with 100% memory usage (24 GiB) and 40+ RedHat java agents running.

**Comment by archenroot** [comment]
I disabled and reenabled the extension and it used initially high-cpu, but after few minutes it went down.

**Comment by witlingw** [comment]
Same here, and we are using this extension at work and several of my colleagues are also blocked by this daily.

**Comment by wkia** [comment]
I'm still able to reproduce the issue with ".vscode-server/extensions/**redhat.java-1.28.1-linux-x64**/jre/17.0.10-linux-x86_64" on JDK11 sources:

`  PID USER   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND`
` 5310 user   20   0   22.3g  14.6g  12.0m S  1390  93.4  28:44.33 /home/user/.vscode-server/extensions/redhat.java-1.28.1-linux-x64/jre/17.0.10-linux-x86_64/bin/jav+`

However I noticed that now the issue occurs when I _put my test into the root folder of downloaded JDK sources_.

**Comment by wkia** [comment]
The issue still occurs with JDK17 sources.

**Comment by wkia** [comment]
I'm still facing the issue with `redhat.java-1.30.0` on VSCode 1.89

**Comment by wkia** [comment]
Still there with VSCode 1.89.1 and redhat.java-1.31.0-linux-x64 on JDK17 sources.

**Comment by maphdze** [comment]
Still here without Java extensions. Only writing latex with two vscode window open then the cpu will go to 60%-80%.

**Comment by johnmccutchan** [comment]
This extension appears to be abandoned. I've deleted it and use Android Studio for working on Java code.

**Comment by snjeza** [comment]
I can reproduce the issue when setting
```
"java.compile.nullAnalysis.mode": "automatic"
```
The imported projects contain `javax.annotation.Nonnull`, but don't contain `javax.annotation.Nullable`.
JDT null analysis requires both of the classes to be included in the projects. Otherwise, it will throw an AIOOB exception and rebuild the workspace.
Java LS enables null analysis even when any of these classes is present. I'm preparing a patch.

@wkia @maphdze @johnmccutchan @witlingw @archenroot @tonyganchev @zhiqiang-hhhh  could you try to set 
```
"java.compile.nullAnalysis.mode": "disabled"
```
Please check also <openjdk|jdk11u-dev>/.vscode/settings.json

**Comment by rgrunber** [comment]
Definitely related to null analysis. I basically see the following error on repeat (using just the instructions at https://github.com/redhat-developer/vscode-java/issues/3387#issuecomment-1963708894 ). It's not extremely consistent, as there's a few instances where it it didn't enter a loop but there's definitely a problem.

```
!ENTRY org.eclipse.core.resources 4 75 2024-06-18 15:23:18.806
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.jdt.core 4 75 2024-06-18 15:23:18.806
!MESSAGE Errors running builder 'Java Builder' on project 'Settings'.
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1829)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.initializeUsesNullTypeAnnotation(LookupEnvironment.java:1684)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.usesNullTypeAnnotations(LookupEnvironment.java:1659)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.scanFieldForNullAnnotation(BinaryTypeBinding.java:2028)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:645)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1080)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1061)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:307)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:368)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:624)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findSingleImport(CompilationUnitScope.java:696)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.resolveSingleImport(CompilationUnitScope.java:953)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3551)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3274)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:60)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:525)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:637)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:633)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveSuperType(TypeReference.java:605)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.findSupertype(ClassScope.java:1644)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectSuperclass(ClassScope.java:1176)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1451)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:409)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment$CompleteTypeBindingsSteps.perform(LookupEnvironment.java:185)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:558)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:880)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:393)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:447)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:425)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:410)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:211)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:341)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:286)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:198)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Setting `java.compile.nullAnalysis.mode` to `disabled` is one way to work around the issue.

**Comment by snjeza** [comment]
>  It's not extremely consistent...

You can consistently reproduce it in the following way:

- set `"java.compile.nullAnalysis.mode": "automatic"`
- import the openjdk project
- Open the command palette (F1)
- select `Java: Force Java Compilation`
- select `Full`

**Comment by wkia** [comment]
Using version 1.32 now, I uninstalled the extensions, and install it again, the issue seems still there for me.

Also tried this setting in my workspace:
`"java.compile.nullAnalysis.mode": "disabled"`
it doesn't help.

Still consumes a lot of memory (growing up to OOM error), and CPU ~1400%.

**Comment by snjeza** [comment]
I can't reproduce the issue. `"java.compile.nullAnalysis.mode": "disabled"` isn't necessary anymore.
Could you, please, try the following:
- [Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)
- attach your [server log](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server)

**Comment by wkia** [comment]
I've cleaned workspace directory in both Windows and WSL. Removed ".vscode*" folders from $HOME and from the project directory.
The issue still occurs. Logs attached,
[vscode.log](https://github.com/user-attachments/files/16111681/vscode.log)

@snjeza Did you try to reproduce with the steps I provided at the very beginning? 
See the description of the issue above, **step 8: "In VSCode, open ~/openjdk/MyApp.java file in editor."**
The issue starts occuring on the step 8, and it is continuing until I delete MyApp.java, and reload VSCode window.
You can even skip installing "Debugger for Java", install only "Language support for Java".

**Comment by snjeza** [comment]
> Did you try to reproduce with the steps I provided at the very beginning?

Yes, I did but still can't reproduce the issue.
Could you try to add 
```
"java.jdt.ls.vmarg": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:disable",
```
Could you reproduce the issue outside of WSL?

**Comment by wkia** [comment]
> Could you reproduce the issue outside of WSL?

Yes, I'm able to reproduce it on Windows 11:

![image](https://github.com/redhat-developer/vscode-java/assets/17044077/3768fa07-a5fb-4691-9a9a-6c4b41597d2c)
![image](https://github.com/redhat-developer/vscode-java/assets/17044077/3bcff6ae-ddd4-47dd-9b2b-05f5f285d7b2)
![image](https://github.com/redhat-developer/vscode-java/assets/17044077/c6441a1c-dd67-4896-b863-aafb17fba3f7)

All of the tries above ended up with OOM error:

![image](https://github.com/redhat-developer/vscode-java/assets/17044077/2f46c8c6-0e0a-4125-9d06-83a465a860f1)

Every time i clicked "Increase...", the issue occured again and again, so now my current workspace settings is:
```
.vscode/settings.json
{
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx8G -Xms100m -Xlog:disable"
}
```

**Comment by wkia** [comment]
For the following settings, the try ended up with OOM error on Windows 11:
```
{
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx4G -Xms100m -Xlog:disable",
    "java.trace.server": "verbose"
}
```
The logs: 
[vscode-win.log](https://github.com/user-attachments/files/16127047/vscode-win.log)

**Comment by snjeza** [comment]
@wkia Could you attach your settings.json?

**Comment by wkia** [comment]
@snjeza 
User settings: 
[settings.json](https://github.com/user-attachments/files/16202539/settings.json)
Workspace setting:
[settings.json](https://github.com/user-attachments/files/16202541/settings.json)

**Comment by snjeza** [comment]
@wkia Could you try the following:

- set `"java.import.maven.enabled": true,`
- exit VS Code
- delete C:\Users\user\AppData\Roaming\Code\User\workspaceStorage -[[Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)]( https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)
- start VS Code

**Comment by snjeza** [comment]
> Workspace setting:
[settings.json](https://github.com/user-attachments/files/16202541/settings.json)

@wkia You can also try to add
```
"java.import.maven.enabled": false,
"java.project.sourcePaths": [
        "src"
    ]
```
and [Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)

**Comment by wkia** [comment]
@snjeza Here are the results:

- [`"java.import.maven.enabled": true`](https://github.com/redhat-developer/vscode-java/issues/3387#issuecomment-2226941933)  - issue is **NOT** reproducible
- [`"java.import.maven.enabled": false` + `"java.project.sourcePaths"`](https://github.com/redhat-developer/vscode-java/issues/3387#issuecomment-2226994017) - issue is **NOT** reproducible

Double checked **without the changes above** - issue **is** still reproducible.
Also, just in case checked, `"java.import.maven.enabled": false` only, without adding  `"java.project.sourcePaths"` - issue **is** reproducible.

Cleaned workspace before each test case.

**Comment by wkia** [comment]
@snjeza 
The issue is still reproducible with "**test**" folder rather than "**src**":
```
    "java.import.maven.enabled": false,
    "java.project.sourcePaths": [
            "test"
        ]

```

**Comment by snjeza** [comment]
@wkia Could you try the following:

```
$ rm -rf ~/.vscode-server/data/User/workspaceStorage # clean the workspace directory
$ wsl
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
$ cd <openjdk>
$ sudo apt-get install autoconf make zip
$ bash configure
$ make eclipse-java-env
$ code .
```
See [IDE support in the JDK](https://github.com/openjdk/jdk/blob/master/doc/ide.md)

**Comment by wkia** [comment]
@snjeza It seems helping. Thanks!
