### ISSUE TITLE
Language Support for Java client: couldn't create connection to server.

### ISSUE THREAD

**Issue by Hogenbirk** [redhat-developer/vscode-java#3391]
macOS : Sonoma 14.1.1
VSCode : Version: 1.84.2 (Universal)
JDK : jdk-21
Language Support for Java(TM) by Red Hat : v1.24.0

copilot directed me to check java.home settings in both VSCode, ~/. zshrc , pom file, but paths are all set correctly. 

##### Current Result
When starting VSCode, this popup message appears, Language Support for Java client: couldn't create connection to server.
This is found in output upon running  : [Error - 14:02:00] Language Support for Java client: couldn't create connection to server.
Error: spawn Unknown system error -8
In JSON i increased from 1G to 2G "java.jdt.ls.vmargs": "-Xmx2G"
Note I also configured   "java.jdt.ls.java.home": "/Users/MyName/Desktop/jdk-21"

Could you please help here? Many thanks for looking at this.

**Comment by rgrunber** [comment]
Would you be able to set `java.trace.server` to `verbose` and re-launch ? Once it fails, go to the command palette and run `Java: Open All Log Files` . I'd expect the `.out-jdt.ls-${date}.log` & `.err-jdt-ls-${date}.log` to be empty but it would be interesting to know if there's any errors in the `.log` file and what is in the `client.log.${date}` file.

**Comment by AnnalisaBX** [comment]
Hi,
I have the same problem, I have tried to check the .json configuration file but it correctly detects my JDK installation, none of the solutions that I found works.

Environment
Operating System: Sonoma 14.1.2 (M1)
JDK version: 17.0.9 2023-10-17 LTS
Visual Studio Code version: 1.85.1
Java extension version: 1.25.1

This error doesn't let me compile anything.
Thanks!

**Comment by roadking** [comment]
I am having the same issue
OS:  Windows_NT x64 10.0.0.22621
JDK version: OpenJDK 64-Bit Server VM Corretto-11.0.12.7.1 (build 11.0.12+7-LTS, mixed mode)
Visual Studio Code version: 1.85.1
Java extension version: ALL

I have un-installed and reinstalled the plugin and tried several versions, all with the same error:

Language Support for Java (Syntax Server) client: couldn't create connection to server.

at Object.spawn (node:child_process:817:9)
	at c:\Users\liduzui\.vscode\extensions\redhat.java-1.25.1-win32-x64\dist\extension.js:2:1332062
	at async c.createConnection (c:\Users\liduzui\.vscode\extensions\redhat.java-1.25.1-win32-x64\dist\extension.js:2:1164690)
	at async c.start (c:\Users\liduzui\.vscode\extensions\redhat.java-1.25.1-win32-x64\dist\extension.js:2:1155207)

**Comment by roadking** [comment]
Changing the default JDK for VSCode to v17 solved the issue. I had tried that earlier, but it wasn't working, likely due to not escaping "\" in the path to the jdk.

**Comment by PRANJALJAG99** [comment]
I am also facing same problem plz give solutions why it is happening @Language Support for Java client: couldn't create connection to server.

**Comment by rgrunber** [comment]
Would you be able to perform any of the steps listed in https://github.com/redhat-developer/vscode-java/issues/3391#issuecomment-1819930237 ? Having some logs would definitely be needed to narrow down how/why this is happening.

**Comment by robinwyss** [comment]
I ran into the same issue. In my case it seems to pick up the wrong jdk, it uses `/Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home` even though I have `configured java.jdt.js.java.home` to /`Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home` any ideas why it might pick up the wrong jdk (I tried both user and workspace settings). 

here is the log output

```
!SESSION 2025-02-04 14:58:16.103 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_CH
Framework arguments:  --pipe=/private/var/folders/1j/dxx1p1k95037sby17l0_9p0r65qqm6/T/lsp-e0494efdfgdfgdfgdfg5cfaa3dca913ac41.sock
Command-line arguments:  -data /Users/XXXXX/Library/Application Support/Code/User/workspaceStorage/b16176dfgdfgdfg74ad91967/redhat.java/jdt_ws --pipe=/private/var/folders/1j/dxx1p1k95037sby17l0_9p0r65qqm6/T/lsp-e0494efdfgdfgdfgdfg5cfaa3dca913ac41.sock

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 14:58:17.376
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 14:58:17.413
!MESSAGE Started org.eclipse.buildship.core 25ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 14:58:17.417
!MESSAGE Started org.eclipse.m2e.core 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 14:58:17.485
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 14:58:17.504
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 14:58:17.509
!MESSAGE Initializing Java Language Server 1.44.0.202501220510

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 14:58:17.899
!MESSAGE ProjectRegistryRefreshJob finished 469ms

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.180
!MESSAGE Process returned with error code "137".
Command line arguments: /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home/bin/java -Xmx16m -classpath /Users/XXXXX/Library/Application Support/Code/User/globalStorage/redhat.java/1.39.0/config_mac/org.eclipse.osgi/57/0/.cp/lib/launchingsupport.jar org.eclipse.jdt.internal.launching.support.LibraryDetector
Output: Standard output:

Standard error:

!STACK 0
java.lang.IllegalStateException: Process returned with error code "137".
Command line arguments: /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home/bin/java -Xmx16m -classpath /Users/XXXXX/Library/Application Support/Code/User/globalStorage/redhat.java/1.39.0/config_mac/org.eclipse.osgi/57/0/.cp/lib/launchingsupport.jar org.eclipse.jdt.internal.launching.support.LibraryDetector
Output: Standard output:

Standard error:

	at org.eclipse.jdt.internal.launching.StandardVMType.checkProcessResult(StandardVMType.java:895)
	at org.eclipse.jdt.internal.launching.StandardVMType.generateLibraryInfo(StandardVMType.java:707)
	at org.eclipse.jdt.internal.launching.StandardVMType.getLibraryInfo(StandardVMType.java:224)
	at org.eclipse.jdt.internal.launching.StandardVMType.getVMVersion(StandardVMType.java:265)
	at org.eclipse.jdt.internal.launching.macosx.MacOSXVMInstallType.getVMVersion(MacOSXVMInstallType.java:432)
	at org.eclipse.jdt.internal.launching.macosx.MacOSXVMInstall.getJavaVersion(MacOSXVMInstall.java:53)
	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironmentAnalyzer.analyze(ExecutionEnvironmentAnalyzer.java:130)
	at org.eclipse.jdt.internal.launching.environments.Analyzer.analyze(Analyzer.java:43)
	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.analyze(EnvironmentsManager.java:430)
	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.initializeCompatibilities(EnvironmentsManager.java:337)
	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.init(ExecutionEnvironment.java:185)
	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.getDefaultVM(ExecutionEnvironment.java:227)
	at org.eclipse.jdt.ls.core.internal.JVMConfigurator.setDefaultEnvironmentVM(JVMConfigurator.java:235)
	at org.eclipse.jdt.ls.core.internal.JVMConfigurator.configureJVMs(JVMConfigurator.java:190)
	at org.eclipse.jdt.ls.core.internal.JVMConfigurator.configureJVMs(JVMConfigurator.java:105)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:128)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:95)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:68)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:284)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.198
!MESSAGE Failed to retrieve default libraries for /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.324
!MESSAGE Process returned with error code "137".
Command line arguments: /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home/bin/java -Xmx16m -classpath /Users/XXXXX/Library/Application Support/Code/User/globalStorage/redhat.java/1.39.0/config_mac/org.eclipse.osgi/57/0/.cp/lib/launchingsupport.jar org.eclipse.jdt.internal.launching.support.LibraryDetector
Output: Standard output:

Standard error:

!STACK 0
java.lang.IllegalStateException: Process returned with error code "137".
Command line arguments: /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home/bin/java -Xmx16m -classpath /Users/XXXXX/Library/Application Support/Code/User/globalStorage/redhat.java/1.39.0/config_mac/org.eclipse.osgi/57/0/.cp/lib/launchingsupport.jar org.eclipse.jdt.internal.launching.support.LibraryDetector
Output: Standard output:

Standard error:

	at org.eclipse.jdt.internal.launching.StandardVMType.checkProcessResult(StandardVMType.java:895)
	at org.eclipse.jdt.internal.launching.StandardVMType.generateLibraryInfo(StandardVMType.java:707)
	at org.eclipse.jdt.internal.launching.StandardVMType.getLibraryInfo(StandardVMType.java:227)
	at org.eclipse.jdt.internal.launching.StandardVMType.getVMVersion(StandardVMType.java:265)
	at org.eclipse.jdt.internal.launching.macosx.MacOSXVMInstallType.getVMVersion(MacOSXVMInstallType.java:432)
	at org.eclipse.jdt.internal.launching.macosx.MacOSXVMInstall.getJavaVersion(MacOSXVMInstall.java:53)
	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironmentAnalyzer.analyze(ExecutionEnvironmentAnalyzer.java:130)
	at org.eclipse.jdt.internal.launching.environments.Analyzer.analyze(Analyzer.java:43)
	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.analyze(EnvironmentsManager.java:430)
	at org.eclipse.jdt.internal.launching.environments.EnvironmentsManager.initializeCompatibilities(EnvironmentsManager.java:337)
	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.init(ExecutionEnvironment.java:185)
	at org.eclipse.jdt.internal.launching.environments.ExecutionEnvironment.getDefaultVM(ExecutionEnvironment.java:227)
	at org.eclipse.jdt.ls.core.internal.JVMConfigurator.setDefaultEnvironmentVM(JVMConfigurator.java:235)
	at org.eclipse.jdt.ls.core.internal.JVMConfigurator.configureJVMs(JVMConfigurator.java:190)
	at org.eclipse.jdt.ls.core.internal.JVMConfigurator.configureJVMs(JVMConfigurator.java:105)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:128)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:95)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:68)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:284)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.346
!MESSAGE Failed to retrieve default libraries for /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.363
!MESSAGE Could not determine Java version for location /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home.

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.369
!MESSAGE Could not determine Java version for location /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home.

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.374
!MESSAGE Could not determine Java version for location /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home.

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.378
!MESSAGE Could not determine Java version for location /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home.

!ENTRY org.eclipse.jdt.launching 4 4 2025-02-04 14:58:18.382
!MESSAGE Could not determine Java version for location /Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home.
```

**Comment by rgrunber** [comment]
> I ran into the same issue. In my case it seems to pick up the wrong jdk, it uses `/Users/XXXXX/Library/Java/JavaVirtualMachines/corretto-1.8.0_322/Contents/Home` even though I have `configured java.jdt.js.java.home` to /`Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home` any ideas why it might pick up the wrong jdk (I tried both user and workspace settings).

This seems to be a slightly different issue, but still interesting.

`java.jdt.ls.java.home` is the optional setting that points to the JRE (or even JDK) that will be used to start the language server used by vscode-java. As of vscode-java 1.39.0, that must be 21 or newer. It was Java 17 or newer since around June 2022, and 11 or newer since July 2020. Looking at the logs I see `java.version=21.0.5` for the startup, so I'm guessing it ignores the setting and either attempts to find a proper JRE, or uses the embedded one (we embed a JRE even on `macosx-aarch64`). It uses that for startup.

However, the errors `Could not determine Java version for location ...` are more about the language server attempting to get the version information of that `corretto-1.8.0_322` JVM. It basically runs the `LibraryDetector` application with it's `java` binary to detect information from the initial system properties. You can read what it's doing at https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/master/org.eclipse.jdt.launching/support/org/eclipse/jdt/internal/launching/support/LibraryDetector.java#L50 . It probably tries a bunch of other things to get the version information which ultimately fail. As a workaround, are you able to temporarily uninstall that `corretto-1.8.0_322` and see if that fixes the issue ?

**Comment by robinwyss** [comment]
I deleted corretto, not sure where it came from and I need to check if something else is broken now, but that solved the issue. Now it lists several JRE/JDKs and then picks one, it seems that before it failed on corretto (probably the first one it checked) and that crashed the extensions.

```
!SESSION 2025-02-04 16:23:23.672 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_CH
Framework arguments:  --pipe=/private/var/folders/1j/dxx1p1k95037sby17l0dfff_9p0r65qqm6/T/lsp-67a4e9fcc491864c900adddd5038fc.sock
Command-line arguments:  -data /Users/XXXXXLibrary/Application Support/Code/User/workspaceStorage/b16176231891ddddd1cb0cfe74ad91967/redhat.java/jdt_ws --pipe=/private/var/folders/1j/dxx1p1k95037sby17l0_9p0r65qqm6/T/lsp-67a4e9fcc491864c900adddd5038fc.sock

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.402
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.439
!MESSAGE Started org.eclipse.buildship.core 23ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.442
!MESSAGE Started org.eclipse.m2e.core 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.531
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.543
!MESSAGE Initializing Java Language Server 1.44.0.202501220510

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.551
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.897
!MESSAGE ProjectRegistryRefreshJob finished 452ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.972
!MESSAGE Setting /Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home as 'JavaSE-19' environment (id:net.java.openjdk.jdk)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.979
!MESSAGE Setting /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home as 'JavaSE-21' environment (id:1738682605973)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.994
!MESSAGE Setting /opt/homebrew/Cellar/openjdk/23.0.1/libexec/openjdk.jdk/Contents/Home as 'JavaSE-23' environment (id:1738682605980)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:25.998
!MESSAGE Setting /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home as 'JavaSE-17' environment (id:1738682605995)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.008
!MESSAGE Setting java.home /Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home as default global VM

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.042
!MESSAGE Default VM Install changed from  1738676650417-/Users/XXXXX.vscode/extensions/redhat.java-1.39.0-darwin-arm64/jre/21.0.5-macosx-aarch64 to net.java.openjdk.jdk-/Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.056
!MESSAGE JVM Runtimes changed, saving new configuration

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.067
!MESSAGE Installed reference:file:/Users/XXXXX.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.3.2/dist/com.microsoft.jdtls.intellicode.core-0.7.1.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.078
!MESSAGE Installed reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-gradle-3.16.4/server/com.microsoft.gradle.bs.importer-0.5.3.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.088
!MESSAGE Installed reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-java-debug-0.58.1/server/com.microsoft.java.debug.plugin-0.53.1.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.100
!MESSAGE Installed reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-java-dependency-0.24.1/server/com.microsoft.jdtls.ext.core-0.24.1.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.119
!MESSAGE Installed reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-maven-0.44.0/jdtls.ext/com.microsoft.java.maven.plugin/target/com.microsoft.java.maven.plugin-0.39.0.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.143
!MESSAGE Started reference:file:/Users/XXXXX.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.3.2/dist/com.microsoft.jdtls.intellicode.core-0.7.1.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.166
!MESSAGE Started reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-maven-0.44.0/jdtls.ext/com.microsoft.java.maven.plugin/target/com.microsoft.java.maven.plugin-0.39.0.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.185
!MESSAGE Started reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-java-debug-0.58.1/server/com.microsoft.java.debug.plugin-0.53.1.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.205
!MESSAGE Started reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-gradle-3.16.4/server/com.microsoft.gradle.bs.importer-0.5.3.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.223
!MESSAGE Started reference:file:/Users/XXXXX.vscode/extensions/vscjava.vscode-java-dependency-0.24.1/server/com.microsoft.jdtls.ext.core-0.24.1.jar

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.229
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.244
!MESSAGE Non-Static Commands: [java.project.import, java.project.changeImportedProjects, java.navigate.openTypeHierarchy, java.project.resolveStackTraceLocation, java.edit.handlePasteEvent, java.edit.stringFormatting, java.project.getSettings, java.project.resolveWorkspaceSymbol, java.project.upgradeGradle, java.project.createModuleInfo, java.vm.getAllInstalls, java.edit.organizeImports, java.project.refreshDiagnostics, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.updateSettings, java.project.getAll, java.reloadBundles, java.project.isTestFile, java.project.resolveText, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.smartSemicolonDetection, java.project.updateSourceAttachment, java.project.updateClassPaths, java.decompile, java.protobuf.generateSources, java.project.resolveSourceAttachment, java.project.updateJdk, java.project.addToSourcePath, java.completion.onDidSelect]

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.256
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.260
!MESSAGE Non-Static Commands: [java.intellicode.enable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.263
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.266
!MESSAGE Non-Static Commands: [java.maven.initializeSearcher, java.maven.searchArtifact, java.maven.addDependency, java.maven.controlContext]

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.269
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.272
!MESSAGE Non-Static Commands: [vscode.java.checkProjectSettings, vscode.java.isOnClasspath, vscode.java.fetchUsageData, vscode.java.validateLaunchConfig, vscode.java.resolveInlineVariables, vscode.java.resolveClassFilters, vscode.java.resolveMainMethod, vscode.java.resolveClasspath, vscode.java.resolveBuildFiles, vscode.java.resolveMainClass, vscode.java.updateDebugSettings, vscode.java.resolveSourceUri, vscode.java.fetchPlatformSettings, vscode.java.buildWorkspace, vscode.java.startDebugSession, vscode.java.inferLaunchCommandLength, vscode.java.resolveElementAtSelection, vscode.java.resolveJavaExecutable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.275
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.278
!MESSAGE Non-Static Commands: [java.gradle.delegateTest]

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.283
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.286
!MESSAGE Non-Static Commands: [java.project.refreshLib, java.project.checkImportStatus, java.project.list, java.project.generateJar, java.project.getMainClasses, java.getPackageData, java.resolvePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.296
!MESSAGE RepositoryRegistryUpdateJob finished 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.302
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:26.364
!MESSAGE Importing Maven project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:29.086
!MESSAGE Workspace initialized in 2788ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:29.114
!MESSAGE >> initialization job finished

!ENTRY java-debug 1 0 2025-02-04 16:23:29.793
!MESSAGE Starting com.microsoft.java.debug.plugin

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:29.846
!MESSAGE Reconciled 1. Took 0 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:29.948
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:29.952
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:29.958
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:30.489
!MESSAGE begin problem for /HelloController.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:30.498
!MESSAGE 0 problems reported for /HelloController.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2025-02-04 16:23:30.545
!MESSAGE Validated 1. Took 49 ms
``

**Comment by rgrunber** [comment]
For what it's worth, I tried running with https://github.com/corretto/corretto-8/releases/tag/8.322.06.1 but maybe it's a platform-specific issue. It seems to be a fairly old version of that JDK so maybe there were issues.
