### ISSUE TITLE
Infinite loading after update to 1.25.0

### ISSUE THREAD

**Issue by pingu8007** [redhat-developer/vscode-java#3411]
After update vscode-java to 1.25.0, loading a project is never completed.

##### Environment
- Operating System: Ubuntu 22.04 (over Docker Desktop, over WSL2 on Windows 10)
- JDK version: 17 (Eclipse Adoptium 17.0.8)
- Visual Studio Code version: 1.84.2
- Java extension version: stable 1.25.0 / prerelease 1.26.2023120108

##### Steps To Reproduce
1. open project

##### Current Result

Project is loading infinitely, with full CPU usage.  
Sometime the language server is end in `OutOfMemory` error (-Xmx3000m).

Partial output from Build Status panel:
```
d9ac4536 Setting default character set for resource '/Module-1'. - 68% Module-1
88e3c423 Setting default character set for resource '/Module-2'. - 38% Module-2
af325284 Setting default character set for resource '/Module-3'. - 68% Module-3
ced41a43 Setting default character set for resource '/Module-4'. - 68% Module-4
732bc867 Setting default character set for resource '/Module-5'. - 58% Module-5
db0149e4 Setting default character set for resource '/Module-5b'. - 68% Module-5b
6ea8f7ab Update project Module-5 - 5% project Module-5
4e0a3156 Setting default character set for resource '/Module-6'. - 58% Module-6
f3905bae Setting default character set for resource '/Module-6'. - 68% Module-6
3c8eabe6 Setting default character set for resource '/Module-7'. - 68% Module-7
7ea37365 Setting default character set for resource '/Module-7b'. - 68% Module-7b
4c051edf Setting classpath containers - 37% project Module-8
4a8e09fb Setting default character set for resource '/Module-9'. - 68% Module-9
2b975bf5 Update project Module-10 - 0% Refreshing '/Module-10'.
b0ec73b0 Setting default character set for resource '/Module-10a'. - 68% Module-10a
07426617 Setting classpath containers - 37% project Module-10b
f9bfa629 Setting default character set for resource '/Module-11b'. - 58% Module-11b
35bcdfb0 Setting default character set for resource '/Module-11a'. - 68% Module-11a
6d34a44c Update project Module-11b - 1% Refreshing '/Module-11b'.
```

##### Expected Result

Finish loading in few minutes (1.24.0 can finish loading in 5min).

##### Additional Informations

1. It's internal project and I can't provide details but only environment and vscode configuration.
2. This project has 20+ modules and is more than 600MB.
3. This project is java+kotlin mixed, but I'm only working java parts.

**Comment by testforstephen** [comment]
```
!ENTRY org.eclipse.jdt.core 4 4 2023-12-04 07:01:22.562
!MESSAGE Search failed for index Index for /$MODULE_20
!STACK 0
java.io.IOException: Failed to read index data from file:/appdata/.vscode-server/data/User/workspaceStorage/4e97a51aeba2aad9206659b97b054cb6/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.jdt.core/4170031126.index at offset 208878 and size 1918985317
	at org.eclipse.jdt.internal.core.index.DiskIndex.readCategoryTable(DiskIndex.java:686)
	at org.eclipse.jdt.internal.core.index.DiskIndex.addQueryResults(DiskIndex.java:239)
	at org.eclipse.jdt.internal.core.index.Index.query(Index.java:172)
	at org.eclipse.jdt.internal.core.search.matching.SecondaryTypeDeclarationPattern.queryIn(SecondaryTypeDeclarationPattern.java:47)
	at org.eclipse.jdt.core.search.SearchPattern.findIndexMatches(SearchPattern.java:2517)
	at org.eclipse.jdt.core.search.SearchPattern.findIndexMatches(SearchPattern.java:2489)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.findIndexMatches(MatchLocator.java:310)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.search(PatternSearchJob.java:240)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.search(PatternSearchJob.java:214)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.lambda$0(PatternSearchJob.java:150)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.performParallelSearch(PatternSearchJob.java:156)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.execute(PatternSearchJob.java:117)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:288)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllSecondaryTypeNames(BasicSearchEngine.java:1716)
	at org.eclipse.jdt.internal.core.JavaModelManager.secondaryTypesSearching(JavaModelManager.java:5119)
	at org.eclipse.jdt.internal.core.JavaModelManager.secondaryTypes(JavaModelManager.java:4967)
	at org.eclipse.jdt.internal.core.search.matching.ClasspathSourceDirectory.directoryTable(ClasspathSourceDirectory.java:82)
	at org.eclipse.jdt.internal.core.search.matching.ClasspathSourceDirectory.isPackage(ClasspathSourceDirectory.java:148)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.getModulesDeclaringPackage(JavaSearchNameEnvironment.java:501)
	at org.eclipse.jdt.internal.compiler.env.IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage(IModuleAwareNameEnvironment.java:113)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule.getDeclaredPackage(ModuleBinding.java:102)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createPlainPackage(LookupEnvironment.java:1102)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:138)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:502)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:170)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:117)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:681)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1292)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:543)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jdt.internal.compiler.util.HashtableOfObject.<init>(HashtableOfObject.java:58)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readCategoryTable(DiskIndex.java:682)
	at org.eclipse.jdt.internal.core.index.DiskIndex.addQueryResults(DiskIndex.java:239)
	at org.eclipse.jdt.internal.core.index.Index.query(Index.java:172)
	at org.eclipse.jdt.internal.core.search.matching.SecondaryTypeDeclarationPattern.queryIn(SecondaryTypeDeclarationPattern.java:47)
	at org.eclipse.jdt.core.search.SearchPattern.findIndexMatches(SearchPattern.java:2517)
	at org.eclipse.jdt.core.search.SearchPattern.findIndexMatches(SearchPattern.java:2489)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.findIndexMatches(MatchLocator.java:310)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.search(PatternSearchJob.java:240)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.search(PatternSearchJob.java:214)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.lambda$0(PatternSearchJob.java:150)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob$$Lambda$585/0x000000080073b7b8.call(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.performParallelSearch(PatternSearchJob.java:156)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.execute(PatternSearchJob.java:117)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:288)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllSecondaryTypeNames(BasicSearchEngine.java:1716)
	at org.eclipse.jdt.internal.core.JavaModelManager.secondaryTypesSearching(JavaModelManager.java:5119)
	at org.eclipse.jdt.internal.core.JavaModelManager.secondaryTypes(JavaModelManager.java:4967)
	at org.eclipse.jdt.internal.core.search.matching.ClasspathSourceDirectory.directoryTable(ClasspathSourceDirectory.java:82)
	at org.eclipse.jdt.internal.core.search.matching.ClasspathSourceDirectory.isPackage(ClasspathSourceDirectory.java:148)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.getModulesDeclaringPackage(JavaSearchNameEnvironment.java:501)
	at org.eclipse.jdt.internal.compiler.env.IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage(IModuleAwareNameEnvironment.java:113)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule.getDeclaredPackage(ModuleBinding.java:102)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createPlainPackage(LookupEnvironment.java:1102)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:138)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:502)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:170)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:117)
```

Looks like the index files are broken and cause out-of-memory. Could you try "**F1 -> Java: Clean Java Language Server Workspace**"?

**Comment by testforstephen** [comment]
@rgrunber We also noticed that the out-of-memory ratio increases in recent version 1.25.0. Any thoughts on this?

**Comment by pingu8007** [comment]
@testforstephen No. Clean Java Language Server Workspace doesn't resolve this issue.

While increasing heap size improve the responsive and the increase the chance of success startup, the increment is not acceptable and is not always work.

**Comment by pingu8007** [comment]
@snjeza Yes, it works with 4g heap size in 9min (both are twice then 1.24.0 required, language server workspace is cleared).

[1_27_0-mx4g.log](https://github.com/redhat-developer/vscode-java/files/13553701/1_27_0-mx4g.log)

**Comment by Wroud** [comment]
My project is https://github.com/dbeaver/dbeaver
I use combination of yaozheng.vscode-pde (Eclipse PDE support) with vscjava.vscode-java-pack (Extension Pack for Java)

to work with my project, I need firstly "Import existing maven project" in Eclipse (to generate .project, .classpaths files) then I can work with project in VSCode (vscode don't recognize maven projects as java projects till imported in Eclipse)

@pingu8007  1.27.0 also works for me
