### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by jozefcifre** [redhat-developer/vscode-java#3449]
[provide a description of the issue]

##### Environment
- Operating System: NixOS
- JDK version: 17
- Visual Studio Code version: 1.85.1
- Java extension version: 1.25.1

##### Steps To Reproduce
1. Install the latest release version of this extension.
2. Open the Java project below.

[project reproducing the error](https://github.com/MovingBlocks/DestinationSol)
[dotlog.txt](https://github.com/redhat-developer/vscode-java/files/13814455/dotlog.txt) (logs)

**Comment by rgrunber** [comment]
It seemed to import successfully using the Gradle support from vscode-java. However, after installing `vscjava.vscode-gradle` :

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2024-01-12 15:43:40.456
!MESSAGE Initialization failed 
!STACK 0
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: java.lang.IllegalArgumentException: java.lang.String is not an interface
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
	at com.microsoft.gradle.bs.importer.GradleBuildServerProjectImporter.importToWorkspace(GradleBuildServerProjectImporter.java:171)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:162)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:124)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:263)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: java.lang.IllegalArgumentException: java.lang.String is not an interface
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

`com.microsoft.gradle.bs.importer` gets contributed into the JDT-LS runtime but it actually comes from :

Looks like the issue happens at https://github.com/microsoft/vscode-gradle/blob/fd041f373c57df32b80c473332d1531e85f4d005/extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerProjectImporter.java#L171 .

CC'ing @testforstephen for awareness as this is looking like a vscode-gradle issue.

@jozefcifre , if you disable the "Gradle for Java" extension, does the import work ? It seemed to fix it for me.

**Comment by testforstephen** [comment]
@jdneo for a look.

**Comment by jozefcifre** [comment]
> @jozefcifre , if you disable the "Gradle for Java" extension, does the import work ? It seemed to fix it for me.

Yes, It works. Thank you.
