### ISSUE TITLE
Failed to initialize language server due to "Internal error. Caused by: NPE: Cannot invoke 'o.e.m.c.e.IMaven.getSettings()' because the return value of 'o.e.m.c.MavenPlugin.getMaven()' is null"

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#3469]
Full call stack
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.embedder.IMaven.getSettings()" because the return value of "org.eclipse.m2e.core.MavenPlugin.getMaven()" is null
	at org.eclipse.jdt.ls.core.internal.preferences.StandardPreferenceManager.update(StandardPreferenceManager.java:108)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:115)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:105)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:284)
	... 17 more
```

**Comment by testforstephen** [comment]
From the BI logs, this issue is easier to happen when new version of vscode-java is just released. This might be related to the activation of plugin.

**Comment by testforstephen** [comment]
Latest call stack:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.embedder.IMaven.getSettings()" because the return value of "org.eclipse.m2e.core.MavenPlugin.getMaven()" is null
	at org.eclipse.jdt.ls.core.internal.preferences.StandardPreferenceManager.update(StandardPreferenceManager.java:125)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:115)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:109)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:283)
	... 17 more
```

This NPE is also easier to happen for Windows than other platforms (macOS and linux).

**Comment by Eskibear** [comment]
> Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.embedder.IMaven.getSettings()" because the return value of "org.eclipse.m2e.core.MavenPlugin.getMaven()" is null
	at org.eclipse.jdt.ls.core.internal.preferences.StandardPreferenceManager.update(StandardPreferenceManager.java:125)

Will it be auto resolved (i.e. no NPE) next time when it tries to import the Maven project? If so, is there any approach we can do in jdt.ls.core to catch the NPE and do something to mitigate the issue?

**Comment by testforstephen** [comment]
> Will it be auto resolved (i.e. no NPE) next time when it tries to import the Maven project? If so, is there any approach we can do in jdt.ls.core to catch the NPE and do something to mitigate the issue?

I believe so. This NPE rate goes to a PEAK at the first week of new vscode-java release and then goes down to a lower rate. This is because most of users upgrade to new version on the first week of new release.

**Comment by testforstephen** [comment]
Add @fbricon @rgrunber, since your team is more familiar with m2e mechanism. `org.eclipse.m2e.core.MavenPlugin.getMaven()` returns null when activating jdt.ls.

**Comment by rgrunber** [comment]
Interesting observation. Maybe it's a case of the newer m2e invalidating some aspect of the older settings, that then gets automatically fixed ?

**Comment by tmingniu** [comment]
It's already 2006. Why is this problem still around?
[https://github.com/microsoft/vscode-java-pack/issues/1613](url)

**Comment by FaiqNoman69** [comment]
Thanks for letting me know! I’m actually seeing the same problem in my
workspace. It seems that with multi-folder setups, the Java formatting
isn’t applying correctly. When I open the same folder in a fresh VS Code
window, it works as expected. Do you think this could be a caching issue or
something related to workspace settings? Let me know if you’ve got any
ideas!"
