### ISSUE TITLE
Internal error when starting JLS with JDK 9

### ISSUE THREAD

**Issue by sundayoyeniyi** [redhat-developer/vscode-java#359]
The JLS is not starting up and dumping errors at 22%.  The JLS error logs indicate an illegal argument exception java.lang.IllegalArgumentException: Could not determine java version from '9.0.1'.  See error log below:

- Is this vs code extension able to support **Java 9** at this stage or must I use Java 8 in the interim?
- Is there any workaround?

##### Environment
- Operating System: Mac OS X 10.12.4 x86_64
- JDK version: **9.0.1** (Oracle Corporation 9.0.1+11)
- Visual Studio Code version: 1.17.2
- Java extension version: **0.13.0**
- Gradle: 4.3

##### Steps To Reproduce
1. Install JDK 9
2. Install Gradle 4.3
3. Initialise/create a gradle Java project
4. Open the java project in vs code from the root folder
5. Open a java source file in vs code and the JLS will not start

##### Current Result

[Error - 00:13:50] 6 Nov 2017, 00:13:48 An internal error occurred during: "Initialize Workspace".
Could not determine java version from '9.0.1'.
java.lang.IllegalArgumentException: **Could not determine java version from '9.0.1'**.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
	at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
	at org.gradle.tooling.internal.consumer.ConnectorServices.checkJavaVersion(ConnectorServices.java:57)

##### Expected Result
JLS is able to recognise Java 9 as a valid/supported Java version.

##### Additional Informations

vs code java.home setting is pointing to JDK 9 as below:

"java.home": 	"/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home"

**Comment by fbricon** [comment]
There's a good chance this is caused by jdt.ls using its embedded Gradle version, not compatible with Java 9, instead of picking up the system Gradle. Did you set GRADLE_HOME as an environment variable?

The best, cross-platform way to ensure a Java 9 compatible version of Gradle will be used, is to use the Gradle wrapper.

If that's not an option and GRADLE_HOME envvar doesn't work, you can still try to set `java.jdt.ls.vmargs` with -DGRADLE_HOME=/path/to/gradle

**Comment by sundayoyeniyi** [comment]
@fbricon - thanks for your response.

1.  I set the GRADLE_HOME  environment variable but the same problem persists
2.  I set "java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -DGRADLE_HOME=/usr/local/bin/gradle", but the same problem persists

I am able to build/test my project with gradle from the command line and it is the Language Support for Java (JLS integration with vscode) that is not working.

A screenshot of the verbose output of the JLS is attached if it helps.
![screen shot 2017-11-06 at 02 30 13](https://user-images.githubusercontent.com/3162619/32422832-a24b2b82-c29a-11e7-9093-0c5fdb4fb557.png)

Any other suggestion on getting this extension to work with gradle and Java 9 will be helpful.

**Comment by fbricon** [comment]
@donat any ETA on the availability of a buildship release with https://github.com/eclipse/buildship/commit/6ff9af2813416603a4f72cc4131c797092ddc497?

**Comment by donat** [comment]
All the features are implemented, we are only blocked by the Eclipse release process. The review period ends on 6th December, so most probably we'll do the release on that date. I suggest trying the [latest milestone](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md)for the time being. I'd love to know if the Java 9-related changes work properly with vscode-java.

**Comment by fbricon** [comment]
@donat thanks! initial tests are positive. We'll start with the milestone and move to the release when it's available.
