### ISSUE TITLE
JUnit testing is can not in vscode-java 1.30.0 version

### ISSUE THREAD

**Issue by mklinkj** [redhat-developer/vscode-java#3627]
[provide a description of the issue]

##### Environment
- Operating System: Windows 11
- JDK version: 17
- Visual Studio Code version: 1.88.1
- Java extension version: 1.30.0

##### Steps To Reproduce
1. I am unable to run JUnit tests after upgrading vscode-java to version 1.30.0.

2. After **vscode-java** was upgraded to 1.30.0, [**vscode-java-test**](https://github.com/Microsoft/vscode-java-test) does not seem to work properly. 

* The output from "Language Support for Java" looks like this
  ```
  4월 25, 2024 10:34:36 오후 org.apache.aries.spifly.BaseActivator log
  INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
  4월 25, 2024 10:34:36 오후 org.apache.aries.spifly.BaseActivator log
  INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
  [Error - 오후 10:34:39] 2024. 4. 25. 오후 10:34:37 FrameworkEvent ERROR
  org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [121]
    Unresolved requirement: Require-Bundle: org.jacoco.core; bundle-version="0.8.11"
      -> Bundle-SymbolicName: org.jacoco.core; bundle-version="0.8.11.202310140853"
         org.jacoco.core [120]
           Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.6.0,9.7.0)"
  
	  at org.eclipse.osgi.container.Module.start(Module.java:493)
	  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2073)
	  at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2064)
	  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2004)
	  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1967)
	  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1883)
	  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	  at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	  at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
  
  4월 25, 2024 10:34:45 오후 com.microsoft.java.debug.plugin.internal.JavaDebuggerServerPlugin start
  INFO: Starting com.microsoft.java.debug.plugin
  
  ```
* Downgrading vscode-java to 1.29.0 should resolve the issue.

##### Current Result
* JUnit testing is can not in vscode-java 1.30.0 version

##### Expected Result
* JUnit tests should also be performed on vscode-java version 1.30.0.

**Comment by arey-netceler** [comment]
Hello,

I have the same exact issue. Downgrading to 1.29.0 solves the issue.

Thanks

**Comment by rgrunber** [comment]
This was fixed recently in https://github.com/microsoft/vscode-java-test/issues/1681 . Can you trying using the vscode-java-test pre-release version and see if the issue goes away ?

**Comment by rgrunber** [comment]
I expect there will be a 0.41.1 release soon for that extension.

**Comment by arey-netceler** [comment]
Thank you very much for your help @rgrunber, have a nice day ! ;)

**Comment by jdneo** [comment]
0.41.1 is just released, should be available in the next couple of hours.
