### ISSUE TITLE
Starting language server crashes

### ISSUE THREAD

**Issue by mojo2012** [redhat-developer/vscode-java#370]
When building SAP hybris from the command line (outside of vscode) with ant, nearly all class files get regenerated.
Afterwards the langage server hangs at 22-24% and outputs the error logs down below.

##### Environment
- Operating System: macOS 10.12.6 (16G1036)
- JDK version: 1.8.0_144
- Visual Studio Code version: Version 1.18.0 (1.18.0)
- Java extension version: 0.14.0

##### Steps To Reproduce
1. Start vscode and load a java file -> language server gets invoked
2. rebuild whole SAP hybris suite (several 10k classes)
3 switch back to vscode -> the language server tries to refresh and crashes

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
```
[Error - 15:42:07] 16.11.2017 15:40:54 Invalid project description.
[Error - 15:42:07] 16.11.2017 15:40:54 An internal error occurred during: "Initialize Workspace".
org.eclipse.core.internal.resources.ResourceException: Invalid project description.
java.lang.RuntimeException: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importDir(EclipseProjectImporter.java:96)
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.lambda$0(EclipseProjectImporter.java:63)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importToWorkspace(EclipseProjectImporter.java:63)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:100)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.access$1(ProjectsManager.java:94)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$1.run(ProjectsManager.java:88)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5660)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5617)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:82)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:157)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:169)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:53)
	at org.eclipse.core.internal.resources.Project.create(Project.java:263)
	at org.eclipse.core.internal.resources.Project.create(Project.java:247)
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importDir(EclipseProjectImporter.java:92)
	... 17 more
```

##### Expected Result
Don't crash

**Comment by gorkem** [comment]
Is this a project that we can try for ourselves? Where can we get it?

**Comment by mojo2012** [comment]
No unfortunately not. But tell me how I can gather the information you need and i will do my best to support you.

Allthe orojects are eclipse projects. Would the .project files help you?

**Comment by gorkem** [comment]
yes, `.project` would at least give an idea about the setup.

**Comment by mojo2012** [comment]
Here are all the project files in my workspace.
[project_files.zip](https://github.com/redhat-developer/vscode-java/files/1850764/project_files.zip)

Sorry it took so long - didn't have any time for this.

**Comment by softwareCobbler** [comment]
I am trying to load https://github.com/lucee/Lucee/tree/6.0 but I get this error too.
To get it to resolve all the types and symbols, from a fresh clone I need to tweak the project's JRE paths in eclipse, but from there on out Eclipse 2021-09 works fine, providing autocomplete and jump-to-decl and etc. Once that is fixed up, the VsCode plugin loading the same project exhibits this issue.

```
org.eclipse.core.internal.resources.ResourceException: Invalid project description.
java.lang.RuntimeException: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importDir(EclipseProjectImporter.java:133)
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.lambda$4(EclipseProjectImporter.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importToWorkspace(EclipseProjectImporter.java:100)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:122)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:108)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:238)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:173)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:57)
	at org.eclipse.core.internal.resources.Project.create(Project.java:266)
	at org.eclipse.core.internal.resources.Project.create(Project.java:252)
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importDir(EclipseProjectImporter.java:129)
	... 8 more
```

I also get
```
[Error - 11:22:39 AM] Nov 20, 2021, 11:22:39 AM Error occured while building workspace. Details: 
 message: Project 'core' is missing required Java project: 'Lucee loader'; code: 964; resource: <...elided...>LUCEE_ROOT/Lucee/core;
 message: The project cannot be built until build path errors are resolved; code: 0; resource: <...elided...>/LUCEE_ROOT/Lucee/core;

```
And I just assume resolving the "invalid project description" error would fix the "missing required java project" error

maybe helpful breadcrumb to current commit, for future readers:
https://github.com/lucee/Lucee/commit/94d64bbb270b4f21ab625c3246fe194c50e63a27
