### ISSUE TITLE
Find and rename symbols with Spring

### ISSUE THREAD

**Issue by ralcaidev** [redhat-developer/vscode-java#3762]
Finding or renaming symbols using Spring injection is broken.

##### Environment
- Operating System: Fedora 40
- JDK version: Temurin 17.0.3+7
- Visual Studio Code version: 1.93.0
- Java extension version: 37.791.403

##### Steps To Reproduce
RestController class injects a Service via Interface. Structure example:

- ExampleService implements ExampleServiceInterface.
- ExampleServiceInterface is declared on ExampleRestController.
- (Runtime) Spring injects ExampleService in ExampleRestController.

No matter on which of those three classes/interface you try to find or rename symbols, it just throws this:
```
==> ./window1/exthost/output_logging_20240910T085724/6-Language Support for Java.log <==
sept 10, 2024 11:16:33 A. M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
GRAVE: Internal error: java.lang.ClassCastException
java.util.concurrent.CompletionException: java.lang.ClassCastException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException

[Error - 11:16:33] Request textDocument/rename failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.ClassCastException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException
```

##### Current Result
"Internal Error" popup VSCode and previous log on _Language Support for Java.log_.

##### Expected Result
Find or rename a symbol.

##### Additional Informations
Go to Implementations and Go to References works fine.

**Comment by nikunjk9** [comment]
@ralcaidev  Does the issue occur only when renaming symbols involving interfaces?

Since you're using an interface (ExampleServiceInterface) with an implementation (ExampleService), is the issue restricted to symbol renaming where interfaces are involved? You might test renaming in classes without interfaces to see if the error persists.

**Comment by ralcaidev** [comment]
It works now, some misconfiguration by my side.
