### ISSUE TITLE
Exceptions are thrown when setting the Java type to a new file

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#38]
It seems setting a new file language to java, before a workspace folder has been defined (i.e. not within an already opened Maven or Eclipse project), causes problems, as seen in See https://github.com/gorkem/vscode-java/issues/32#issuecomment-249031009

```
[Error] 22-sep-2016 23:17:02 Exception on incoming message dispatcher
null argument:
org.eclipse.core.runtime.AssertionFailedException: null argument:
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
    at org.eclipse.core.runtime.Path.initialize(Path.java:641)
    at org.eclipse.core.runtime.Path.<init>(Path.java:238)
    at org.eclipse.core.runtime.Path.<init>(Path.java:186)
    at org.eclipse.core.runtime.Path.fromOSString(Path.java:92)
    at org.jboss.tools.vscode.java.handlers.AbstractRequestHandler.resolveCompilationUnit(AbstractRequestHandler.java:33)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.handleOpen(DocumentLifeCycleHandler.java:127)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.access$1(DocumentLifeCycleHandler.java:126)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$OpenHandler$1.run(DocumentLifeCycleHandler.java:75)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:72)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:1)
    at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:222)
    at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:156)
    at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)

[Error] 22-sep-2016 23:17:02 Exception on incoming message dispatcher
null argument:
org.eclipse.core.runtime.AssertionFailedException: null argument:
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
    at org.eclipse.core.runtime.Path.initialize(Path.java:641)
    at org.eclipse.core.runtime.Path.<init>(Path.java:238)
    at org.eclipse.core.runtime.Path.<init>(Path.java:186)
    at org.eclipse.core.runtime.Path.fromOSString(Path.java:92)
    at org.jboss.tools.vscode.java.handlers.AbstractRequestHandler.resolveCompilationUnit(AbstractRequestHandler.java:33)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.handleChanged(DocumentLifeCycleHandler.java:155)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.access$2(DocumentLifeCycleHandler.java:154)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler$1.run(DocumentLifeCycleHandler.java:98)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:95)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:1)
    at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:222)
    at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:156)
    at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)

[Error] 22-sep-2016 23:17:02 Exception on incoming message dispatcher
null argument:
org.eclipse.core.runtime.AssertionFailedException: null argument:
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
    at org.eclipse.core.runtime.Path.initialize(Path.java:641)
    at org.eclipse.core.runtime.Path.<init>(Path.java:238)
    at org.eclipse.core.runtime.Path.<init>(Path.java:186)
    at org.eclipse.core.runtime.Path.fromOSString(Path.java:92)
    at org.jboss.tools.vscode.java.handlers.AbstractRequestHandler.resolveCompilationUnit(AbstractRequestHandler.java:33)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.handleChanged(DocumentLifeCycleHandler.java:155)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.access$2(DocumentLifeCycleHandler.java:154)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler$1.run(DocumentLifeCycleHandler.java:98)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:95)
    at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:1)
    at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:222)
    at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:156)
    at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)


```

**Comment by fbricon** [comment]
So the exception is fixed, but vscode still displays an error message saying the JLS couldn't be started (and logs [Error - 8:57:54 AM] Starting client failed).

I can't decide whether this is better or whether we can improve the situation and how

**Comment by gorkem** [comment]
I think the ideal solution is fixing https://github.com/gorkem/java-language-server/issues/36 

I am just not sure about the behavior though, it feels like the attempt to start JDT LS fails even before a call start the server is done.

**Comment by fbricon** [comment]
Yeah that issue is definitely related. However the difference is we have no physical file to relate to, from a hidden pseudo-project perspective

**Comment by gorkem** [comment]
I think gorkem/java-language-server#36 is exactly that, If there is no other way (pom.xml, .classpath etc.) to determine project fall back to a plain JDT project created on the fly.

**Comment by fbricon** [comment]
well, my point is, even if we do create a plain jdt project on the fly, I don't see how we could attach the new, unsaved resource to that project, since there's no physical file at that point.

**Comment by fbricon** [comment]
So, when opening a single java file or when creating a new file and setting the language to java, the context sent to extension.activate() doesn't contain any storagePath, so we end up trying to launch JLS with a workspace from /undefined/*. On OSX, creating such a folder requires write permissions. So eventually the server fails to start.

We need to figure out some actual context (opened file path, default extension work folder) to be able to generate a reusable workspace.

**Comment by fbricon** [comment]
Even if we were able to figure out the file path and launching a new JLS workspace, it wouldn't work if multiple java files were opened, as the extension would only be started once. Unless we revisit how the whole extension loading works (dunno if feasible)

**Comment by fbricon** [comment]
Closing as partially fixed. Errors no longer appear but, adding support for in-memory java files comes with too many gotchas, so we'll just won't provide autocompletion for these files (same as JavaScript support in stock vscode).
