### ISSUE TITLE
After upgrade version >1.35, my project with lombok and hibernate-jpamodelgen stop to works

### ISSUE THREAD

**Issue by AntonioSeleda** [redhat-developer/vscode-java#3842]
I have a project that uses both Lombok and Hibernate JPA ModelGen. Until version 1.35 of the "Language Support for Java" extension, everything worked fine. After upgrading the plugin and cleaning the workspace, the build enters an infinite loop.

I've attached the log file to this issue for reference. For now, I'm forced to continue working with the older version.

The errors are;
```
!ENTRY org.eclipse.jdt.core 4 0 2024-11-05 10:00:46.486
!MESSAGE Lombok annotation handler class lombok.eclipse.handlers.HandleGetter failed
!STACK 0
java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source)
	at java.base/java.util.regex.Pattern$LazyLoop.match(Unknown Source)
	at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source)
	at java.base/java.util.regex.Pattern$BranchConn.match(Unknown Source)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Unknown Source)
```

and

```
!ENTRY org.eclipse.core.resources 4 2 2024-11-05 10:01:12.071
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.problemsMap" is null
	at org.eclipse.jdt.internal.compiler.CompilationResult.getContext(CompilationResult.java:407)
	at org.eclipse.jdt.internal.compiler.Compiler.backupAptProblems(Compiler.java:548)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:478)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:447)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:441)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:250)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:118)[.bak_0.log](https://github.com/user-attachments/files/17629962/default.bak_0.log)
[.bak_1.log](https://github.com/user-attachments/files/17629961/default.bak_1.log)
[.bak_2.log](https://github.com/user-attachments/files/17629957/default.bak_2.log)
[.bak_3.log](https://github.com/user-attachments/files/17629959/default.bak_3.log)
[.bak_4.log](https://github.com/user-attachments/files/17629965/default.bak_4.log)
[.bak_5.log](https://github.com/user-attachments/files/17629964/default.bak_5.log)
[.bak_6.log](https://github.com/user-attachments/files/17629963/default.bak_6.log)
[.bak_7.log](https://github.com/user-attachments/files/17629956/default.bak_7.log)
[.bak_8.log](https://github.com/user-attachments/files/17629960/default.bak_8.log)
[.bak_9.log](https://github.com/user-attachments/files/17629955/default.bak_9.log)
[.log](https://github.com/user-attachments/files/17629958/default.log)

```

**Comment by bsproger** [comment]
Have a look at [this issue](https://github.com/redhat-developer/vscode-java/issues/3836)

Just switch Lombok version

**Comment by fbricon** [comment]
@AntonioSeleda is it still an issue with latest vscode-java and a recent lombok version?

**Comment by bsproger** [comment]
> [@AntonioSeleda](https://github.com/AntonioSeleda) is it still an issue with latest vscode-java and a recent lombok version?

Sorry for the late reply. Everything works fine.
