### ISSUE TITLE
Error upon importing project

### ISSUE THREAD

**Issue by mamilic** [redhat-developer/vscode-java#3853]
When importing project, https://github.com/spring-projects/spring-boot , it throws an error.

**Environment**
Operating System: Windows 11
JDK version: 21
Visual Studio Code version: 1.95.2
Java extension version: 1.36.0 (Language Support for Java by Red Hat.

```shell
Nov 10, 2024 2:07:44 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Nov 10, 2024 2:07:44 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
Nov 10, 2024 2:28:54 PM com.microsoft.java.debug.plugin.internal.JavaDebuggerServerPlugin start
INFO: Starting com.microsoft.java.debug.plugin
Nov 10, 2024 2:28:55 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 3
Nov 10, 2024 2:28:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 10
Nov 10, 2024 2:28:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2
Nov 10, 2024 2:28:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 22
[Error - 2:36:36 PM] Nov 10, 2024, 2:36:36 PM failed to search tests in: java
<anonymous #1> {key=Lorg/springframework/boot/web/servlet/server/AbstractServletWebServerFactoryTests$49172;} [in onStartup(jakarta.servlet.ServletContext) [in <lambda #1> [in faultyFilterCausesStartFailure() [in AbstractServletWebServerFactoryTests [in AbstractServletWebServerFactoryTests.java [in org.springframework.boot.web.servlet.server [in src/test/java [in spring-boot]]]]]]]] does not exist
Java Model Exception: Error in Java Model (code 969): <anonymous #1> {key=Lorg/springframework/boot/web/servlet/server/AbstractServletWebServerFactoryTests$49172;} [in onStartup(jakarta.servlet.ServletContext) [in <lambda #1> [in faultyFilterCausesStartFailure() [in AbstractServletWebServerFactoryTests [in AbstractServletWebServerFactoryTests.java [in org.springframework.boot.web.servlet.server [in src/test/java [in spring-boot]]]]]]]] does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:546)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:589)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:292)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:278)
	at org.eclipse.jdt.internal.core.Member.getFlags(Member.java:193)
	at org.eclipse.jdt.internal.junit.util.CoreTestSearchEngine.isAccessibleClass(CoreTestSearchEngine.java:64)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.internalIsTest(JUnit5TestFinder.java:251)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.findTestsInContainer(JUnit5TestFinder.java:221)
	at com.microsoft.java.test.plugin.searcher.JUnit5TestSearcher.findTestItemsInContainer(JUnit5TestSearcher.java:130)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.findTestPackagesAndTypes(TestSearchUtils.java:168)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:61)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:609)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by jdneo** [comment]
Filed an issue for the second one here: https://github.com/microsoft/vscode-gradle/issues/1629

**Comment by snjeza** [comment]
> https://github.com/keycloak/keycloak

Please see https://github.com/redhat-developer/vscode-java/issues/3639

**Comment by rgrunber** [comment]
@mamilic , when you reproduce "Logs-1", does the status bar icon spin indefinitely? Also, it seems very similar to what I reported in https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2821#issuecomment-1699831474 so it might be in investigation that needs to happen into https://github.com/microsoft/vscode-java-test .

**Comment by mamilic** [comment]
Hi @rgrunber , actually not, it finishes I think with status Warning.

For the Keycloak I got this errror.

<details><summary>Details</summary>
<p>

```
!ENTRY org.eclipse.jdt.ls.core 4 2 2024-11-13 07:19:10.097
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 1
org.eclipse.core.runtime.CoreException: Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider
	at org.eclipse.jdt.launching.JavaRuntime.abort(JavaRuntime.java:1870)
	at org.eclipse.jdt.launching.JavaRuntime.abort(JavaRuntime.java:1855)
	at org.eclipse.jdt.launching.JavaRuntime.getClasspathProvider(JavaRuntime.java:1181)
	at org.eclipse.jdt.launching.JavaRuntime.computeUnresolvedRuntimeClasspath(JavaRuntime.java:1659)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspathAndModulepath(AbstractJavaLaunchConfigurationDelegate.java:463)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.lambda$8(ProjectCommand.java:435)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2482)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspathsFromJavaProject(ProjectCommand.java:434)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspaths(ProjectCommand.java:414)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:101)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:609)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:527)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
!SUBENTRY 1 org.eclipse.jdt.launching 4 150 2024-11-13 07:19:10.098
!MESSAGE Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider
!SUBENTRY 1 org.eclipse.jdt.launching 4 150 2024-11-13 07:19:10.098
!MESSAGE Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider
```

</p>
</details>

**Comment by mamilic** [comment]
For Kafka I get this.

<details><summary>Details</summary>
<p>

```
info] [gradle-server] Gradle Server started, listening on 40251
[info] Gradle client connected to server
[info] Java Home: /home/mmilic/.vscode/extensions/redhat.java-1.36.0-linux-x64/jre/17.0.13-linux-x86_64
[info] JVM Args: -Xss4m,-XX:+UseParallelGC,--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx2g,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: /home/mmilic/.gradle
[info] Gradle Version: 8.8
[error] FAILURE: Build failed with an exception.

* Where:
Build file '/home/mmilic/Documents/dev/workspace/external/kafka/buildSrc/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> Could not find method compile() for arguments [org.gradle.api.internal.artifacts.dependencies.DefaultFileCollectionDependency_Decorated@3d5d7d89] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

CONFIGURE FAILED in 15s
[error] [gradle-server] The supplied build action failed with an exception.
[error] Error getting build for /home/mmilic/Documents/dev/workspace/external/kafka: The supplied build action failed with an exception.
[info] Found 0 tasks
[info] Java Home: /home/mmilic/.vscode/extensions/redhat.java-1.36.0-linux-x64/jre/17.0.13-linux-x86_64
[info] JVM Args: -Xss4m,-XX:+UseParallelGC,--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx2g,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: /home/mmilic/.gradle
[info] Gradle Version: 8.8
[error] FAILURE: Build failed with an exception.

* Where:
Build file '/home/mmilic/Documents/dev/workspace/external/kafka/buildSrc/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> Could not find method compile() for arguments [org.gradle.api.internal.artifacts.dependencies.DefaultFileCollectionDependency_Decorated@9bb2ad7] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

CONFIGURE FAILED in 537ms
[error] [gradle-server] The supplied build action failed with an exception.
[error] Error getting build for /home/mmilic/Documents/dev/workspace/external/kafka: The supplied build action failed with an exception.
[info] Build file opened: /home/mmilic/Documents/dev/workspace/external/kafka/buildSrc/build.gradle
```

</p>
</details>

**Comment by mamilic** [comment]
As the comment has char limitations, I will add here. Sometime I get this when reopen hadoop project in VSCode.

<details><summary>Details</summary>
<p>

```
!ENTRY org.springframework.tooling.jdt.ls.extension 1 0 2024-11-14 12:05:24.287
!MESSAGE Classpath changed for project: hadoop-yarn-services-core

!ENTRY org.eclipse.jdt.ls.core 4 2 2024-11-14 12:05:33.144
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 1
org.eclipse.core.runtime.CoreException: Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider
	at org.eclipse.jdt.launching.JavaRuntime.abort(JavaRuntime.java:1870)
	at org.eclipse.jdt.launching.JavaRuntime.abort(JavaRuntime.java:1855)
	at org.eclipse.jdt.launching.JavaRuntime.getClasspathProvider(JavaRuntime.java:1181)
	at org.eclipse.jdt.launching.JavaRuntime.computeUnresolvedRuntimeClasspath(JavaRuntime.java:1659)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspathAndModulepath(AbstractJavaLaunchConfigurationDelegate.java:463)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.lambda$8(ProjectCommand.java:435)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2482)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspathsFromJavaProject(ProjectCommand.java:434)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspaths(ProjectCommand.java:414)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:101)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:609)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
!SUBENTRY 1 org.eclipse.jdt.launching 4 150 2024-11-14 12:05:33.146
!MESSAGE Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider
!SUBENTRY 1 org.eclipse.jdt.launching 4 150 2024-11-14 12:05:33.146
!MESSAGE Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2024-11-14 12:05:33.150
!MESSAGE Error in calling delegate command handler
!STACK 1
org.eclipse.core.runtime.CoreException: Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider
	at org.eclipse.jdt.launching.JavaRuntime.abort(JavaRuntime.java:1870)
	at org.eclipse.jdt.launching.JavaRuntime.abort(JavaRuntime.java:1855)
	at org.eclipse.jdt.launching.JavaRuntime.getClasspathProvider(JavaRuntime.java:1181)
	at org.eclipse.jdt.launching.JavaRuntime.computeUnresolvedRuntimeClasspath(JavaRuntime.java:1659)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspathAndModulepath(AbstractJavaLaunchConfigurationDelegate.java:463)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.lambda$8(ProjectCommand.java:435)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2482)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspathsFromJavaProject(ProjectCommand.java:434)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspaths(ProjectCommand.java:414)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:101)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:609)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
!SUBENTRY 1 org.eclipse.jdt.launching 4 150 2024-11-14 12:05:33.150
!MESSAGE Referenced classpath provider does not exist: org.eclipse.m2e.launchconfig.classpathProvider

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-11-14 12:05:35.848
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-11-14 12:05:35.848
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-11-14 12:05:35.855
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'
```

</p>
</details>

**Comment by ikaakkola** [comment]
Same problem as with _Logs-1_

When trying to _Run tests_ via the context-menu of a project (in a multi-project workspace, should that make a difference), only tests under `src/it/java` are executed, all tests under `src/test/java` are missing from the test run.

The project has both unit tests (under src/test/java) and integration tests (under src/it/java). 

The `Language Server for Java` logs (under _Output_) the following, for various `com.private.package.ClassName`, trying to 'run tests' again leads to same error but different classnames, seemingly random:

`[Error - 18:17:04] 10 Feb 2025, 18.17.04 failed to search tests in: java
<anonymous #1> {key=Lcom/private/package/ClassName$45244;} [in execute(com.another.private.package.ClassName) [in <lambda #1> [in functionName(String, Date, Date) [in ClassName [in ClassName.java [in com.private.package [in src/main/java [in project-name]]]]]]]] does not exist
Java Model Exception: Error in Java Model (code 969): <anonymous #1> {key=Lcom/private/package/ClassName$45244;} [in execute(com.another.private.package.ClassName) [in <lambda #1> [in functionName(String, Date, Date) [in ClassName [in ClassName.java [in com.private.package [in src/main/java [in project-name]]]]]]]] does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:546)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:589)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:292)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:278)
	at org.eclipse.jdt.internal.core.Member.getFlags(Member.java:193)
	at org.eclipse.jdt.internal.junit.util.CoreTestSearchEngine.isAccessibleClass(CoreTestSearchEngine.java:64)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.internalIsTest(JUnit5TestFinder.java:251)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.findTestsInContainer(JUnit5TestFinder.java:221)
	at com.microsoft.java.test.plugin.searcher.JUnit5TestSearcher.findTestItemsInContainer(JUnit5TestSearcher.java:130)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.findTestPackagesAndTypes(TestSearchUtils.java:168)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:61)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:615)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
`
(class/package/function names replaced with placeholders due to being a private project)
