### ISSUE TITLE
Test classes not found

### ISSUE THREAD

**Issue by dsyer** [redhat-developer/vscode-java#427]
I don't really know what I did to this project. Normally I'd say it works for me, but now I can't see any test running features in JUnit tests, and there are red markers on the test classes saying they can't be found. So the language server is running, and seems to work for the compile scope classes. It's a maven project (fresh checkout from github).

Here are some logs from the JLS output:

```
[Warn  - 08:01:23] 01-Feb-2018 08:01:14 While loading class "org.eclipse.m2e.core.internal.MavenPluginActivator", thread "Thread[Worker-1: Initialize Workspace,5,main]" timed out waiting (5032ms) for thread "Thread[pool-1-thread-1,5,main]" to finish starting bundle "org.eclipse.m2e.core_1.9.0.20180131-0104 [53]". To avoid deadlock, thread "Thread[Worker-1: Initialize Workspace,5,main]" is proceeding but "org.eclipse.m2e.core.internal.MavenPluginActivator" may not be fully initialized.
Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="1.9.0.20180131-0104"; osgi.identity="org.eclipse.m2e.core"; singleton:="true" [id=53] STARTED [STARTED]
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="1.9.0.20180131-0104"; osgi.identity="org.eclipse.m2e.core"; singleton:="true" [id=53] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:114)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:505)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:392)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:466)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.m2e.jdt.MavenJdtPlugin.start(MavenJdtPlugin.java:93)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:114)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:505)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:392)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:470)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:609)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:177)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:931)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:60)
	at org.eclipse.jdt.core.JavaCore.computeClasspathContainerInitializer(JavaCore.java:3609)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainerInitializer(JavaCore.java:3585)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3145)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2112)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3562)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3113)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3277)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2354)
	at org.eclipse.jdt.internal.core.DeltaProcessor.createExternalArchiveDelta(DeltaProcessor.java:1000)
	at org.eclipse.jdt.internal.core.DeltaProcessor.checkExternalArchiveChanges(DeltaProcessor.java:870)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2079)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:476)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:297)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:287)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:269)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:369)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1546)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1083)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1102)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.createJavaProject(ProjectsManager.java:255)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$1.run(ProjectsManager.java:92)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:38)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:732)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2214)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5676)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5633)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:86)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:193)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 69 more

[Error - 08:01:24] 01-Feb-2018 08:01:14 An error occurred while automatically activating bundle org.eclipse.m2e.jdt (54).
Exception in org.eclipse.m2e.jdt.MavenJdtPlugin.start() of bundle org.eclipse.m2e.jdt.
org.osgi.framework.BundleException: Exception in org.eclipse.m2e.jdt.MavenJdtPlugin.start() of bundle org.eclipse.m2e.jdt.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:800)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:114)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:505)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:392)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:470)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:609)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:177)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:931)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:60)
	at org.eclipse.jdt.core.JavaCore.computeClasspathContainerInitializer(JavaCore.java:3609)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainerInitializer(JavaCore.java:3585)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3145)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2112)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3562)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3113)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3277)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2354)
	at org.eclipse.jdt.internal.core.DeltaProcessor.createExternalArchiveDelta(DeltaProcessor.java:1000)
	at org.eclipse.jdt.internal.core.DeltaProcessor.checkExternalArchiveChanges(DeltaProcessor.java:870)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2079)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:476)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:297)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:287)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:269)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:369)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1546)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1083)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1102)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.createJavaProject(ProjectsManager.java:255)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$1.run(ProjectsManager.java:92)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:38)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:732)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2214)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5676)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5633)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:86)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:193)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.lang.NullPointerException
	at org.eclipse.m2e.jdt.MavenJdtPlugin.start(MavenJdtPlugin.java:102)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	... 52 more

[Error - 08:01:48] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.getProviders(ResourceChangeValidator.java:101)
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.validateChange(ResourceChangeValidator.java:150)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.check(ResourceChangeChecker.java:86)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.checkFilesToBeChanged(ResourceChangeChecker.java:71)
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractMethodRefactoring.checkInitialConditions(ExtractMethodRefactoring.java:330)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getExtractMethodProposal(QuickAssistProcessor.java:265)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getAssists(QuickAssistProcessor.java:152)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:80)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$12(JDTLanguageServer.java:520)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Error - 08:01:48] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.getProviders(ResourceChangeValidator.java:101)
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.validateChange(ResourceChangeValidator.java:150)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.check(ResourceChangeChecker.java:86)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.checkFilesToBeChanged(ResourceChangeChecker.java:71)
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractMethodRefactoring.checkInitialConditions(ExtractMethodRefactoring.java:330)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getExtractMethodProposal(QuickAssistProcessor.java:265)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getAssists(QuickAssistProcessor.java:152)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:80)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$12(JDTLanguageServer.java:520)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Error - 08:02:04] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.getProviders(ResourceChangeValidator.java:101)
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.validateChange(ResourceChangeValidator.java:150)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.check(ResourceChangeChecker.java:86)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.checkFilesToBeChanged(ResourceChangeChecker.java:71)
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractMethodRefactoring.checkInitialConditions(ExtractMethodRefactoring.java:330)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getExtractMethodProposal(QuickAssistProcessor.java:265)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getAssists(QuickAssistProcessor.java:152)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:80)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$12(JDTLanguageServer.java:520)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Error - 08:02:55] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.getProviders(ResourceChangeValidator.java:101)
	at org.eclipse.core.resources.mapping.ResourceChangeValidator.validateChange(ResourceChangeValidator.java:150)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.check(ResourceChangeChecker.java:86)
	at org.eclipse.ltk.core.refactoring.participants.ResourceChangeChecker.checkFilesToBeChanged(ResourceChangeChecker.java:71)
	at org.eclipse.jdt.ls.core.internal.corext.refactoring.code.ExtractMethodRefactoring.checkInitialConditions(ExtractMethodRefactoring.java:330)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getExtractMethodProposal(QuickAssistProcessor.java:265)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getAssists(QuickAssistProcessor.java:152)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:80)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$12(JDTLanguageServer.java:520)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

```

**Comment by dsyer** [comment]
Update: I deleted the Eclipse metadata and re-opened the project and now the test classes are found, but my tests are not runnable.

**Comment by dsyer** [comment]
The same project works for me on another machine (same ubuntu release, different packages installed), so there is something about this laptop that sucks. I had issues yesterday with it and ended up deleting all of `~/.config/Code` (which fixed a different problem). Is there any other global state that might be different in the two environments?

**Comment by fbricon** [comment]
Log showed the m2e bits failed to start as the workspace seems to be corrupted. [Deleting the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) is usually a good remedy. 

No idea why the tests are not runnable though. Can you be more specific? Any  message, logs for that? Is the project available publicly?

**Comment by fbricon** [comment]
Also, can you make sure vscode-java is updated to the latest version (0.18.1 as of now)

**Comment by dsyer** [comment]
> Is the project available publicly?

It's the same for all projects. FWIW I was looking at spring-projects/spring-guice and spring-io/initializr today.

I deleted the workspace directory as per the link. I can't see the little "thumbs up" (Ready) icon and I only see a little rocket that has no text on it.I don't think the language server is running at all now. I saw this briefly:

```
[Error - 14:21:21] Connection to server is erroring. Shutting down server.
```

> Also, can you make sure vscode-java is updated to the latest version (0.18.1 as of now)

Yes, that's what I have.

**Comment by fbricon** [comment]
@dsyer both spring-guice and initializr open properly for me. Tests compile. Some tests run some others don't, but that's an issue with the [Java Test Runner](https://github.com/Microsoft/vscode-java-test/issues).

Close VSCode and check with `jps` if you have zombie server processes running:
```
>jps
77089 Jps
76856 org.eclipse.equinox.launcher_1.5.0.v20180119-0753.jar
```
kill whatever org.eclipse.equinox.launcher* process you find and reopen Code.

**Comment by fbricon** [comment]
So m2e failing to start on an existing workspace is a known issue, see #390.

For the tests failing to run, please open a ticket at https://github.com/Microsoft/vscode-java-test/issues (cc @ansyral).

Closing as a duplicate.
