### ISSUE TITLE
Support running the JLS with Java 9

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#43]
We check the java version used to run the JLS is 1.8. We should ensure 1.9 works too.

**Comment by fbricon** [comment]
Relates to #44

**Comment by fbricon** [comment]
And just when I thought this was over, I realized it fails with the latest JDK 9-ea release (I was testing with an old 1.9.0-ea-b63 build).
- the version prefix is different, that's easy to fix
- then I get an error similar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=498728 on startup:

```
java.version=9-ea
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=fr_FR
Framework arguments:  --add-modules=java.se.ee
Command-line arguments:  -data /Users/fbricon/Library/Application Support/Code - Insiders/User/workspaceStorage/b8821950c971f4d89c32232a9065b58c/redhat.java/jdt_ws --add-modules=java.se.ee

!ENTRY org.eclipse.core.resources 2 10035 2016-10-11 15:47:38.002
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.osgi 4 0 2016-10-11 15:47:38.479
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: java/sql/Time
	at com.google.gson.Gson.<init>(Gson.java:240)
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:569)
	at org.jboss.tools.langs.base.LSPServer.<init>(LSPServer.java:143)
	at org.jboss.tools.vscode.java.internal.JavaClientConnection.<init>(JavaClientConnection.java:71)
	at org.jboss.tools.vscode.java.internal.JavaLanguageServerPlugin.startConnection(JavaLanguageServerPlugin.java:49)
	at org.jboss.tools.vscode.java.internal.JavaLanguageServerPlugin.startLanguageServer(JavaLanguageServerPlugin.java:103)
	at org.jboss.tools.vscode.java.internal.LanguageServer.start(LanguageServer.java:26)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-ea/Method.java:535)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.lang.ClassLoader.findClass(java.base@9-ea/ClassLoader.java:665)
	at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:491)
	at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:424)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:360)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:424)
	... 20 more

```

**Comment by fbricon** [comment]
PR #174 provides a way to start the language server with JDK 9, but doesn't provide support for building Java 9 projects.
