### ISSUE TITLE
JDT.LS crashes repeatedly

### ISSUE THREAD

**Issue by oakad** [redhat-developer/vscode-java#439]
##### Environment
- Operating System: Windows 10
- JDK version: 9.0.4
- Visual Studio Code version: 1.20.0
- Java extension version: 0.18.1

##### Steps To Reproduce
Happens persistently and repeatedly

Attempt to use vscode-java extension results in JDT.LS crashing repeatedly, every minute or so (everything appears to work fine between crashes). Most of the time JDT crashes silently, occasionally a stack trace is visible in the output window (I have attempted tracing at higher verbosity level, but could not obtain any further information).

I have used vscode.java 0.18 on the very same project on Linux (jdk-9.0.1) with no issues.

[Trace - 18:41:13] Received response 'codeLens/resolve - (5)' in 51ms. Request failed: Internal error. (-32603).
[Error - 18:41:13] Request codeLens/resolve failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createAnnotation(BinaryTypeBinding.java:169)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createAnnotations(BinaryTypeBinding.java:182)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:904)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:973)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:535)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1023)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1009)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:1004)
	at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.accept(HierarchyResolver.java:115)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:314)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1642)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getResolvedType(LookupEnvironment.java:1564)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getResolvedType(LookupEnvironment.java:1563)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getResolvedJavaBaseType(LookupEnvironment.java:1576)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getJavaLangObject(Scope.java:2824)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectSuperclass(ClassScope.java:955)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1120)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:359)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:590)
	at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.resolve(HierarchyResolver.java:824)
	at org.eclipse.jdt.internal.core.hierarchy.HierarchyResolver.resolve(HierarchyResolver.java:633)
	at org.eclipse.jdt.internal.core.hierarchy.HierarchyBuilder.buildSupertypes(HierarchyBuilder.java:126)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:166)
	at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:320)
	at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1316)
	at org.eclipse.jdt.internal.core.CreateTypeHierarchyOperation.executeOperation(CreateTypeHierarchyOperation.java:91)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:732)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:798)
	at org.eclipse.jdt.internal.core.SourceType.newSupertypeHierarchy(SourceType.java:788)
	at org.eclipse.jdt.internal.core.SourceType.newSupertypeHierarchy(SourceType.java:739)
	at org.eclipse.jdt.internal.core.search.IndexSelector.getFocusedElementsAndTypes(IndexSelector.java:163)
	at org.eclipse.jdt.internal.core.search.IndexSelector.initializeIndexLocations(IndexSelector.java:224)
	at org.eclipse.jdt.internal.core.search.IndexSelector.getIndexLocations(IndexSelector.java:295)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.selectIndexURLs(JavaSearchParticipant.java:129)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.getIndexes(PatternSearchJob.java:83)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.ensureReadyToRun(PatternSearchJob.java:56)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:174)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:231)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:592)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:604)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.findReferences(CodeLensHandler.java:140)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.resolve(CodeLensHandler.java:90)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:560)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 4 more

[Trace - 18:41:14] Received response 'codeLens/resolve - (6)' in 380ms.

**Comment by fbricon** [comment]
Do you get an `extension crashed 5 times in the last 3 minutes` kind of message?
Do you see shutdown statements in the log?

**Comment by fbricon** [comment]
Can you try running the server with jdk 8?
Have you tried [cleaning the workspace](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)?

**Comment by oakad** [comment]
1. The extension crash message is there, as expected
2. In the vscode output window the server just starts over. I'm not sure where to look for other log files on Windows.

As to the rest - will do further experiments.

**Comment by fbricon** [comment]
That reminds me about a problem with zombie java processes preventing new instances to start.
- Close all your vscode instances
- in a terminal, run `jps` and check all java `org.eclipse.equinox.launcher` processes, like
```
> jps
2082 org.eclipse.equinox.launcher_1.5.0.v20180119-0753.jar
4307 org.eclipse.equinox.launcher_1.5.0.v20180119-0753.jar
2060 org.eclipse.equinox.launcher_1.5.0.v20180119-0753.jar
```
- if you see any of those processes, despite having vscode closed, just kill them all and try to reopen vscode

**Comment by oakad** [comment]
I confirmed that there are no zombie instances. Also, if I reload the window LS restarts properly and works for some (not very prolonged) time.

I have tried it with an old maven project which I never opened in vscode before. Same symptoms - LS works properly, but regularly crashes.

Unfortunately, I don't have  jdk-8 on that windows box, so could not try that. But again, on Linux jdk-9 works just fine, no issues whatsoever.

Are there any additional log files or tracing options I can look at (apart from the output window in vscode)?

**Comment by oakad** [comment]
I have tried java 1.8.0_162. Same results - LS keeps crashing. I also tried to supply it all kinds of diagnostic switches on command line, as well as attaching a java debugger to it. No luck - it crashes instantly, no diagnostics can be obtained. Some issue on the native level I'd imagine.

The whole thing is rather strange as the machine is a plain Win 10 enterprise install without any other issues (other java apps work just fine).

**Comment by oakad** [comment]
I have got a debug build of openjdk-1.8.0_111 and tried to dump the process, like so:

    .\procdump64.exe -ma -e -t <java_pid>

Procdump reported no exception and dumped the LS process on sudden exit. Upon inspection of the dump only one thread is still active at exit, and it looks like a deliberate exit, not crash:

    jvm!vm_direct_exit+0x15 [c:\ojdkbuild\lookaside\java-1.8.0-openjdk\hotspot\src\share\vm\runtime\java.cpp @ 604] 
    jvm!VM_Operation::evaluate+0x102 [c:\ojdkbuild\lookaside\java-1.8.0-openjdk\hotspot\src\share\vm\runtime\vm_operations.cpp @ 63] 
    jvm!VMThread::evaluate_operation+0x148 [c:\ojdkbuild\lookaside\java-1.8.0-openjdk\hotspot\src\share\vm\runtime\vmthread.cpp @ 379] 
    jvm!VMThread::loop+0x366 [c:\ojdkbuild\lookaside\java-1.8.0-openjdk\hotspot\src\share\vm\runtime\vmthread.cpp @ 502] 
    jvm!VMThread::run+0xcb [c:\ojdkbuild\lookaside\java-1.8.0-openjdk\hotspot\src\share\vm\runtime\vmthread.cpp @ 281] 
    jvm!java_start+0xbe [c:\ojdkbuild\lookaside\java-1.8.0-openjdk\hotspot\src\os\windows\vm\os_windows.cpp @ 441] 

However, those exits come as a surprise to vscode-java, which counts them as crashes.
