### ISSUE TITLE
error message on console

### ISSUE THREAD

**Issue by qiukeren** [redhat-developer/vscode-java#46]
on MAC OSX, 

the version is the newest version from vscode ,and vscode is the newest release from vscode(downloaded today)(1.5.3).

node version is v6.7.0

mac version is sierra

how ever, the console shows these log time after time

```
[Error - 6:20:53 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
[Error - 6:21:59 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
[Error - 6:22:03 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
[Error - 6:22:04 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
[Error - 6:22:50 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
[Error - 6:28:35 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
[Error - 6:30:26 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/mudu/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)

```

**Comment by gorkem** [comment]
Error message should be harmless. It is normal that symbol on a file can not be resolved, for instance when it is activated on a keyword. It looks like server fails to report back the request ID on those cases and VSCode gets confused and reports on console.

**Comment by gorkem** [comment]
Can you verify this still exists on new 0.0.5 release?

**Comment by qiukeren** [comment]
It stills happens when it occurs like `cannot find import some class` however the class is already there.
(A condition hard to describe with two errors, the first is `cannot find import class`,the second is response is not in law)

(It is confusing that when I copy the import class from the origin line to cover the import line and save, the `cannot find import` does not happen again)



**Thanks for your work,

In common condition, it is considered to be fixed.**
