### ISSUE TITLE
Message: Problem during accessing system variable: http_proxy

### ISSUE THREAD

**Issue by 38leinaD** [redhat-developer/vscode-java#471]
I always see an expcetion in the language-server log related to no proxy beeing set. But i am not in an proxied environment.
Expected: No error/stacktrace should be printed to the language-server log.

##### Environment
- Operating System: Centos 7
- JDK version: 1.8.0_151
- Visual Studio Code version: 1.21.1
- Java extension version: 0.3.0; Language Support for Java: 0.21.0

##### Steps To Reproduce
1. Open a Java Project in VSCode. E.g. standard project generated by Gradle 4.5 "gradle init --type java-application"
2. Inspect Output / Langugae Server Log

[Error - 9:27:01 AM] Mar 17, 2018 9:26:59 AM Problem during accessing system variable: https_proxy
no host in 
java.lang.NullPointerException: no host in 
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.eclipse.core.internal.net.proxy.unix.UnixProxyProvider.getSystemProxyInfo(UnixProxyProvider.java:163)
	at org.eclipse.core.internal.net.proxy.unix.UnixProxyProvider.getProxyForTypes(UnixProxyProvider.java:90)
	at org.eclipse.core.internal.net.proxy.unix.UnixProxyProvider.getProxyData(UnixProxyProvider.java:83)
	at org.eclipse.core.internal.net.ProxyManager.getNativeProxyData(ProxyManager.java:169)
	at org.eclipse.core.internal.net.ProxySelector.getProxyData(ProxySelector.java:91)
	at org.eclipse.core.internal.net.ProxyType.getProxyData(ProxyType.java:434)
	at org.eclipse.core.internal.net.ProxyType.updateSocksSystemProperties(ProxyType.java:489)
	at org.eclipse.core.internal.net.ProxyType.updateSystemProperties(ProxyType.java:223)
	at org.eclipse.core.internal.net.ProxyType.initialize(ProxyType.java:517)
	at org.eclipse.core.internal.net.ProxyManager.initialize(ProxyManager.java:264)
	at org.eclipse.core.internal.net.Activator.start(Activator.java:175)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.eclipse.buildship.core.CorePlugin.ensureProxySettingsApplied(CorePlugin.java:130)
	at org.eclipse.buildship.core.CorePlugin.start(CorePlugin.java:116)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1002)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:354)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:468)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:114)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:505)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:328)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:392)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:466)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jdt.ls.core.internal.managers.GradleBuildSupport.cleanGradleModels(GradleBuildSupport.java:68)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager$1.run(ProjectsManager.java:91)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:38)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:732)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5727)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5684)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:86)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:201)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

Note the "no host in " contains the empty proxy-string. I.e. If i set a proxy just to test the difference to e.g. "abc" via export http_proxy=abc, i get the same exception with "no host in abc".

**Comment by snjeza** [comment]
Could you try the following:

```
unset http_proxy
code .
```

**Comment by 38leinaD** [comment]
i am a little suprised i did not think about it myself. that resolved it. thanks.
