### ISSUE TITLE
Go to/Peek definition only results in "No definition found"

### ISSUE THREAD

**Issue by ncarmona21** [redhat-developer/vscode-java#512]
Go to and peek definition actions are not finding definitions. Tried uninstalling and reinstalling the Java Extension pack for VSCode and browsed the other issues with no avail. 

##### Environment
- Operating System:Centos 7
- JDK version: 1.8.0_161
- Visual Studio Code version: 1.22.2
- Java extension version: 0.23.0

##### Steps To Reproduce
1. Right click method
2. "Go to definition" 

Logs:

[on hover and when right click + go to or peek definition]:
ERR Invalid arguments: Error: Invalid arguments
	at new e (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:423:566)
	at asRange (/home/ncarmona/.vscode/extensions/redhat.java-0.23.0/node_modules/vscode-languageclient/lib/protocolConverter.js:41:16)
	at asLocation (/home/ncarmona/.vscode/extensions/redhat.java-0.23.0/node_modules/vscode-languageclient/lib/protocolConverter.js:211:59)
	at item.map (/home/ncarmona/.vscode/extensions/redhat.java-0.23.0/node_modules/vscode-languageclient/lib/protocolConverter.js:201:43)
	at Array.map (native)
	at asDefinitionResult (/home/ncarmona/.vscode/extensions/redhat.java-0.23.0/node_modules/vscode-languageclient/lib/protocolConverter.js:201:25)
	at propagateAslWrapper (/home/ncarmona/.vscode/extensions/vscjava.vscode-maven-0.7.0/node_modules/async-listener/index.js:502:23)
	at /home/ncarmona/.vscode/extensions/vscjava.vscode-maven-0.7.0/node_modules/async-listener/glue.js:188:31
	at /home/ncarmona/.vscode/extensions/vscjava.vscode-maven-0.7.0/node_modules/async-listener/index.js:539:70
	at /home/ncarmona/.vscode/extensions/vscjava.vscode-maven-0.7.0/node_modules/async-listener/glue.js:188:31
	at <anonymous>

**Comment by fbricon** [comment]
Are you still seeing this issue?
