### ISSUE TITLE
Formatting code doesnt work sometimes.

### ISSUE THREAD

**Issue by gitorko** [redhat-developer/vscode-java#520]
Formatting java code sometimes doesnt work. The following is the error in output log. Looks like array index out of bound error.

[Error - 15:14:34] Request textDocument/formatting failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by mrrobworks** [comment]
Got the same issue today. I resolved it using the <b>[latest snapshot realse 1.16.21 of lombok](https://projectlombok.org/download-edge)</b>.

<b>User settings:</b>
`"java.jdt.ls.vmargs": "-javaagent:<path-to-lombok-edge.jar> -Xbootclasspath/a:<path-to-lombok-edge.jar>"`
