### ISSUE TITLE
Error in the console - response has neither result nor error

### ISSUE THREAD

**Issue by navneetkarnani** [redhat-developer/vscode-java#55]
[Error - 8:14:38 AM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/navneet/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/navneet/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/navneet/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/navneet/.vscode/extensions/redhat.java-0.0.4/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)

**Comment by gorkem** [comment]
Can you verify this still exists with the new 0.0.5 release?

**Comment by navneetkarnani** [comment]
Don't see this any more after upgrading.

**Comment by navneetkarnani** [comment]
Spoke too soon:


[Error - 7:16:28 PM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/navneet/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/Users/navneet/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/Users/navneet/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/Users/navneet/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

**Comment by tszebeni** [comment]
I experience the same error message. Also there are some local java class the plugin can't recognise and marks with error. The project compiles otherwise.

**Comment by gorkem** [comment]
@tszebeni is there a pattern to those local classes. Do you have an example project that I can use to repro.

**Comment by kjunghoan** [comment]
I'm still getting this same error:

2024-04-28 12:28:08.022 [error] [redhat.java] provider FAILED
2024-04-28 12:28:08.022 [error] Error: The received response has neither a result nor an error property.
	at /home/kjunghoan/.vscode-server/extensions/redhat.java-1.30.0-linux-x64/dist/extension.js:2:1105294
	at ie (/home/kjunghoan/.vscode-server/extensions/redhat.java-1.30.0-linux-x64/dist/extension.js:2:1105375)
	at /home/kjunghoan/.vscode-server/extensions/redhat.java-1.30.0-linux-x64/dist/extension.js:2:1099815
	at Immediate.<anonymous> (/home/kjunghoan/.vscode-server/extensions/redhat.java-1.30.0-linux-x64/dist/extension.js:2:1099835)
	at process.processImmediate (node:internal/timers:476:21)
