### ISSUE TITLE
Problem getting code lense for app

### ISSUE THREAD

**Issue by arafato** [redhat-developer/vscode-java#58]
Hi --, 

I've used the following maven command to create a project 
`mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=create-device-identity -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`

When I open the project I get the following error message:

```
[Error - 15:44:09] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:09] 12.10.2016 15:44:02 Problem with codeComplete forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:72)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.handle(CompletionHandler.java:43)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.handle(CompletionHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:16] 12.10.2016 15:44:02 Problem with compute occurrences forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentHighlightHandler.computeOccurrences(DocumentHighlightHandler.java:50)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentHighlightHandler.handle(DocumentHighlightHandler.java:97)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentHighlightHandler.handle(DocumentHighlightHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:17] 12.10.2016 15:44:02 Problem with compute occurrences forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentHighlightHandler.computeOccurrences(DocumentHighlightHandler.java:50)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentHighlightHandler.handle(DocumentHighlightHandler.java:97)
	at org.jboss.tools.vscode.java.internal.handlers.DocumentHighlightHandler.handle(DocumentHighlightHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:44] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:45] 12.10.2016 15:44:02 Problem with codeComplete forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:72)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.handle(CompletionHandler.java:43)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.handle(CompletionHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:45] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:46] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:49] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:50] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:50] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[Error - 15:44:51] 12.10.2016 15:44:02 Problem getting code lenses forApp.java
create-device-identity does not exist
Java Model Exception: Java Model Status [create-device-identity does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:137)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:134)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
	at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:261)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea what might cause this behaviour? Thanks!

**Comment by arafato** [comment]
Now it's suddenly working...

**Comment by gorkem** [comment]
When the project is started for the first time, we collect the dependencies through maven and the project is not properly initialized yet. I think the model problems were due to that.
