### ISSUE TITLE
Java Model Exception: Java Model Status [src/main/java/suddenly.in.dot.notation [in some-maven-submodule] is not on its project's build path]

### ISSUE THREAD

**Issue by rubin55** [redhat-developer/vscode-java#588]
I have a maven project, with 5 submodules, nothing too special, Spring Boot 2, Lombok, AWS SDK. Project builds fine, ie, I can mvn test/compile/package/install to hearts' delight.

When I open this project in VS Code, I get the following errors (many of them, see also attached log):

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2018-07-11 18:14:02.128
!MESSAGE Failed to publish diagnostics.
!STACK 1
Java Model Exception: Java Model Status [src/main/java/this.in.dot.notation.why [in aesop-dfp] is not on its project's build path]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:580)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:253)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:527)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:527)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1240)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:593)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:323)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:309)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:295)
	at org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.publishDiagnostics(BuildWorkspaceHandler.java:112)
	at org.eclipse.jdt.ls.core.internal.handlers.BuildWorkspaceHandler.buildWorkspace(BuildWorkspaceHandler.java:65)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$21(JDTLanguageServer.java:672)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$22(JDTLanguageServer.java:716)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
!SUBENTRY 1 org.eclipse.jdt.core 4 1006 2018-07-11 18:14:02.132
!MESSAGE src/main/java/this.in.dot.notation.why [in aesop-dfp] is not on its project's build path
```

Note: I changed the package name.

##### Environment
- Operating System: Windows 10 x64
- JDK version: OpenJDK 8 r163 x64
- Visual Studio Code version: 1.25.0
- Java extension version: 0.28.0

##### Steps To Reproduce
1. Open Maven project in VS code
2. Open log file (see attached)

[jdt-ls.log](https://github.com/redhat-developer/vscode-java/files/2185385/jdt-ls.log)

##### Current Result
Code completion doesn't work.

##### Expected Result
Code completion works.

**Comment by rubin55** [comment]
Check this line in the logs:

```!MESSAGE src/main/java/some.partial.package.name/entity [in aesop-dfp] is not on its project's build path
```

It seems to me a part of the path is accidentally not a path but a package part. Extra hint is the `/entity` on the end, the full package name in that case is indeed `some.partial.package.name.entity` and the path is then `some/partial/package/name/entity`.. Seems fishy to me.

**Comment by kflu** [comment]
I'm seeing a similar error.

**Comment by fbricon** [comment]
Can you guys please attach a sample project reproducing this error?

**Comment by schmidp** [comment]
same problem

**Comment by fbricon** [comment]
That's really odd. Can you try the "Clean the Java Language server workspace" command?
If it doesn't fix the issue, we'll definitely need a sample project to reproduce this issue

**Comment by schmidp** [comment]
@fbricon Cleaning the workspace helped. Thank you. I will see if I can manage to reduce our project to a sample.

**Comment by jimtng** [comment]
> Can you try the "Clean the Java Language server workspace" command?

@fbricon thanks, that solved my problem

**Comment by anandbibek** [comment]
I've the same error with an error message like 

```
Java Model Exception: Error in Java Model (code 1006): _/src/xx/xx/xx/xx/protectedModel/view/client/.ade_path [in protectedModel_48d582b1] is not on its project's build path
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:584)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:254)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:528)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:248)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:528)
```

Errors are always with this specific folder types. .ade_path is some folder that is maintained by our VCS and possibly contains symlinks and all weird stuff. I don't want java extension to be going in there. How can I exclude such folder?

Tried below two and didn't make a difference 

```
"java.project.resourceFilters": [
        "node_modules",
        "\\.git",
        "\\.ade_path"
    ],
    "java.import.exclusions": [
        "**/.ade_path/**",
        "**/node_modules/**",
        "**/.metadata/**",
        "**/archetype-resources/**",
        "**/META-INF/maven/**"
    ],
```

**Comment by anandbibek** [comment]
More information on this:

- No matter how many times I tried cleaning workspace and reopening the project, it never really worked (would not recognize all java source files properly).
- If I forced "Rebuild All" it would recognize more java source files, but not all.
- It also never picked up the library references I added in my workspace file.

After tinkering around sometime, finally made it to work, by comparing with a working project I had. Did the following:

- Opened up file `/scratch/anaray/.vscode-server/data/User/workspaceStorage/647c049edba9537d8fc502620dd6860c/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.core.resources/.projects/protectedModel_48d582b1/.project` and added following snippet manually there which were missing compared to my working project

```
<nature>org.eclipse.jdt.ls.unmanagedFolderNature</nature>
```

```
       <filteredResources>
		<filter>
			<id>1675774599078</id>
			<name></name>
			<type>30</type>
			<matcher>
				<id>org.eclipse.core.resources.regexFilterMatcher</id>
				<arguments>node_modules|\.git|\.ade_path|__CREATED_BY_JAVA_LANGUAGE_SERVER__</arguments>
			</matcher>
		</filter>
	</filteredResources>
```

- Also opened up `/scratch/anaray/.vscode-server/data/User/workspaceStorage/647c049edba9537d8fc502620dd6860c/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.core.resources/.projects/protectedModel_48d582b1/.classpath` and added all referenced lib entries from working project.

**Comment by anandbibek** [comment]
@fbricon could you please have a look? Maybe you could point me to some resources, which could get me up to speed to debug and understand the issues myself. Might be able to contribute in a better fashion.

**Comment by anandbibek** [comment]
Now that I've manually messed with the project internal files and made the compilation work 90% at the least, any further changes in workspace file to add referenced libraries, or adding libraries via UI are not picked up. Seems like manual edits have somehow put the project in limbo.

**Comment by anandbibek** [comment]
Sounds like issue #1655 - I can't set up project without excluding bad folders, I cannot exclude bad folders if project is not set up :)
Also #2929 on top 😿
