### ISSUE TITLE
0.30.0 fails to start a spring-boot project using yaml properties

### ISSUE THREAD

**Issue by y0n3t4n1** [redhat-developer/vscode-java#629]
[provide a description of the issue]

##### Environment
- Operating System: macOS 10.13.6
- JDK version: 1.8.0_101
- Visual Studio Code version: 1.26.1
- Java extension version:
  - redhat.java-0.30.0
  - vscjava.vscode-java-debug-0.12.1

##### Steps To Reproduce
1. Download and open a sample project mentioned in Microsoft/vscode-java-debug#399
2. Start a debugging session

[attach a sample project reproducing the error] https://github.com/bobjiang1988/java-debugger
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
```
01:05:37.050 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to load property source from location 'classpath:/application.yml'
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:535)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadForFileExtension(ConfigFileApplicationListener.java:494)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:462)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$null$4(ConfigFileApplicationListener.java:444)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$load$5(ConfigFileApplicationListener.java:443)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:440)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:331)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:213)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:196)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:183)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
        at com.example.demo.DemoApplication.main(DemoApplication.java:10)
Caused by: java.lang.IllegalStateException: Attempted to load applicationConfig: [classpath:/application.yml] but snakeyaml was not found on the classpath
        at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:47)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadDocuments(ConfigFileApplicationListener.java:542)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:515)
        ... 23 common frames omitted
```

##### Current Result
With 0.30.0, the project fails to start because of missing snakeyaml in the classpath.  Downgrading Language Support for Java to 0.29.0 also works.

##### Expected Result
The project starts fine
##### Additional Informations
Adding an extra dependency to snakeyaml in pom.xml, as explained in the original report, also fixes the problem.  However, as the dependency to snakeyaml is caused by the spring-boot project and not by this sample project itself,  I guess I don't have to add that extra dependency in the project's pom.xml.

The version 0.30.0 is already on Visual Studio Marketplace, but it's somehow not listed on your releases page.

**Comment by snjeza** [comment]
Related issues:
https://github.com/Microsoft/vscode-java-debug/issues/402
https://bugs.eclipse.org/bugs/show_bug.cgi?id=414645

**Comment by fbricon** [comment]
This issue must be fixed on the debugger side, see Microsoft/vscode-java-debug#402.
