### ISSUE TITLE
The language server always throws exception...

### ISSUE THREAD

**Issue by bobjiang1988** [redhat-developer/vscode-java#630]
The language server always throws exception. It really troubled me.

Log's here.
```
 Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid number literal : >1L<
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalArgumentException: Invalid number literal : >1L<
	at org.eclipse.jdt.core.dom.NumberLiteral.setToken(NumberLiteral.java:177)
	at org.eclipse.jdt.core.dom.AST.newNumberLiteral(AST.java:2182)
	at org.eclipse.jdt.ls.core.internal.corext.fix.SerialVersionDefaultOperation.addInitializer(SerialVersionDefaultOperation.java:52)
	at org.eclipse.jdt.ls.core.internal.corext.fix.AbstractSerialVersionOperation.rewriteAST(AbstractSerialVersionOperation.java:105)
	at org.eclipse.jdt.internal.corext.fix.CompilationUnitRewriteOperationsFixCore.createChange(CompilationUnitRewriteOperationsFixCore.java:98)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.FixCorrectionProposal.createTextChange(FixCorrectionProposal.java:85)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.CUCorrectionProposal.createChange(CUCorrectionProposal.java:152)
	at org.eclipse.jdt.ls.core.internal.corrections.proposals.ChangeCorrectionProposal.getChange(ChangeCorrectionProposal.java:143)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCommandFromProposal(CodeActionHandler.java:102)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:77)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:557)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$25(JDTLanguageServer.java:751)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```

**Comment by yaohaizh** [comment]
@bobjiang1988  Could you help provide the sample project to reproduce this issue and include the reproduce steps?  Thanks.

**Comment by bobjiang1988** [comment]
It can not be reproduced all the time. And a similar issue is #627 .
By the way, I can also get an exception like "Connection to server is erroring. Shutting down server.".

**Comment by yaohaizh** [comment]
![untitled](https://user-images.githubusercontent.com/17268517/45400108-594a2a00-b67d-11e8-956e-61cf05c464e4.png)
@fbricon @snjeza   We got similar issue for eclipse with lombok. How to log an bug for eclipse?

**Comment by yaohaizh** [comment]
Track upstream issue: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538957

**Comment by yaohaizh** [comment]
https://github.com/rzwitserloot/lombok/issues/1860

**Comment by fbricon** [comment]
Exceptions are no longer thrown in this case. Closing.
