### ISSUE TITLE
Issue about start java in VSCode

### ISSUE THREAD

**Issue by planck35** [redhat-developer/vscode-java#648]
[provide a description of the issue]

##### Environment
- Operating System: Win10
- JDK version: jdk-9.0.1
- Visual Studio Code version: latest
- Java extension version: latest

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
I have some problems about use java in VSCode.
I used to write Python in VSCode and recently I want to practice Java in VScode
I got some problems. and can't figure why
1)
![image](https://user-images.githubusercontent.com/35860851/46055658-e5d6fc80-c101-11e8-9c75-fa9a854575ec.png)
how this notice happens.
2) here is my debug json file
![image](https://user-images.githubusercontent.com/35860851/46055704-0e5ef680-c102-11e8-9580-a92bb3ac7bbe.png)
and I select that Debug(launch) one
It said Build failed. If I proceed.
It report the following message
Debug Console:
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	Syntax error on token "void", @ expected
	Syntax error on token "]", :: expected after this token
	Syntax error, insert "enum Identifier" to complete EnumHeader

	at test.main(test.java:2)

Terminal:
SyntaxError: invalid syntax
PS C:\Users\planck\Desktop\leetcode\leetcode> cd 'c:\Users\planck\Desktop\leetcode\leetcode'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; ${env:PYTHONPATH}='C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd'; & 'C:\Users\planck\AppData\Local\Programs\Python\Python37\python.exe' '-m' 'ptvsd' '--host' 'localhost' '--port' '51046' 'c:\Users\planck\Desktop\leetcode\leetcode\.vscode\launch.json'
Traceback (most recent call last):
  File "C:\Users\planck\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\planck\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 211, in <module>
    singlesession=args.single_session)
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\__main__.py", line 205, in main
    debug_main(addr, name, kind, *extra, **kwargs)
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 30, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 64, in run_file
    run(argv, addr, **kwargs)
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_local.py", line 125, in _run
    _pydevd.main()
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1743, in main
    debugger.connect(host, port)
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1099, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1106, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\planck\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "c:\Users\planck\Desktop\leetcode\leetcode\.vscode\launch.json", line 2
    // Use IntelliSense to learn about possible attributes.
     ^
SyntaxError: invalid syntax

Can anybody help me!!
I am desperate
Thanks

**Comment by planck35** [comment]
> Your class declaration has syntax error.
> `public class test(){}` -> `public class test{}`

Oh my Gosh!!
Thanks for point out!
I am so stupid, you save my day

**Comment by 4F2E4A2E** [comment]
That's how I've got it to work: https://stackoverflow.com/a/50632086/543426 :man_facepalming:
