### ISSUE TITLE
Java language support not working for JDK 11 gradle project

### ISSUE THREAD

**Issue by xzel23** [redhat-developer/vscode-java#653]
Java language support is not working in Gradle project after update to JDK 11, probably to an old gradle version included in language support.

##### Environment
- Operating System:
macOS 10.13.6 High Sierra

- JDK version: 
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

- Visual Studio Code version:
1.27.2

- Java extension version:
V0.31.0

##### Steps To Reproduce
1. Make sure to have OpenJDK 11 as default Java installation
2. Open a Java Project in VS code

##### Current Result
The "thumbs down" icon appears in the status bar. Stack trace:
[Error - 4:34:21 PM] 26 Sep 2018, 16:34:21 Initialization failed 
Could not determine java version from '11'.
java.lang.IllegalArgumentException: Could not determine java version from '11'.
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
	at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
	at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.javaDeprecationWarning(UnsupportedJavaRuntimeException.java:36)
	at org.gradle.tooling.internal.consumer.ConnectorServices.checkJavaVersion(ConnectorServices.java:59)
	at org.gradle.tooling.internal.consumer.ConnectorServices.createCancellationTokenSource(ConnectorServices.java:41)
	at org.gradle.tooling.GradleConnector.newCancellationTokenSource(GradleConnector.java:95)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.<init>(ToolingApiJob.java:57)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.<init>(SynchronizeGradleBuildsJob.java:46)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.forSingleGradleBuild(SynchronizeGradleBuildsJob.java:122)
	at org.eclipse.buildship.core.workspace.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:58)
	at org.eclipse.buildship.core.workspace.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:53)
	at org.eclipse.buildship.core.workspace.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:48)
	at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerInitializer.loadClasspath(GradleClasspathContainerInitializer.java:58)
	at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerInitializer.initialize(GradleClasspathContainerInitializer.java:39)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3211)
	at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:3095)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2319)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3157)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2128)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3622)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3147)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3311)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2388)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.getRootInfos(DeltaProcessingState.java:311)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.initializeRoots(DeltaProcessingState.java:259)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:733)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2319)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5736)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5693)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:114)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:221)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

##### Expected Result
Java language support works.

##### Additional Informations
I had this problem with older gradle versions on the command line. upgrading gradle to 4.10.2 solved it.

**Comment by fbricon** [comment]
Ok so the problem seems to be caused by [Buildship](https://github.com/eclipse/buildship), which hasn't been updated in a while. Need to check if we can get a more recent build from somewhere

**Comment by xzel23** [comment]
Oh, so the gradle installation used comes from buildship. If that's the case, there might be a simple workaround. At least in eclipse Gradle settings, I can set tell buildship to use the Gradle Wrapper in the project directory. I cannot find a matching setting in vs code-java. Would it be possible to tell vs code-java to use the wrapper instead?

**Comment by xzel23** [comment]
According to [buildship issue #762](https://github.com/eclipse/buildship/issues/762) this will work as of buildship version 2.2.2 which as of today is still unreleased. Soit will probably have to wait for the next buildship release.

**Comment by fbricon** [comment]
The wrapper is used when available. But here the error occurs before the wrapper is being called, in Buildship proper, so we definitely need to get that buildship update

**Comment by snjeza** [comment]
@fbricon Would you like me to update the buildship plugin to the latest 2.2 snapshots?

**Comment by fbricon** [comment]
@snjeza  you can open a PR if you want, so we can test it, but we can't merge until [CQ 17443](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17443)  is approved

**Comment by fbricon** [comment]
@snjeza CQ was approved, go ahead
