### ISSUE TITLE
Busy loop java.nio.file.ClosedFileSystemException; regression

### ISSUE THREAD

**Issue by shoffmeister** [redhat-developer/vscode-java#664]
[provide a description of the issue]

##### Environment
- Operating System: Fedora 28 (current)
- JDK version: Oracle 10.0.2
- Visual Studio Code version: 1.27.2 (current -> repo)
- Java extension version: 0.32

##### Steps To Reproduce
1. start VS code
2. open (big) workspace containing a large set of mvn projects
3. open Java file
// java file opens
// vs code language extension welcome page opens
4. wait

-> builds automatically, but ends up with java.nio.file.ClosedFileSystemException in a busy loop (stack trace below repeats forever), shows "Failed to load tests" in the status bar.

Keeps the laptop hot and noisy.

##### Current Result

[Error - 18:46:01] 04.10.2018, 18:46:01 Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
null
java.nio.file.ClosedFileSystemException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1105)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.checkAccess(ZipFileSystem.java:332)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.checkAccess(ZipPath.java:830)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:185)
	at java.base/java.nio.file.Files.exists(Files.java:2431)
	at org.eclipse.jdt.internal.core.builder.ClasspathMultiReleaseJar.findClass(ClasspathMultiReleaseJar.java:206)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.findClass(ClasspathLocation.java:58)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.findClass(NameEnvironment.java:524)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.findType(NameEnvironment.java:556)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.fromSplitPackageOrOracle(LookupEnvironment.java:414)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.lambda$1(LookupEnvironment.java:289)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(LookupEnvironment.java:384)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:288)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:262)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.findImport(CompilationUnitScope.java:530)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.checkAndSetImports(CompilationUnitScope.java:254)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:501)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:868)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:448)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:267)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:834)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:271)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:324)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:327)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:379)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:400)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

##### Expected Result
No busy looping.
No stack trace.
Clean build.

##### Additional Informations
Searching Google for the exception message, I could not help but notice https://bugs.eclipse.org/bugs/show_bug.cgi?id=539536

**Comment by shoffmeister** [comment]
I would love to contribute a project, but my workspace is too large, sorry.

**Comment by fbricon** [comment]
Apparently JDT fixed their bug. Download the most recent [`java-<version>.vsix` build](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D) and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

Please report back here if that fixes your issue.

**Comment by shoffmeister** [comment]
I can confirm that java-0.33.0-1252.vsix makes the reported problem disappear.

**Comment by fbricon** [comment]
Cool. Thanks for checking.
