### ISSUE TITLE
Getting error: "The received response has neither a result nor an error property" with 0.0.5 on Ubuntu

### ISSUE THREAD

**Issue by emargob** [redhat-developer/vscode-java#67]
Hi,

Getting this error with 0.0.5 using VSCode version 1.6.1 on Ubuntu 14.04 when trying to Ctrl-left-click on a Java HashMap:

[Error - 10:05:52 AM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
[Error - 10:05:52 AM] Request textDocument/definition failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:294:40)
    at StreamMessageReader.callback (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:366:13)
    at StreamMessageReader.onData (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:197:18)
    at Socket.<anonymous> (/home/emargob/.vscode/extensions/redhat.java-0.0.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageReader.js:164:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

**Comment by emargob** [comment]
java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by fbricon** [comment]
I can reproduce with 0.0.5 but not with current master. I'm pretty sure this was fixed with https://github.com/gorkem/java-language-server/commit/3bff066def97987d36d2f8654f6a595a6c9ec7d7 that I forgot to push for the 0.0.5 release.
