### ISSUE TITLE
Getting error: "The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted."

### ISSUE THREAD

**Issue by SirRollo** [redhat-developer/vscode-java#700]
I did the clean workspace command, I reloaded all the Java extensions, I tried it on another Windows machine and there it works.

So, after loading a Java Project via Maven quickstart archetype, it takes a few minutes and I get the error described in the title of this post.

##### Environment
- Operating System: Windows 10 Version 1809
- JDK version: jdk-11.0.1 (tried with 10er version before)
- Visual Studio Code version: 1.28.2
- Java extension version: 0.33.0 (October 23rd, 2018)

##### Steps To Reproduce
1. Loading java project in vscode with maven
2. wait few minutes until error pops up

##### Additional Informations

**Error log I get from developer webview:**

 ```
INFO no standard startup: not a new window
console.ts:136 [Extension Host] vscode-icons is active!
console.ts:136 [Extension Host] settings: {"maxStringLength":0,"showStaticVariables":true,"showQualifiedNames":false,"showHex":false,"enableHotCodeReplace":true,"logLevel":"SEVERE","javaHome":"C:\\Program Files\\Java\\jdk-11.0.1"}
notificationsAlerts.ts:42 The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.
t.onDidNotificationChange @ notificationsAlerts.ts:42
touch.ts:144 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
t.onTouchStart @ touch.ts:144
notificationsAlerts.ts:42 net::ERR_TIMED_OUT
t.onDidNotificationChange @ notificationsAlerts.ts:42
log.ts:171   ERR Running the contributed command:'java.execute.workspaceCommand' failed.: Error: Running the contributed command:'java.execute.workspaceCommand' failed.
    at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:802)
    at e.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:28)
    at Object.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:169)
    at Object.executeJavaLanguageServerCommand (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\Constants\commands.js:32:28)
    at Object.fetchTests (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\Utils\fetchTestUtility.js:7:21)
    at JUnitCodeLensProvider.<anonymous> (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:28:38)
    at Generator.next (<anonymous>)
    at C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:9:71
    at new WrappedPromise (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\es6-wrapped-promise.js:13:18)
    at __awaiter (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:5:12)
    at JUnitCodeLensProvider.provideCodeLenses (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:27:16)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:498:405
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:368
    at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:776)
    at Object.t.asThenable (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:333)
    at e.provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:498:364)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:215
    at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:91)
    at e.$provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:177)
    at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
    at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
    at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:60)
    at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
    at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Log(Extension Host):**

```
[2018-10-31 12:36:48.887] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\npm\dist\main
[2018-10-31 12:38:28.339] [exthost] [error] Error: Language client is not ready yet
    at LanguageClient.sendRequest (C:\Users\Pascal\.vscode\extensions\redhat.java-0.33.0\node_modules\vscode-languageclient\lib\client.js:1694:19)
    at vscode_1.commands.registerCommand.rest (C:\Users\Pascal\.vscode\extensions\redhat.java-0.33.0\out\src\extension.js:220:47)
    at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:706)
    at e.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:28)
    at Object.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:169)
    at Object.executeJavaLanguageServerCommand (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\Constants\commands.js:32:28)
    at Object.fetchTests (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\Utils\fetchTestUtility.js:7:21)
    at JUnitCodeLensProvider.<anonymous> (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:28:38)
    at Generator.next (<anonymous>)
    at C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:9:71
    at new WrappedPromise (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\es6-wrapped-promise.js:13:18)
    at __awaiter (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:5:12)
    at JUnitCodeLensProvider.provideCodeLenses (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-test-0.10.0\out\src\junitCodeLensProvider.js:27:16)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:498:405
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:368
    at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:776)
    at Object.t.asThenable (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:333)
    at e.provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:498:364)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:215
    at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:91)
    at e.$provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:177)
    at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
    at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
    at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:60)
    at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
    at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20) java.execute.workspaceCommand
[2018-10-31 12:38:28.344] [exthost] [error] Error: Language client is not ready yet
    at LanguageClient.sendRequest (C:\Users\Pascal\.vscode\extensions\redhat.java-0.33.0\node_modules\vscode-languageclient\lib\client.js:1694:19)
    at vscode_1.commands.registerCommand.rest (C:\Users\Pascal\.vscode\extensions\redhat.java-0.33.0\out\src\extension.js:220:47)
    at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:706)
    at e.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:28)
    at Object.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:169)
    at Object.executeJavaLanguageServerCommand (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\commands.js:19:28)
    at C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:108:35
    at Generator.next (<anonymous>)
    at C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:9:71
    at new WrappedPromise (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\es6-wrapped-promise.js:13:18)
    at __awaiter (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:5:12)
    at resolveMainMethod (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:106:12)
    at DebugCodeLensProvider.<anonymous> (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:30:39)
    at Generator.next (<anonymous>)
    at C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:9:71
    at new WrappedPromise (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\es6-wrapped-promise.js:13:18)
    at __awaiter (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:5:12)
    at DebugCodeLensProvider.provideCodeLenses (C:\Users\Pascal\.vscode\extensions\vscjava.vscode-java-debug-0.14.0\out\src\debugCodeLensProvider.js:29:16)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:498:405
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:368
    at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:776)
    at Object.t.asThenable (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:333)
    at e.provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:498:364)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:215
    at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:512:91)
    at e.$provideCodeLenses (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:513:177)
    at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
    at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
    at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:60)
    at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
    at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20) java.execute.workspaceCommand
```

**Comment by fbricon** [comment]
the log shows the vscode-java-debug extension executing a command while the java server is not ready. I'm not sure whether this causes the server to crash or if the server already crashed at that point. But vscode-java-debug should definitely wait to execute those commands. cc @yaohaizh @andxu.
Stuff you can try: 
1- Close vscode
2- in a terminal, execute `jps`, to find org.eclipse.equinox.launcher_*.jar processes, kill them if necessary.
3- reopen vscode, see if it still fails.
4- If it does, disable all java related extensions, only keep redhat.java (start by disabling the microsoft java extension pack if you have it)
5- repeat steps 1-3

**Comment by SirRollo** [comment]
> the log shows the vscode-java-debug extension executing a command while the java server is not ready. I'm not sure whether this causes the server to crash or if the server already crashed at that point. But vscode-java-debug should definitely wait to execute those commands. cc @yaohaizh @andxu.
> Stuff you can try:
> 1- Close vscode
> 2- in a terminal, execute `jps`, to find org.eclipse.equinox.launcher_*.jar processes, kill them if necessary.
> 3- reopen vscode, see if it still fails.
> 4- If it does, disable all java related extensions, only keep redhat.java (start by disabling the microsoft java extension pack if you have it)
> 5- repeat steps 1-3

Hi, I did what you wrote but I don't get any running Java processes when running jps after I closed vscode.

Is there something else I can try? I really want to program Java with vscode...

**Comment by SirRollo** [comment]
more troubleshooting I did:

- went into AppData\Roaming\Code\User\workspaceStorage and deleted everything in this folder.
- uninstalled all java related extension and also disabled all of my other extensions.
- went to .vscode\extensions and deleted folder "redhat.java-0.33.0"
- installed just the java.lang extension by redhat
- reloaded vscode
- waited a bit - error appeared again
- while waiting, when using jps, I can see that the launcher gets different PIDs, probably because server gets restarted several times

**Comment by ctonsing** [comment]
Was a solution found for this. I have the same problem and none of these steps help. The extension is not usable at the moment in my case...
