### ISSUE TITLE
Problem with codeComplete forApp.java proxy does not exist 

### ISSUE THREAD

**Issue by lilixom** [redhat-developer/vscode-java#76]
I install plugin from marketplace , and setting user profile like followed, but when edit *.java file ,Console  notice  " Problem with codeComplete forApp.java proxy does not exist "
"java.home": "C:\\Program Files\\Java\\jdk1.8.0_102",
"java.jdt.ls.vmargs": "-noverify -Xmx1G"
 echo. %JDK_HOME%
C:\Program Files\Java\jdk1.8.0_102
echo. %Java_HOME%
C:\Program Files\Java\jdk1.8.0_102

`[Error - 下午1:35:30] 2016-10-21 13:35:28 Problem with codeComplete forApp.java
proxy does not exist
Java Model Exception: Java Model Status [proxy does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:72)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.handle(CompletionHandler.java:43)
	at org.jboss.tools.vscode.java.internal.handlers.CompletionHandler.handle(CompletionHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:183)
	at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by lilixom** [comment]
I find this problem , I just config User settings in vscode, ignore Workstation Setting
