### ISSUE TITLE
The IntelliSense suddenly not working

### ISSUE THREAD

**Issue by bobjiang1988** [redhat-developer/vscode-java#779]
##### Environment
- Operating System: Ubuntu 18.04
- JDK version: 1.8.0_131
- Visual Studio Code version: 1.30.2
- Java extension version:0.37.0

##### Steps To Reproduce
1. Input a letter, not working
![image](https://user-images.githubusercontent.com/5567404/51811873-15815580-22ea-11e9-90b3-5e62ac659a4d.png)

2. Completion it and input '.', it works
![image](https://user-images.githubusercontent.com/5567404/51811938-685b0d00-22ea-11e9-8096-58ce642ef607.png)

##### Error Log
`
Cannot decrypt model file
Illegal key size
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaModelLoader.decrypt(PythiaModelLoader.java:76)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaModelLoader.access$0(PythiaModelLoader.java:70)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaModelLoader$1.run(PythiaModelLoader.java:57)

`

**Comment by kzinglzy** [comment]
have the same issue

**Comment by kzinglzy** [comment]
@yaohaizh fixed after reinstall the extension 😄 . thx for your reply

**Comment by NENightElves** [comment]
I meet the same issue with both jdk10 and openjdk11. I also tried to reinstall this extension and vs intellicode. But this can only fix the problem for a while. When I restart the vscode for some times, the bug appear again.

**Comment by yaohaizh** [comment]
@NENightElves Could you attach your log here? https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

**Comment by NENightElves** [comment]
@yaohaizh 
the command 'Java: Open Java Language Server log file' get the .log file shows the text below:
```
!SESSION 2019-01-29 14:42:30.605 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -data c:\***\redhat.java\jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:33.050
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:33.184
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:33.210
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:33.212
!MESSAGE Initializing Java Language Server 0.31.0.201901170522

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:33.242
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:33.930
!MESSAGE Creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.090
!MESSAGE Finished creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.581
!MESSAGE Workspace initialized in 1358ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.610
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.613
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.617
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.687
!MESSAGE >>New configuration: {java={home=null, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}}, configuration={updateBuildConfiguration=interactive, maven={userSettings=null}}, trace={server=verbose}, import={gradle={enabled=true}, maven={enabled=true}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, referencesCodeLens={enabled=false}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=null}, comments={enabled=true}, onType={enabled=true}}, saveActions={organizeImports=false}, contentProvider={preferred=null}, autobuild={enabled=true}, maxConcurrentBuilds=1.0, completion={enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], importOrder=[java, javax, com, org]}, progressReports={enabled=true}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=true, showQualifiedNames=false, maxStringLength=0.0, enableHotCodeReplace=true, enableRunDebugCodeLens=true, forceBuildBeforeLaunch=true}}, dependency={showOutline=true, syncWithFolderExplorer=true, packagePresentation=flat}, test={report={position=sideView}, log={level=info}, message={hintForDeprecatedConfig=true, hintForSetingDefaultConfig=true}, defaultConfig=, config={}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.689
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.727
!MESSAGE >> workspace/executeCommand java.intellicode.enable

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:34.743
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:35.773
!MESSAGE begin problem for /Main.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:35.775
!MESSAGE 4 problems reported for /Main.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:35.781
!MESSAGE Reconciled 0, validated: 1. Took 653 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:35.834
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:36.126
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:36.128
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:36.130
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY java-debug 1 0 2019-01-29 14:42:36.147
!MESSAGE Starting com.microsoft.java.debug.plugin

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:36.440
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:36.443
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:36.446
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:38.976
!MESSAGE >> workspace/executeCommand sts.java.addClasspathListener

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:38.978
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:38.984
!MESSAGE >> workspace/executeCommand vscode.java.test.get.testpath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:39.307
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:39.309
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:39.311
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:39.314
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:39.315
!MESSAGE >> workspace/executeCommand vscode.java.test.search.codelens

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:39.317
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:48.794
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:42:53.400
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:43:01.453
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:43:03.795
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-01-29 14:43:03.865
!MESSAGE >> workspace/executeCommand java.project.list
```
However in Develop Tools' Console Tab, I just see one message about java(User filter), but it is about another extension. The message shows below:
```
/C:/***/workbench.main.js:3266 Extension Host
/C:/***/workbench.main.js:1504   ERR Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined
    at module.exports.e.DependencyDataProvider.revealPaths.n.find.t (C:\***\.vscode\extensions\vscjava.vscode-java-dependency-0.3.0\dist\extension.js:46:26196)
    at Array.find (native)
    at module.exports.e.DependencyDataProvider.<anonymous> (C:\***\.vscode\extensions\vscjava.vscode-java-dependency-0.3.0\dist\extension.js:46:26177)
    at Generator.next (<anonymous>)
    at s (C:\***\.vscode\extensions\vscjava.vscode-java-dependency-0.3.0\dist\extension.js:46:24568)
    at propagateAslWrapper (C:\***\.vscode\extensions\vscjava.vscode-java-pack-0.5.0\node_modules\async-listener\index.js:504:23)
    at C:\***\.vscode\extensions\vscjava.vscode-java-pack-0.5.0\node_modules\async-listener\index.js:541:70
    at <anonymous>
```

**Comment by fbricon** [comment]
can you try with simply the Language support for Java extension? Looks like other extensions are misbehaving here

**Comment by NENightElves** [comment]
I reinstall vscode yesterday and reset all the settings and extensions by removing .vscode and %appdata%/code. Everything goes well until now. THX.

**Comment by bobjiang1988** [comment]
@yaohaizh 
Recent log
```
[Error - 10:46:06 AM] Jan 30, 2019 10:46:06 AM Problem with codeComplete for file:///mnt/work/project/zhongdong/zd-cloud/src/main/java/net/zdpcc/cloud/modules/operation/controller/OperOilBatchController.java
null
java.lang.NullPointerException
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompletionContext.getReceiverType(PythiaCompletionContext.java:165)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompletionProvider.provideCompletionItems(PythiaCompletionProvider.java:55)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.computeContentAssist(CompletionProvider.java:117)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.provideCompletionItems(CompletionProvider.java:60)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.executeCommand(CommandHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:152)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:142)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:451)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by bobjiang1988** [comment]
@yaohaizh 
Recent log
```
[Error - 10:46:06 AM] Jan 30, 2019 10:46:06 AM Problem with codeComplete for file:///****.java
null
java.lang.NullPointerException
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompletionContext.getReceiverType(PythiaCompletionContext.java:165)
	at com.microsoft.jdtls.intellicode.core.pythia.PythiaCompletionProvider.provideCompletionItems(PythiaCompletionProvider.java:55)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.computeContentAssist(CompletionProvider.java:117)
	at com.microsoft.jdtls.intellicode.core.CompletionProvider.provideCompletionItems(CompletionProvider.java:60)
	at com.microsoft.jdtls.intellicode.core.CommandHandler.executeCommand(CommandHandler.java:57)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:152)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:142)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:451)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Eskibear** [comment]
It works well after disabling the Spring Tools extension. 

Same issue here https://github.com/spring-projects/sts4/issues/193
