### ISSUE TITLE
Extension fails to start with Visual Studio Code 1.6.1

### ISSUE THREAD

**Issue by jpeffer** [redhat-developer/vscode-java#79]
After setting java.home in the user settings and installing the extension, Java files opened from within a maven project result in the following errors:

[Error - 1:43:59 PM] Oct 22, 2016 1:43:59 PM Problem getting code lenses forErrorController.java
ui does not exist
Java Model Exception: Java Model Status [ui does not exist]
    at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
    at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
    at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
    at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:140)
    at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler.access$0(CodeLensHandler.java:137)
    at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:59)
    at org.jboss.tools.vscode.java.internal.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
    at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:183)
    at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:134)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

[Error - 1:44:01 PM] Oct 22, 2016 1:43:59 PM Creating working copy 
ui does not exist
Java Model Exception: Java Model Status [ui does not exist]
    at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
    at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
    at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
    at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
    at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
    at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
    at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler.handleOpen(DocumentLifeCycleHandler.java:153)
    at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler.access$1(DocumentLifeCycleHandler.java:137)
    at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler$OpenHandler$1.run(DocumentLifeCycleHandler.java:86)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
    at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:83)
    at org.jboss.tools.vscode.java.internal.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:1)
    at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:205)
    at org.jboss.tools.langs.base.LSPServer.lambda$1(LSPServer.java:125)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by gorkem** [comment]
Do you have a project that I can use to reproduce the issue?

**Comment by jpeffer** [comment]
Unfortunately it's a corporate application that I would not be able to share. I will see if I can recreate the issue with a simple sample project.

**Comment by jpeffer** [comment]
I am able to reproduce the problem with the following:

**Create a new sample project**
`mvn archetype:generate -DgroupId=com.example -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`

Replace the generated pom.xml with the attached pom.xml.
[pom.zip](https://github.com/redhat-developer/vscode-java/files/546584/pom.zip)

I also observed that when the .project file and .settings directory are generated when opening the root maven directory, if the .project file or .settings directory is later deleted, neither are later regenerated. I assume something is cached somewhere that I am not seeing.

**Comment by gorkem** [comment]
The root cause is the projects generated are not java projects. I think this is because we do not really support _war_ projects yet but I will let @fbricon comment on that. 

I have a fix to avoid messages if no Java projects are created. We can follow up https://github.com/gorkem/java-language-server/issues/85 and #62 for further enhancements to this case.

**Comment by fbricon** [comment]
Can you please check if the 0.0.6 release fixes this issue?

**Comment by jpeffer** [comment]
The latest version does appear to have resolved the issue. Thanks!
