### ISSUE TITLE
Windows 10 x64/macOS, open spring-boot/wildfly, it will always trigger full build after initialized after imported

### ISSUE THREAD

**Issue by yaohaizh** [redhat-developer/vscode-java#793]
[provide a description of the issue]

##### Environment

- Version: 1.31.0 (user setup)
- Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
- Date: 2019-02-05T22:35:56.624Z
- Electron: 3.1.2
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- OS: Windows_NT x64 10.0.17763

##### Steps To Reproduce
1. Clone https://github.com/spring-projects/spring-boot or https://github.com/wildfly/wildfly
2. Open the repo in vscode
3. Close the repo after the first-time initialization is done(full built is done for the first time)
4. Reopen the repo in vscode

##### Current Result
A full build will be triggered after some times

##### Expected Result
No full build should be triggered since there is no change made on the contents

##### Additional Informations
The issue only exists on the Windows platform, but not macOS, Linux
Might also exists for  small/medium size projects, but it takes less time to do the building.

**Comment by snjeza** [comment]
@yaohaizh Could you test https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.43.0.vsix ?

**Comment by yaohaizh** [comment]
@snjeza With this change, the issue was fixed.

**Comment by fbricon** [comment]
Is this a problem with the current release or with the extension from the master branch?

**Comment by snjeza** [comment]
The problem exists in all the version of vscode-java.

**Comment by yaohaizh** [comment]
And on all platform, but not Windows specifically.

**Comment by apupier** [comment]
@yaohaizh said:
> @snjeza With this change, the issue was fixed.

but there was more comments afterwise.
Someone know if it is fixed or not? Or have Windows to try it?

**Comment by snjeza** [comment]
@fbricon @rgrunber could you try https://github.com/snjeza/vscode-test/raw/master/java-1.2.1.vsix
You have to set the following properties:

```
"java.jdt.ls.vmargs": "-DwatchParentProcess=10 <YOUR_VMARGS>",
"java.import.generatesMetadataFilesAtProjectRoot": true,
```

Test case - https://github.com/redhat-developer/vscode-java/issues/2233#issue-1065621014

**Comment by jdneo** [comment]
Is there any reason that `java.import.generatesMetadataFilesAtProjectRoot` has to be set to `true`?

**Comment by snjeza** [comment]
@Is there any reason that java.import.generatesMetadataFilesAtProjectRoot has to be set to true?

I have faced the following exception:
```
!ENTRY org.eclipse.buildship.core 4 0 2021-11-29 23:41:37.785
!MESSAGE Could not read persisted classpath for project spring-boot-test-support.
!STACK 0
org.xml.sax.SAXParseException; lineNumber: 81; columnNumber: 4; The element type "attributes" must be terminated by the matching end-tag "</attributes>".
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at org.eclipse.buildship.core.internal.preferences.ClasspathConverter.readClasspathNode(ClasspathConverter.java:76)
        at org.eclipse.buildship.core.internal.preferences.ClasspathConverter.toEntries(ClasspathConverter.java:66)
        at org.eclipse.buildship.core.internal.preferences.ClasspathConverter.toEntries(ClasspathConverter.java:115)
        at org.eclipse.buildship.core.internal.preferences.PersistentModelConverter$13.apply(PersistentModelConverter.java:154)
        at org.eclipse.buildship.core.internal.preferences.PersistentModelConverter$13.apply(PersistentModelConverter.java:149)
        at org.eclipse.buildship.core.internal.preferences.PersistentModelConverter.loadValue(PersistentModelConverter.java:207)
        at org.eclipse.buildship.core.internal.preferences.PersistentModelConverter.toModel(PersistentModelConverter.java:149)
        at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence.doLoadModel(DefaultModelPersistence.java:127)
        at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence.access$000(DefaultModelPersistence.java:51)
        at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$1.load(DefaultModelPersistence.java:60)
        at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$1.load(DefaultModelPersistence.java:56)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
        at org.eclipse.buildship.core.internal.preferences.DefaultModelPersistence$2.run(DefaultModelPersistence.java:190)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I can't reproduce it again. You can test with and without `generatesMetadataFilesAtProjectRoot:true`
