### ISSUE TITLE
code runner broken, missmatch between compiler & runner

### ISSUE THREAD

**Issue by Nopzen** [redhat-developer/vscode-java#801]
[provide a description of the issue]
I have no problem using the java & javac command in my terminal to compile and run the code, but when running inside VSCode it messes up, it throws error described under section **Current Result**

##### Environment
- Operating System: macOS Sierra, 10.12.6
- JDK version:  java version "1.8.0_202"
- Visual Studio Code version: 1.31.1
- Java extension version: 0.4.0

##### Steps To Reproduce
1. install java8 with home brew
2. install the java extention pack in vscode
3. make a simple hello world
4. press the run code in vscode

[attach a sample project reproducing the error]
Simple project running this code:

```
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello, world");
  }
}
```

##### Current Result
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: HelloWorld has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
##### Expected Result
"Hello, world"

##### Additional Informations
Im pretty new to Java development, so i might also have messed something up. Here is a bit more information about my setup on the mac hopefully this can help to sole this issue:

```
➜  hello-world which java
/usr/bin/java
➜  hello-world ls -l `which java`
lrwxr-xr-x  1 root  wheel  74 24 Nov  2017 /usr/bin/java -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
➜  hello-world echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home
➜  hello-world java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
➜  hello-world javac -version
javac 1.8.0_202
➜  hello-world ls -l `which javac`
lrwxr-xr-x  1 root  wheel  75 24 Nov  2017 /usr/bin/javac -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/javac
```

**Comment by Nopzen** [comment]
after some long hours of debuggin, i figured that the workspace for some reason was using java 11 to compile and java 8 to run, it was not in the workspace setting but i got an error that lead me to that.

Fixed it with complete re-install of vscode, and my java 8 is now working properly :) (i know this is not a "fix" per say, but it work)

**Comment by medsonk** [comment]
I got the SAME problem just like yours !! this thing was driving me crazy ! and there is no answer on google! i knew it compiled with a higher version java (in fact there is only one jdk in my computer)  but i have no idea what to do

**Comment by jstanley23** [comment]
Same issue, but I am in Windows.

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

redhat.java@0.42.0
VisualStudioExptTeam.vscodeintellicode@1.1.5
vscjava.vscode-java-debug@0.17.0
vscjava.vscode-java-dependency@0.4.0
vscjava.vscode-java-pack@0.6.0
vscjava.vscode-java-test@0.15.1
vscjava.vscode-maven@0.15.2

C:\Users\jstan>java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)

C:\Users\jstan>javac -version
javac 1.8.0_202

C:\Users\jstan>echo %JAVA_HOME%
C:\Program Files\AdoptOpenJDK\jdk-8.0.202.08\


Debug Console message:
java.lang.UnsupportedClassVersionError: HelloWorld has been compiled by a more recent version of the Java Runtime (class file version 52.65535), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"

**Comment by 18796299507** [comment]
Same issue, I am in Windows. But how to solve it?

**Comment by yaohaizh** [comment]
Could you guys invoke "Java: Clean the Java language server workspace" command or "Java: Force Java Compilation" to see whether fix this problem?

**Comment by medsonk** [comment]
> Could you guys invoke "Java: Clean the Java language server workspace" command or "Java: Force Java Compilation" to see whether fix this problem?

I tried, no help. Beside, it is very strange to see “52.65535”, while 65535 means 2^32

**Comment by yaohaizh** [comment]
@fbricon  Seems language server issue. https://github.com/Microsoft/vscode-java-debug/issues/555

**Comment by merqrial** [comment]
Same issue for me too. And since there is no setting which allows me to choose the runtime, I am kinda stuck now.

**Comment by fbricon** [comment]
Fix is merged upstream. New 0.42.1 release is imminent. You might need to clean the workspace folders though, after reopening your folder.

**Comment by mapio** [comment]
I'm afraid that here we are again with JDK13

**Comment by yaohaizh** [comment]
@testforstephen
