### ISSUE TITLE
Big java project freezes with problems auto-scanning (1 million lines of code)

### ISSUE THREAD

**Issue by JayDi85** [redhat-developer/vscode-java#867]
Big java project freezes on files scanning (1 million lines of code, 30k+ files). It's can't be disabled from IDE:
- Project: https://github.com/magefree/mage
- Project language: java + maven

##### Environment
- Operating System: Windows 7 x64
- JDK version: 1.8.0_201
- Visual Studio Code version: 1.32.3
- Java extension version: 0.42.1

##### Steps To Reproduce
1. `git clone https://github.com/magefree/mage.git`
2. open folder with that java project;
3. install java support plugin from red hat;
4. try to add or change configuration (debug);
![shot_190402_174233](https://user-images.githubusercontent.com/8344157/55411165-32e6d000-5576-11e9-94b1-3b9c2e6d0245.png)
5. vs code runs background project scanning with problems count updates;
![shot_190402_183149](https://user-images.githubusercontent.com/8344157/55411154-2ebab280-5576-11e9-946a-1b2becb59d41.png)
6. it's freeze and ask to "reopen, wait or close" every minute.
![shot_190402_174611](https://user-images.githubusercontent.com/8344157/55411129-22365a00-5576-11e9-9805-11da413df22b.png)
![shot_190402_174019](https://user-images.githubusercontent.com/8344157/55411145-2a8e9500-5576-11e9-9a46-c11953673d86.png)

##### Current Result
 * freezes (you can't do anything, IDE's window is locked);
##### Expected Result
 * must shows scan progress status, not freeze or available to disable auto-scan;

**Comment by snjeza** [comment]
Related issue: https://github.com/eclipse/eclipse.jdt.ls/issues/824

**Comment by fbricon** [comment]
By default the Java Language Server runs with 1GB of heap, which might be too small for your project. You might want to try increasing the Xmx value in the java.jdt.ls.vmargs preference.

**Comment by fbricon** [comment]
@snjeza I don't think this relates to eclipse/eclipse.jdt.ls#824, as this would need to invoke multiple calls to workspace/didChangeWatchedFiles (which might happen when switching branches in a git repo). Here the problem seems to be caused by the large amount of messages sent to the client, and/or possibly the very ineffective calls to refreshLocal on Windows, as mentioned in https://github.com/eclipse/eclipse.jdt.ls/pull/915#issuecomment-476516532.

**Comment by JayDi85** [comment]
I've changed jvm params to 2G but nothing has changed. It's not a java.exe freeze, it's code.exe problem:

![shot_190402_234721](https://user-images.githubusercontent.com/8344157/55431744-4d36a300-55a2-11e9-9953-a04a46f3be58.png)
![shot_190402_235057](https://user-images.githubusercontent.com/8344157/55431733-4b6cdf80-55a2-11e9-8a03-6efbb0b1596a.png)
![shot_190402_234810](https://user-images.githubusercontent.com/8344157/55431742-4d36a300-55a2-11e9-9b43-ece17dd6bf18.png)
![shot_190402_235132](https://user-images.githubusercontent.com/8344157/55431731-4b6cdf80-55a2-11e9-9cb2-12b29c954cc3.png)

**Comment by fbricon** [comment]
I see the same freeze on Mac too. My gut feeling is the server is pounding the client with a ton of diagnostic messages. Something I believe we should send by batch instead. @aeschli what amount of diagnostics is VS Code capable of sustaining?

@JayDi85 thanks for the project, that's a great way to test performance :-)

**Comment by fbricon** [comment]
The server sends more than 10k diagnostics for about 22.8k java files. Maybe the combination of diagnostics with that amount of files is an issue.

**Comment by fbricon** [comment]
Tried with 2G, after disabling all extensions but vscode-java, on vscode-insiders, no freeze. But the server choked on some hover with:
```
Caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at org.eclipse.jdt.internal.compiler.util.HashtableOfObject.<init>(HashtableOfObject.java:41)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readCategoryTable(DiskIndex.java:683)
	at org.eclipse.jdt.internal.core.index.DiskIndex.addQueryResults(DiskIndex.java:204)
	at org.eclipse.jdt.internal.core.index.Index.query(Index.java:150)
```

So looks like the freeze might be caused by some 3rd party plugin

**Comment by JayDi85** [comment]
I have `Language Support for Java(TM) by Red Hat` only:
![shot_190403_002329](https://user-images.githubusercontent.com/8344157/55433711-f384a780-55a6-11e9-9497-9f55dbafd847.png)

Well, I'm wait ~30 mins and it's done (unfreeze) with 38k warnings:
![shot_190403_002159](https://user-images.githubusercontent.com/8344157/55433683-e5cf2200-55a6-11e9-99aa-6c322f860595.png)

But after project re-open -- it's start to scan again.

**Comment by fbricon** [comment]
Can you try with https://code.visualstudio.com/insiders/, just vscode-java?

**Comment by snjeza** [comment]
> 

> @snjeza I don't think this relates to [eclipse/eclipse.jdt.ls#824](https://github.com/eclipse/eclipse.jdt.ls/issues/824), as this would need to invoke multiple calls to workspace/didChangeWatchedFiles (which might happen when switching branches in a git repo). Here the problem seems to be caused by the large amount of messages sent to the client, and/or possibly the very ineffective calls to refreshLocal on Windows, as mentioned in [eclipse/eclipse.jdt.ls#915 (comment)](https://github.com/eclipse/eclipse.jdt.ls/pull/915#issuecomment-476516532).

**Comment by snjeza** [comment]
You can also try with https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.43.0.vsix

**Comment by JayDi85** [comment]
Yes, I can confirm -- insider version with red hat's java plugin works fine and scans project in background without freezes and very fast (it's takes < minute to scan full projects instead 20 minutes before).
