### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by mattjcl** [redhat-developer/vscode-java#899]
Code completion is all but non-existent when typing in a .java file.
##### Environment
- Operating System: macOS Mojave 10.14.4
- JDK version: 12.0.1
- Visual Studio Code version: 1.33.1
- Java extension version: 0.6.0

##### Steps To Reproduce
n-a

##### Logs:

Language support for java log:

[Error - 3:01:13 PM] 25 Apr. 2019, 3:01:13 pm Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
null
java.lang.NullPointerException
	at com.microsoft.java.test.plugin.util.ProjectUtils.lambda$0(ProjectUtils.java:80)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.microsoft.java.test.plugin.util.ProjectUtils.parseProjects(ProjectUtils.java:83)
	at com.microsoft.java.test.plugin.util.ProjectUtils.getTestSourcePaths(ProjectUtils.java:63)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:40)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:439)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$33(JDTLanguageServer.java:835)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

[Error - 3:01:13 PM] 25 Apr. 2019, 3:01:13 pm Error in calling delegate command handler
null
java.lang.NullPointerException
	at com.microsoft.java.test.plugin.util.ProjectUtils.lambda$0(ProjectUtils.java:80)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.microsoft.java.test.plugin.util.ProjectUtils.parseProjects(ProjectUtils.java:83)
	at com.microsoft.java.test.plugin.util.ProjectUtils.getTestSourcePaths(ProjectUtils.java:63)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:40)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:439)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$33(JDTLanguageServer.java:835)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

##### Current Result

Within a .java file, typing "class", amongst others, does not offer any code snippets.

##### Expected Result

Within a .java file, typing "class" should result in code snippet suggestions, as per https://code.visualstudio.com/docs/java/java-tutorial

**Comment by yaohaizh** [comment]
@mattjcl You could disable vscode java tester extension to see whether work around this issue.

@jdneo Could you help take a look at this issue?

**Comment by jdneo** [comment]
@mattjcl Are you working with a default package?

**Comment by mattjcl** [comment]
@yaohaizh Language Support for Java no longer outputs the above errors after disabling Java Test Runner extension. However intellisense is still largely missing.

@jdneo yes I am.

**Comment by jdneo** [comment]
Could not reproduce in 1.3.0
