### ISSUE TITLE
Unable to properly load a directory with multiple maven projects

### ISSUE THREAD

**Issue by 3ximus** [redhat-developer/vscode-java#93]
The files .project .classpath and the directory .settings are created when I open a single maven project, but not if I open a directory with multiple projects.

It produces the following for each project
```
[Error - 12:00:55 AM] Nov 15, 2016 12:00:52 AM Problem importing to workspace
The project description file (.project) for 'vehicle' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
org.eclipse.core.internal.resources.ResourceException: The project description file (.project) for 'vehicle' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored
```
Its not really a problem since I can open them one by one to generate the needed files...

##### Environment
- Operating System: Arch Linux
- JDK version: 8
- Visual Studio Code version: 1.7.1
- Java extension version: 0.06

**Comment by 3ximus** [comment]
Actually, I have now tried on another project and the same problem appears:

```
[Error - 12:34:27 AM] Nov 15, 2016 12:34:25 AM Problem importing to workspace
The project description file (.project) for 'resources' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
org.eclipse.core.internal.resources.ResourceException: The project description file (.project) for 'resources' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:907)
	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:904)
	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:774)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1041)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1087)
	at org.jboss.tools.vscode.java.internal.managers.MavenProjectImporter.collectProjects(MavenProjectImporter.java:105)
	at org.jboss.tools.vscode.java.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:87)
	at org.jboss.tools.vscode.java.internal.managers.ProjectsManager.createProject(ProjectsManager.java:51)
	at org.jboss.tools.vscode.java.internal.handlers.InitHandler$1.run(InitHandler.java:89)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55
```

**Comment by 3ximus** [comment]
OK, I fixed this by clearing $HOME/.config/Code/Users/workspaceStorage since i noticed some metadata was being saved there. It was my bad since i sync this directory between multiple computers and maybe that caused the issue.
I guess this can be closed :+1:
