### ISSUE TITLE
Test Explorer can't expand project

### ISSUE THREAD

**Issue by goldpicker** [redhat-developer/vscode-java#994]
Issue Type: <b>Bug</b>

When I open then Java project, in test explorer, can't expand it to run test.
when i expand, log is
[Error - 6:44:30 PM] Jul 19, 2019, 6:44:30 PM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
Property must not be null: range
java.lang.IllegalArgumentException: Property must not be null: range
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:23)
	at org.eclipse.lsp4j.Location.<init>(Location.java:36)
	at com.microsoft.java.test.plugin.model.TestItem.<init>(TestItem.java:45)
	at com.microsoft.java.test.plugin.util.TestItemUtils.constructTestItem(TestItemUtils.java:54)
	at com.microsoft.java.test.plugin.util.TestItemUtils.constructTestItem(TestItemUtils.java:36)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.searchInFolder(TestSearchUtils.java:350)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.searchTestItems(TestSearchUtils.java:144)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:46)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:206)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:196)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:459)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$41(JDTLanguageServer.java:909)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

[Error - 6:44:30 PM] Jul 19, 2019, 6:44:30 PM Error in calling delegate command handler
Property must not be null: range
java.lang.IllegalArgumentException: Property must not be null: range
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:23)
	at org.eclipse.lsp4j.Location.<init>(Location.java:36)
	at com.microsoft.java.test.plugin.model.TestItem.<init>(TestItem.java:45)
	at com.microsoft.java.test.plugin.util.TestItemUtils.constructTestItem(TestItemUtils.java:54)
	at com.microsoft.java.test.plugin.util.TestItemUtils.constructTestItem(TestItemUtils.java:36)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.searchInFolder(TestSearchUtils.java:350)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.searchTestItems(TestSearchUtils.java:144)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:46)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:206)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:196)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:459)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$41(JDTLanguageServer.java:909)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

Extension version: 0.47.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|-psn_0_884952|
|Screen Reader|no|
|VM|0%|
</details>

![Screen Shot 2019-07-19 at 6 49 11 PM](https://user-images.githubusercontent.com/2731456/61530251-2075a100-aa56-11e9-8108-e99bbdab41f8.png)

**Comment by fbricon** [comment]
It's a vscode-java-test issue: https://github.com/microsoft/vscode-java-test/issues/749
